### ISSUE TITLE
How can i download video ?

### ISSUE THREAD

**Issue by kishan2212** [davidteather/TikTok-Api#10]
hello there ,
i'm unaware of python but i'm looking for this.
how can i video download with URL and how can i get "video_id" using URL?

hope i will get some help from you.

**Comment by davidteather** [comment]
Are you talking about [itemInfos][id]? 

Currently there’s no ability to get that json by a url. I’ll implement that feature either today or over the weekend.

**Comment by kishan2212** [comment]
can you please explain to me that how i get "video_id"(v12345679978912zxasd) ?
what should i have to call to get this file "ExTikTokResonse.json" response in php ?

**Comment by davidteather** [comment]
Since this is a python package you would have to create a python script that you could use the php exec command to execute the code and fetch the output of that program.


[Here](https://gist.github.com/davidteather/02e8d4adf8893ab319a2a7dfb5dbcf19) is example code of how to specify a search by hashtag and result number. Ex calling command 
```
python TikTok-Api-CLI.py funny 10
```

[Here](https://www.php.net/manual/en/function.exec.php) is a link to the php exec command.


The other option is to use this python API to find the signature you need to make requests to their database, however that would still require integration to a python script.

**Comment by davidteather** [comment]
If you want to download the video in python here's example code

```
from TikTokApi import TikTokapi
import urllib.request
# Starts T
api = TikTokapi("path/to/browsermob-proxy")

# The Number of trending TikToks you want to be displayed
results = 1
trending = api.trending(results)

for tiktok in trending:
    # Prints the text of the tiktok
    videoURL = tiktok["itemInfos"]["video"]["urls"][2]
    urllib.request.urlretrieve(videoURL, 'video_name.mp4') 

```

**Comment by kishan2212** [comment]
sorry but i'm getting error of browsermob-proxy... i don't understand how to set that path. i already downloaded that.

**Comment by davidteather** [comment]
Download browsermob proxy and place it as such and change “path/to/browsermob-proxy” to be “browsermob-proxy”

If that doesn’t work try “browsermob-proxy/bin”
 
```
ProjectFolder
  - main.py
   - browsermob-proxy
       - bin
```

Google adding to path on whatever your operating system is. 


Then add ProjectFolder/browsermob-proxy/bin to the path.

**Comment by kishan2212** [comment]
okay i will check it. thanks again.

**Comment by davidteather** [comment]
Updated main branch adding new release and pypi release in a few minutes.

**Comment by theparcel** [comment]
Trying to download hashtag videos with the api,
`from TikTokApi import TikTokapi

# Starts The Api Class
api = TikTokapi("browsermob-proxy/bin/browsermob-proxy")

# The Number of trending TikToks you want to be displayed
results = 10

hashtag = ("meme")


result = api.search_by_hashtag(hashtag, results)

prevloops = 0

for tiktok in trending:
    # Prints the text of the tiktok
    videoURL = tiktok["itemInfos"]["video"]["urls"]
    videoname = "video" + str(prevloops) + ".mp4"
    urllib.request.urlretrieve(videoURL, videoname)
    prevloops += 1

`

but unfortunately get this error
`  File ".\testest.py", line 20, in <module>
    urllib.request.urlretrieve(videoURL, 'videoname.mp4')
  File "C:\Users\loren\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 245, in urlretrieve
    url_type, path = splittype(url)
  File "C:\Users\loren\AppData\Local\Programs\Python\Python37\lib\urllib\parse.py", line 940, in splittype
    match = _typeprog.match(url)
TypeError: expected string or bytes-like object`

Any advice on how to download videos based on hashtag? 
Thank you very much ! @davidteather

**Comment by davidteather** [comment]
You're trying to download an array of urls try
```
from TikTokApi import TikTokapi

# Starts The Api Class
api = TikTokapi("browsermob-proxy/bin/browsermob-proxy")

# The Number of trending TikToks you want to be displayed
results = 10

hashtag = ("meme")


result = api.search_by_hashtag(hashtag, results)

prevloops = 0

for tiktok in result :
    # Prints the text of the tiktok
    videoURL = tiktok["itemInfos"]["video"]["urls"][0]
    videoname = "video" + str(prevloops) + ".mp4"
    urllib.request.urlretrieve(videoURL, videoname)
    prevloops += 1
```
