### ISSUE TITLE
update api 

### ISSUE THREAD

**Issue by xtekky** [davidteather/TikTok-Api#1004]
https://github.com/xtekky/TikTok-Web-Reverse, use this (userinfo api etc...), give credits

**Comment by ryanbbrown** [comment]
So does the API not work right now? I just tried it out but haven't been able to get anything to work.

**Comment by xtekky** [comment]
this api is mainly browser based and quite old

**Comment by xtekky** [comment]
what are u looking for, scraping ?

**Comment by ryanbbrown** [comment]
A newer/updated TikTok API that actually works

**Comment by dwicak** [comment]
> A newer/updated TikTok API that actually works

which one? I tried but nothing is work

**Comment by ryanbbrown** [comment]
I don't know, I'm also looking for one. What have you tried already?
