### ISSUE TITLE
[BUG] - user_example.py throws EmptyResponseException

### ISSUE THREAD

**Issue by ryanbbrown** [davidteather/TikTok-Api#1006]
Fill Out the template :)

**Describe the bug**

user_example.py file is throwing an EmptyResponseException. I ran this file while it was alone in its own folder. I already ran `pip install TikTokApi` and `python -m playwright install`.

**The buggy code**

```py
from TikTokApi import TikTokApi

with TikTokApi() as api:
    user = api.user(username="therock")

    for video in user.videos():
        print(video.id)
```

**Expected behavior**

I expected a list of The Rock's video id's to be printed.

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
Traceback (most recent call last):
  File "C:\Users\ryanb\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ryanb\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ryanb\Desktop\code\tiktok2\user_example.py", line 6, in <module>
    for video in user.videos():
  File "C:\Users\ryanb\anaconda3\lib\site-packages\TikTokApi\api\user.py", line 153, in videos
    self.__find_attributes()
  File "C:\Users\ryanb\anaconda3\lib\site-packages\TikTokApi\api\user.py", line 282, in __find_attributes
    for u in self.parent.search.users(self.username):
  File "C:\Users\ryanb\anaconda3\lib\site-packages\TikTokApi\api\search.py", line 105, in search_type
    api_response = Search.parent.get_data(
  File "C:\Users\ryanb\anaconda3\lib\site-packages\TikTokApi\tiktok.py", line 378, in get_data
    raise EmptyResponseException(0, None,
TikTokApi.exceptions.EmptyResponseException: 0 -> Empty response from Tiktok to https://www.tiktok.com/api/search/user/full/?aid=1988&app_name=tiktok_web&device_platform=web_mobile&region=US&priority_region=&os=ios&referer=&cookie_enabled=true&screen_width=1368&screen_height=827&browser_language=en-us&browser_platform=iPhone&browser_name=Mozilla&browser_version=Mozilla%2F5.0+%28iPhone%3B+CPU+iPhone+OS+12_2+like+Mac+OS+X%29+AppleWebKit%2F605.1.15+%28KHTML%2C+like+Gecko%29+Version%2F16.4+Mobile%2F15E148+Safari%2F604.1&browser_online=true&timezone_name=America%2FChicago&is_page_visible=true&focus_state=true&is_fullscreen=false&history_len=4&language=en&keyword=therock&cursor=0&app_language=en&verifyFp=verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq&device_id=6158266019410327993&_signature=_02B4Z6wo00f01CiUouQAAIBAImUaiZgVGlwohYZAAG4qf4
```

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - TikTokApi Version: [5.2.2] -

**Comment by naveedamir484** [comment]
same goes for me, if someone has  resolved this issue please, let us know

**Comment by hunjison** [comment]
it is same to me. now working at all

**Comment by pasmat** [comment]
Same for me - something has probably changed on the API?

**Comment by Schmoaaaaah** [comment]
> Same for me - something has probably changed on the API?

I dont think so. If you open the link in a normal browser you get a valid json response.

**Comment by charliesxia** [comment]
i got the same problem ,

**Comment by lihuelworks** [comment]
+1 same thing

**Comment by Apfez** [comment]
+1, I still get the same thing too. Anyone came up with a solution?

**Comment by Apfez** [comment]
When using the similar repository https://github.com/avilash/TikTokAPI-Python , the same problem arises: you can get trending videos but not user information. Using that repository I found the following is returned: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

Which seems to suggest TikTok is blocking these requests, right? Does that mean no chance of a work-around?

**Comment by RenHong-HC** [comment]
+1
Excuse me, has anyone solved it?

**Comment by davidteather** [comment]
Should be fixed in V6
