### ISSUE TITLE
Is there a way to pull the count of comments between two dates containing a word?

### ISSUE THREAD

**Issue by josh-ashkinaze** [davidteather/TikTok-Api#1013]
Hi, any way to pull total counts of comments published between day X and day Y that contain a given word?

**Comment by Omak2r3a** [comment]
You can get the text of the comment and use a simple if statement
for the day part, I'm not sure if comments have dates in their data but you can use `as_dict` and see if there is date or not

**Comment by josh-ashkinaze** [comment]
That would be assuming I have a set of comments. I am asking: Is there some way to search how many TOTAL comments on TikTok, published between day X and day Y, contained a given word W?

**Comment by Omak2r3a** [comment]
Check the [comment example](https://github.com/davidteather/TikTok-Api/blob/master/examples/comment_example.py)

**Comment by davidteather** [comment]
You could filter this after collecting all comments
