### ISSUE TITLE
[BUG] - empty output when searching for trending videos

### ISSUE THREAD

**Issue by aminoz1234** [davidteather/TikTok-Api#1019]
Fill Out the template :)

**trying to get the trending videos (used the code sample provided in the documentation) but there is no output**

****

Please add any relevant code that is giving you unexpected results.

Preferably the smallest amount of code to reproduce the issue.

**SET LOGGING LEVEL TO INFO BEFORE POSTING CODE OUTPUT**
```py
import logging
TikTokApi(logging_level=logging.INFO) # SETS LOGGING_LEVEL TO INFO
# Hopefully the info level will help you debug or at least someone else on the issue
```

```py
# from TikTokApi import TikTokApi

# Watch https://www.youtube.com/watch?v=-uCt1x8kINQ for a brief setup tutorial
with TikTokApi() as api:
    for trending_video in api.trending.videos(count=50):
        # Prints the author's username of the trending video.
        print(trending_video.author.username)
```

**Expected behavior**

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - TikTokApi Version [e.g. 5.2.2] - if out of date upgrade before posting an issue

**Additional context**

**Comment by nekitalek** [comment]
[trending.py](https://github.com/davidteather/TikTok-Api/blob/master/TikTokApi/api/trending.py) literally not fully implemented. Just a bit of code without any working connections. Probably someone will fix it, but chances are minimal I think.

**Comment by aminoz1234** [comment]
> [trending.py](https://github.com/davidteather/TikTok-Api/blob/master/TikTokApi/api/trending.py) literally not fully implemented. Just a bit of code without any working connections. Probably someone will fix it, but chances are minimal I think.

i tried other features and they were not working as well because tiktok blocked me or rum , i used cookies still didn't work and i dont know how to get a proxy

**Comment by nekitalek** [comment]
> 

one guy helped me with search by hashtag and i'm trying to code trending. Seems like tiktok changed something

**Comment by aminoz1234** [comment]
> > 
> 
> one guy helped me with search by hashtag and i'm trying to code trending. Seems like tiktok changed something. Proxy not needed this case, this code requires recode part which is working with cookies. Trending.py really generates valid `full_url` but when I start trying to show result or write it in a file got `{"status_code": 0}`

im talking about uploading a vid i cant even log in

**Comment by SachitNayak** [comment]
yeah I noticed trending videos list is empty list... facing same problem as the original issue creator

**Comment by davidteather** [comment]
Should be fixed in V6
