### ISSUE TITLE
Importing Api

### ISSUE THREAD

**Issue by itisthoughttobemaeri** [davidteather/TikTok-Api#102]
After `pip install TikTokApi`, when trying the example `getTrendings` I get the error `ImportError: cannot import name 'TikTokApi' from 'TikTokApi' (/Users/mari/opt/anaconda3/lib/python3.7/site-packages/TikTokApi/__init__.py)`. Am I missing something? Thank you in advance

**Comment by davidteather** [comment]
Did you run the pip install command while your anaconda environment was activated?

**Comment by davidteather** [comment]
You might want to run 
```
pip install TikTokApi --upgrade
```

The TikTokApi might have been on an older version of it 2.x or lower.

**Comment by itisthoughttobemaeri** [comment]
It worked! Thanks!
