### ISSUE TITLE
Can't extract createTime using create_time attribute

### ISSUE THREAD

**Issue by shreyakannan1205** [davidteather/TikTok-Api#1022]
Hi, I am unable to extract the create_time of a video using the API
```
api = TikTokApi()
vi = api.video(id = 'XXXX')
ct = vi.create_time
print(ct)
```
while api.video works, vi.create_time does not work.
Any help would be appreciated!

**Comment by davidteather** [comment]
Use `.as_dict` if `.create_time` doesn't work and extract the value manually from the dictionary
