### ISSUE TITLE
[BUG] - Your Error Here

### ISSUE THREAD

**Issue by Loremz01** [davidteather/TikTok-Api#1023]
Fill Out the template :)

Hello! I copy-pasted the starting lines from the example of tiktoklive, the code with connect and comments, i changed the unique_id with a started live but when i start the bot i have this error:
"TikTokLive.types.errors.FailedFetchRoomInfo: Failed to fetch room id from Webcast, see stacktrace for more info."
i also tried to find some tutorial on youtube but all them are old.
i installed tiktok live
the only thing i know is when i pasted "python -m playwright install" in the terminal appeared this message "No module named playwright"

Please add any relevant code that is giving you unexpected results.
Preferably the smallest amount of code to reproduce the issue.

i have error in: client.run()

**SET LOGGING LEVEL TO INFO BEFORE POSTING CODE OUTPUT**
```py
import logging
TikTokApi(logging_level=logging.INFO) # SETS LOGGING_LEVEL TO INFO
# Hopefully the info level will help you debug or at least someone else on the issue
```

```py
from TikTokLive import TikTokLiveClient
from TikTokLive.types.events import CommentEvent, ConnectEvent

client: TikTokLiveClient = TikTokLiveClient(unique_id="@erposse_90")

@client.on("connect")
async def on_connect(_: ConnectEvent):
    print("Connected to Room ID:", client.room_id)

async def on_comment(event: CommentEvent):
    print(f"{event.user.nickname} -> {event.comment}")

client.add_listener("comment", on_comment)

if __name__ == '__main__':
    client.run()
```

**Expected behavior**

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```

```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - TikTokApi Version [e.g. 5.0.0] - if out of date upgrade before posting an issue

**Additional context**

**Comment by davidteather** [comment]
this is the wrong github repo
