### ISSUE TITLE
[BUG] - TikTokApi.exceptions.EmptyResponseException: 0 -> Empty response from Tiktok to

### ISSUE THREAD

**Issue by Superheroff** [davidteather/TikTok-Api#1024]
除了`test_video_info`其他都无法使用了，赶快更新

**Comment by pdkhanh** [comment]
@davidteather

**Comment by Fabien-desablens** [comment]
same issue: \search.py", line 105, in search_type
    api_response = Search.parent.get_data(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\TikTokApi\tiktok.py", line 378, in get_data
    raise EmptyResponseException(0, None,
TikTokApi.exceptions.EmptyResponseException: 0 -> Empty response from Tiktok to https://www.tiktok.com/api/search/user/full/?aid=1988&app_name=tiktok_web&device_platform=web_mobile&region=US&priority_region=&os=ios&referer=&cookie_enabled=true&screen_width=1736&screen_heigh

**Comment by gradill22** [comment]
I'm getting the same issue. I was using the trending search at first, but now that's not working. The generator for the videos is being created, but I can't get any response from TikTok. I've tried changing my VPN and restarting my computer and internet connection, but nothing is working.

**Comment by VinMing** [comment]
Hi, I edited the tiktok.py file as your say, it's not work.

video = api.video(id="7244132640813796654")
video_info_dict = video.info_full()

ERROR:TikTokApi.exceptions.EmptyResponseException: 0 -> Empty response from Tiktok to https://www.tiktok.com/api/item/detail/?aid=1988&app_name=tiktok_web&device_platform=MacIntel&region=CN&priority_region=&os=ios&referer=&cookie_enabled=true&screen_width=485&screen_height=397&browser_language=zh-cn&browser_platform=iPhone&browser_name=Mozilla&browser_version=Mozilla%2F5.0+%28iPhone%3B+CPU+iPhone+OS+12_2+like+Mac+OS+X%29+AppleWebKit%2F605.1.15+%28KHTML%2C+like+Gecko%29+Version%2F16.4+Mobile%2F15E148+Safari%2F604.1&browser_online=true&timezone_name=Asia%2FShanghai&channel=tiktok_web&focus_state=true&is_fullscreen=false&history_len=4&language=zh&itemId=7244132640813796654&verifyFp=XXXXXXX&device_id=XXXXXXXXXX&_signature=XXXXXXX

My version:
TikTokApi                 5.2.2
playwright                1.30.0

How can i fix it? 
thx

**Comment by liechtym** [comment]
@Kresys I implemented all the changes you said in this PR: https://github.com/davidteather/TikTok-Api/pull/1032. However I'm still having the same issue. Any insight into how you got it to work?

**Comment by creativejace** [comment]
@Kresys unfortunately I cannot get it to work either

**Comment by denis019** [comment]
I stepped upon some different solution, I did some slightly modification and it worked.
All credits goes to: https://github.com/ssovit/TikTok-API-PHP/blob/master/lib/TikTok/Api.php#L521

I was able to rewrite it in TS but it should be straightforward to do it in python also.
```
      const response = await axios.get<string>(
        `https://m.tiktok.com/v/${post.id}.html`
      );
      const result: string | undefined = this.getStringBetween(
        response.data,
        '<script id="SIGI_STATE" type="application/json">',
        "</script>"
      );
```

**Comment by davidteather** [comment]
Probably fixed in V6

**Comment by VinMing** [comment]
已收到。
