### ISSUE TITLE
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

### ISSUE THREAD

**Issue by peter0x7f** [davidteather/TikTok-Api#1026]
Hey so I am just trying to make the standard api call as shown in doc's, but I am shown this error, I have read somethings about altering how playwright is called, so would the best solution be to rewrite the TIkTokApi package to resolve this error?
code:
`
from TikTokApi import TikTokApi
api = TikTokApi()
with TikTokApi() as api:
    for trending_video in api.trending.videos(count=10):
        # Prints the author's username of the trending video.
        print(trending_video.author.username)`

Error:playwright\_impl\_impl_to_api_mapping.py:54: RuntimeWarning: coroutine 'browser._clean_up' was never awaited
  for name, value in obj.items():
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

packages:
playwright==1.30
TikTokApi==5.2.2

**Comment by davidteather** [comment]
Should be fixed in V6
