### ISSUE TITLE
how to get url's post and possibility to scrape by period of date

### ISSUE THREAD

**Issue by ihabpalamino** [davidteather/TikTok-Api#1028]
from tiktokapipy.api import TikTokAPI

with TikTokAPI() as api:
    user = api.user("tv2m")
    for video in user.videos:
        print(video.stats.play_count,video.stats.digg_count, video.stats.share_count, video.stats.comment_count,video.create_time)
hello this is my code and my question is how to get url of each videos here and my second question is there any possibilty to scrap data from tiktok using a start and an end date like with period of date since until...

**Comment by davidteather** [comment]
You can create url from the video object by combining `video.author.username` & `video.id` to make the full url.
You cannot select videos by date period
