### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by Godmyhave** [davidteather/TikTok-Api#1029]
我没有开代理，网络也正常，是缺什么东西吗？
报requests.exceptions.ConnectionError: HTTPSConnectionPool(host='tiktok.com', port=443): Max retries exceeded with url: /@Renyi%E6%AF%85%E5%93%A5?lang=en (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021B7B6F35E0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
![image](https://github.com/davidteather/TikTok-Api/assets/59076131/7a82c126-57e4-443b-b138-d21df271aa66)

**Comment by ihabpalamino** [comment]
i think its just needed a good network

**Comment by davidteather** [comment]
If it was a library issue should be fixed in V6
