### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by charliew54321** [davidteather/TikTok-Api#103]
When i try to run the program it shuts it self down.

**Comment by davidteather** [comment]
Please run the script in the terminal instead of double clicking on the python file and paste the error

**Comment by charliew54321** [comment]
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
like it or not? #reversevideo
Hair color #eghebarbershop #haircolor #fyp #eghebarber #egheoghi #barbershop
Every.damn.time 🤦🏽‍♂️🌞 #foryou #fyp #fy #foryoupage
Making sure the clinic is safe 😂 | @diegohojeda @saps_entertainment @alexojeda  @dominictoliver
Nguyên một dàn cute xỉu 💓🥰 #yeupet #thucung #xuhuong #trend #foryou #following
like it or not? #reversevideo
Making sure the clinic is safe 😂 | @diegohojeda @saps_entertainment @alexojeda  @dominictoliver
Had to this one ago😂🥕#fyp #foryou #foryoupage
#foryoupage #fyp #foryou
Nguyên một dàn cute xỉu 💓🥰 #yeupet #thucung #xuhuong #trend #foryou #following
10

**Comment by charliew54321** [comment]
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>
pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.
like it or not? #reversevideo
Hair color #eghebarbershop #haircolor #fyp #eghebarber #egheoghi #barbershop
Every.damn.time 🤦🏽‍♂️🌞 #foryou #fyp #fy #foryoupage
Making sure the clinic is safe 😂 | @diegohojeda @saps_entertainment @alexojeda  @dominictoliver
Nguyên một dàn cute xỉu 💓🥰 #yeupet #thucung #xuhuong #trend #foryou #following
like it or not? #reversevideo
Making sure the clinic is safe 😂 | @diegohojeda @saps_entertainment @alexojeda  @dominictoliver
Had to this one ago😂🥕#fyp #foryou #foryoupage
#foryoupage #fyp #foryou
Nguyên một dàn cute xỉu 💓🥰 #yeupet #thucung #xuhuong #trend #foryou #following
10
any way i can make this english

**Comment by charliew54321** [comment]
Like make it so its only uk or usa

**Comment by davidteather** [comment]
The program is working as intended. Trending is based on your ip use a proxy to an English only country and it’ll only do English
