### ISSUE TITLE
[BUG] - TikTokApi.exceptions.EmptyResponseException: 0 -> Empty response from Tiktok

### ISSUE THREAD

**Issue by baton008** [davidteather/TikTok-Api#1035]
trying to download video

code:
from TikTokApi import TikTokApi
import json

def get_cookies_from_file():
    with open('cookies.json') as f:
        cookies = json.load(f)

    cookies_kv = {}
    for cookie in cookies:
        cookies_kv[cookie['name']] = cookie['value']

    return cookies_kv

cookies = get_cookies_from_file()

def get_cookies(**kwargs):
    return cookies

with TikTokApi() as api:
    video = api.video(id="7041997751718137094")

    # Bytes of the TikTok video
    video_data = video.bytes()

    with open("out.mp4", "wb") as out_file:
        out_file.write(video_data)
Error:
Traceback (most recent call last):
  File "C:\Users\mrbar\PycharmProjects\pythonProject4\main.py", line 24, in <module>
    video_data = video.bytes()
  File "D:\pythonProject4\lib\site-packages\TikTokApi\api\video.py", line 113, in bytes
    video_data = self.info(**kwargs)
  File "D:\pythonProject4\lib\site-packages\TikTokApi\api\video.py", line 74, in info
    return self.info_full(**kwargs)["itemInfo"]["itemStruct"]
  File "D:\pythonProject4\lib\site-packages\TikTokApi\api\video.py", line 95, in info_full
    return self.parent.get_data(path, **kwargs)
  File "D:\pythonProject4\lib\site-packages\TikTokApi\tiktok.py", line 378, in get_data
    raise EmptyResponseException(0, None,
TikTokApi.exceptions.EmptyResponseException: 0 -> Empty response from Tiktok to https://m.tiktok.com/api/item/detail/?aid=1988&app_name=tiktok_web&device_platform=web_mobile&region=RU&priority_region=&os=ios&referer=&cookie_enabled=true&screen_width=1056&screen_height=1671&browser_language=ru-ru&browser_platform=iPhone&browser_name=Mozilla&browser_version=Mozilla%2F5.0+%28iPhone%3B+CPU+iPhone+OS+12_2+like+Mac+OS+X%29+AppleWebKit%2F605.1.15+%28KHTML%2C+like+Gecko%29+Version%2F16.4+Mobile%2F15E148+Safari%2F604.1&browser_online=true&timezone_name=Europe%2FKiev&is_page_visible=true&focus_state=true&is_fullscreen=false&history_len=1&language=ru&itemId=7041997751718137094&verifyFp=verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq&device_id=2921701494326634416&_signature=_02B4Z6wo00f01h7KJGgAAIBCFDucBmKgVY4e2wDAAOOA85

**Comment by Giaochan** [comment]
api has been down since like a week

**Comment by baton008** [comment]
is there a working api?

**Comment by baton008** [comment]
> api has been down since like a week

is there a working api?

**Comment by Giaochan** [comment]
> > api has been down since like a week
> 
> is there a working api?

nope, im waiting the developer to fix the issue

**Comment by baton008** [comment]
> 


he said approximate time for this

**Comment by baton008** [comment]
> > > api has been down since like a week
> > 
> > 
> > is there a working api?
> 
> nope, im waiting the developer to fix the issue

he said approximate time for this

**Comment by Giaochan** [comment]
> > > > api has been down since like a week
> > > 
> > > 
> > > is there a working api?
> > 
> > 
> > nope, im waiting the developer to fix the issue
> 
> he said approximate time for this

nope

**Comment by gradill22** [comment]
Part of the issue is TikTok IP blocking people after some number of simultaneous requests. I don't know what that exact limit is, but I have requested hundreds, maybe thousands of videos a day from TikTok. After a while, I get this same exception. This specific issue is not the API's fault, but TikTok's engineering.

**Comment by baton008** [comment]
> Part of the issue is TikTok IP blocking people after some number of simultaneous requests. I don't know what that exact limit is, but I have requested hundreds, maybe thousands of videos a day from TikTok. After a while, I get this same exception. This specific issue is not the API's fault, but TikTok's engineering.

the problem is that I just installed everything, and have not sent any request yet

**Comment by gradill22** [comment]
> > Part of the issue is TikTok IP blocking people after some number of simultaneous requests. I don't know what that exact limit is, but I have requested hundreds, maybe thousands of videos a day from TikTok. After a while, I get this same exception. This specific issue is not the API's fault, but TikTok's engineering.
> 
> the problem is that I just installed everything, and have not sent any request yet

That's a separate issue. I wish I knew how to solve that. I'll be looking into it in the near future.

**Comment by Vanilla-Mix** [comment]
Yeah I'm getting the same issue

**Comment by hakob8956** [comment]
The same issue for me

**Comment by dismaien** [comment]
I have the same issue and get it from different devices and connections, so shouldn't be an IP issue. 

The error I get is

`TikTokApi.exceptions.EmptyResponseError: Empty response from Tiktok to https://m.tiktok.com/api/item/detail/?aid=1988&app_name=tiktok_web&device_platform=web&referer=&root_referer=&user_agent=Mozilla%252F5.0%2B%28iPhone%253B%2BCPU%2BiPhone%2BOS%2B12_2%2Blike%2BMac%2BOS%2BX%29%2BAppleWebKit%252F605.1.15%2B%28KHTML%2C%2Blike%2BGecko%29%2BVersion%252F16.0%2BMobile%252F15E148%2BSafari%252F604.1&cookie_enabled=true&screen_width=684&screen_height=672&browser_language=&browser_platform=&browser_name=&browser_version=&browser_online=true&ac=4g&timezone_name=&appId=1233&appType=m&isAndroid=False&isMobile=False&isIOS=False&OS=windows&itemId=7234327458508573994&language=en&verifyFp=verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq&did=459587834&_signature=_02B4Z6wo00f01Dj1ueQAAIBC3LHUJRPq8wA49L1AAGr824`

**Comment by sakhstaebir** [comment]
I have same issue. In my opinion it's based on captcha.
I will try to implement the captcha solution from here https://rapidapi.com/SteveJobsnihack/api/flycaptcha

**Comment by dismaien** [comment]
I actually thought now it's related to the inofficial TikTok API changing? Lots of people are getting an EmptyResponse error and it seems to be known

https://github.com/davidteather/TikTok-Api/issues/1035

**Comment by davidteather** [comment]
V6 should fix this, although download is not yet implemented
