### ISSUE TITLE
[BUG] Only returns top 100 videos for a creator

### ISSUE THREAD

**Issue by bfelbo** [davidteather/TikTok-Api#104]
**Describe the bug**

The userPosts method to get videos by a given creator only returns 100 videos. Is there a way to get around that limit?

**The buggy code**

```
from TikTokApi import TikTokApi
api = TikTokApi()
videos = api.userPosts(str(id), sec_uid, n_videos)
```

**Expected behavior**

More than 100 videos.

**Comment by davidteather** [comment]
I’ll look into this later today it should return more than 100.

**Comment by tarkhil** [comment]
maxCount = 99 (tiktok.py:93) so it is a library limit. I guess there should be callback-based interface to prevent memory hogging.

**Comment by davidteather** [comment]
Hey there I looked into it. I'm getting more results than 100 videos for a creator. What version are you running?
```
pip show TikTokApi
```

If your version is not 3.1.1 please upgrade with the following command
```
pip install TikTokApi --upgrade
```

It shouldn't make a difference, but this is the code I was using it's slightly different.
```
from TikTokApi import TikTokApi
api = TikTokApi()
tiktoks = api.byUsername("addisonre", count=200)
```

**Comment by bfelbo** [comment]
Ah, that was it. I was running 3.1.0. Thanks!
