### ISSUE TITLE
[BUG] - count=1 when getting a user's last video returns more than 1 video.

### ISSUE THREAD

**Issue by luca4s** [davidteather/TikTok-Api#1063]
**Describe the bug**
As the title says, I'm trying to get the users most recent video, however it also return other recent videos.

**The buggy code**
```py
async def get_videos():
    async with TikTokApi(logging_level=logging.INFO) as api:
        await api.create_sessions(ms_tokens=[ms_token], num_sessions=1, sleep_after=3)
        async for video in api.user(username="laufey").videos(count=1):
            print(video.id)

if __name__ == "__main__":
    asyncio.run(get_videos())
```
output:
```py
lucas@DESKTOP-041QCM3 MINGW64 ~/Desktop
$ py __main__.py
7275069081420565803
7274970022747901230
7274401699723349294
... (+28 other videos)
```

**Expected behavior**
I wan't the output to only show 1 ID of the most recent video. That's all.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version 6.1.1

**Comment by Duralie** [comment]
Try this:

async def get_videos():
    async with TikTokApi() as api:
        await api.create_sessions(ms_tokens=[ms_token], num_sessions=1, sleep_after=3)
        async for video in api.user(username="laufey").videos(count=1):
            print(video.id)
            return

if __name__ == "__main__":
    asyncio.run(get_videos())

**Comment by luca4s** [comment]
> Try this:
> 
> async def get_videos(): async with TikTokApi() as api: await api.create_sessions(ms_tokens=[ms_token], num_sessions=1, sleep_after=3) async for video in api.user(username="laufey").videos(count=1): print(video.id) return
> 
> if **name** == "**main**": asyncio.run(get_videos())

works fine for me, thanks!
