### ISSUE TITLE
video.info() TikTokApi.exceptions.InvalidResponseException: 200 -> TikTok returned an invalid response.

### ISSUE THREAD

**Issue by jimmychuang95** [davidteather/TikTok-Api#1064]
video.info() TikTokApi.exceptions.InvalidResponseException: 200 -> TikTok returned an invalid response.

**Comment by eliich** [comment]
same

**Comment by eliich** [comment]
Im getting that error inconsistently, when trying to retrieve video metadata from specific user. Helped when I used a slightly aged ms_token(around 1 min).

**Comment by serpentinesr** [comment]
any updates to this one?

**Comment by timmy-code12** [comment]
Currently dealing with the same issue, has anyone figured out what the issue might be?

**Comment by zakrian07** [comment]
im having same issue it work on my 1 DO instance but never working on my local environment if i trie proxy it say timeout after 30 sec
