### ISSUE TITLE
run the user_example and I get many videos and video url, But I can not open the video url in chrome , what should I do to open it?

### ISSUE THREAD

**Issue by tlament** [davidteather/TikTok-Api#1066]
run the user_example and I get many videos and video url, But I can not open the video url in chrome , what should I do to open it?

**Comment by eliich** [comment]
video url is tied to cookies/timestamp and wont load if not from same session or close time to timestamp. assuming youre talking  about this ```https://v16-webapp-prime.us.tiktok.com/video/tos/useast5/...```. 

If you are trying to download video you need to use another tool, as this doesn't support downloading videos. I would suggest yt-dlp.

**Comment by tlament** [comment]
I tried yt-dlp to download and got it, Thank you very much!

**Comment by etale-cohomology** [comment]
I wonder how the URL can used to actually download a video in practice though, from scratch, without using a tool like yt-dlp (which actually works).
