### ISSUE TITLE
TikTokApi on CentOS

### ISSUE THREAD

**Issue by ZhangNemo34** [davidteather/TikTok-Api#107]
**Describe the bug**
I have a problem to make this module work on CentOS.
I am using Python3.7 and I've already pip installed TikTokApi, pyppeteer.

When I use TikTokApi I always get an error message that "pyppeteer.errors.BrowserError: Browser closed unexpectedly"

![image](https://user-images.githubusercontent.com/32252145/83318119-8a1e1a00-a1e6-11ea-9af1-7a90c63c2ef8.png)

I am pretty sure that it might be a dependency problem but I don't have any clue how to resolve this.

Because I've followed the guide written in the document and it is not working.

May thanks in advance.

**Comment by davidteather** [comment]
Try the solutions in #95
