### ISSUE TITLE
playwright._impl._api_types.Error: TypeError: Cannot read properties of undefined (reading 'frontierSign')

### ISSUE THREAD

**Issue by glenn-jocher** [davidteather/TikTok-Api#1074]
**Describe the bug**

Demo code does not work, produces error below:

```python
Traceback (most recent call last):
  File "/content/download_trending.py", line 17, in <module>
    asyncio.run(trending_videos())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/content/download_trending.py", line 12, in trending_videos
    async for video in api.trending.videos(count=30):
  File "/usr/local/lib/python3.10/dist-packages/TikTokApi/api/trending.py", line 43, in videos
    resp = await Trending.parent.make_request(
  File "/usr/local/lib/python3.10/dist-packages/TikTokApi/tiktok.py", line 416, in make_request
    signed_url = await self.sign_url(encoded_params, session_index=i)
  File "/usr/local/lib/python3.10/dist-packages/TikTokApi/tiktok.py", line 353, in sign_url
    x_bogus = (await self.generate_x_bogus(url, session_index=i)).get("X-Bogus")
  File "/usr/local/lib/python3.10/dist-packages/TikTokApi/tiktok.py", line 341, in generate_x_bogus
    result = await session.page.evaluate(
  File "/usr/local/lib/python3.10/dist-packages/playwright/async_api/_generated.py", line 8665, in evaluate
    await self._impl_obj.evaluate(
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_page.py", line 389, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_frame.py", line 271, in evaluate
    await self._channel.send(
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
  File "/usr/local/lib/python3.10/dist-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: TypeError: Cannot read properties of undefined (reading 'frontierSign')
    at eval (eval at evaluate (:216:30), <anonymous>:1:38)
    at UtilityScript.evaluate (<anonymous>:223:19)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
```

**The buggy code**

Exact code in README example, nothing changed except for inlined ms_token definition (hidden here for privacy).
```python
from TikTokApi import TikTokApi
import asyncio
import os

ms_token = 'v9tj...'

async def trending_videos():
    async with TikTokApi() as api:
        await api.create_sessions(ms_tokens=[ms_token], num_sessions=1, sleep_after=3)
        async for video in api.trending.videos(count=30):
            print(video)
            print(video.as_dict)

if __name__ == "__main__":
    asyncio.run(trending_videos())
```

**Desktop (please complete the following information):**
 - OS: Linux
 - TikTokApi-6.1.1

**Comment by Suchismit4** [comment]
Was this fixed?

**Comment by jamiemlee** [comment]
I'm able to sporadically get it to run if I remove ms_tokens completely. But it's not 100%

**Comment by yangsu10yen** [comment]
Hi, 
I have investigated the cause of this problem and found that sometimes it succeeds.
So I added the following retry process and it seems to work almost perfectly.

Hope this will help you.

```diff
diff --git a/TikTokApi/tiktok.py b/TikTokApi/tiktok.py
index c52838b..ac69679 100644
--- a/TikTokApi/tiktok.py
+++ b/TikTokApi/tiktok.py
@@ -367,7 +367,7 @@ class TikTokApi:
         url: str,
         headers: dict = None,
         params: dict = None,
-        retries: int = 3,
+        retries: int = 5,
         exponential_backoff: bool = True,
         **kwargs,
     ):
@@ -423,10 +423,16 @@ class TikTokApi:
             )
 
             if result is None:
-                raise Exception("TikTokApi.run_fetch_script returned None")
+                if i == (retries - 1):
+                    raise Exception("TikTokApi.run_fetch_script returned None")
+                else:
+                    continue
 
             if result == "":
-                raise EmptyResponseException()
+                if i == (retries - 1):
+                    raise EmptyResponseException()
+                else:
+                    continue
 
             try:
                 data = json.loads(result)

```

**Comment by yukon12345** [comment]
> Hi, I have investigated the cause of this problem and found that sometimes it succeeds. So I added the following retry process and it seems to work almost perfectly.
> 
> Hope this will help you.
> 
> ```diff
> diff --git a/TikTokApi/tiktok.py b/TikTokApi/tiktok.py
> index c52838b..ac69679 100644
> --- a/TikTokApi/tiktok.py
> +++ b/TikTokApi/tiktok.py
> @@ -367,7 +367,7 @@ class TikTokApi:
>          url: str,
>          headers: dict = None,
>          params: dict = None,
> -        retries: int = 3,
> +        retries: int = 5,
>          exponential_backoff: bool = True,
>          **kwargs,
>      ):
> @@ -423,10 +423,16 @@ class TikTokApi:
>              )
>  
>              if result is None:
> -                raise Exception("TikTokApi.run_fetch_script returned None")
> +                if i == (retries - 1):
> +                    raise Exception("TikTokApi.run_fetch_script returned None")
> +                else:
> +                    continue
>  
>              if result == "":
> -                raise EmptyResponseException()
> +                if i == (retries - 1):
> +                    raise EmptyResponseException()
> +                else:
> +                    continue
>  
>              try:
>                  data = json.loads(result)
> ```

In a similar vein, I found that if you have a bad network speed environment, such as using a proxy, you can get a high probability of success in getting comments, while on a good network, this error will be repeatedly displayed.... That should  some place retry requests be too fast..

**Comment by Lewington-pitsos** [comment]
I got the same error as @glenn-jocher I then made these changes and continue to get the exact same error.





> Hi, I have investigated the cause of this problem and found that sometimes it succeeds. So I added the following retry process and it seems to work almost perfectly.
> 
> Hope this will help you.
> 
> ```diff
> diff --git a/TikTokApi/tiktok.py b/TikTokApi/tiktok.py
> index c52838b..ac69679 100644
> --- a/TikTokApi/tiktok.py
> +++ b/TikTokApi/tiktok.py
> @@ -367,7 +367,7 @@ class TikTokApi:
>          url: str,
>          headers: dict = None,
>          params: dict = None,
> -        retries: int = 3,
> +        retries: int = 5,
>          exponential_backoff: bool = True,
>          **kwargs,
>      ):
> @@ -423,10 +423,16 @@ class TikTokApi:
>              )
>  
>              if result is None:
> -                raise Exception("TikTokApi.run_fetch_script returned None")
> +                if i == (retries - 1):
> +                    raise Exception("TikTokApi.run_fetch_script returned None")
> +                else:
> +                    continue
>  
>              if result == "":
> -                raise EmptyResponseException()
> +                if i == (retries - 1):
> +                    raise EmptyResponseException()
> +                else:
> +                    continue
>  
>              try:
>                  data = json.loads(result)
> ```



Also the error is related to 

`  File "/usr/local/lib/python3.10/dist-packages/TikTokApi/tiktok.py", line 416, in make_request
    signed_url = await self.sign_url(encoded_params, session_index=i)`

A line which sits just **before** the modified code.

It seems to be something to do with playwright not having the "frontierSign" object defined, rather than some kind of networking issue.

**Comment by Lewington-pitsos** [comment]
OK, this fixed the error for me:         

find the code in toktok.py 
```
result = await session.page.evaluate(
    f'() => {{ return window.byted_acrawler.frontierSign("{url}") }}'
)
``` 

add an extra line just above


```
await session.page.wait_for_function("window.byted_acrawler !== undefined")
print('finished waiting')
result = await session.page.evaluate(
    f'() => {{ return window.byted_acrawler.frontierSign("{url}") }}'
)
``` 

looks like `byted_acrawler` is lazy loaded, so often it doesn't exist at the time we call `session.page.evaluate`. Such a shame the maintainer got an internship :'(

**Comment by glenn-jocher** [comment]
@Lewington-pitsos awesome! I haven't tested this but I've opened a PR with your recommended fix in https://github.com/davidteather/TikTok-Api/pull/1080. Does that look right?

**Comment by ketanmalempati** [comment]
Hey did you guys get it working?
I am getting this error TypeError: TikTokException.__init__() missing 2 required positional arguments: 'raw_response' and 'message'
after making the changes mentioned above

**Comment by Jordan-Mesches** [comment]
> Hey did you guys get it working? I am getting this error TypeError: TikTokException.**init**() missing 2 required positional arguments: 'raw_response' and 'message' after making the changes mentioned above

same

**Comment by glenn-jocher** [comment]
@ketanmalempati @Jordan-Mesches yes it appears my PR still does not work :(

If anyone knows how to resolve this please let us know!!

**Comment by MorgusLethe** [comment]
I am getting the same errors as others in this thread. I have just started to use this project and it's a shame the examples don't work right now.

To be clear I tried adding this line as explained by @Lewington-pitsos, but the example for getting video comments then outputs "missing 2 required positional arguments: 'raw_response' and 'message'".

**Comment by shinitiandrei** [comment]
Hey guys, thank you very much for providing this tool

After changes applied locally with: https://github.com/davidteather/TikTok-Api/pull/1080

I was able to get passed the 'raw_response' and 'message' error by doing this:
https://github.com/davidteather/TikTok-Api/issues/1053#issuecomment-1764871049
in my case, just had to add "headless=False" and "override_browser_args=["--incognito"]" to the call.

I hope this helps :)

**Comment by glenn-jocher** [comment]
@shinitiandrei this works! Thanks for the tip! 

Do you know by chance how to download the videos that are returned?

**Comment by shinitiandrei** [comment]
> @shinitiandrei this works! Thanks for the tip!
> 
> Do you know by chance how to download the videos that are returned?

Hey @glenn-jocher , I haven't done that yet but according to this: https://github.com/davidteather/TikTok-Api/blob/fdde79816fc8bf2b84a27e1cf6603ef572b5ec7e/TikTokApi/api/video.py#L138
It's still to be implemented I guess
