### ISSUE TITLE
[BUG] - ERROR get user info

### ISSUE THREAD

**Issue by hanmactu2112** [davidteather/TikTok-Api#1078]
Fill Out the template :)

**Describe the bug**

2023-10-12 12:37:18,213 - TikTokApi.tiktok - ERROR - Got an unexpected status code: {'userInfo': {'user': {}, 'stats': {}, 'shareMeta': {}}}
Traceback (most recent call last):
  File "/home/su/tiktok/python/test_user_v64.py", line 53, in <module>
    asyncio.run(user_example())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/su/tiktok/python/test_user_v64.py", line 31, in user_example
    user_data = await user.info()
  File "/home/su/.local/lib/python3.10/site-packages/TikTokApi/api/user.py", line 87, in info
    self.__extract_from_data()
  File "/home/su/.local/lib/python3.10/site-packages/TikTokApi/api/user.py", line 204, in __extract_from_data
    data["userInfo"]["user"]["id"],
KeyError: 'id'

**The buggy code**

# Code Goes Here
```
from TikTokApi import TikTokApi
import asyncio
import os
import json
import requests

def get_cookies_from_file():
    with open('cookies.json') as f:
        cookies = json.load(f)

    cookies_kv = {}
    for cookie in cookies:
        cookies_kv[cookie['name']] = cookie['value']

    return cookies_kv

cookies = get_cookies_from_file()

def get_cookies(**kwargs):
    return cookies

ms_token = os.environ.get(
    "ms_token", None
)  # set your own ms_token, think it might need to have visited a profile


async def user_example():
    async with TikTokApi() as api:
        await api.create_sessions(ms_tokens=[ms_token], num_sessions=1, sleep_after=3)
        user = api.user("marianrivera")
        user_data = await user.info()
        print(user_data)
        print(ms_token)

        async for video in user.videos(count=10):
            print("-----")
            print(video.id)
            print(video.author.username)
            print(video.as_dict)
            print(video.author.username)
            # URL = "http://192.168.1.88:8217/tiktok-scraper/v1/test/get/title?type=Sexy Girl"
            # DATA = video.as_dict
            #
            # ID_VIDEO = video.id
            # AUTHOR = video.author.username
            # PARAMS = {'id':ID_VIDEO, 'author':AUTHOR}
            # r = requests.post(url = URL,json=DATA)
            # data = r.json()
            # print(data)


if __name__ == "__main__":
**Expected behavior**

**Comment by JermellB** [comment]
You're probably getting bot checked. 

Try a proxy or vpn.

Also, from a regular browser get the 

```
ms_token = os.environ.get(
    "ms_token", None
)  # set your own ms_token, think it might need to have visited a profile
```

The response returned empty because you're probably getting some kinda challenge.

**Comment by jpratt9** [comment]
@JermellB do you have a way to programmatically generate those tokens so we can avoid the bot check?
