### ISSUE TITLE
is there any way to get user linked account(Instagram,Facebook)[question]

### ISSUE THREAD

**Issue by shmulik323** [davidteather/TikTok-Api#112]
hi David ,is there any way to get user linked account?
tnx in advanced 
Shmuel.M

**Comment by davidteather** [comment]
Can you provide an example of a tiktok user with a linked social media account?

**Comment by shmulik323** [comment]
![image](https://user-images.githubusercontent.com/7191121/83794017-052f7680-a6a6-11ea-8dab-5a80f7319d7a.png)

I see that only the application but I'm not signed in ,so I thought maybe it was possible

**Comment by davidteather** [comment]
Sorry I don't think so. The view on desktop is a little different and doesn't show the linked social media. The tiktok app on mobile has more features than the desktop version.

![image](https://user-images.githubusercontent.com/34144122/83795379-fc6a8080-a664-11ea-8b28-141da3c543e9.png)
