### ISSUE TITLE
Any function returns permanently empty fields

### ISSUE THREAD

**Issue by nedoai** [davidteather/TikTok-Api#1128]
The basic function that is provided in the documentation returns status_code = 0 and that's it. All other functions return an empty dictionary in the same way.

**Comment by nedoai** [comment]
> I also get an empty response. [But status code 0 is the same as status code 200, which means OK](https://github.com/davidteather/TikTok-Api/issues/403#issuecomment-971818109)

Oh, thanks. But the question with empty answers remains open

**Comment by jdeplato** [comment]
Using the comment example and not altering it, I'm getting the following error:

  File "C:\Python312\Lib\site-packages\TikTokApi\tiktok.py", line 430, in make_request
    raise EmptyResponseException(result, "TikTok returned an empty response")
TikTokApi.exceptions.EmptyResponseException: None -> TikTok returned an empty response

Any updates / assistance would be appreciated - could TikTok have updated/changed their API endpoint?

**Comment by HTShin** [comment]
I also get this issue and try change another API endpoint, but not working.

I guess Tiktok API update header to get data

Ref Tiktok API endpoint: https://gist.github.com/nhandt64/f691579d31898ee023d921dd21866c54

**Comment by Gereks123** [comment]
When using the example of fetching a user: https://github.com/davidteather/TikTok-Api/blob/main/examples/user_example.py

I get the following error: Got an unexpected status code: {'userInfo': {'user': {}, 'stats': {}, 'shareMeta': {}}} data["userInfo"]["user"]["id"],
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'id'

Seems like the headers are updated/API endpoints have changed

**Comment by tigra323** [comment]
Solution here: [#1090 (comment)](https://github.com/davidteather/TikTok-Api/issues/1090#issuecomment-2030409545)
Addition: here links for browsers: [linux](https://storage.googleapis.com/chrome-for-testing-public/115.0.5790.170/linux64/chrome-linux64.zip) [win32](https://storage.googleapis.com/chrome-for-testing-public/115.0.5790.170/win32/chrome-win32.zip) [win64](https://storage.googleapis.com/chrome-for-testing-public/115.0.5790.170/win64/chrome-win64.zip) from [here](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)
