### ISSUE TITLE
[BUG]likePost and unlikePost

### ISSUE THREAD

**Issue by tab-1** [davidteather/TikTok-Api#113]
**Describe the bug**

Can I do likePost and unlikPost ?

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by davidteather** [comment]
There's no support for logging into TikTok as a user right now sorry about that.
