### ISSUE TITLE
music have 40k videos but scrab only 4k videos

### ISSUE THREAD

**Issue by lazezo2** [davidteather/TikTok-Api#1131]
music ids have 40k videos but scarab only 4k videos or less...
any one know how to fix that?
why we cant scarab all videos? i know some videos are private but at least scab close number to music videos...

**Comment by pulakmehta** [comment]
Can you share your working code? Would like to see if I can help debug.

**Comment by davidteather** [comment]
TikTok Limits Web Endpoints to 4K afaik at least if you're not logged in

**Comment by lazezo2** [comment]
> TikTok Limits Web Endpoints to 4K afaik at least if you're not logged in

i already logged in while scabbing...
