### ISSUE TITLE
RuntimeWarning: coroutine 'browser.start' was never awaited and nothing is printed on async [BUG]

### ISSUE THREAD

**Issue by elblogbruno** [davidteather/TikTok-Api#115]
**Describe the bug**
I'm putting this api inside a discord bot using discord.py, thus I'm running the api inside an async function. I'm getting this error that makes the bot close.
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited

**The buggy code**

async def tiktok_interact(message,channel):

    trending = api.trending(results)
    
    for tiktok in trending:
        # Prints the text of the tiktok
        print(tiktok['desc'])
        await channel.send(tiktok['video']['cover'])

    print(len(trending))

**Expected behavior**

await channel.send function makes the bot send whatever text or input I insert. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10481058/83858950-8b3ad400-a71d-11ea-8e89-90c80a111378.png)

**Additional context**

I'm running it on a debian 9 VPS.

**Comment by davidteather** [comment]
You need to update your TikTokApi package. TikTok made changes yesterday that broke the package. Update with the following command.

```
pip install TikTokApi --upgrade
```

**Comment by elblogbruno** [comment]
![image](https://user-images.githubusercontent.com/10481058/83903771-007ac900-a75f-11ea-8b35-a2e0e2fa0fc7.png)
I'm still having the same issue!

**Comment by davidteather** [comment]
I'll be releasing a patch later today that might help your issue.

**Comment by elblogbruno** [comment]
Thank you!🤗

**Comment by elblogbruno** [comment]
Now I simply don't have an answer back from the library and after a long time this pops up
![image](https://user-images.githubusercontent.com/10481058/83919154-501abe00-a77a-11ea-9cee-02c5f5b9c107.png)

**Comment by davidteather** [comment]
I'm not super great with asyncio and I haven't run into this issue so I'll leave this open hoping someone else finds a solution.

**Comment by Inzilkin** [comment]
Yes, i'm know to find solution.
1) Rewrite all library to async
// async def ..
2) delete from start pyppeteer class  asyncio loop
![image](https://user-images.githubusercontent.com/32675835/83949842-7a827f00-a83f-11ea-906d-083650d7d8f9.png)
3) start browser like that:
![image](https://user-images.githubusercontent.com/32675835/83949850-88380480-a83f-11ea-951a-58985fa739de.png)
4) You have work async library

**Comment by Inzilkin** [comment]
3. 1. Use aiohttp session or another async library.
Thanks for reading my solution :)

**Comment by Inzilkin** [comment]
@davidteather, please rewrite requests to aiohttp.

**Comment by elblogbruno** [comment]
There's any update about this?
Thanks

**Comment by elblogbruno** [comment]
Now is not printing anything.

**Comment by elblogbruno** [comment]
https://github.com/pyppeteer/pyppeteer/issues/143 Based on this I added autoClose to false and now it does not print anything and the program closes.

**Comment by Rodrigo-ip** [comment]
I'm getting the same thing : RuntimeWarning: coroutine 'browser.start' was never awaited then gc.collect()

**Comment by crazygmr101** [comment]
I can confirm running this in a discord bot breaks things. In my case, it's https://github.com/davidteather/TikTok-Api/blob/master/TikTokApi/browser.py#L52-L57. Writing those to use the *current* event loop, and using run_in_executor *should* fix the issue and allow it to be used with async libraries

**Comment by elblogbruno** [comment]
Awesome @crazygmr101 let us know!

**Comment by crazygmr101** [comment]
I submitted #198  - I'm not sure if it fixes this issue, but I did run it in a discord bot with
```
@bot.command()
async def tiktok(ctx: commands.Context, link: str):
    video = api.getTikTokByUrl(link)["itemInfo"]["itemStruct"]["video"]
    print(video)
```

**Comment by davidteather** [comment]
Try to use my comment on #235 it should resolve your issue. It might throw a lot of errors when the bot is closed, but it'll work.

**Comment by elblogbruno** [comment]
Ok thanks I will test asap!

**Comment by alvesdavidr** [comment]
> 
> 
> I submitted #198 - I'm not sure if it fixes this issue, but I did run it in a discord bot with
> 
> ```
> @bot.command()
> async def tiktok(ctx: commands.Context, link: str):
>     video = api.getTikTokByUrl(link)["itemInfo"]["itemStruct"]["video"]
>     print(video)
> ```

I am trying to utilize the API within Discord.py but I'm still running into issues with async. The above code snippet is very similar to what I'd like to implement, but where did you initialize the api = TikTokApi() ?
