### ISSUE TITLE
Data from the past

### ISSUE THREAD

**Issue by hubdreadp** [davidteather/TikTok-Api#1152]
Hi everyone, I know that my demand is more a db-related matter instead of a thing that web scraping api can afford, but either way I'm asking in case anybody knows any possible solution.
I'd like to collect tiktok data with a diachronic perspective, for example monitoring a profile/comment/post stats from its first days up to now. The now (and the future) its not the problem since I can use the api for this purpose, but do you know how to get back to past days? Is it possible through any proxies or anything else?
Thanks for your time considering my question :)

**Comment by ekorian** [comment]
Hello, it is not possible.

**Comment by hubdreadp** [comment]
as I expected. Thanks anyway
