### ISSUE TITLE
Follwer/following lists

### ISSUE THREAD

**Issue by tarkhil** [davidteather/TikTok-Api#117]
Currently, TikTokApi does not support requests of the following/followers list of user.
I've serached inet but so far found only some old and obsolete implementetion using requests like aweme/v1/user/following/list/?user_id=. My attempt to guess working path yielded no success.
Maybe someone has knowledge on this topic?

**Comment by davidteather** [comment]
Yeah I believe TikTok has deprecated the ability to get a follower list.

**Comment by tarkhil** [comment]
As far as I know, three companies offers that functionality.
