### ISSUE TITLE
API response for getUserObject has changed?

### ISSUE THREAD

**Issue by dj2ball** [davidteather/TikTok-Api#118]
File "C:\development\tiktok\env\lib\site-packages\TikTokApi\tiktok.py", line 301, in getUserObject
    return self.getData(api_url, b.signature, b.userAgent)['userInfo']['user']
KeyError: 'userInfo'

Looks like there has been an update to the JSON layout?

**Comment by davidteather** [comment]
Make sure your package is up to date. There was an update that fixed something tiktok changed yesterday. 

pip install TikTokApi —upgrade
