### ISSUE TITLE
Sentence: Add async

### ISSUE THREAD

**Issue by Inzilkin** [davidteather/TikTok-Api#123]
Hello everyone who reads this issue. I would like to ask to add async to this api, I just have to copy corrections from the new commit to change my code and this is not very convenient. RapidApi also has a limitation in the basic version for requests, for this reason I can not use it. Thank you very much for reading my suggestion.

**Comment by davidteather** [comment]
You’re able to make multiple calls to the api at once. The rapid api I have is running flask and the library is able to handle multiple requests at once.

**Comment by Inzilkin** [comment]
![image](https://user-images.githubusercontent.com/32675835/83949488-82412400-a83d-11ea-958b-474131b2f123.png)

**Comment by davidteather** [comment]
> I would like to ask to add async to this api

My point is that the library supports async and is able to handle multiple requests.

**Comment by Inzilkin** [comment]
It's doesn't true :(
RuntimeError: Cannot run the event loop while another loop is running
sys:1: RuntimeWarning: coroutine 'browser.start' was never awaited

**Comment by Inzilkin** [comment]
I'm starting in aiohttp and it's doesn't works.

**Comment by davidteather** [comment]
Run the following command what does it output

```
pip show TikTokApi
```

**Comment by davidteather** [comment]
#115
