### ISSUE TITLE
[FEATURE_REQUEST] - Expose all user data

### ISSUE THREAD

**Issue by Xodarap** [davidteather/TikTok-Api#125]
`getUserObject` just returns `self.getData(api_url, b.signature, b.userAgent)['userInfo']['user']`. I want the whole thing.

Could you create a `getUser` method which returns everything?

I can currently do it via subclassing, but that's mildly annoying:

```
class BenTikTokApi(TikTokApi):
    def getUser(self, username, language='en'):
        api_url = "https://m.tiktok.com/api/user/detail/?uniqueId={}&language={}&verifyFp=".format(
            username, language)
        b = browser.browser(api_url)
        return self.getData(api_url, b.signature, b.userAgent)
```

(My particular use case is that I want a follower count. It seems that the exact follower list is not available per #120, but the count would be nice)

**Comment by davidteather** [comment]
Merged in 3.1.4

**Comment by coreyli1** [comment]
For this method, what would you put in the argument? I have tried using a tiktoker's user name but end up with an "Invalid Response" error

**Comment by davidteather** [comment]
Api is broken see #154
