### ISSUE TITLE
[FEATURE_REQUEST] - getLikeCount

### ISSUE THREAD

**Issue by tytech038** [davidteather/TikTok-Api#131]
**Describe the solution you'd like**
getLikeCount would be printed on the screen or on a variable.

**Describe alternatives you've considered**
web scraping

**Additional context**
I need to track the likes on a video.

**Comment by tytech038** [comment]
with an input url too btw

**Comment by davidteather** [comment]
There’s a diggCount in the tiktok object which is the like count, so you just really need to get the tiktok object by a url. I’ll combine this request with #61
