### ISSUE TITLE
[INSTALLATION] - Your error here

### ISSUE THREAD

**Issue by LegionerJ** [davidteather/TikTok-Api#132]
Hello , I  get the error below when I run file.py : file.py is the Quick Start codes.

[https://ibb.co/wcVZVVv](screen-shot)

 I 've installed chromedriver but nothing changed.

**Comment by davidteather** [comment]
It’s can’t see that image it doesn’t seem to be a valid url. If you copy the image and paste into GitHub it’ll automatically embed the image

**Comment by davidteather** [comment]
Ok I managed to figure out why that url wasn’t working. Please see issue #88
