### ISSUE TITLE
[FEATURE_REQUEST] - Get Videos by User ID Instead of Username

### ISSUE THREAD

**Issue by bryan** [davidteather/TikTok-Api#133]
**Is your feature request related to a problem? Please describe.**
A user can change their username which breaks certain scripts based on a variable name.

**Describe the solution you'd like**
Having the ability to input a user id as a parameter instead of user name is more effective as the user id does not change per profile. 

**Describe alternatives you've considered**
You can create a local cache of a user and their user id to handle this, but it would be more elegant if there is a way to leverage the user id. I am unsure if there is an open endpoint that is based off the id that would make this possible.

**Comment by davidteather** [comment]
Already exists here’s the method header 
userPosts(self, userID, secUID, count=30, language='en')
