### ISSUE TITLE
[INSTALLATION] - All "api.___ " function is taking forever to execute"

### ISSUE THREAD

**Issue by JoyceJiang73** [davidteather/TikTok-Api#137]
**Describe the error**

All api.___() functions are taking forever to execute 

**The buggy code**

`
from TikTokApi import TikTokApi
api = TikTokApi()

results = 10

trending = api.trending(count=results)

for tiktok in trending:
    print(tiktok['desc'])

print(len(trending))
`

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome]
 - Version [e.g. 82]

**Additional context**

It's not like I'm receiving any error message. This section of the code is taking forever to execute --kernel keeps running for hours at this step

**Comment by davidteather** [comment]
What os and python version are you on? Any virtual environments?

**Comment by JoyceJiang73** [comment]
> What os and python version are you on? Any virtual environments?
> Windows 10 and Python 3.7. I'm not using any virtual environments.

> Have you had this api working in the past?
> No I didn't. Do I need an API key from TikTok to run this API?

> From the little information I have. I’ve got to assume it’s an error with the browser part of the script.
> I tried with both windows and mac OS. For Mac OS, I won't be able to install a version of urllib3 that satisfies both requests and pyppeteer. But this issue doesn't happen on my Windows OS. I used "pip install -r requirements.txt" to install all libraries successfully. 

Same issue happening on both Mac and Windows OS: it's taking forever to execute the code

> What happens when you type chromedriver into your terminal?
I got this "'chromedriver' is not recognized as an internal or external command,
operable program or batch file."

But I can open chrome with "start chrome" in the command line.

**Comment by davidteather** [comment]
Ok to fix your issue I believe you will need to install chromedriver globally on your system. Get chromedriver [here](https://chromedriver.chromium.org/) download the correct version for your system and add the file to your system environmental variables.

To check if this works you should be able to run the chromedriver command. Then hopefully this library will work for you.

**Comment by JoyceJiang73** [comment]
Hi David, thank you so much! I installed chromedriver globally. But it seems the issue occurs because I'm running it on Jupyter Notebook. Once I change it back to the terminal, everything works out!!

**Comment by davidteather** [comment]
Glad you figured it out!

**Comment by nitneo** [comment]
Hello, i am facing the same error, am trying the first example code and looks like it is taking forever to download something. I also installed chromedriver as instructed above and set up the path and checked it again from cmd prompt, but again no success.
