### ISSUE TITLE
[FEATURE_REQUEST] - Support for user/password on proxies

### ISSUE THREAD

**Issue by dj2ball** [davidteather/TikTok-Api#138]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

Pyppeteer does not support the passing of proxy user/pass via command line (which is the format Requests takes them in). In the current implementation requests will accept a https://user:pass@ip:port formatted proxy, but Pypeteer will throw an error.

I have tested some code offline and have got this working ok, if you’d like I can make a pull request to incorporate the change 

**Describe the solution you'd like**

passing of user/pass as separate argument alongside the proxy (how I managed to implement it) then some logic in the Browser.py file to skip the login section if login details aren’t provided

**Describe alternatives you've considered**

**Additional context**

**Comment by davidteather** [comment]
That’d be great if you can make a PR thanks.

**Comment by dj2ball** [comment]
Just submitted.

**Comment by davidteather** [comment]
There's a new release out. Does this version solve your problem?

**Comment by dj2ball** [comment]
Much more elegant than my hacked together code!

**Comment by davidteather** [comment]
I uploaded a new version again does this one fix the issue with puppeteer?

**Comment by dj2ball** [comment]
Indeed - working well!
