### ISSUE TITLE
[INSTALLATION] - Is it possible to get a code snippet for launching the API functions asynchronously?

### ISSUE THREAD

**Issue by dj2ball** [davidteather/TikTok-Api#143]
I'm not experienced in writing asyncio code and while writing a basic  loop and trying to make an api call I'm getting a "Cannot run the event loop while another loop is running
sys:1: RuntimeWarning: coroutine 'browser.start' was never awaited" error. This is definitely down to my code, not the module, but a basic snippet of the implementation of async on say "getUserObject" would be great.

**Comment by davidteather** [comment]
Yeah I’ve been unable to reproduce this issue. You can use this api in an asynchronous wrapper style like with flask. 
See #115 for more information on this issue

**Comment by Inzilkin** [comment]
@davidteather, hi. I can rewrite your library to asynchronous.
