### ISSUE TITLE
[INSTALLATION] - TikTokApi with Juypter Notebook

### ISSUE THREAD

**Issue by caneale320** [davidteather/TikTok-Api#146]
Runtime error upon running the sample code from installation
`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-3eb3fc6ad4cf> in <module>
----> 1 trending = api.trending(results)

~\Anaconda3\lib\site-packages\TikTokApi\tiktok.py in trending(self, count, language, proxy)
     84             api_url = "https://m.tiktok.com/api/item_list/?count={}&id=1&type=5&secUid=&maxCursor={}&minCursor=0&sourceType=12&appId=1233&region=US&language={}&verifyFp=".format(
     85                 str(realCount), str(maxCursor), str(language))
---> 86             b = browser(api_url, language=language, proxy=proxy)
     87             res = self.getData(api_url, b.signature,
     88                                b.userAgent, language=language, proxy=proxy)

~\Anaconda3\lib\site-packages\TikTokApi\browser.py in __init__(self, url, language, proxy, find_redirect)
     42             loop.run_until_complete(self.find_redirect())
     43         else:
---> 44             loop.run_until_complete(self.start())
     45 
     46     async def start(self):

~\Anaconda3\lib\asyncio\base_events.py in run_until_complete(self, future)
    564         future.add_done_callback(_run_until_complete_cb)
    565         try:
--> 566             self.run_forever()
    567         except:
    568             if new_task and future.done() and not future.cancelled():

~\Anaconda3\lib\asyncio\base_events.py in run_forever(self)
    522         if events._get_running_loop() is not None:
    523             raise RuntimeError(
--> 524                 'Cannot run the event loop while another loop is running')
    525         self._set_coroutine_origin_tracking(self._debug)
    526         self._thread_id = threading.get_ident()

RuntimeError: Cannot run the event loop while another loop is running
`
**The buggy code**

`api = TikTokApi()

results = 10

trending = api.trending(results)`

 - OS: Windows 10
 - Browser: Chrome

**Additional context**

It seems like this may be an issue with how Juypter handles events, however help finding a workaround would be appreciated.

**Comment by davidteather** [comment]
Yeah it’s a Juypeter issue with asyncio. It’s got to do something on how it handles threads and loops.

**Comment by diviramon** [comment]
You need to install asyncio as explained here: https://markhneedham.com/blog/2019/05/10/jupyter-runtimeerror-this-event-loop-is-already-running/

After that, the error won't show up any longer. However, it find it goes into an infinite loop and it never returns anything. Any help or ideas?

**Comment by crazygmr101** [comment]
This is a Jupyter-specific issue, from what I've seen. I made a pr that might fix this, but another solution I've seen is to install the package `nest_asyncio` and
```
import nest_asyncio
nest_asyncio.apply()
``` I didn't have much luck trying that in a normal python installation, and haven't tried Jupyter, so YMMV

**Comment by thecoolwinter** [comment]
Same issue here. Anyone found a fix? I'm afraid I'm not very good with python and I'm stuck with this issue

**Comment by crazygmr101** [comment]
@thecoolwinter #198 is a fix, otherwise the library would have to be rewritten slightly :shrug:

**Comment by davidteather** [comment]
#198 has been merged should work now
