### ISSUE TITLE
[BUG] - Multiple Chromium process are stacking up

### ISSUE THREAD

**Issue by yas-h** [davidteather/TikTok-Api#147]
**Describe the bug**
When downloading multiple videos multiple chrome/chromium process are stacking in the task manager.The ratio is almost 4-5 times the number of videos.

**The buggy code**

    c=1 
    f=open("links.txt","r") # links.txt contains the links of videos to be downloaded. 
    lines=f.readlines()
    for x in lines:      
        x=x.strip()
        tiktokData = api.get_Video_No_Watermark(str(x), return_bytes=1)               
        with open("%d.mp4"%c, 'wb') as out:
            out.write(tiktokData)
       c=c+1
**Expected behavior**
Chrome process should automatically close upon each download completion.
**Screenshots**

![Screenshot from 2020-06-13 01-43-17](https://user-images.githubusercontent.com/59865275/84542931-08ff7080-ad18-11ea-857c-389980fb0867.png)

**Desktop**
 - OS: Windows 8.1 and Linux Mint
 
**Additional context**

My use of this code is on windows, same issue persist there too.

**Comment by davidteather** [comment]
Thanks for the bug report! The code is just missing a line to close the browser on that specific method. I’ll issue a patch later today.

**Comment by davidteather** [comment]
Just released an update to fix this.

```
pip install TikTokApi --upgrade
```
