### ISSUE TITLE
[BUG] - Status Code 10204

### ISSUE THREAD

**Issue by Coloradohusky** [davidteather/TikTok-Api#148]
**Describe the bug**

When running `api.getTikTokById` on a silent video's ID, it returns `{'statusCode': 10204}` when it should return a TikTok object.

**The buggy code**

```
from TikTokApi import TikTokApi

api = TikTokApi()
tiktoks = api.byUsername('penguins')
for tiktok in tiktoks:
    if (tiktok['id'] == '6791925545199258886'):
        print(tiktok)

newTik = api.getTikTokById('6791925545199258886')
print (newTik)
```

**Expected behavior**

The code above shows what happens when the ID is found from `api.byUsername` and how the result is different when calling `api.getTikTokById` for the same ID.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Default is Chrome
 - Version 3.1.9

**Additional context**

Silent videos have always been a problem on desktop TikTok, [direct links don't work](https://www.tiktok.com/share/video/6791925545199258886) but [clicking on the video works](https://imgur.com/a/iZkUc6f).

**Comment by davidteather** [comment]
This seems to be a strange TikTok shadow banning on the video in question.

Below is the valid URL, but you can't directly navigate to it.
```
https://www.tiktok.com/@penguins/video/6791925545199258886
```

If you go to the following link and click the arrow on the right it'll show up with an identical url
```
https://www.tiktok.com/@penguins/video/6795636641642843398
```

TikTok has censored LGBTQ+ content on their platform and that video in question probably qualifies and is actively being censored by Tiktok.

**Comment by Coloradohusky** [comment]
No, it just happens with all the videos that don’t have sound (they say ‘This sound isn’t available’ at the top)

**Comment by davidteather** [comment]
The video in question has sound for me

**Comment by Coloradohusky** [comment]
![838BEC1D-F2DE-4F01-908E-315516D630AE](https://user-images.githubusercontent.com/45430066/84551751-84dbc780-acdc-11ea-941b-e110a0943a41.png)

**Comment by davidteather** [comment]
That's strange, but this API uses desktop endpoints and the censorship aspect seems to make sense. Are you able to provide another example with the same issue, that TikTok wouldn't censor.

The flow I'm able to see the video with on desktop is user account -> video not directly to the video which is what the endpoint that errors you're trying to do.

Directly to the TikTok
![image](https://user-images.githubusercontent.com/34144122/84551923-bfd9fd00-acd4-11ea-9a7f-04e151c0cd44.png)

API Request
![image](https://user-images.githubusercontent.com/34144122/84551950-d6805400-acd4-11ea-9690-b89dafebe02d.png)

I'm only able to achieve the video by first going to the profile
![image](https://user-images.githubusercontent.com/34144122/84551979-ebf57e00-acd4-11ea-8513-c2b6d890e81b.png)

**Comment by davidteather** [comment]
My other guess is that maybe potentially it was DCMA'd or something, but it's strange that I can still listen to the song on desktop.

**Comment by davidteather** [comment]
I'll reopen and hope someone else can confirm or deny the theories.

**Comment by davidteather** [comment]
Closing because stale

**Comment by Coloradohusky** [comment]
This is the URL that is POSTed when viewing through the profile:
`https://m.tiktok.com/api/impression/write/?aid=1988&app_language=en&device_platform=web_pc¤t_region=US&fromWeb=1&app_name=tiktok_web&cookie_enabled=true&screen_width=1920&screen_height=1080&browser_language=en-US&browser_platform=Win32&browser_name=Mozilla&browser_version=5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/83.0.4103.116+Safari/537.36&browser_online=true&timezone_name=America/New_York&brand=&page_referer=https://www.tiktok.com/@penguins/video/6791925545199258886&verifyFp=verify_kbwkgtpj_rgTDoQ2W_meii_4CdO_8Cfz_2uS8pEHHnEWx`
and this one is from the direct link:
`https://m.tiktok.com/api/item/detail/?itemId=6791925545199258886&language=en&verifyFp=verify_kbwkgtpj_rgTDoQ2W_meii_4CdO_8Cfz_2uS8pEHHnEWx&_signature=_02B4Z6wo00f0146VH9AAAIBD-g.3QmulE7OOlBtAAL1q81`

This is the full request for when viewed from the profile:
`{"frameId":0,"initiator":"https://www.tiktok.com","method":"POST","parentFrameId":-1,"requestId":"120790","responseHeaders":[{"name":"status","value":"200"},{"name":"server","value":"nginx/1.14.2"},{"name":"content-type","value":"application/json; charset=utf-8"},{"name":"content-length","value":"57"},{"name":"x-janus-mini-api-forward","value":"Janus-Mini(fast)"},{"name":"x-krakend","value":"Version 2"},{"name":"x-krakend-completed","value":"false"},{"name":"x-tt-logid","value":"202006302028430101890501595E48FF55"},{"name":"access-control-allow-credentials","value":"true"},{"name":"allow","value":"GET, OPTIONS, POST, PUT"},{"name":"content-encoding","value":"gzip"},{"name":"protocol","value":"json"},{"name":"access-control-allow-headers","value":"DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type"},{"name":"access-control-allow-methods","value":"GET, POST, OPTIONS"},{"name":"access-control-allow-origin","value":"https://www.tiktok.com"},{"name":"strict-transport-security","value":"max-age=31536000"},{"name":"x-tt-trace-host","value":"015f5e9cdd7e6e3a84332a3cc7cc18cea268ced15544837997b68f8435652a8ec8258ada63a7f4aaf8733362134c94ce310e94716495aa03cabc29a2c9602cce1e38f90ebc551820f3484f72c1d009c41681e0fb8df5f0389331d439192ef49410"},{"name":"x-origin-response-time","value":"14,23.199.71.173"},{"name":"date","value":"Tue, 30 Jun 2020 20:28:43 GMT"},{"name":"vary","value":"Accept-Encoding"},{"name":"x-tt-trace-tag","value":"id=16;cdn-cache=miss;type=dyn"},{"name":"server-timing","value":"cdn-cache; desc=MISS, edge; dur=6, origin; dur=14"},{"name":"server-timing","value":"inner; dur=12"},{"name":"x-parent-response-time","value":"20,23.215.132.62"}],"statusCode":200,"statusLine":"HTTP/1.1 200","tabId":1996,"timeStamp":1593548922975.6912,"type":"xmlhttprequest","url":"https://m.tiktok.com/api/impression/write/?aid=1988&app_language=en&device_platform=web_pc¤t_region=US&fromWeb=1&app_name=tiktok_web&cookie_enabled=true&screen_width=1920&screen_height=1080&browser_language=en-US&browser_platform=Win32&browser_name=Mozilla&browser_version=5.0+(Windows+NT+10.0%3B+Win64%3B+x64)+AppleWebKit%2F537.36+(KHTML,+like+Gecko)+Chrome%2F83.0.4103.116+Safari%2F537.36&browser_online=true&timezone_name=America%2FNew_York&brand=&page_referer=https:%2F%2Fwww.tiktok.com%2F@penguins%2Fvideo%2F6791925545199258886&verifyFp=verify_kbwkgtpj_rgTDoQ2W_meii_4CdO_8Cfz_2uS8pEHHnEWx"}`
and this is from the direct link
`{"frameId":0,"initiator":"https://www.tiktok.com","method":"GET","parentFrameId":-1,"requestId":"121045","responseHeaders":[{"name":"status","value":"200"},{"name":"server","value":"nginx/1.14.2"},{"name":"content-type","value":"application/json; charset=utf-8"},{"name":"content-length","value":"44"},{"name":"x-janus-mini-api-forward","value":"Janus-Mini(fast)"},{"name":"x-krakend","value":"Version 2"},{"name":"x-krakend-completed","value":"false"},{"name":"access-control-allow-credentials","value":"true"},{"name":"access-control-allow-headers","value":"DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type"},{"name":"allow","value":"GET, OPTIONS, POST, PUT"},{"name":"protocol","value":"json"},{"name":"access-control-allow-methods","value":"GET, POST, OPTIONS"},{"name":"access-control-allow-origin","value":"https://www.tiktok.com"},{"name":"content-encoding","value":"gzip"},{"name":"x-tt-logid","value":"202006302031590101890660243C4898D2"},{"name":"strict-transport-security","value":"max-age=31536000"},{"name":"x-tt-trace-host","value":"015f5e9cdd7e6e3a84332a3cc7cc18cea22fbaac05b537a08c491ab581bfe1c141f0c147b363f041739fe571a570b77dc8898c24f9b9aed305c0531d98606ca44def3a727bec59752c9684e0b671ce43315f2e441ca0e47cb9ee4f8d35f49d64da"},{"name":"x-origin-response-time","value":"29,23.32.17.6"},{"name":"date","value":"Tue, 30 Jun 2020 20:31:59 GMT"},{"name":"vary","value":"Accept-Encoding"},{"name":"x-tt-trace-tag","value":"id=16;cdn-cache=miss;type=dyn"},{"name":"server-timing","value":"cdn-cache; desc=MISS, edge; dur=0, origin; dur=29"},{"name":"server-timing","value":"inner; dur=28"},{"name":"x-parent-response-time","value":"29,23.215.132.63"}],"statusCode":200,"statusLine":"HTTP/1.1 200","tabId":2003,"timeStamp":1593549118886.92,"type":"xmlhttprequest","url":"https://m.tiktok.com/api/item/detail/?itemId=6791925545199258886&language=en&verifyFp=verify_kbwkgtpj_rgTDoQ2W_meii_4CdO_8Cfz_2uS8pEHHnEWx&_signature=_02B4Z6wo00f0146VH9AAAIBD-g.3QmulE7OOlBtAAL1q81"}`

Other things I noticed:
- `webapp_tiktok_open` under Session Storage was `page_404` from the profile, and `video_detail` from the URL
- `webapp_tiktok_privious` from profile viewing:
```
href: "https://www.tiktok.com/@penguins/"
pageName: "others_homepage"
twoPrev: "video_detail"
twoPrevHref: "https://www.tiktok.com/@penguins/video/6791925545199258886"
```
- `webapp_tiktok_privious` from URL:
```
href: "https://www.tiktok.com/@penguins/video/6791925545199258886"
pageName: "video_detail"
```

Another (unrelated) note: `aweme_id` can be used to get the comments, url looks like `https://www.tiktok.com/api/comment/list/?aweme_id=6791925545199258886&cursor=0&count=20&aid=1988&app_language=en&device_platform=web_pc¤t_region=US&fromWeb=1&channel_id=3&verifyFp=verify_kbwkgtpj_rgTDoQ2W_meii_4CdO_8Cfz_2uS8pEHHnEWx&_signature=_02B4Z6wo00901qhkNuQAAIBC3P7ed9PLTYqoZTJAAPTx04`

**Comment by davidteather** [comment]
About the comment url that only works when you're logged in, if you try to open that url in a browser it responds with blocked.

**Comment by isaackogan** [comment]
I think I might have an update on this, someone reached out to me on Discord for my implementation of the API because videos were getting blocked. I found the 10204 status code, and searched it on google to find this issue. 

It looks to be a region issue in my case, perhaps the sound not being available in the request region.

Directly curling the URL from https://www.tiktok.com/@jjay.mal/video/6950355238276631814 on my VPS in germany returns that 10204, tried again on my VPS with https://www.tiktok.com/embed/v2/6950355238276631814?lang=en-US 10204.

Both return valid video data from my home in Canada when locally requested.

Credit goes to the user oof ouch my bones#3778 for figuring this out if it does help in any way.

**Comment by ConsHskns** [comment]
I am trying to call videos from a German url and received the same error code 10204. Do you know a potential workaround for this, or a way to use a try/except statement to avoid videos with no sound? 

Thanks a lot for the work you put into this API!

**Comment by tilekm** [comment]
I have the same problem on my VPS, but everything works correctly on my device. The only solution I have found is to use a proxy. But they are too expensive for a fun project.
