### ISSUE TITLE
[FEATURE_REQUEST] - What you want here] - How to get all videos by a user?

### ISSUE THREAD

**Issue by ivenkrish** [davidteather/TikTok-Api#151]
**Is your feature request related to a problem? Please describe.**
Is it possible to get all video urls uploaded by a user with just the user id? 

**Describe the solution you'd like**
I dont know if there is a way to achieve this today, with the user object itself. It would be great to have an api that simply returns all the video objects or urls of a particular user.

**Describe alternatives you've considered**
I am exploring to see if I can use the user object to get this

**Additional context**
N/A

**Comment by davidteather** [comment]
The byUsername and userPosts method will return tiktok objects.  

From there you there’s a link to play the video within that tiktok.
