### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by makeev** [davidteather/TikTok-Api#154]
new param `verifyFp=verify_kbg2qpav_kcD2KEdS_DR2W_4kAY_BnzD_rlugVyf6Sxs7 ` needed

**Comment by makeev** [comment]
verifyFp  is cookie `s_v_web_id `, but not working for me even with this param. Have no ideas for now

**Comment by sriramkumar1996** [comment]
I have changed the User-Agent, used `verifyFp` from `s_v_web_id` and also changed the goto url in `browser.py` to dynamically get `_signature`, but still not working. No ideas for now.

**Comment by harshall28** [comment]
Hi I am getting below trace:
(just today only and was working till last night)

Converting response to JSON failed response is below (probably empty)

Traceback (most recent call last):
  File "/home/vidooly/ML/DeepLearning/Projects/user/harshall/practice/pytorch_prac/lib/python3.6/site-packages/TikTokApi/tiktok.py", line 50, in getData
    return r.json()
  File "/home/vidooly/ML/DeepLearning/Projects/user/harshall/practice/pytorch_prac/lib/python3.6/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scrap_no_watermark.py", line 26, in <module>
    tiktoks = api.byHashtag(tag, count=count)
  File "/home/vidooly/ML/DeepLearning/Projects/user/harshall/practice/pytorch_prac/lib/python3.6/site-packages/TikTokApi/tiktok.py", line 236, in byHashtag
    id = self.getHashtagObject(hashtag)['challengeInfo']['challenge']['id']
  File "/home/vidooly/ML/DeepLearning/Projects/user/harshall/practice/pytorch_prac/lib/python3.6/site-packages/TikTokApi/tiktok.py", line 272, in getHashtagObject
    return self.getData(api_url, b.signature, b.userAgent, proxy=proxy)
  File "/home/vidooly/ML/DeepLearning/Projects/user/harshall/practice/pytorch_prac/lib/python3.6/site-packages/TikTokApi/tiktok.py", line 54, in getData
    raise Exception('Invalid Response')
Exception: Invalid Response


Is this a related issue?
If yes when can we expect a resolution?

**Comment by makeev** [comment]
yes, its the same issue, no solution for now. I'll try to check deeply this evening

**Comment by tarkhil** [comment]
Same here, they seems to change signing algo again

**Comment by davidteather** [comment]
They seem to be detecting puppeteer / pyppeteer right now. There's a way to get around it with playwright, but there's no adaptation of playwright for python.

It seems that the puppeteer detection is only detecting the object routes such as getUserObject. For me I've changed the code and it supports bySound, because it never retrieves a sound object to get the music id, but not byHashtag or byUsername.

I'll work on this for a little bit longer and release what I have so far, but for the same level of functionality a python playwright rewrite might be a necessity. (unless I'm able to get around the object route detection)

**Comment by davidteather** [comment]
Alright I looked into it and I don't believe I'll be able to fix this without playwright (or another automation that isn't detected). I could interact with playwright through a server running on node, but that's not very practical.

**Comment by TimeToGoogle** [comment]
Did you try it with puppeteer-extra and maked use of their stealth package?

**Comment by davidteather** [comment]
@TimeToGoogle  The current project uses [pyppeteer-stealth](https://pypi.org/project/pyppeteer-stealth/) which is based on puppeteer-extra-plugin-stealth. Still doesn't help.

**Comment by makeev** [comment]
Its not pyppeteer related, if url signed correctly - it's opening anywhere with same user-agent, even without cookies.

**Comment by davidteather** [comment]
Url doesn’t get signed correctly when tiktok detects it’s an automation script.  

The automation software currently fails to load tiktok but does sign the urls but incorrectly. We can’t tell the browser to correctly sign them because it’s being detected.

**Comment by makeev** [comment]
But have you tried sign url in usual chrome console? I did and with no success.

**Comment by davidteather** [comment]
I haven’t tired in chrome console, but compare puppeteer on [this](https://www.npmjs.com/package/tiktok-signature) version 1.1.4 vs the current version which uses playwright. Nothing major but changes for playwright was made. 

The puppeteer version with extra stealth can’t sign urls correctly 

The playwright version can sign urls that work.

**Comment by makeev** [comment]
yes, you a right, seems like i tested it incorrectly.

**Comment by Inzilkin** [comment]
Everything works fine through the Chrome console, but does not want to through pyppeteer.

**Comment by DeadlyMissile** [comment]
What did they change exactly?

**Comment by davidteather** [comment]
They’re able to detect the automation software the library used, which they used to restrict displaying tiktok information from.

**Comment by DeadlyMissile** [comment]
@davidteather How does this affect grabbing non watermarked videos though?  It is not automating anything

**Comment by davidteather** [comment]
Well to find the videos without a watermark it uses the automation software puppeteer to get a signature and find a redirect to the actual url.

**Comment by DeadlyMissile** [comment]
Shit we screwed then

**Comment by Inzilkin** [comment]
Who knows how to get video with him Id in api? Old api method sends white page

**Comment by Xodarap** [comment]
As a temporary fix, could you add a way for us to add the signature ourselves? (Ideally with some instructions on how to do so.)

This is the approach that this node-based API takes: https://github.com/szdc/tiktok-api

**Comment by dj2ball** [comment]
I have a successfully working android api based on an old apk - the endpoints from those old musical.ly apps are still active and lack the signature requirements of the updated app api. It doesn’t support signed login methods but those in this library work well and there is no need for a browser (pyppeteer etc) since the only check is for valid header info which you can generate from an android emulator. Would advise you take the api in that direction for now.

**Comment by Inzilkin** [comment]
> I have a successfully working android api based on an old apk - the endpoints from those old musical.ly apps are still active and lack the signature requirements of the updated app api. It doesn’t support signed login methods but those in this library work well and there is no need for a browser (pyppeteer etc) since the only check is for valid header info which you can generate from an android emulator. Would advise you take the api in that direction for now.

can you help me with getting signatures from the app? tg - @inzilkin

**Comment by dj2ball** [comment]
If you use an old app version they lack the code to authenticate using X-Gorgon and Khronos (the new mobile signatures) and the signature being discussed here is for the desktop version only. The old apps use CP, AS and MAS  but it does not appear to be reliably enforced on the client ( try reversing the Java library code using Jadx and you’ll see the code allows placeholder values to be acceptable)

**Comment by sriramkumar1996** [comment]
@davidteather  
I've used playwright to generate signature value. 
I could get the hashtag id from hashtag name but couldn't get the item list from hashtag id.

For example: 
hashtag_id_url = "https://t.tiktok.com/api/challenge/detail/?challengeName=funny&language=en&verifyFp=verify_kblhn8bm_LLbrJ3PN_qfY1_4uok_AzIg_ROHNJzdxaMaE&_signature=_02B4Z6wo00f01OzwBkgAAIBASzRV6uwYUhjs8QLAAGXW91"

hashtag_items_url = "https://www.tiktok.com/share/item/list?secUid=&id=5424&type=3&count=30&minCursor=0&maxCursor=0&shareUid=&recType=&lang=en&verifyFp=verify_kblhn8bm_LLbrJ3PN_qfY1_4uok_AzIg_ROHNJzdxaMaE&_signature=_02B4Z6wo00f01OzwBkgAAIBASzRV6uwZK.zs8QLAAGXWd2"

`hashtag_id_url` is working but `hashtag_items_url` is not working.
I've used the same UserAgent and tried with cookies and without cookies, no result for `hashtag_items_url`.
Where do you think the problem is?

**Comment by dibashthapa** [comment]
Should I have to decompile the app to get the CP , AS and Mas ?? I tried to find those params in api but I couldn't find any.

**Comment by ZhangNemo34** [comment]
I have the same problem with v3.2.3 on Python3.8
Is this fixed?

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 52, in getData
    return r.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tiktok_api_scraper.py", line 8, in <module>
    user_data = api.getUserObject(user_id)
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 327, in getUserObject
    return self.getUser(username, language, proxy=proxy)
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 336, in getUser
    data_chunk = self.getData(api_url, b, proxy=proxy)['userInfo']
  File "/usr/local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 56, in getData
    raise Exception('Invalid Response')
Exception: Invalid Response

**Comment by davidteather** [comment]
I've been working on this I've managed to get the user object route working again as it looks like TikTok is changing the way they do this.

I've found a relevant issue [here](https://github.com/berstend/puppeteer-extra/issues/218) on TikTok detecting puppeteer. I've been trying to work around this with little success.

**Comment by olitomas** [comment]
Related to this? 🤔
https://github.com/digitalhurricane-io/puppeteer-detection-100-percent

**Comment by davidteather** [comment]
https://github.com/davidteather/TikTok-Api/releases/tag/V3.3.0
