### ISSUE TITLE
The url in response of get_Video_No_Watermark is blank page

### ISSUE THREAD

**Issue by kienvtqhi** [davidteather/TikTok-Api#156]
I tested your api on [rapidapi.com](https://rapidapi.com/rapidapideveloper/api/tiktok2?endpoint=apiendpoint_eb116f6b-9dc9-4b4a-80b8-064a6fe19040). I tried to get video no watermark.

Input url: https://www.tiktok.com/@tiktok/video/6800111723257941253
Output: https://api2.musical.ly/aweme/v1/playwm/?video_id=v09044b90000bpfdj5q91d8vtcnie6o0

But when i opened the output url in browser, it shown a blank page. I also tried to open it in postman but the same result. The response is empty.

Any solution to open it and see the video without water mark? 
Thank you!

**Comment by davidteather** [comment]
There's quite a few issues with the api / library right now. There's only a few working methods right now. Which the video without watermark is not currently working sorry. To find working methods visit [this](https://github.com/davidteather/TikTok-Api/releases/tag/V3.2.3) release. The current issues are detailed on #154

**Comment by davidteather** [comment]
Looked into this more and TikTok has noticed this and removed this endpoint from their server.
