### ISSUE TITLE
what is window.byted_acrawler.sign?

### ISSUE THREAD

**Issue by DeadlyMissile** [davidteather/TikTok-Api#157]
I am trying to use this to scrape data from a video link, like username, like count etc. However this seems to require a signature now. Since I am using this with the Dart language I can’t for the love god find out what is window.byted_acrawler.sign so I can generate a signature. What is it?

**Comment by davidteather** [comment]
window.byted_acrawler is how tiktok generates its signatures. It’s an actual method they’ve included on their website. 
If you go to a tiktok page in your browser and open the JavaScript console you can do window.byted_acrawler

**Comment by DeadlyMissile** [comment]
@davidteather Do you mean that extremely long acrawler.js ?

**Comment by davidteather** [comment]
Nah they’re probably different. The library loads  up tiktok and signs a url just using the JavaScript console on tiktok’s website. They’ve got quite a bit of bot detection so I doubt you could just use that js file if it’s related.

**Comment by DeadlyMissile** [comment]
@davidteather Last thing David! Do you think they do this on their mobile app as well? It looks like an expensive operation

**Comment by davidteather** [comment]
They use a different on their app see #120

**Comment by DeadlyMissile** [comment]
@davidteather Hell I don’t even where to pass the url in this https://github.com/clicker777/Algorithm-X-Gorgon-Tik-Tok/blob/master/func.py lol. Oh well thanks for everything David!

**Comment by davidteather** [comment]
You might want to setup a server to make calls to from your app. Or use an api on rapidapi or something similar.

**Comment by DeadlyMissile** [comment]
I will stick to the web implementation lol @davidteather

**Comment by DeadlyMissile** [comment]
@davidteather I couldn’t find the window acrawler method David 😕. Is it the TAC one?
