### ISSUE TITLE
[BUG] - userPosts (and possibly other API calls) fails always

### ISSUE THREAD

**Issue by tarkhil** [davidteather/TikTok-Api#164]
On first call to /api/item_list, TikTok seems to always return only cursor data, such as 
`{
  "statusCode": 0,
  "hasMore": false,
  "maxCursor": "0",
  "minCursor": "1593197167000"
}
`
or
`{
  "statusCode": 0,
  "hasMore": true,
  "maxCursor": "1574413429000",
  "minCursor": "1574531699000"
}
`

so TikTokApi fails on line 121 ` for t in res['items']:`

Subsequent requests are Ok, so simply guarding the loop by `if 'items' in res:` is sufficient

**Comment by davidteather** [comment]
I'm unable to reproduce this, For my system TikTok is always sending data on the first call? Are you sending too many requests too fast?

**Comment by tarkhil** [comment]
Maybe; I was sending about two requests per second for some time, and userPosts always returned empty first result for me.

**Comment by davidteather** [comment]
I made some changes to the api do you mind downloading the nightly branch and see if that fixes your issue?

**Comment by tarkhil** [comment]
Not right now, but in about 10 hours

**Comment by davidteather** [comment]
Sounds good!

**Comment by tarkhil** [comment]
Works just fine. Sorry, only right now I've got time to test.
