### ISSUE TITLE
[BUG] & [INSTALLATION_HELP] - AttributeError: 'browser' object has no attribute 'verifyFp'

### ISSUE THREAD

**Issue by babydickdanilko** [davidteather/TikTok-Api#166]
**Describe bug**

After running the script, an error is generated after a while:
No future exception was found.
future: Future exception was never retrieved
future: <Future finished exception = ConnectionClosedError ('code = 1006 (connection closed abnormally [internal]), no reason',)>, after another 15 ~ seconds:
AttributeError: 'browser' object has no attribute 'verifyFp'

**The buggy code**

```
from TikTokApi import TikTokApi

api = TikTokApi()

count = 30

tiktoks = api.byHashtag('cat', count=count)

for tiktok in tiktoks:
    print(tiktok)
```
**Expected behavior**

Print(tiktok)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 83.0.4103.116
 - Python: 3.6.1

**Additional context**

The first couple of times everything was fine, after the mistakes started
(Sorry for my english)

**Full traceback:**
Future exception was never retrieved
future: <Future finished exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason',)>
Traceback (most recent call last):
  File "C:\Users\babyd\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 795, in transfer_data
    message = await self.read_message()
  File "C:\Users\babyd\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 863, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\Users\babyd\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 938, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\Users\babyd\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 1018, in read_frame
    extensions=self.extensions,
  File "C:\Users\babyd\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\framing.py", line 121, in read
    data = await reader(2)
  File "C:\Users\babyd\AppData\Local\Programs\Python\Python36\lib\asyncio\streams.py", line 666, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
Traceback (most recent call last):
  File "C:/Users/babyd/Desktop/Python/tikitiki.py", line 7, in <module>
    tiktoks = api.byHashtag('cat', count=count)
  File "C:\Users\babyd\AppData\Local\Programs\Python\Python36\lib\site-packages\TikTokApi\tiktok.py", line 236, in byHashtag
    id = self.getHashtagObject(hashtag)['challengeInfo']['challenge']['id']
  File "C:\Users\babyd\AppData\Local\Programs\Python\Python36\lib\site-packages\TikTokApi\tiktok.py", line 272, in getHashtagObject
    return self.getData(api_url, b, proxy=proxy)
  File "C:\Users\babyd\AppData\Local\Programs\Python\Python36\lib\site-packages\TikTokApi\tiktok.py", line 30, in getData
    "&_signature=" + b.signature
AttributeError: 'browser' object has no attribute 'verifyFp'

Process finished with exit code 1

**Comment by davidteather** [comment]
Are you running any delays between your calls to the api? Tiktok might be rate limiting your ip

**Comment by babydickdanilko** [comment]
I made 4 requests maximum, now I checked for 2 ip, the error remained. Requests did manually

**Comment by davidteather** [comment]
Does TikTok load when you go to https://www.tiktok.com/foryou?lang=en what TikTokApi version are you running?

**Comment by babydickdanilko** [comment]
The nightly branch has earned, thanks for the help

**Comment by babydickdanilko** [comment]
Ahahah, аfter the first start, the error reappeared, strange I started only 1 time

**Comment by davidteather** [comment]
Would you consider internet connection slower than most people? It might be taking a few seconds longer than normal to generate the verifyFp attribute I’ll change some things on the nightly branch in ~12hrs

**Comment by babydickdanilko** [comment]
Well I'm waiting for

**Comment by davidteather** [comment]
Alright I added a delay download the branch and reinstall. You might have to uninstall TikTokApi before installing the new one as it's the same version.

**Comment by babydickdanilko** [comment]
Uninstalled all TikTokApi, installed the last nightly branch, unfortunately the error remained

**Comment by davidteather** [comment]
When you [here](https://www.tiktok.com/@therock) with your regular browser you can see the TikTok's correct?

**Comment by babydickdanilko** [comment]
Yes, all good, videos played

**Comment by davidteather** [comment]
Run the following script
```
from pyppeteer.launcher import Launcher
print(' '.join(Launcher().cmd))
```

Then copy the output of that program and run it into your terminal or cmd, please respond with the output of that command.

**Comment by babydickdanilko** [comment]
If im run with all arguments, then nothing happens, if im run just chrome.exe then everything is fine

**Comment by davidteather** [comment]
If you go to [tiktok](https://www.tiktok.com/foryou?lang=en) and click on the pad icon at the top by the url and click cookies under www.tiktok.com -> cookies is there an item called s_v_web_id?

**Comment by babydickdanilko** [comment]
Yes he is

**Comment by davidteather** [comment]
Do you live in a region where you have to consent to cookies?

Try opening an incognito browser without clicking accept anywhere and see if that cookie is still present.

**Comment by babydickdanilko** [comment]
In incognito mode s_v_web_id is present

**Comment by davidteather** [comment]
I have no idea what the issue is at this point. I'm hoping that someone else in the community is able to find an answer.

**Comment by babydickdanilko** [comment]
Oh, i get it

**Comment by rahulzura** [comment]
I too am facing the same issue. 

> Run the following script
> 
> ```
> from pyppeteer.launcher import Launcher
> print(' '.join(Launcher().cmd))
> ```
> 
> Then copy the output of that program and run it into your terminal or cmd, please respond with the output of that command.

After running the code, I got:
```
/home/lulu/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome --disable-background-networking --disable-background-timer-throttling --disable-breakpad --disable-browser-side-navigation --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=site-per-process --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-translate --metrics-recording-only --no-first-run --safebrowsing-disable-auto-update --enable-automation --password-store=basic --use-mock-keychain --headless --hide-scrollbars --mute-audio about:blank --remote-debugging-port=39083 --user-data-dir=/home/lulu/.local/share/pyppeteer/.dev_profile/tmpo0h0jr61
```

When I run the above in the terminal, I get:

```
[0630/204516.471722:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:39083/devtools/browser/eccb7ac8-82a9-49f5-a874-472d8af76f19
```

**Comment by fratamico** [comment]
Not sure what country you're running it from, but I get the same `AttributeError: 'browser' object has no attribute 'verifyFp'` issue when running from my Mumbai AWS server and when I VPN to India. From other locations, I have no issue.

**Comment by avilash** [comment]
India recently banned TIkTok. Its because of that

**Comment by PhiTheG** [comment]
I am facing the same issue, located in Italy

**Comment by tarkhil** [comment]
`/home/tarkhil/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome --disable-background-networking --disable-background-timer-throttling --disable-breakpad --disable-browser-side-navigation --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=site-per-process --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-translate --metrics-recording-only --no-first-run --safebrowsing-disable-auto-update --enable-automation --password-store=basic --use-mock-keychain --headless --hide-scrollbars --mute-audio about:blank --remote-debugging-port=54127 --user-data-dir=/home/tarkhil/.local/share/pyppeteer/.dev_profile/tmpvsvt1kbf
`

`[0706/225217.902004:ERROR:gpu_process_transport_factory.cc(980)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:54127/devtools/browser/85fe5464-4a47-4726-9138-9fac778ce99a
`

Two servers running in the same datacenter, both runs Ubuntu 18.04.4 LTS \n \l 

Works without virtualenv, fails within it - that's the only difference.

**Comment by tarkhil** [comment]
Test without virtualenv on the problem box did not show significantly better stability.

**Comment by avilash** [comment]
You can use this one for the time being
https://github.com/avilash/TikTokAPI-Python

**Comment by davidteather** [comment]
The verifyFp issue seems to be a geolocation issue. It’s an issue raised when there’s no cookie that tiktok uses to generate a parameter. 

India makes sense due to the ban, Italy sort of makes sense because of potential gdpr compliance. 

You can try to get around this issue by using a proxy or changing server location. Unless anyone else has a better idea I think this is the only way to get around it. 

I don’t have access to any proxies in these regions to test the Api and debug.

**Comment by PhiTheG** [comment]
I have tested it with an US proxy but i still get the same error

**Comment by PhiTheG** [comment]
I tested it on my US server, there it woks, but from italy using a proxy does not work.

**Comment by davidteather** [comment]
I just released an update that hopefully fixes this. Upgrade with the following and tell me if it solved your issue.

```
pip install TikTokApi --upgrade
```

**Comment by davidteather** [comment]
Closing for now, because it should be fixed with the new update to the package (unless TikTok is banned in your region).

**Comment by fuomag9** [comment]
In my case GCP (google cloud platform) was the issue, https://github.com/avilash/TikTokAPI-Python works fine from italy for example

**Comment by rocailler** [comment]
i suggest to imporve debug mode, cause i had the same problem `AttributeError: 'browser' object has no attribute 'verifyFp'` BUT it was not verifyFP but browser problem. 
in class TikTokApi __init__ there is 
`b = browser('newParam', newParams=True)`
if there is an error it doesn't return any info. The problem is in Try, which in debug mode gives:
`print("The following error occurred, but it was ignored.")`
(I had a big chromedriver problem so no, it's not too good info :D ) 

so after exception I had error with verifyFP only because it is a FIRST parameter, which script is trying to get:
`url = b.url + \
            "&verifyFp=" + b.verifyFp + \
            "&_signature=" + b.signature`


My problem was with certificate ;) proper error info i've get after usage of script:
```
from pyppeteer.launcher import Launcher
print(' '.join(Launcher().cmd))
```
and resolve with this advices: [https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org](https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org)

**Comment by bengisupinar** [comment]
> Run the following script
> 
> ```
> from pyppeteer.launcher import Launcher
> print(' '.join(Launcher().cmd))
> ```
> 
> Then copy the output of that program and run it into your terminal or cmd, please respond with the output of that command.

Hi,
The output:

 error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory

This issue is fixed with some sudo apt-get command, but I work on cmd
