### ISSUE TITLE
[BUG] - on some hashtags, byHash crashes

### ISSUE THREAD

**Issue by tarkhil** [davidteather/TikTok-Api#167]
The code
`
from TikTokApi import TikTokApi
api.byHashtag('14_birthday')
`
crashes, reporting 
`
  File "/usr/local/lib/python3.6/dist-packages/TikTokApi/tiktok.py", line 236, in byHashtag
    id = self.getHashtagObject(hashtag)['challengeInfo']['challenge']['id']
`
Dump of JSON from server shows
`
{
  "statusCode": 10202
}
`

**Comment by davidteather** [comment]
Means it’s not a valid hashtag 

https://www.tiktok.com/tag/14_birthday
