### ISSUE TITLE
why use a real brower not some lib like requests

### ISSUE THREAD

**Issue by hugit6** [davidteather/TikTok-Api#17]
too heavy.
and no login,like,follow etc.

**Comment by davidteather** [comment]
Can’t use requests because the videos are loaded over Ajax or something. If you use requests you won’t get the list of videos just a blank html with a header and footer.

**Comment by hugit6** [comment]
for the app load json and parse the mp4 url process, it can be load by requests.
captcha also solvable by pure python code, your can refer to another tiktok api repo.

**Comment by davidteather** [comment]
For my purposes and most other users the repository is adequate and gets the job done. In the future I may end up making it more efficient and reworking it, but it’s not my main project.

**Comment by davidteather** [comment]
But for the Tiktok video to mp4 the Url actually gets redirected making it impossible to do with requests.
