### ISSUE TITLE
[BUG] - TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a coroutine.

### ISSUE THREAD

**Issue by elblogbruno** [davidteather/TikTok-Api#173]
**Describe the bug**

I am trying to insert this library in a flask server so I can get tiktok data from Unity3D for example making web requests to my flasks server and getting raw mp4 url or thumbnail url I can play on unity. When I run the flask server and make the get petition it shows this error:
```
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a coroutine.
```
**The buggy code**

```
@app.route('/get_trending')
async def get_trending():
    results = 10

    trending = api.trending(count=results)

    for tiktok in trending:
        # Prints the text of the tiktok
         return jsonify(tiktok)

    print(len(trending))
    return 'OK'
```

**Expected behavior**

Return a json answer that is a dictionary of the tiktok.

**Error Trace (if any)**

RuntimeError: There is no current event loop in thread 'Thread-1'.
```
# Error Trace Here
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Debian 10
 - TikTokApi Version [e.g. 3.3.1] - 3.3.1

**Additional context**
I know there's an api running on rapidApi but I want to host it myself.

**Comment by elblogbruno** [comment]
If I do remove "async" from function I do get this error `RuntimeError: There is no current event loop in thread 'Thread-2'.`

**Comment by elblogbruno** [comment]
I finally got it working. Trying to fix issue #115 I did change `loop = asyncio.new_event_loop()` to `loop = asyncio.get_event_loop()` on Browser.py which made it not work.
Anyway a doubt has come to me. It is normal it takes long time to receive data once it has been called? it depends on the  number of tiktoks you retrieve?

**Comment by davidteather** [comment]
Yeah if you retrieve a lot of tiktok it’ll take longer. And your flask return isn’t setup in a great way. Instead of jsonify the tiktoks do something like the following
`return jsonify({“tiktoks”: trending})` 

That’s all you need after the trending call

**Comment by elblogbruno** [comment]
Thanks for the info! Last question, is it planned to be able to give likes, and aswell I'd like to ask if I can use this api in a production manner.

**Comment by davidteather** [comment]
I believe likes should be in the current dictionary response under the key diggCount. The library is licensed under the MIT license so you basically can do anything you want with it even for commercial purposes!

**Comment by elblogbruno** [comment]
Thanks! But I meant liking a TikTok not getting the number of likes a TikTok has.
Anyway, great job!

**Comment by davidteather** [comment]
I don't have plans to do that right now, but #120 might interest you.
