### ISSUE TITLE
[BUG] -  AttributeError: 'browser' object has no attribute 'browser'

### ISSUE THREAD

**Issue by elblogbruno** [davidteather/TikTok-Api#174]
**Describe the bug**
When I do put my flask server with this api on Heroku I get this error everytime. It works perfectly on my local machine.
```
await self.browser.close()
2020-07-10T15:19:40.179682+00:00 app[web.1]: AttributeError: 'browser' object has no attribute 'browser'
```

**The buggy code**

This is just an example of the many of code functions I have

```
@app.route('/get_trending')
def get_trending():
    results = 10 if request.args.get('limit') == None else int(request.args.get('limit')) 
    lang = 'en' if request.args.get('lang') == None else request.args.get('lang')

    print("Getting {0} results in {1} language".format(results,lang))
    trending = api.trending(count=results,language=lang)
    return jsonify({"tiktoks": trending})
```

**Expected behavior**

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
File "/app/.heroku/python/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
2020-07-10T15:19:40.179680+00:00 app[web.1]: return future.result()
2020-07-10T15:19:40.179681+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/TikTokApi/browser.py", line 113, in start
2020-07-10T15:19:40.179681+00:00 app[web.1]: await self.browser.close()
2020-07-10T15:19:40.179682+00:00 app[web.1]: AttributeError: 'browser' object has no attribute 'browser'

```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Heroku
 - TikTokApi Version [e.g. 3.3.1] - 3.3.1

**Additional context**

**Comment by davidteather** [comment]
You need to properly install pyppeteer and the chromium builds on heroku. You’ll need to install chromium and some other stuff. 

Google how to setup puppeteer for heroku you might get some results

**Comment by elblogbruno** [comment]
Ok thanks!

**Comment by rahulgoel1106** [comment]
**I am facing a similar issue. I am trying to run the code in google colab. Any help will be appreciated.**

---------------------------------------------------------------------------
BrowserError                              Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/TikTokApi/browser.py in start(self)
     58         try:
---> 59             self.browser = await pyppeteer.launch(self.options)
     60             self.page = await self.browser.newPage()

7 frames
/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py in launch(options, **kwargs)
    304     """
--> 305     return await Launcher(options, **kwargs).launch()
    306 

/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py in launch(self)
    165         connectionDelay = self.slowMo
--> 166         self.browserWSEndpoint = get_ws_endpoint(self.url)
    167         logger.info(f'Browser listening on: {self.browserWSEndpoint}')

/usr/local/lib/python3.6/dist-packages/pyppeteer/launcher.py in get_ws_endpoint(url)
    224         if time.time() > timeout:
--> 225             raise BrowserError('Browser closed unexpectedly:\n')
    226         try:

BrowserError: Browser closed unexpectedly:


During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-15-19a2a133e906> in <module>()
      4 results = 10
      5 
----> 6 trending = api.trending(count=results)
      7 
      8 for tiktok in trending:

/usr/local/lib/python3.6/dist-packages/TikTokApi/tiktok.py in trending(self, count, language, region, proxy)
     87             api_url = "https://m.tiktok.com/api/item_list/?count={}&id=1&type=5&secUid=&maxCursor={}&minCursor=0&sourceType=12&appId=1233&region={}&language={}&verifyFp=".format(
     88                 str(realCount), str(maxCursor), str(region), str(language))
---> 89             b = browser(api_url, language=language, proxy=proxy)
     90             res = self.getData(api_url, b, proxy=proxy)
     91 

/usr/local/lib/python3.6/dist-packages/TikTokApi/browser.py in __init__(self, url, language, proxy, find_redirect, api_url)
     53             loop.run_until_complete(self.find_redirect())
     54         else:
---> 55             loop.run_until_complete(self.start())
     56 
     57     async def start(self):

/usr/lib/python3.6/asyncio/base_events.py in run_until_complete(self, future)
    482             raise RuntimeError('Event loop stopped before Future completed.')
    483 
--> 484         return future.result()
    485 
    486     def stop(self):

/usr/local/lib/python3.6/dist-packages/TikTokApi/browser.py in start(self)
    111             await self.browser.close()
    112         except:
--> 113             await self.browser.close()
    114 
    115     async def find_redirect(self):

AttributeError: 'browser' object has no attribute 'browser'

**Comment by davidteather** [comment]
You’ll need to install chromium and a few things in the virtual environment on google colab. Check the .travis.yml for some commands that are executed to get the virtual environment ready for Travis. Might be slightly different for your environment but it might help you out

**Comment by elblogbruno** [comment]
For anyone having the same issue as me with heroku I fixed it by using this https://elements.heroku.com/buildpacks/jontewks/puppeteer-heroku-buildpack
Thanks @davidteather

**Comment by thanhnguyen1121** [comment]
@davidteather hi. I am facing the same problem. "AttributeError: 'browser' object has no attribute 'browser'
". but it appears on Ubuntu OS. I have installed chromeDriver, pyppeteer. Can you tell me how to solution?
