### ISSUE TITLE
[BUG] - pyppeteer.errors.BrowserError: Browser closed unexpectedly:

### ISSUE THREAD

**Issue by TimeToGoogle** [davidteather/TikTok-Api#178]
Since the update I'm always running into the error: pyppeteer.errors.BrowserError: Browser closed unexpectedly.

This is the output:
Traceback (most recent call last):
  File "/.local/lib/python3.7/site-packages/TikTokApi/browser.py", line 61, in start
    self.browser = await pyppeteer.launch(self.options)
  File "/.local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "/.local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 166, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/.local/lib/python3.7/site-packages/pyppeteer/launcher.py", line 225, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')

Because if this I'm getting an AttributeError: 'browser' object has no attribute 'browser' error in my TikTokApi function.

Any ideas how I can fix this?

**Comment by davidteather** [comment]
Your pyppeteer isn't launching.
Run the following script
```
from pyppeteer.launcher import Launcher
print(' '.join(Launcher().cmd)) # prints the command used to launch pyppeteer
```
Then copy the output of that program and run it into your terminal or cmd, please respond with the output of that command. If this command throws an error it may be easier to investigate.

**Comment by TimeToGoogle** [comment]
/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome --disable-background-networking --disable-background-timer-throttling --disable-breakpad --disable-browser-side-navigation --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=site-per-process --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-translate --metrics-recording-only --no-first-run --safebrowsing-disable-auto-update --enable-automation --password-store=basic --use-mock-keychain --headless --hide-scrollbars --mute-audio about:blank --remote-debugging-port=60603 --user-data-dir=/.local/share/pyppeteer/.dev_profile/tmp7c7dulgm

Was the response. Thx for your help.

**Comment by davidteather** [comment]
Please run that in your console

**Comment by TimeToGoogle** [comment]
Well the console always saying chrome command not found.

**Comment by davidteather** [comment]
Install chrome on your computer as well as download [chromedriver](https://sites.google.com/a/chromium.org/chromedriver/) and add it to your system path.
