### ISSUE TITLE
TikTok Changed How They Index TikToks

### ISSUE THREAD

**Issue by davidteather** [davidteather/TikTok-Api#183]
Hello, 
I've found out that TikTok has changed the way they index their API calls. They don't seem to utilize max & min cursors anymore. It looks like they must keep a record of your IP and they don't seem to return duplicates. 

### Proof
If you open [TikTok](https://www.tiktok.com/foryou?lang=en) in an incognito (to prove it's not cookies) and view a few of the TikToks then close the tab and reopen it, TikTok won't return any TikToks that you viewed.

Proof from API:
```
from TikTokApi import TikTokApi
api = TikTokApi()

first_call = api.trending(count=1)
second_call = api.trending(count=1)

print("Printing comparison of both calls")
print(first_call == second_call)
```

This code will print out false even though it should be true.

### How you can help

I'm reaching out to the community to help me investigate this change. Below I've listed some questions that ideally we can investigate. 

What information I'd like to know
* How long they store your IP until you can see TikToks you've already seen
* If there are anyways to bypass this
* If any endpoints are unaffected (the suggested methods shouldn't be affected based on requests using cursors, but the ones that retrieve TikTok objects should be affected)

### Consequences

Problems It's going to cause for the library
* If you're running a server with multiple user requests to it, users will not see the same information (you'll have to store a DB of queries)

Benefits For The API
* No need to do offset calls made to the api
* You shouldn't see duplicates

**Comment by Jho00** [comment]
byHashtag method collect posts of top hashtags. For the double calls of that method results should be idempotent. Maybe this behavior acceptable for some other methods

**Comment by skdcodes** [comment]
Just my two cents.

When you scroll down the first batch of results in the trending page, you see that an EXACT same request is made. Only a different  `_signature` parameter is used to handle pagination. The entire URL including the `verfiyFp` parameter remains unchanged. That's quite strange.

I was unable to reverse engineer how this new signature was being generated. It seems evident that just the `url` is being used to generate the token, I guess more parameters are also being used. This might explain the above behavior. 

If you can please tell how you found the `window.byted_acrawler({url})` method, then that might help with my investigation. I've unable to figure it out some simple Breakpoints in Chrome DevTools. I would be very grateful if you give me some pointers in this direction so that I can research and give back to this repo.

**Comment by llacb47** [comment]
@skdcodes the `byted_acrawler` function is loaded from this script: `https://sf16-muse-va.ibytedtos.com/obj/rc-web-sdk-gcs/acrawler.js`

**Comment by skdcodes** [comment]
> @skdcodes the `byted_acrawler` function is loaded from this script: `https://sf16-muse-va.ibytedtos.com/obj/rc-web-sdk-gcs/acrawler.js`

I've updated my above post. I do know where it is from but it seems to be Obfuscated. How do you work around this? Any method that you've tested and sure?

**Comment by llacb47** [comment]
I don't understand what the issue is to be honest.

**Comment by skdcodes** [comment]
@llacb47 The issue is that previous cursors were used for pagination. However, now that's not the case. I had the above observations and felt it might help in ultimately obtaining a solution.

**Comment by skdcodes** [comment]
> I don't understand what the issue is to be honest.

@llacb47 The issue is that previous cursors were used for pagination. However, now that's not the case. I had the above observations and felt it might help in ultimately obtaining a solution.

**Comment by davidteather** [comment]
Yeah it changes each time. I'm not sure why or anything, because it would take too long for me to figure out. So I just ended up loading that script and running it in the chrome console.

**Comment by skdcodes** [comment]
> Yeah it changes each time. I'm not sure why or anything, because it would take too long for me to figure out. So I just ended up loading that script and running it in the chrome console.

@davidteather Thanks for your prompt reply. I'm interested in how you reverse engineered the `.sign({url})` function. How did you arrive at this conclusion?

**Comment by davidteather** [comment]
I was back tracing the tiktok.com stuff to see how it got the signature value and I found the window.byted_acrawler.sign

**Comment by skdcodes** [comment]
@davidteather Unfortunately, that's not very helpful to look further.

**Comment by davidteather** [comment]
I've linked a helpful issue, if I knew where to look more indepth I probably would've found a solution by now.

**Comment by skdcodes** [comment]
@davidteather Thanks for the information. It seems `window.byted_acrawler.sign()` is not your research. I was mistaken, sorry.

**Comment by davidteather** [comment]
window.byted_acrawler.sign() is a function built into tiktok’s website you can sign functions using the console while on tiktok’s website

**Comment by llacb47** [comment]
@skdcodes I don't understand your obsession with `original source`. It's a well known function. Do your own research and RE if you're unhappy with what's available. You're certainly not entitled to anything.

**Comment by ios878** [comment]
N
