### ISSUE TITLE
[BUG] - Stats not accurate

### ISSUE THREAD

**Issue by fiqriwicaksono** [davidteather/TikTok-Api#187]
I used the byUsername() function to look for stats(likes, comment, play) of a tiktok by given user but unfortunately, it doesn't show accurate result, even the results are far from the actual data that I checked using tiktok app. :(

[https://drive.google.com/file/d/1gpPzGAD_7c-KPnuc44GTpYbMAyKbFF-K/view?usp=sharing](url)
[https://drive.google.com/file/d/1L03m8kHEfZ7N0iLCXq-RYZU7-bj0mLp5/view?usp=sharing](url)
[https://drive.google.com/file/d/1KzfIHJhK9jeYTmE451QGEc_epQD5E2Ve/view?usp=sharing](url)

**Comment by rezaarifandee** [comment]
Huh, i just checked mine and yeah, u are right. Is it possible that there could be a different API?

It's not this project's fault, though, pretty sure it's TikTok's fault. And the fact that they don't have a public API for this is frustrating.

**Comment by rezaarifandee** [comment]
[This](https://github.com/szdc/tiktok-api) uses different url than this project, however the request header seems different and more complex. I'll try it later and if it's correct, (huge) maybe i'll port it here since szdc's use MIT license.

**Comment by davidteather** [comment]
Yeah right now this uses the website of TikTok's api calls #120 is a discussion on how to access the mobile api. Feel free to comment on this issue further, but not an api issue.
