### ISSUE TITLE
I want waterless video 

### ISSUE THREAD

**Issue by 5wcx** [davidteather/TikTok-Api#19]
http://vm.tiktok.com/jN55fJ/    i need no water video ,how to do?

**Comment by davidteather** [comment]
Right now the api is broken

**Comment by davidteather** [comment]
Just released a new update that fixed the video function. You'll have download the latest **chromedriver** from [Google](https://sites.google.com/a/chromium.org/chromedriver/downloads), and include the .exe in your path.

You have to update your TikTokApi version by running
```
pip install TikTokApi
```

Then here's the code for the link you provided

```
from TikTokApi.tiktok import TikTokapi

api = TikTokapi("browsermob-proxy", headless=False)
f = api.get_Video_By_Url("https://www.tiktok.com/@mmjiepai/video/6712998958161087749", return_bytes=1)

with open('test.mp4', 'wb') as filthign:
    filthign.write(f)
```

This will write the video to test.mp4

**Comment by RotemAkerman** [comment]
@davidteather I've tried the code above (using the same link) but it just wrote the following JSON into test.mp4:

`{"statusCode":200,"contentType":"application/json","content":""}`

**Comment by davidteather** [comment]
@RotemAkerman Apparently it broke during one of the updates. Just uploaded a new PyPi package so just update TikTokApi using pip and it should now work.

Official release release on github will come in a few hours.

**Comment by RotemAkerman** [comment]
@davidteather Thanks!
This seems to work now, but **video does include the watermark...**

BTW: when running, the Chrome window tries to access `http://www.tiktok.com/en/trending` instead of `https://` which forces me to manually click `Advanced -> Proceed Anyway` in order to make it work.

**Comment by RotemAkerman** [comment]
@davidteather BTW: How do I translate video link from 
http://vm.tiktok.com/jN55fJ/ -> https://www.tiktok.com/@mmjiepai/video/6712998958161087749

**Comment by konman1989** [comment]
> Google

Hi @davidteather , having issues running api.trending(10), it throws a 'selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH.' error.  

The driver itself is in 'browsermob-proxy' dir.  Is there a way to explicitly give it a path?
Thanks
