### ISSUE TITLE
[FEATURE_REQUEST] - Cursor support to get all TikToks from certain user

### ISSUE THREAD

**Issue by rahadiancs** [davidteather/TikTok-Api#193]
**Is your feature request related to a problem? Please describe.**
I can't seem to find the way to download all videos of certain user, especially those with hundreds of videos.

**Describe the solution you'd like**
Is it possible to add a maxcursor parameter (if we want to decide to continue downloading from certain point), or implement automatic maxcursor calculation to keep downloading video list like how the website works.

**Comment by rezaarifandee** [comment]
What are u talking about? I can download all user's TikToks using count object just fine (yes, even if the user has thousands of TikToks). Just specify how many do you want to download in count argument.

About cursor support, i don't think this wrapper implemented it yet, but the API url has minCursor and maxCursor, it should be easy to modify the function if u want a proper cursor support. Maybe u can do a pull request for this?

**Comment by davidteather** [comment]
Maxcursor isn't really like an offset number it's a longer number returned in the json response from the server. (I think it's hidden in most methods).

**Comment by davidteather** [comment]
New release is this was an issue for you
