### ISSUE TITLE
The byHashtag Method 

### ISSUE THREAD

**Issue by eburmicz** [davidteather/TikTok-Api#194]
This method is possibly broken. Perhaps they have changed it on TikToks end?

e.g.

`api.byHashtag('savage')`

should give a lot of return results. The error suggests the response is empty.

Does this occur for anyone else?

I am using TikTokAPI 3.3.6

**Comment by davidteather** [comment]
The current version of tiktokapi is 3.3.6 please upgrade 

pip install TikTokApi —upgrade

**Comment by eburmicz** [comment]
That was a typo my mistake. I am using 3.3.6 and edited to reflect.

**Comment by eburmicz** [comment]
Oh this is working now. Perhaps the API was down last night as the JSON  responses appeared empty.

**Comment by davidteather** [comment]
Yeah that’s strange. Sometimes it does rate limiting issues or bugs I guess.
