### ISSUE TITLE
[BUG] - Stale Chrome Processes

### ISSUE THREAD

**Issue by josbraden** [davidteather/TikTok-Api#195]
**Description**

Chrome processes spawn and hang around until the Python process ends. Running API calls in a loop will eventually throw an error `OSError: [Errno 24] Too many open files` because there aren't any pipes left.

**Steps to reproduce**

Run below in your Python interpreter:

```
from TikTokApi import TikTokApi
api = TikTokApi()
resultKnt = 2
data = api.trending(count=resultKnt)
# Check chrome processes from another shell with:
# `ps -e | grep chrome`
# There'll be one <defunct> process like below:
# `   2475 pts/0    00:00:00 chrome <defunct>`
# Now make another API call:
data = api.trending(count=resultKnt)
# There'll be two <defunct> processes:
#   2475 pts/0    00:00:00 chrome <defunct>
#   2525 pts/0    00:00:00 chrome <defunct>
```

**Desktop Information:**

 - OS: Ubuntu Server 20.04
 - TikTokApi Version 3.3.4 via pip3
- Python 3.8.2

**Resolution**

I'm not familiar with chromium or python, but [this Stackoverflow user describes a similar problem](https://stackoverflow.com/questions/54431289/too-many-open-files-error-when-using-asyncio-pyppeteer) and was able to resolve it by calling 'browser.process.communicate()'

I'll open a PR for a fix that worked in my testing, but please know that I don't know what I'm doing!

Thanks!!

**Comment by davidteather** [comment]
fixed [here](https://github.com/davidteather/TikTok-Api/releases/tag/V3.3.7)

**Comment by lekhanhtoan37** [comment]
Dear @davidteather,
Im in v3.5.4 and still meet this bug when run as python service in ubuntu 16.04. It is only 3 or 4 hours when i run as a while-loop to getTrending automatically.

ERROR:root:Caught exception [Errno 24] Too many open files
