### ISSUE TITLE
Get the playable watermark free URL

### ISSUE THREAD

**Issue by lazidoca** [davidteather/TikTok-Api#197]
**Is your feature request related to a problem? Please describe.**
I see some online tools can extract the playable watermark free URL with the format like this: https://v16m.tiktokcdn.com/f627758a57c9fd0e0a48b266b4eb0bc7/5f1c23a6/video/tos/alisg/tos-alisg-pve-0037/738f56402f2a41fdb98d1a8dec087bbe/xxxxxxxxxxxxxxx

**Describe the solution you'd like**
The current API can get the downloadable watermark free but when I paste it to browser, it doesn't play. It would be nice if there is an API to get the playable URL

**Comment by davidteather** [comment]
Can you link of these free online tools that does this?

**Comment by lazidoca** [comment]
@davidteather OK, for an example of this one https://snaptik.app/en

Input video: https://www.tiktok.com/@pawsuppetsalon/video/6849389320973913350

Ouptut playable watermark free: https://v19.tiktokcdn.com/78f294641a723d2fcb12a106c8ecdfe3/5f1d3247/video/tos/useast2a/tos-useast2a-pve-0068/ec3191cf05f54ac09e0e38c7526d9306/?a=1180&br=5892&bt=2946&cr=0&cs=0&dr=0&ds=6&er=&l=202007260135200101151192450FDBBF45&lr=&mime_type=video_mp4&qs=0&rc=anl3Zmc4PGp4djMzOzczM0ApPGk1OWlkNDs8Nzg0ZzdpZ2czNS5obl8wajNfLS1gMTZzczJfYjJfY19iXjQzNmJjYy86Yw%3D%3D&vl=&vr=

**Comment by davidteather** [comment]
closed with latest release
