### ISSUE TITLE
[BUG] - userPosts function KeyError: 'hasMore'.

### ISSUE THREAD

**Issue by rezaarifandee** [davidteather/TikTok-Api#201]
I haven't used this api for like a week, and today i got this error. 

>File "/usr/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 144, in byUsername
>    return self.userPosts(data['id'], data['secUid'], count=count, proxy=proxy, language=language, region=region)
>  File "/usr/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 128, in userPosts
>    if not res['hasMore'] and not first:
>KeyError: 'hasMore'

I looked at the function and added `print(res)`, but it just prints `{'statusCode': 10201}`.
Anybody got this error? Is this normal? What the status code 10201 mean? 

I am not sure if this is a ban or not since `byUsername` function able to retrieve the user info just fine.

**Comment by rezaarifandee** [comment]
Ok, i changed the count argument for byUsername to something small like 10, and it works!

However when i changed it to 100, the error shows up again.

**Comment by rezaarifandee** [comment]
I tested a bit, and it seems like 50 is the biggest count i can input that produces no error. So i think the API needs some changes regarding the max of 99 count in it. Do you want me to do a pull request for it, @davidteather?

**Comment by davidteather** [comment]
New version released to fix this

**Comment by rezaarifandee** [comment]
Thanks, David.

**Comment by rezaarifandee** [comment]
Seems like this one is broken again. However, changing the `maxCount` doesn't seems to work (i even tried changing it to 1). Printing the response, i got the response below:

> {'statusCode': 0, 'hasMore': False, 'maxCursor': '0', 'minCursor': '1596052508000'}
> {'statusCode': 0, 'hasMore': False, 'maxCursor': '0', 'minCursor': '1596052509000'}
> TikTok isn't sending more TikToks beyond this point.

Seems like TikTok is under a big API changes.

**Comment by davidteather** [comment]
Does byUsername work for you? I don't think I have tests for userPosts. If byUsername works that's strange because it uses userPosts

**Comment by rezaarifandee** [comment]
Oh, it's my fault, i got a typo in the username, and the wrong user didn't post any TikToks.

Sorry, Dave.

**Comment by davidteather** [comment]
No worries!
