### ISSUE TITLE
[BUG] - api.get_Video_No_Watermark is not working

### ISSUE THREAD

**Issue by RVLVT** [davidteather/TikTok-Api#203]
**Describe the bug**

I haven't used this api for a while, after update latest version i cant use api.get_Video_No_Watermark. it only download 81 bytes video, sometimes returning NoneType

**Comment by davidteather** [comment]
Try api.get_Video_No_Watermark_Faster while I look into that issue further

**Comment by llacb47** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/266

**Comment by davidteather** [comment]
Well that's kind of annoying. I would assume there's some way to use the details of the tiktok json object to generate the key for the video download, but I doubt it would be easy to figure out.

**Comment by rezaarifandee** [comment]
Ah, i experienced this too yesterday, it was only one video so ignored it. I'll test if there any possibilities that the watermarked video still contains video id (even if it got no "vid:" string).

**Comment by rezaarifandee** [comment]
Doesn't seem like there is video id. I regexed for v 5number and a alphabet and it returns nothing like video id.

**Comment by drdexter1989** [comment]
I wonder how its possible that this website has the possibility to get the without watermark video. https://snaptik.app

**Comment by davidteather** [comment]
@drdexter1989 There are some private scripts that you can pay for that use the app's endpoints with generating X-Gorgon and stuff. I'd imagine that site is using something like that.

**Comment by vnnegt** [comment]
> I wonder how its possible that this website has the possibility to get the without watermark video. https://snaptik.app

i tried this site and received the same video that `tiktok-scraper` provided

**Comment by davidteather** [comment]
@vnnegt Did you get the video without a watermark using tiktok-scraper?

**Comment by vnnegt** [comment]
> @vnnegt Did you get the video without a watermark using tiktok-scraper?

Sorry, should have added that it was the same watermarked version tiktok-scraper provides

**Comment by ssovit** [comment]
https://savevideo.ninja/tiktok-no-watermark-video-downloader/?tiktok-search=https%3A%2F%2Fwww.tiktok.com%2F%40jasonderulo%2Fvideo%2F6859437817035083014

**Comment by davidteather** [comment]
Here's workaround you can use as a function. I don't want to put it in the api fully, because it's making requests to a website that isn't TikTok and I'd rather not send thousands of requests to their servers from the people who use this api.

```
import requests

def download_no_wm(url, get_bytes=1):
    url = url.split("?")[0]
    base_url = "https://savevideo.ninja/wp-admin/admin-ajax.php?action=wppress_tt_download&url={}&key=no-watermark".format(url)
    if get_bytes == 1:
        r = requests.get(base_url)
        return r.content
    else:
        return base_url
```

**Comment by ssovit** [comment]
https://rapidapi.com/wppressapi-wppressapi-default/api/tiktok9 this API has endpoint that works with non watermarked videos

**Comment by davidteather** [comment]
I’m unable to reverse engineer a private api. I’m aware there’s sites that return them without watermarks, but they’re most likely mobile endpoints.

**Comment by bbmarroquin** [comment]
You can use this endpoint to get full json video with non-watermakr video url https://demo.wppress.net/wp-json/wppress/tiktok-downloader/videos?search={url}&type=video_url&max=0

**Comment by ssovit** [comment]
I have my API script on sale if anybody is interested.

**Comment by jjohnreese** [comment]
Did anyone had any luck with finding a way to get the Video ID of the new tiktoks?

**Comment by davidteather** [comment]
@jjohnreese I don't believe we have, but in the meantime you can use
```
import requests

def download_no_wm(url, get_bytes=1):
    url = url.split("?")[0]
    base_url = "https://savevideo.ninja/wp-admin/admin-ajax.php?action=wppress_tt_download&url={}&key=no-watermark".format(url)
    if get_bytes == 1:
        r = requests.get(base_url)
        return r.content
    else:
        return base_url
```

although, I'm not liable for anything you use this for.

**Comment by jjohnreese** [comment]
@davidteather Thanks for the suggestion, but I run a bot with many requests and I don't want to overwhelm this website.
I do wonder how those kind of websites achieved this, how did they get the video id.
anyway ill keep looking for a solution for this.

**Comment by rizkyfarhanrr** [comment]
> @jjohnreese I don't believe we have, but in the meantime you can use
> 
> ```
> import requests
> 
> def download_no_wm(url, get_bytes=1):
>     url = url.split("?")[0]
>     base_url = "https://savevideo.ninja/wp-admin/admin-ajax.php?action=wppress_tt_download&url={}&key=no-watermark".format(url)
>     if get_bytes == 1:
>         r = requests.get(base_url)
>         return r.content
>     else:
>         return base_url
> ```
> 
> although, I'm not liable for anything you use this for.

how to use this

**Comment by ssovit** [comment]
> > @jjohnreese I don't believe we have, but in the meantime you can use
> > ```
> > import requests
> > 
> > def download_no_wm(url, get_bytes=1):
> >     url = url.split("?")[0]
> >     base_url = "https://savevideo.ninja/wp-admin/admin-ajax.php?action=wppress_tt_download&url={}&key=no-watermark".format(url)
> >     if get_bytes == 1:
> >         r = requests.get(base_url)
> >         return r.content
> >     else:
> >         return base_url
> > ```
> > 
> > 
> > although, I'm not liable for anything you use this for.
> 
> how to use this

Hmm. I  am owner of savevideo.ninja .. and I would suggest not to add too many requests on the server.

I have cheap RapidAPI endpoint that you can use for affordable price if you want to use https://rapidapi.com/wppressapi-wppressapi-default/api/tiktok9/endpoints

**Comment by davidteather** [comment]
@ssovit yeah that’s why I didn’t include it in the official package it would be a ton of requests

**Comment by ssovit** [comment]
@davidteather yeah.. appreciate that.. but with your last comment, people were bombarding! so I can had to add token verifications.

it's been challenging..I manage multiple plugins that depend on my private API that does the stuffs.. I would be more than happy to explain how I got it, but afraid it would get patched.

I was never into RapidAPI, but the endpoints I have provided(the cheapest I could go) is just so I can provide the service for 5 servers and  I can use on my products for myself..

**Comment by Zachary24** [comment]
> @davidteather yeah.. appreciate that.. but with your last comment, people were bombarding! so I can had to add token verifications.
> 
> it's been challenging..I manage multiple plugins that depend on my private API that does the stuffs.. I would be more than happy to explain how I got it, but afraid it would get patched.
> 
> I was never into RapidAPI, but the endpoints I have provided(the cheapest I could go) is just so I can provide the service for 5 servers and I can use on my products for myself..

did you take down the api on RapidAPI?

**Comment by ssovit** [comment]
> > @davidteather yeah.. appreciate that.. but with your last comment, people were bombarding! so I can had to add token verifications.
> > it's been challenging..I manage multiple plugins that depend on my private API that does the stuffs.. I would be more than happy to explain how I got it, but afraid it would get patched.
> > I was never into RapidAPI, but the endpoints I have provided(the cheapest I could go) is just so I can provide the service for 5 servers and I can use on my products for myself..
> 
> did you take down the api on RapidAPI?

https://rapidapi.com/ssovit/api/tiktok-no-watermark1 here it is

**Comment by demon071** [comment]
get video_id from https://tiktok.com/v/{video_id}}.html

**Comment by davidteather** [comment]
> get video_id from [https://tiktok.com/v/{video_id}}.html](https://tiktok.com/v/%7Bvideo_id%7D%7D.html)

Doesn't seem to work for me goes to 404

**Comment by davidteather** [comment]
Stale
