### ISSUE TITLE
[BUG] - wrong answer after several requests

### ISSUE THREAD

**Issue by tarkhil** [davidteather/TikTok-Api#206]
After several requests to tiktok (getTikTokbyId in my case), TikTok begins to return only

{"code": "10000", "from": "", "type": "verify", "version": "", "region": "va", "subtype": "slide", "detail": "xEjm*7jBPnMllKzEUYW8xSJ-ivjFjq65ZCYvEfIj3pI1Z3VtwL-uBL4JnDUOshgBEzoHt7mfm6YHTheB0ulhLuQchGb6mFdS1tvGxJA08J9k8x37-lFZS-pmCl4PMOANhq32MJ7GwBNl4wJDcEAdTM-bqP4gVZgcrdE3QWBRGu0LJ0akzT1OIeFsuVNzmxjWDG2aTIXtAaNvtEakfXSR*kgFNSUI3AI.", "verify_event": "", "fp": "verify_551e7a5c9e57bd01a65a2b32ad396360"}

to each request. Is it indefeatable ban by IP or something we're able to cope with?

**Comment by llacb47** [comment]
That's a captcha, I guess you have to use another IP address, or slow down the rate of your requests.

**Comment by davidteather** [comment]
Are you using a proxy? I've sent a ton of requests from a single IP and it hasn't thrown this error yet. The captcha software might have added a list of proxies or something.

**Comment by tarkhil** [comment]
No proxy, just two threads running for 5 minutes. Now API works again, I'll look if it will last more or less long

**Comment by davidteather** [comment]
Yeah I imagine you were sending too many requests

**Comment by tarkhil** [comment]
Message like this (now {"code": "10000", "from": "", "type": "verify", "version": "", "region": "va", "subtype": "slide", "detail": "XCK4-u6GpYEvkAmd8RvRKchEVNPPXtuEDFz3Z2dmBlzao52XsyJw2Ekz0CuYjQ6-0eNfNWceEb5uj3ElicI6ZtM8kI-hGcVfUlVdw5RwNVRJCrGBdEd0QOylcOZF96r*2MX4B4sTfgulLqHIvUyO4xjMRLhJFORWfsuIG1Cw*OSigGAsylUA7tYJ4Wl5mRu9EYInoxhxXM*X36X2RIE*ADqUp39Yj3I.", "verify_event": "", "fp": "verify_e2d2e4378ce6e8b60480c59ae44fdb68"}) repeats after several minutes of work. On my new IP restarting works, on old ones does not. Ok, I'll use proxy and look
