### ISSUE TITLE
Why can't i get  object user ?

### ISSUE THREAD

**Issue by markdrrr** [davidteather/TikTok-Api#207]
Hi, can you help me? Why does not it work? 

code
```
from TikTokApi import TikTokApi
api = TikTokApi() 
tiktoks = api.byUsername('donelij')
print(tiktoks)
for tiktok in tiktoks:
    print(tiktok) 
```

error
> `https://m.tiktok.com/api/user/detail/?uniqueId=donelij&language=en&verifyFp=verify_kdf52cly_U2LFCuwM_JFHm_4Fk3_8l68_fGaEzZPtjX4a&_signature=_02B4Z6wo00f01zGrCoQAAIBAWvEwRGVyrasxqy4AAJNLc1
> Converting response to JSON failed response is below (probably empty)
> 
> Traceback (most recent call last):
> .....
>     raise Exception('Invalid Response')
> Exception: Invalid Response`

**Comment by markdrrr** [comment]
How can I get complete information about a user? page for json is empty
Help me, please

**Comment by davidteather** [comment]
Does your script work for other users? The library is working for me to return that user.

What happens when you run 
```
chromedriver
```

in a console? If there's errors doing that fix them

**Comment by markdrrr** [comment]
How to write complete correct code to get a user object?

**Comment by markdrrr** [comment]
> Does your script work for other users? The library is working for me to return that user.
> 
> What happens when you run
> 
> ```
> chromedriver
> ```
> 
> in a console? If there's errors doing that fix them

How to write complete correct code to get a user object?

**Comment by davidteather** [comment]
Your code is correct for getting TikToks, but there is an issue with your installation. What happens when you run chromedriver in terminal?

**Comment by markdrrr** [comment]
I don't run chromedriver in terminal, how make it ?

**Comment by davidteather** [comment]
See #178
