### ISSUE TITLE
Getting error "{"code": "10000", "from": "", "type": "verify" while running getTikTokById()

### ISSUE THREAD

**Issue by Incher25** [davidteather/TikTok-Api#222]
Hi all,

I try to get info about few TikToks, so I have the following python script:
```
#!/usr/bin/env python3
import sys
import json
from TikTokApi import TikTokApi
api = TikTokApi()

tiktokId = sys.argv[1]

tiktok = json.dumps(api.getTikTokById(id=tiktokId))
print(tiktok)
```

Then I call it from php script:
```
foreach ($videos as $video) {
            $command = escapeshellcmd("python3 {$this->pythonScriptPath} {$video->getRemoteId()}");
            $result = shell_exec($command);
            $videoData = json_decode($result);

            // Saving video info into DB
}
```

And I often get errors like this:

> {"code": "10000", "from": "", "type": "verify", "version": "", "region": "va", "subtype": "slide", "detail": "yDh6ULqmLqVDRICGAyi4jPFInBgXJZz1CIUKUb9a9KAp*pr-vAShXGRpksfBueV-Vcx4XxRN2i3vziV4fwZF-3z-x5pS6bZxU5jdMydcTkeqxgLKNzJgVBcynsbFctnPMIMe-VK*22osBIvDl45PnUlJEjikdXD*DKqNJ0zjI9JgPsIHSfOXGOpHFZmwq7WPMCiDAjRxxw8EJ5mTWQpQ..", "verify_event": "", "fp": "verify_3df7d7a1795c135b58a39084f58d3"}

I've tried to put sleep(10) after each request in php code, but still getting those error messages. Is there an API errors description anywhere? And what should I do with this error?

I'm using 
CentOS Linux release 7.7.1908 (Core)
Python 3.6
TikTokApi-3.4.0

Thanks for help in advance!

**Comment by alternativshik** [comment]
This is captcha.

**Comment by davidteather** [comment]
Yea that's a captcha response. Not sure where you're running your server, but I got issues running it on shared IP addresses like a heroku instance. AWS EC2 has worked for me without issue.

**Comment by NitendraKumar** [comment]
I am facing the same issue.  Anyone  solve  this issue.
@Incher25 did you get any workaround for the  problem.

**Comment by Incher25** [comment]
@NitendraKumar no, unfortunately I haven't found any workaround, so I just repeat request if it failed before. Sometimes it works, sometimes not.

**Comment by davidteather** [comment]
> I must have started this week to be WAY more aggressive.

It's possible that TikTok ended up banning your IP. 

Yeah the best work around is using less detectable proxies right now.

**Comment by tokjii** [comment]
I literally have this on my home IP. But maybe there is also an issue in my implementation, I'm not using the TikTok-Api repo in production, only a boiled-down version
