### ISSUE TITLE
[BUG] - Installing with pip adds a global 'tests' package 

### ISSUE THREAD

**Issue by hoylemd** [davidteather/TikTok-Api#226]
**Describe the bug**
When I install the package with pip 

`pip install TikTokApi`

A `tests` module appears in `site-packages`.  This isn't a problem on it's own, but it's pretty common to name the test directory 'tests' in python projects. If you have a helper module in there (e.g. `your_project/tests/helpers.py`) then you can no longer import anything from that `tests` directory, as `site-packages` takes precedence over pythonpath.

**The buggy code**

```
# myproject/tests/test_something.py
from tests.helpers import some_helper
```

> ModuleNotFoundError: No module named 'tests.helpers'

**Expected behavior**

I expect to be able to name my tests module 'tests'

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6 Mojave
 - TikTokApi Version: 3.4.3
 - Python: 3.8.3

**Additional context**

Just renaming that to `TikTokApi-tests` would work great.

**Comment by davidteather** [comment]
Tests package seems to be created by the pyppeteer package. I don't have control over that code.

**Comment by hoylemd** [comment]
Well then, I shall take my bug report elsewhere sir, good DAY! ;)

**Comment by hoylemd** [comment]
As a workaround, things seem to work fine if you just delete that `tests` package from `site-packages`.
