### ISSUE TITLE
[BUG] - Putting Spanish lang code gives me Russian hashtags and Arabic trendings

### ISSUE THREAD

**Issue by elblogbruno** [davidteather/TikTok-Api#227]
**Describe the bug**

Putting the Spanish lang code gives me Russian hashtags using the get trending hashtag. If I do use the get trending function I do get Arabic videos.

![errorLanguage](https://user-images.githubusercontent.com/10481058/90764660-ec1f8480-e2e8-11ea-8efb-604f3665c8d3.png)

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
@app.route('/get_tiktoks_by_hashtag')
def get_tiktoks_by_hashtag():
    hashtag = request.args.get('hashtag')
    results = 10 if request.args.get('limit') is None else int(request.args.get('limit'))
    lang = 'en' if request.args.get('lang') is None else request.args.get('lang')

    print("Getting {0} hashtag in {1} language".format(hashtag, lang))

    try:
        tiktoks = api.byHashtag(hashtag, language=lang, count=results)
    except BadStatusLine as e:
        print(str(e))
        time.sleep(30)
    return jsonify({"hashtag_tiktok": tiktoks})
```

**Expected behavior**
When I do access tiktok from my country,Spain, I do get this as trending.
![2020-08-20 13_26_12-Vídeos populares en TikTok](https://user-images.githubusercontent.com/10481058/90764573-c5f9e480-e2e8-11ea-92db-035c27ffea9c.png)

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Debian 9
 - TikTokApi Version [e.g. 3.3.1] - if out of date upgrade before posting an issue 3.4.3

**Additional context**

**Comment by davidteather** [comment]
Yeah they don’t really do anything but are parameters you can request in the tiktok url it just doesn’t seem to do much. There’s a closed issue somewhere about it. Use a proxy in the country you want

**Comment by elblogbruno** [comment]
How can I use a proxy?
