### ISSUE TITLE
[INSTALLATION] - Your error here

### ISSUE THREAD

**Issue by dudabomm** [davidteather/TikTok-Api#229]
**Describe the error**

Put the error trace here.

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - TikTokApi Version [e.g. 3.3.1] - if out of date upgrade before posting an issue

**Additional context**

Put what you have already tried. Your problem is probably in the closed issues tab already.

**Comment by davidteather** [comment]
You didn’t fill out the template. You gotta fill it out for help
