### ISSUE TITLE
[FEATURE_REQUEST] - Request Get Data Comment

### ISSUE THREAD

**Issue by irfangerard44** [davidteather/TikTok-Api#239]
**Is your feature request related to a problem? Please describe.**
Would be super helpful if video data was included the latest comment in the meta data returned

**Comment by davidteather** [comment]
Comments endpoint is blocked for the desktop site without sign in

**Comment by irfangerard44** [comment]
> Comments endpoint is blocked for the desktop site without sign in

Can you provide that option by Sign in?

**Comment by davidteather** [comment]
Potentially in a few weeks, but as of right now that feature isn't going to be added for a bit. It's now on my todo list

**Comment by irfangerard44** [comment]
Thank you very much
