### ISSUE TITLE
[FEATURE_REQUEST] - What you want here

### ISSUE THREAD

**Issue by dylanbarne** [davidteather/TikTok-Api#241]
I would like a function to get the amount of followers a user has as the data returned from the get user method is not easy to filter due to its format

**Comment by davidteather** [comment]
Here's code to do that. All the information is in dictionary formatting. I am not planning to add methods for each of the statistics as that's a bit redundant.
```
from TikTokApi import TikTokApi
api = TikTokApi()
tiktok_username = "therock"

user_data = api.getUser(tiktok_username)
followers = user_data['stats']['followerCount'] 
print(followers) # prints number of followers for the given user
```
