### ISSUE TITLE
[FEATURE_REQUEST] - The url to request data has browser and OS related parameters

### ISSUE THREAD

**Issue by Saketh41** [davidteather/TikTok-Api#245]
The url to request data has browser and OS related parameters. The user agent value is hard coded to Windows specifications in the code. Request you to make it feasible with other OS also.

Access the website in a linux machine (or a virtual machine with linux) and track the network to see the pattern in the request link. 

Tried scraping using Selenium, Beautiful Soup and scrapy but after few requests site is blocking the content

**Comment by davidteather** [comment]
I run the rapid api for this repo on Linux machines and the Travis-cj tests are also Linux and they work without issue.
