### ISSUE TITLE
[BUG] - The API returns consistently 404 after 335 consecutive calls are made

### ISSUE THREAD

**Issue by hemswayy** [davidteather/TikTok-Api#246]
When running the API code on an AWS ec2 instance (t3.xlarge) the API consistently returns 404 for the calls (api.getUser() method) and only works when I restart the app and start calling it again. The API is running on a simple flask app that is serving it on port 8080 of the server.

**The buggy code**

The code I use to call the deployed API
```
import requests
url = "HTTP://SERVERURL//userdetail?username=bcthemc"

payload = {}
headers= {}

limit = 10000

for i in range(0, 10000):
    response = requests.request("GET", url, headers=headers, data = payload)
    print(i, response.text.encode('utf8'))
```

The /userdetail API call in the flask app on the ubuntu server
```
from flask import Flask, request
from TikTokApi import TikTokApi
app = Flask(__name__)
api = TikTokApi()
proxy = '0.0.0.0:3128'
#proxy = None

@app.route('/userdetail')
def get_user_detail():
    try:
        user_data = api.getUser(request.args.get("username"), proxy=proxy)
        return user_data, 200
    except:
        return user_data, 404
```

**Expected behavior**

I expect the API to keep returning the responses as I am using proxy rotation as well and there are no restrictions on this data from Tiktok so I don't understand why this behavior is happening.

**Error Trace (if any)**

The first 334 calls yield successful results but after the 334th call, all calls return the error in the second picture.

Calls 1 to 334 work fine but after that, all of them have this error:
![image](https://user-images.githubusercontent.com/63860220/91793032-61307980-ec5a-11ea-990a-d1d355977831.png)

This is error in detail:

![image](https://user-images.githubusercontent.com/63860220/91792702-7c4eb980-ec59-11ea-99cd-c9f17567a938.png)

I had to return the user_data variable and I know it will throw an error normally but I did that to capture the actual error :)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - TikTokApi Version [e.g. 3.3.1] - 3.4.6

**Additional context**

The ec2 instance I am using is not the limiting problem as I have tried on a t2.micro, t2.medium & t3.xlarge and all exhibit the same problem and return a 404 after 334 calls are made. I have to restart the flask app and then start calling again which is not feasible in a production environment.

**Comment by Justylol** [comment]
It may be a problem with pyppeteer.
I came across a similar problem. Try to add **'dumpio': True** option key on browser launch and tell if it help.

**Comment by davidteather** [comment]
@hemswayy did the solution above, help you?

**Comment by dombuggy** [comment]
Anyone find a solution for this? Thx

**Comment by davidteather** [comment]
Coming back to this with more information it might be an issue with current open files. If you're on Linux you can increase it with ulimit.

**Comment by davidteather** [comment]
It may be worth trying out a proxy if you haven't already. I'll close the issue for now due to substantial API changes.
