### ISSUE TITLE
[BUG] - AttributeError:'browser' object has no attribute 'verifyFp'

### ISSUE THREAD

**Issue by arthron** [davidteather/TikTok-Api#247]
# Read Below!!! If this doesn't fix your issue delete these two lines
**You may need to install chromedriver for your machine globally. Download it [here](https://sites.google.com/a/chromium.org/chromedriver/) and add it to your path.**

**Describe the bug**

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
# Code Goes Here
```

**Expected behavior**

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - TikTokApi Version [e.g. 3.3.1] - if out of date upgrade before posting an issue

**Additional context**

Why does this error occur？

**Comment by davidteather** [comment]
#237
