### ISSUE TITLE
[FEATURE_REQUEST] - Hope to add support for search users, videos, sounds by keywords

### ISSUE THREAD

**Issue by yswtrue** [davidteather/TikTok-Api#249]
Is your feature request related to a problem? Please describe.
Hope to add support for search users, videos, sounds by keywords, not only user id

Describe the solution you'd like
Add a API to search by keyword and return total count and support custom page size.

Additional context

**Comment by yswtrue** [comment]
there is the API endpoint. I found in this repository `https://github.com/RobertGrubb/tiktok-php`

``
      'discover-user' => [
        'url' => 'https://m.tiktok.com/api/discover/user/?',
        'vars' => [
          'discoverType' => 0,
          'needItemList' => 'false',
          'keyWord'      => '',
          'offset'       => 0,
          'count'        => 28,
          'useRecommend' => 'false',
          'language'     => 'en'
        ]
      ],
```

**Comment by davidteather** [comment]
@yswtrue Which file did you find that in the repository? I can't seem to find it

**Comment by davidteather** [comment]
Added in the latest release, I kinda messed up the V3.4.8 release so I'm fixing it and will update package in probably ~10 minutes
