### ISSUE TITLE
chromedriver needs to be in path.

### ISSUE THREAD

**Issue by giaccomgl** [davidteather/TikTok-Api#25]
Hi @davidteather. First of all my congratulation. Your work is great. Just one question:
As I try to run my first code: 

==========
from TikTokApi import TikTokapi

api = TikTokapi('/Users/mariadaniello/Desktop/browsermob-proxy-2.1.4/bin/browsermob-proxy')
# path_to_browsermob_directory - String - should be the path from the directory you are running from the code to the extracted zip file of [browsermob-proxy](https://bmp.lightbody.net/)
# Will Get the 10 most recent trending on the tiktok trending page
api.trending(10)`
===========

The IDLE returns me the following error:

===========
`Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`
==========

My chromedriver, as a norml MacOs user, is in /usr/local/bin/. Could you please tell me how to solve this iussue? Thank you.

**Comment by davidteather** [comment]
[here](https://www.google.com/amp/s/www.pegaxchange.com/2017/06/17/mac-os-x-path-variable/amp/) is an article on getting path on macOS. Even if you get that to work the trending function won’t work at the moment because due to a change in tiktok’s website that has broken this unofficial Api for now.

**Comment by davidteather** [comment]
Some of the api has been fixed and closing this because the issue has gone stale.

**Comment by giaccomgl** [comment]
Hi David. I had some iusses on installation because of my few experience.
Could you please help me? Through telegram or any way you want. Thank you.

Il giorno lun 18 nov 2019 alle 00:16 David Teather <notifications@github.com>
ha scritto:

**Comment by davidteather** [comment]
Hey there, were you able to add chrome driver to your path? [here](https://chromedriver.chromium.org/downloads) is the link to download the chrome driver. 

You have to save that to some directory that you will remember. Then follow [this](https://www.pegaxchange.com/2017/06/17/mac-os-x-path-variable/) guide on how to add the directory to your path. Then try to rerun the program and tell me if you run into any other errors.
