### ISSUE TITLE
[BUG] AttributeError: 'browser' object has no attribute 'verifyFp'

### ISSUE THREAD

**Issue by tiffblahthegiraffe** [davidteather/TikTok-Api#250]
Ran into the AttributeError when running the following script: 

from TikTokApi import TikTokApi
api = TikTokApi()
results = 10
trending = api.trending(count=results)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-d0a8dd0b53ec> in <module>
      1 results = 10
      2 
----> 3 trending = api.trending(count=results)

~/opt/anaconda3/lib/python3.7/site-packages/TikTokApi/tiktok.py in trending(self, count, language, region, proxy)
    130                 self.__add_new_params__() ,str(realCount), str(maxCursor), str(region), str(language))
    131             b = browser(api_url, language=language, proxy=proxy)
--> 132             res = self.getData(api_url, b, proxy=proxy)
    133 
    134             if 'items' in res.keys():

~/opt/anaconda3/lib/python3.7/site-packages/TikTokApi/tiktok.py in getData(self, api_url, b, language, proxy)
     64         url = b.url + \
     65             "&verifyFp=" + b.verifyFp + \
---> 66             "&_signature=" + b.signature
     67         r = requests.get(url, headers={
     68             'authority': 'm.tiktok.com',

AttributeError: 'browser' object has no attribute 'verifyFp'
------------------------------------------------------------------------------

I've downloaded chromedriver to and put it in system path and have ran the python script under the same directory.

**Comment by davidteather** [comment]
Look in the issues tab there’s a ton of issues with the same error
