### ISSUE TITLE
[INSTALLATION] - Chromium downloading taking forever for any api calls

### ISSUE THREAD

**Issue by nitneo** [davidteather/TikTok-Api#252]
**Describe the error**

When I am calling api the script started to download the chromium and it took forever to complete the download. It looks like it almost struck at 39-40% and never complete. Am getting the below message from the code, please note this is not an error or script won't terminate but and endless download which is downloading only few bits per sec.

```
RESTART: C:\Users\***\Desktop\tiktok.py ==================
[W:pyppeteer.chromium_downloader] start chromium download.
Download may take a few minutes.
```

I also downloaded chromedriver as per instruction given in this [issue ](https://github.com/davidteather/TikTok-Api/issues/137)and tested through cmd prompt (windows) and it is running fine. Still issue exist for me

**The buggy code**

from TikTokApi import TikTokApi # this imports the library
api = TikTokApi() # initializes the library to api
count = 2

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - TikTokApi Version [e.g. 3.3.1] - Downloaded on 9/4/2020
- Python version - 3.8 (script was not runing in python version 3.7)

**Comment by davidteather** [comment]
Not an issue with this library, check out [puppeteer](https://github.com/pyppeteer/pyppeteer) for help.
