### ISSUE TITLE
Query oldest tiktoks skipping the newest when user have too many uploads

### ISSUE THREAD

**Issue by foodtourama** [davidteather/TikTok-Api#253]
Is it possible to query older user tiktoks? For example, for a user with ~400 tiktoks, I just want to retrieve/query the oldest 50, skipping the newest 350... Does that make sense? Or do I have to go through all ~400 tiktoks?
Obviously not a bug, but a feature request or an option I don't know how to use. Don't know how to tag it as "feature request". Thanks!

**Comment by llacb47** [comment]
Not possible

**Comment by davidteather** [comment]
Something sort of what you're looking for is on my plans for the future. It's not necessarily sorting by oldest, but it's using unix epoch to filter the time that the TikToks were created at. I'll close for now, as what you're suggesting isn't totally possible, but my solution is more of a workaround with more guesswork.

If you don't mind doing the cpu time you could just reverse the array, but that's probably not the solution you want.
