### ISSUE TITLE
[BUG]search_by_hashtag

### ISSUE THREAD

**Issue by rever96** [davidteather/TikTok-Api#26]
I've just started using that api, using the function 
`result = api.search_by_hashtag('simpaticissimi', count=10)`
the browser gives me the results about "simpaticissimi" tag, but the code crashed give me into the console that error:
`New class reference, finding valid signature. This might take a minute.
Found signature, continuing.
Traceback (most recent call last):
  File "botticelliAPI.py", line 7, in <module>
    result = api.search_by_hashtag('simpaticissimi', count=10)
  File "/usr/lib/python3.7/site-packages/TikTokApi/tiktok.py", line 193, in search_by_hashtag
    raise Exception('Unable to locate the hashtag ID')
Exception: Unable to locate the hashtag ID`

What that meaning?
How to fix it to run the code under the api call?

**Comment by theparcel** [comment]
Sfortunatamente queste API non funzionano più da due settimane, poichè tiktok ha modificato la signature ed adesso rileva selenium bloccandolo.

**Comment by rever96** [comment]
does you know if the api will be fixed in further future?

**Comment by rever96** [comment]
it seems [here](https://medium.com/@ospiegel51191/the-art-of-not-getting-blocked-how-i-used-selenium-python-to-scrape-facebook-and-tiktok-fd6b31dbe85f) they found a workaround

**Comment by davidteather** [comment]
Changed quite a few things [here](https://github.com/davidteather/TikTok-Api/releases/tag/V2.2.0) is the new release you will have to reinstall using pip. It's not as powerful as before, but it's better than nothing.
