### ISSUE TITLE
[BUG] - KeyError: 'challengeInfo'

### ISSUE THREAD

**Issue by DiegoMORENO-DS** [davidteather/TikTok-Api#260]
Hi,

I was trying to scrap a hashtag but now is not possible. I've had been many problems and the process is not successful. I did in the past and worked well. I'd like to understand why the changes?. Thnaks

code:
from TikTokApi import TikTokApi
api = TikTokApi()
hashtag = 'pasta'
hash1 =  api.byHashtag(hashtag, count=10000, language='en', proxy=None)

Error message:
>>> hash1 =  api.byHashtag(hashtag, count=10000, language='en', proxy=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\diego\Desktop\TikTok2\TikTok-Api-master\TikTokApi\tiktok.py", line 545, in byHashtag
    id = self.getHashtagObject(hashtag)['challengeInfo']['challenge']['id']
KeyError: 'challengeInfo'

**Comment by davidteather** [comment]
Please provide your OS and TikTokApi version.

If you're not on TikTokApi 3.5.0 or higher please upgrade with the following
```
pip install TikTokApi --upgrade
```

If you still run into issues, you may be sending too many requests. The code below will allow you to delay your requests automatically.
```
from TikTokApi import TikTokApi
request_delay_seconds = 1 # throttling requests 
api = TikTokApi(request_delay=request_delay_seconds)
hashtag = 'pasta'
hash1 = api.byHashtag(hashtag, count=10000, language='en', proxy=None)
```

**Comment by davidteather** [comment]
I think I fixed this in a recent update

**Comment by Etanial** [comment]
I used the API a lot in the last 24 hours, doing similar queries for hashtags as DiegoMORENO-DS. As of this morning, I am getting the challenge error above. I suspect it is related to number of requests over a given period. Adding the delay to the request did not help.

The API version is up to date. Here is the error:

`
~/anaconda3/lib/python3.7/site-packages/TikTokApi/tiktok.py in byHashtag(self, hashtag, count, **kwargs)
    545         """
    546         region, language, proxy, minCursor, maxCursor, maxCount = self.__process_kwargs__(kwargs)
--> 547         id = self.getHashtagObject(hashtag)['challengeInfo']['challenge']['id']
    548         response = []
    549 

KeyError: 'challengeInfo'
`
