### ISSUE TITLE
[BUG] - AttributeError: 'browser' object has no attribute 'verifyFp'

### ISSUE THREAD

**Issue by edenhikri** [davidteather/TikTok-Api#263]
I am trying to get the last 10 video stats of users with over 1m followers from a 150 user list on tiktok. However, once it is about half way finished printing all the stats, I get the error.

This is the error I receive:

```
Traceback (most recent call last):
  File "snowball.py", line 24, in <module>
    tiktok = api.getUser(accounts)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 723, in getUser
    return self.getData(b, proxy=proxy)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 71, in getData
    query = {'verifyFp': b.verifyFp, 'did': b.did, '_signature': b.signature}
AttributeError: 'browser' object has no attribute 'verifyFp'
```

my code script:
```
from TikTokApi import TikTokApi

api = TikTokApi()

# file_data is the list of 150 tiktok users accounts) 

for accounts in file_data:
	tiktok = api.getUser(accounts)
	name = (tiktok['userInfo']['user']['uniqueId'])
	followers = (tiktok['userInfo']['stats']['followerCount'])


	if followers > 1000000:
		user_videos = api.byUsername(name, count=10)

		for video in user_videos:
			stats = (video['stats'])
			print(stats, name)

```

It should print the stats of the last 10 videos for each user that is over 1 million followers, and it does so. However, I get an error after it has printed 21 user's stats.

 - OS: macOS Catalina 10.15.3
 - TikTokApi latest version 
 - My location: Australia

I have looked at similar issues under this GitHub repository, however, nothing has fixed it

**Comment by edenhikri** [comment]
Unfortunately, none of the comments on these other issues resolved the issue I am facing...

**Comment by davidteather** [comment]
If the following issues don't help you comment on #237 
* #255 
* #250 
* #247 
* #27 
* #182 
* #166

**Comment by edenhikri** [comment]
I have tried all of these issues and nothing seems to work. I am not in a country in which TikTok is banned. I have also tried running it with debug mode enabled `api = TikTokApi(debug=True)` however the issue still occurs. After printing 20 users stats, it gives me the error. It seems as though it gets stuck. @davidteather
