### ISSUE TITLE
[BUG] - Cannot Download Video

### ISSUE THREAD

**Issue by bravma** [davidteather/TikTok-Api#265]
**Describe the bug**

The downloadAddr of a tiktok item points to a site where I get a 403 - Forbidden Message. Therefore, I am not able to download the videos by using `api.get_Video_By_TikTok`. Is there a workaround?

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
api = TikTokApi()
items = api.trending(5)
for item in items:
    video_bytes = api.get_Video_By_TikTok(item)
```

**Comment by chasingrainbows** [comment]
+1 have the same problem with get_Video_By_TikTok, its doesnt raises any exceptions, just returns something like 1x1 pixel video without sound.

**Comment by ZebTheWizard** [comment]
I'm having the same problem with other methods. When using getTiktokById the video playAddr and downloadAddr both return a 403 error.

Is it possible that Tiktok changed some networking features?

**Comment by llacb47** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/301#issuecomment-693432340

**Comment by davidteather** [comment]
Fixed in nightly, waiting for tests to pass to release an update

**Comment by davidteather** [comment]
Fixed in [the newest release](https://github.com/davidteather/TikTok-Api/releases/tag/V3.5.2) will be out on pypi in a few minutes

**Comment by ZebTheWizard** [comment]
I downloaded the newest release and the URLs still return 403 when using getTikTokById.

**Comment by chasingrainbows** [comment]
Thx! Fix has resolved my problem.

**Comment by michellebao** [comment]
Also still getting the 403 error

**Comment by davidteather** [comment]
@ZebTheWizard @michellebao 
Can you provide the code you're running? I can't seem to reproduce the issue.

Also, make sure you're on the most recent version use the following command to check the version.
```
pip show TikTokApi
```

**Comment by michellebao** [comment]
I just double checked that I'm on version 3.5.2.

`def processTikTokObject(tiktok:dict) -> dict:
  id = tiktok['id']
  resp = {}
  resp['id'] = id
  resp['desc'] = tiktok.get('desc')
  resp['createTime'] = datetime.fromtimestamp(int(tiktok.get('createTime'))).isoformat()
  resp['playAddr'] = tiktok.get('video', {}).get('playAddr')`

where the tiktok parameter is each element of `api.trending(count=n)`.

You can see how I'm calling it here: https://github.com/michellebao/tiktok/blob/master/newTikTok.py#L184

**Comment by davidteather** [comment]
Where ever you're actually downloading it from the playAddr add the following header then it should work.
```
r = requests.get(tiktok_video_url, headers={'referer': ''https://www.tiktok.com/'})
```

**Comment by michellebao** [comment]
Thanks that does work for downloading!

**Comment by KaranTrivedi** [comment]
All I ever get is 403 response. Garbage library.
