### ISSUE TITLE
[INSTALLATION] - How to get a custom running SQUID proxy to work.

### ISSUE THREAD

**Issue by elblogbruno** [davidteather/TikTok-Api#289]
**Describe the error**

Hello, recently I posted an issue about asking for spanish tiktoks and getting russian ones. The answer was to use a proxy. So I installed a proxy server on my server using squid. The thing is I can't get tiktok petitions to work now, am I doing it wrong?
Maybe it is a server configuration error so sorry for that if it is a reason
Thanks!
Great job!
Bruno

**The buggy code**

@app.route('/get_trending')
def get_trending():
    results = 10 if request.args.get('limit') is None else int(request.args.get('limit'))
    lang = 'en' if request.args.get('lang') is None else request.args.get('lang')

    print("Getting {0} results in {1} language".format(results, lang))
    try:
        global proxy_url
        print(proxy_url)
        trending = api.trending(count=results,language=lang,proxy=proxy_url)
    except BadStatusLine as e:
        print(str(e))
        time.sleep(30)
    return jsonify({"tiktoks": trending})

Where proxy_url is a string that contains my proxy url witouth https,only the ip:port

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
At start this popped up at first request, then nothing.

    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='m.tiktok.com', port=443): Max retries exceeded with url: /api/item_list/?aid=1988&app_name=tiktok_web&device_platform=web&referer=https%3A%2F%2Fwww.tiktok.com%2F&user_agent=Mozilla%252F5.0%2B%28Windows%2BNT%2B10.0%253B%2BWin64%253B%2Bx64%29%2BAppleWebKit%252F537.36%2B%28KHTML%2C%2Blike%2BGecko%29%2BChrome%252F84.0.4147.125%2BSafari%252F537.36&cookie_enabled=true&screen_width=800&screen_height=600&browser_language=&browser_platform=&browser_name=&browser_version=&browser_online=true&ac=4g&timezone_name=&appId=1233&appType=m&isAndroid=False&isMobile=False&isIOS=False&OS=windows&count=10&id=1&type=5&secUid=&maxCursor=0&minCursor=0&sourceType=12&appId=1233&region=US&priority_region=US&language=es&verifyFp=XSWO0PKTiZ9SdfnS&did=18007046&_signature=_02B4Z6wo00f01BuaJlQAAIBDJ0UT2rX1NcAbiiLAAFln7a (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Debian 9
 - TikTokApi Version [e.g. 3.3.1] - if out of date upgrade before posting an issue 3.5.0

**Additional context**

Put what you have already tried. Your problem is probably in the closed issues tab already.

**Comment by davidteather** [comment]
Hi, I've made substantial changes to the api in the last few days your code will probably need updating but your proxies should work provided they're in one of the following formats `proxy="http://user:pass@ip:port"` or `proxy="http://ip:port/"` you should be able to use whatever prefix you need instead of `http` 

Let me know if this is still an issue

**Comment by elblogbruno** [comment]
Ok I'll update and try again!

**Comment by elblogbruno** [comment]
I can't install playwright
```
ERROR: Could not find a version that satisfies the requirement playwright (from versions: none)
ERROR: No matching distribution found for playwright
```

**Comment by elblogbruno** [comment]
Had a bad python version,sorry!
