### ISSUE TITLE
api.get_Video_By_TikTok(data, language='en', proxy=None)[BUG] - Your Error Here

### ISSUE THREAD

**Issue by madibag** [davidteather/TikTok-Api#291]
# Read Below!!! If this doesn't fix your issue delete these two lines
**You may need to install chromedriver for your machine globally. Download it [here](https://sites.google.com/a/chromium.org/chromedriver/) and add it to your path.**

**Describe the bug**

The get_video_By_Tiktok can't grab the download url because of the dictionary returned value has been modified(changed) 

**The buggy code**
class TiktokApi:
    
Please insert the code that is throwing errors or is giving you weird unexpected results.

```
# Code Goes Here
```
a['itemInfos']['video']['urls'][0]
**Expected behavior**

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - TikTokApi Version [e.g. 3.3.1] - if out of date upgrade before posting an issue

**Additional context**
replace the code with a['itemInfo']['itemStruct']['video']['downloadAddr']

**Comment by rabiranjankumar** [comment]
[W:pyppeteer.chromium_downloader] start chromium download.
Download may take a few minutes.
Traceback (most recent call last):
  File "downloadTikTok.py", line 8, in <module>
    "https://www.tiktok.com/@raja_jii555/video/6817097295914388737", return_bytes=1
  File "C:\conda\lib\site-packages\TikTokApi\tiktok.py", line 928, in get_Video_By_Url
    raise Exception("Deprecated. Other Methods Work Better.")
Exception: Deprecated. Other Methods Work Better.

i am  getting this error

**Comment by davidteather** [comment]
See #203 

@rabiranjankumar I'm updating that python file now
