### ISSUE TITLE
I want to use this API in dart and also I want to use auth token of tiktok to access private account.

### ISSUE THREAD

**Issue by deveshgarg-max** [davidteather/TikTok-Api#293]
HI,
I really need to use this API in dart format and want to access a private account via auth token of TikTok I am not able to receive data from this request method it is sending me headers but not the body. The HTTP request is giving me an empty value with status code 200 and header values is there any solution for that I really need it.

**Comment by davidteather** [comment]
If TikTok doesn't return data with a statuscode of 200 that means you are being detected by their servers you can use a server running something like flask to return the data and handle it in dart.
