### ISSUE TITLE
[BUG] - Video playAddr/downloadAddr video URL invalid 

### ISSUE THREAD

**Issue by michellebao** [davidteather/TikTok-Api#296]
I am not able to access the video url in playAddr or downloadAdd by using the requests package.

Example playAddr/downloadAddr: `url = https://v16-web-newkey.tiktokcdn.com/72bd098ebfeaa71c084919d3a55efd64/5f93f32e/video/tos/useast2a/tos-useast2a-ve-0068c003/6e2d74eb3de944a28013313625663e6f/?a=1988&br=5980&bt=2990&cr=0&cs=0&cv=1&dr=0&ds=3&er=&l=2020102403255301019020801232109270&lr=tiktok_m&mime_type=video_mp4&qs=0&rc=M3lzajV1czVodzMzaDczM0ApaDNkODs0ZTxkNzdlOzhkOmdhYi4tcDVkZTFfLS0xMTZzc2NfX18tYWIxMDFgMS1gXi86Yw%3D%3D&vl=&vr=`

When trying to access: 
`video_bytes = requests.get(url, headers={"User-Agent": "okhttp"}).content`
I get response:
`b'<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;v16&#45;web&#45;newkey&#46;tiktokcdn&#46;com&#47;72bd098ebfeaa71c084919d3a55efd64&#47;5f93f32e&#47;video&#47;tos&#47;useast2a&#47;tos&#45;useast2a&#45;ve&#45;0068c003&#47;6e2d74eb3de944a28013313625663e6f&#47;&#63;" on this server.<P>\nReference&#32;&#35;18&#46;bfa83617&#46;1603510554&#46;9d99b4\n</BODY>\n</HTML>\n'`

**Versioning:**
 - Google Colab
 - TikTokApi Version 3.5.5 (3.5.6 was giving some weird errors about `DevTools listening on ws://127.0.0.1:49147/devtools/browser/9a11fbf1-4032-42c0-95f3-5c22a8356070
[1024/035014.316372:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory` so I used the prev version)

**Comment by davidteather** [comment]
As far as I can tell they're matching the userAgent used in the requests. 

You can either do
```
api.get_Video_By_DownloadURL(url)
```

which returns bytes or if you don't want to use the TikTok class function you can do the following

```
video_bytes = requests.get(url, headers={"User-Agent": api.userAgent}).content
```

**Comment by michellebao** [comment]
Using either of the two methods, I'm still getting the following error response:

`b'<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;v16&#45;web&#45;newkey&#46;tiktokcdn&#46;com&#47;72bd098ebfeaa71c084919d3a55efd64&#47;5f93f32e&#47;video&#47;tos&#47;useast2a&#47;tos&#45;useast2a&#45;ve&#45;0068c003&#47;6e2d74eb3de944a28013313625663e6f&#47;&#63;" on this server.<P>\nReference&#32;&#35;18&#46;463819b8&#46;1603659279&#46;5ebfadf\n</BODY>\n</HTML>\n'`

**Comment by davidteather** [comment]
Hmm what about api.get_Video_By_TikTok(api.trending()[0]) does that get you the right content?

**Comment by michellebao** [comment]
`>>> api.get_Video_By_TikTok(api.trending()[0])`

`b'<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;v16&#45;web&#46;tiktok&#46;com&#47;video&#47;tos&#47;useast2a&#47;tos&#45;useast2a&#45;ve&#45;0068c002&#47;dc04204da7a14aa394aadf3128a1407e&#47;&#63;" on this server.<P>\nReference&#32;&#35;18&#46;2fdc1cb8&#46;1603669689&#46;21af02\n</BODY>\n</HTML>\n'`

No such luck, it seems.

**Comment by davidteather** [comment]
Yeah I'm getting the issue now. Working on a fix

**Comment by davidteather** [comment]
Looks like TikTok is now generating the tt_webid_2 cookie in the request to the server.

**Comment by davidteather** [comment]
Found a solution, most of the get_video_by methods won't currently work as I'm kinda tired right now and there's probably better logic to do this, but in the meantime, the following script will work when the package is updated (probably 30 minutes)

```
from TikTokApi import TikTokApi
api = TikTokApi()
tiktok_url = "https://www.tiktok.com/@kaweee1234/video/6883470508726258949"
video_bytes = api.get_Video_By_Url(tiktok_url)
```

It might be a while before fixing the other methods so use this one for now. If you have a TikTok object you can construct the URL yourself using the schema something like `"https://www.tiktok.com/@{}/video/{}?lang=en".format(tiktok['author']['uniqueId'], tiktok['id'])` but the use of that depends on what the schema you're getting looks like.

**Comment by davidteather** [comment]
Released

**Comment by kami4ka** [comment]
I'm using the https://github.com/davidteather/TikTokBot/blob/master/tiktokbot.py

Every possible variant leads to response

```<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;v16&#45;web&#46;tiktok&#46;com&#47;video&#47;tos&#47;useast2a&#47;tos&#45;useast2a&#45;pve&#45;0068&#47;ddb00c589e8c4db49e81d0feafadde5b&#47;&#63;" on this server.<P>
Reference&#32;&#35;18&#46;4591502&#46;1603748016&#46;41f956ab
</BODY>
</HTML>```

**Comment by kami4ka** [comment]
@davidteather I've got the idea of the fix, it wasn't so obvious. Thanks for the workaround 🙃👍

**Comment by lucasoares** [comment]
@davidteather tiktok user post requests now have to be made using the same `did` parameter as the one used to download video bytes?

Can you please explain what you've found? Thanks.

**Comment by davidteather** [comment]
@lucasoares TikTok is basically checking the cookie that was made to watch or download the TikTok video matches the one that's trying to request it.

**Comment by lucasoares** [comment]
The website itself doesn't need a _signature parameter do download TikTok video but the api is generating it, why?

And I got it needs the tt_webid_2 cookie.

I basically need to:
- Fetch user posts
- Download all videos

For that what is the workaround because I don't want to make extra call for each videeo.

I need use the same cookie to fetch user posts and download videos?

**Comment by davidteather** [comment]
Yes

**Comment by davidteather** [comment]
@lucasoares Releasing a fix soon you can do the following 
```
from TikTokApi import TikTokApi
import random

api = TikTokApi()
did = str(random.randint(10000, 999999999))
tiktoks = api.trending(custom_did=did)

for t in tiktoks:
    # The bytes of the TikTok to download
    b = api.get_Video_By_TikTok(t, custom_did=did)
```

**NOTE:** I haven't experimented without using a randomly generated DID, so you may end up getting blocked or something. If you do get blocked change the DID variable again and retry.

**Comment by ziyueluo** [comment]
Still couldn't use the code to download video. By run the code you posted.
It still returns Access Denied.

**Comment by MinghaoXu16** [comment]
It did not work for me neither. Hope to see new updates. Still received access denied.....

**Comment by davidteather** [comment]
@MinghaoXu16  Make sure you're on the last version run `pip install TikTokApi --upgrade`

**Comment by MinghaoXu16** [comment]
I did. I used 3.5.9 but did not work

**Comment by MinghaoXu16** [comment]
Did I use the correct version?

**Comment by davidteather** [comment]
@MinghaoXu16 That's strange, does it fail on every request or just latter requests? Does this print bytes?
```
from TikTokApi import TikTokApi
import random

api = TikTokApi()
did = str(random.randint(10000, 999999999))
tiktoks = api.trending(custom_did=did)

b = api.get_Video_By_TikTok(tiktoks[0], custom_did=did)
print(b)
```

**Comment by MinghaoXu16** [comment]
Thanks for your help! I found the issue. The objects returned by ByHashtag and getTikTokById are different.

**Comment by lucasoares** [comment]
@davidteather thank you for the update.
