### ISSUE TITLE
I think there is still an issue with getting more than 68 videos

### ISSUE THREAD

**Issue by filipdraganic** [davidteather/TikTok-Api#3]
I think the issue is still present because when I invoke trending(100) let's say, the len() function of the data it returns never exceeds more than 65-68 videos. Also in line 32, in the if statement the two urls are the same, but one has a space so the signature was never returned. I got it working by setting one of the two links to m.tiktok.com/.... .

Maybe I didn't use the function properly or something?

**Comment by davidteather** [comment]
Yeah, I see the extra space on line 32.
In theory, it shouldn't matter and I was getting valid signatures last time I tried it out.
I'll take a look at it either today or tomorrow though.

**Comment by davidteather** [comment]
Could you provide your example code that you are running?

**Comment by filipdraganic** [comment]
[tiktok.zip](https://github.com/davidteather/TikTok-Api/files/3556337/tiktok.zip)

This is your code, just with the space removed and www.tiktok.com substituted with m.tiktok.com

**Comment by davidteather** [comment]
Can you also provide an example of the code where you called the API from?

**Comment by filipdraganic** [comment]
tiktok = TikTokapi()

data = tiktok.trending(200)

print(len(data))

**Comment by davidteather** [comment]
So I looked at it and at least for me the signature thing was working.
The weird thing is that I am able to get 141 results when I select to do 200.
The limit may be the website trending page I'll use wireshark tomorrow and see where the apps database calls are going to.

**Comment by filipdraganic** [comment]
Okay, im very interested to see what is the issue

**Comment by davidteather** [comment]
So you doing the change that first link with a space to m.tiktok.com just solved the signature issue not the limit thing right?

Making unofficial APIs really sucks sometimes. I didn’t have much time today to debug to figure out what was causing the issue or anything. The only thing I can think of is that the trending tiktok website limits to presumably 141 videos. 

Tomorrow I should have more free time to figure out what’s wrong with it.

**Comment by filipdraganic** [comment]
> So you doing the change that first link with a space to m.tiktok.com just solved the signature issue not the limit thing right?

Yes, now the code always gets the signature, and before it was a 1 in 10 chance. Maybe its just a issue with my region or something and not necessarily a problem with the code.

> Tomorrow I should have more free time to figure out what’s wrong with it.

I totally get that, im just interested in this and im glad someone else is. Hope to hear from you soon!

**Comment by filipdraganic** [comment]
Hey, David,
Did you find anything that would help solve the problem?

**Comment by davidteather** [comment]
I haven’t been able to yet. Sorry.

**Comment by davidteather** [comment]
It seems like I've been able to resolve the issue. I'm not sure why or how, but it looks like it's able to retrieve more than 200 for me at least. I should have a new PyPi update for V2.1.8 in at most 2 hours.

Thanks for using api!

**Comment by fratamico** [comment]
Hi David,

I'm using the userPosts method to get videos by a given creator, but it seems to only be returning 100 videos? Do you know if there is a way to get around that limit?
