### ISSUE TITLE
Only get_song and get_Video_By_Url methods work in headless mode

### ISSUE THREAD

**Issue by PaluchowskiMatthew** [davidteather/TikTok-Api#30]
![image](https://user-images.githubusercontent.com/13195985/69447208-090c3480-0d24-11ea-8327-76b74102da6e.png)

Unfortunately on headless Ubuntu 18.04 with Chromium installed only get_song and get_Video_By_Url methods work in headless mode. I am not that fluent with Selenium so I have troubles debugging whats going on. Could you please advise @davidteather?

Thanks!

**Comment by davidteather** [comment]
Right now headless doesn’t work due to tiktok detecting headless browsers. Sorry.

**Comment by PaluchowskiMatthew** [comment]
Ok, thank you for your response!
