### ISSUE TITLE
[FEATURE_REQUEST] - Get followers list.

### ISSUE THREAD

**Issue by aaronn** [davidteather/TikTok-Api#300]
**Is your feature request related to a problem? Please describe.**
Would be nice to be able to get the list of followers an authenticated (or otherwise) account has.

**Describe the solution you'd like**
A simple call to list the users following a fixed account. 

**Describe alternatives you've considered**
I’ve seen a few other packages offer this, but would prefer to use this package if it’s something that is going to be added because I prefer Python 

**Additional context**
—

**Comment by davidteather** [comment]
These type of calls are only accessible through the mobile app/endpoints to my knowledge. #120 might be of interest to you
