### ISSUE TITLE
[BUG] - [WARNING] main: Invalid status received for

### ISSUE THREAD

**Issue by hibare** [davidteather/TikTok-Api#301]
Unable to detect user videos, seems like tiktok API is returning None. Tried with VPN, same results

**Expected behavior**
Detects user videos

**Error Trace (if any)**
NA

**Desktop (please complete the following information):**
 - OS: Elementary OS (Linux)
 - TikTokApi Version [e.g. 3.3.1] - 3.5.7

**Comment by davidteather** [comment]
What code are you running

**Comment by hibare** [comment]
getUser method to get user details

**Comment by davidteather** [comment]
Can you provide a section of code that's able to reproduce the issue because I'm unable to reproduce it

**Comment by davidteather** [comment]
The byusername method is working fine for me so I’m assuming it’s an issue with providing the user Id and secuid

**Comment by hibare** [comment]
getUser return data structure has changed and I missed to notice it. This broke my program. 

Its good now.
