### ISSUE TITLE
[BUG] - tiktok might have blocked use of playAddr / downloadAddr with "referer" header

### ISSUE THREAD

**Issue by ming2377** [davidteather/TikTok-Api#302]
I was debugging _get_Video_By_DownloadURL_.

line 898
`b looks fine, it has referrer="https://www.tiktok.com/"`

I added a new line before the return
`c = self.getBytes(b, proxy=proxy)`

c endup with following bytes
`<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;v16&#45;web&#46;tiktok&#46;com&#47;video&#47;tos&#47;useast2a&#47;tos&#45;useast2a&#45;ve&#45;0068c002&#47;3655adba697c4b3ba6619518a67e9d6a&#47;&#63;" on this server.<P>\nReference&#32;&#35;18&#46;3732c517&#46;1603667681&#46;1d5b645d\n</BODY>\n</HTML>\n`

I have been using postman to fetch playAddr/downloadAddr urls with "referer" header all along, just found that is also broken today, 403 all day long.

### Did tiktok finally banned us?

**Comment by davidteather** [comment]
Make sure you're on the latest version
```
pip install TikTokApi --upgrade
```

Does the following code give you correct bytes? 
```
api.get_Video_By_TikTok(api.trending()[0])
```

**Comment by ming2377** [comment]
api.get_Video_By_TikTok(api.trending()[0]) doesn't work either!!

I am on the latest commit in master branch.

**Comment by davidteather** [comment]
I'm working on a fix now

**Comment by davidteather** [comment]
Consolidating to #296

**Comment by kami4ka** [comment]
@davidteather looks like it hasn't fixed the problem

**Comment by davidteather** [comment]
@kami4k provide your code on #296

**Comment by kami4ka** [comment]
@davidteather provided. Thanks
