### ISSUE TITLE
[BUG] - byHashtag not working anymore

### ISSUE THREAD

**Issue by jp-wagner** [davidteather/TikTok-Api#305]
**Describe the bug**
Using the byHashtag method in the TikTokApi class fails.

**The buggy code**
```
api.byHashtag("test", count=50)
```

**Expected behavior**
The method should return 50 posts for the hashtag #test, however the query response I get is
```
{'statusCode': 10201, 'statusMsg': ''}
```
and thus the code fails with 
```
/.../python3.8/site-packages/TikTokApi/tiktok.py", line 707, in byHashtag
    for t in res["itemList"]:
KeyError: 'itemList'
```
**Desktop (please complete the following information):**
 - OS: Arch Linux
 - TikTokApi Version 3.5.8

**Comment by davidteather** [comment]
Looks like they've changed the max count per request. It should be an easy fix. In the meantime, you can use count=35 seems to work for me

**Comment by jp-wagner** [comment]
That does work indeed. Thanks!

**Comment by jp-wagner** [comment]
I fixed the issue as far as I can tell and made my first ever pull request. Hope everything was done properly and thanks again for your work!

**Comment by sipka** [comment]
Hi all - I am having the same issue. How would I be able to use the fix? I am using this for research purposes and getting more than 35 videos per hashtag is important. Thanks both for your work :)

**Comment by davidteather** [comment]
@sipka make sure you’re on the latest version of the library

**Comment by sipka** [comment]
Indeed, I was being daft. Thank you!
