### ISSUE TITLE
Update JSON Structure [HELP]

### ISSUE THREAD

**Issue by theparcel** [davidteather/TikTok-Api#31]
**Describe the bug**

In the previous version of this API i use the following code to create an array with all the urls

**The buggy code**

```
for tiktok in trending:
    videoURL = tiktok["itemInfos"]["video"]["urls"]
    videoname = "downloaded/" + str(prevloops) + ".mp4"
    wget.download(videoURL[0], videoname)
    open("downloaded/concat.txt", 'a').write("file " + str(prevloops) + ".mkv" + "\n")
    clip = VideoFileClip(videoname)
    d = ( clip.duration )
    open("downloaded/durata.txt", 'a').write(str(d) + "\n")
    os.system("ffmpeg -loglevel panic -i downloaded/" + str(prevloops) +  ".mp4" + " -c copy -map 0 downloaded/" + str(prevloops) + ".mkv")
    prevloops += 1
```
**Expected behavior**

Download the videos from a target hashtag

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser  Chrome  78.0.3904.108

**Additional context**

Here the error in the console
```
Traceback (most recent call last):
  File "downloader.py", line 40, in <module>
    videoURL = tiktok["itemInfos"]["video"]["urls"]
KeyError: 'itemInfos'
```

**I think this error is due to the different json structure, I tried to use the new one but didn't succeed**

**Comment by davidteather** [comment]
Unfortunately with the new api to download a video you have to two it in two different "stages"

```
for tiktok in trending:
    videoURL = tiktok["link"]
    data = get_Video_By_Url(videoURL, return_bytes=1)
    with open("downloads/download.mp4", "rb") as downloadedObject:
        downloadedObject.write(data)
```
