### ISSUE TITLE
[BUG] - 2000 Post Limit on Search

### ISSUE THREAD

**Issue by dwight9339** [davidteather/TikTok-Api#313]
So does anyone have an idea why post search result counts are restricted to ~2000?

![search_results_limit](https://user-images.githubusercontent.com/25517492/98165630-78325880-1ea3-11eb-8256-bd5311a1cfd3.PNG)

**Comment by davidteather** [comment]
TikTok just straight up doesn’t return data from their api after 2,000 in my experience
