### ISSUE TITLE
BySound and ByHashtag Problem 

### ISSUE THREAD

**Issue by ziyueluo** [davidteather/TikTok-Api#314]
Hi, I found some problems for method bySound and byHashtag( I'm using 3.6.0)
when I tried: 
musics=api.bySound('6883993546467051522',count=10)
it returns:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Anaconda3\envs\lib\site-packages\TikTokApi\tiktok.py", line 633, in bySound
    for t in res["body"]["itemListData"]:
KeyError: 'body'

And when I tried with byHashtag, sometimes it returned the same error but sometimes it worked well.
And when I used byHashtag, like:
hashtags=api.byHashtag(hashtag,count=2000,proxies=proxies)
the result only contained around 50 unique tiktoks and just kept repeating the same 50 tiktoks.

Thanks for your help!

**Comment by davidteather** [comment]
Are you running the latest version

**Comment by ziyueluo** [comment]
Yes, I'm running with version 3.6.0

**Comment by davidteather** [comment]
What hashtag were you trying to get

**Comment by davidteather** [comment]
I also can't seem to replicate your bySound issue are you sending requests too fast to TikTok?

**Comment by davidteather** [comment]
I'm updating the bySound endpoint and the byHashtag method although I'm not sure it will fix your issue.

**Comment by ziyueluo** [comment]
Right now, I tried with your latest version. BySound is working fine. 
But for byHashtag, I still get repeated results for some hashtags. 
When I run:
hashtags=api.byHashtag('#HeinzHalloween',count=2000)
It return 2000 results but there are only 29 unique objects.

**Comment by davidteather** [comment]
The hashtag string shouldn’t contain # you’re searching for ##HeinzHalloween there’s probably only 29 videos there

**Comment by ziyueluo** [comment]
I tried with:
hashtags=api.byHashtag('HeinzHalloween',count=2000)
Still the same result

**Comment by davidteather** [comment]
```
from TikTokApi import TikTokApi
api = TikTokApi()

def ensure_unique(arr):
  tmp = []
  for t in arr:
    if t['id'] not in arr:
      tmp.append(t['id'])
  return tmp

tiktoks=api.byHashtag('HeinzHalloween',count=2000)
print(len(ensure_unique(tiktoks)))
```

I'm personally getting 2,000 unique results.

**Comment by Lancelot-d** [comment]
Hi, in fact with the previous code you get 2000 unique results but if you restart the function immediately afterwards it will find the same 2000 results again. (of course the hashtag has more than 2000). how to explain this? is it resolvable?
