### ISSUE TITLE
[FEATURE_REQUEST] - Improved Documentation

### ISSUE THREAD

**Issue by davidteather** [davidteather/TikTok-Api#316]
I've changed a lot with this API in the past few weeks, however, I don't have much time to update the documentation right now.

If anyone is willing to update the documentation to reflect the actual code better that would be great even if it's not all of it. I'll probably be able to get around to this in a month or two.

**Comment by SwedishBotMafia** [comment]
Tell me what you need completed and I'll start helping.

**Comment by SwedishBotMafia** [comment]
I've been digging for your code for a few months now and I'm really enjoying it. Great stuff.

**Comment by davidteather** [comment]
I've improved the documentation 😎
