### ISSUE TITLE
[BUG] - Retrieve Tiktok on specific date or range

### ISSUE THREAD

**Issue by Goldrest** [davidteather/TikTok-Api#318]
**Describe the bug**

I have tried to retrieve tiktok between a time range (one month) when using minCursor and maxCursor

**The buggy code**

```
tiktoks = api.trending(count = 2, minCursor=1580511600, maxCursor=1583017199)
for tiktok in tiktoks:
    print(tiktok["createTime"])
```

**Expected behavior**

**1580511600** corresponds to '01-1-2020 00:00:00' timestamp
**1583017199** corresponds to '31-1-2020 23:59:59' timestamp

Documentation says : 
```
:param minCursor: time stamp for the earliest TikTok to retrieve
:param maxCursor: time stamp for the latest TikTok to retrieve
```
So i expected to have Tiktok's ['createtime'] between them.
Unfortunatly trending, byHashtag or others methodes seems to not use minCursor/maxCursor anymore.
I see in others issues that yu've mentionned that point but i'm not sure.

**Error Trace**

print from the code below
```
1597097470
1603220442
```

**Desktop (please complete the following information):**
 - OS: [ Windows 10]
 - TikTokApi Version [3.6.0] - if out of date upgrade before posting an issue

**Additional context**

I think that the documentation is out of the date.
Do you know a way to retrieve video between a range of dates or a specific one ?

Thank you for you help !

**Comment by davidteather** [comment]
Yeah the documentation is out of date. Tiktok no longer supports the max and min cursor for every endpoint. If you look at the method headers for byHashtag and trending it’ll show offset as one of the parameters. 

The methods that support max and min cursor are also in the method header now. 

You’re unable to do both currently.

**Comment by Goldrest** [comment]
Thank you for your quick reply !

Yes i see that in the documentation, but what is the meaning of the **offset** parameter ?

And how can i can limit my retrieve range ? There are no feature/parameter/methods who can help me do that ?

**Comment by davidteather** [comment]
The offset parameter is the index you want to start retrieving tiktoks for. 

If a page has a size of 30 then giving an offset of 60 would return the 3rd page of videos 60-90

I don’t believe you’re able to bound retrieving tiktoks only between a specific time anymore

**Comment by Goldrest** [comment]
Again thank you for your reactivity !

It's more clear now.

Not even a start date for retrieve ? Such a shame, that can be really useful.
I've seen that Tiktok's ID is composed of the posting date (like presents here https://dfir.blog/tinkering-with-tiktok-timestamps/) but i dont know if it can be useful.

**Comment by davidteather** [comment]
TikTok won't index by IDs you could create a function to filter out TikToks that don't have a createTime value between the returned list though.
