### ISSUE TITLE
Getting error connecting to browsermob-proxy

### ISSUE THREAD

**Issue by muneeb331** [davidteather/TikTok-Api#32]
I am getting this error when running the API on CentOS 7.

[root@backups tiktok]# python3.6 test.py
New class reference, finding valid signature. This might take a minute.
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    api = TikTokapi("/root/tiktok/browsermob-proxy-2.1.4/bin/browsermob-proxy")
  File "/usr/local/lib/python3.6/site-packages/TikTokApi/tiktok.py", line 26, in __init__
    self.server.start()
  File "/usr/local/lib/python3.6/site-packages/browsermobproxy/server.py", line 127, in start
    raise ProxyServerError("Can't connect to Browsermob-Proxy")
browsermobproxy.exceptions.ProxyServerError: Can't connect to Browsermob-Proxy

**Comment by davidteather** [comment]
Instead of passing in an absolute root try to pass in a relative path to your project 

Ex
‘’’
api = TikTikApi(“browsermob-proxy-2.1.4/bin/browsermob-proxy”)
‘’’

**Comment by davidteather** [comment]
Closing due to no update
