### ISSUE TITLE
[BUG] - DownloadAddr from "byHashtag()" is invalid

### ISSUE THREAD

**Issue by JohnTYH** [davidteather/TikTok-Api#322]
# Read Below!!! If this doesn't fix your issue delete these two lines
**You may need to install chromedriver for your machine globally. Download it [here](https://sites.google.com/a/chromium.org/chromedriver/) and add it to your path.**

**Describe the bug**
Hi, I tried to combine the "byHashtag() and get_Video_By_Video() functions as shown in the code below. I realised that the download Addr given by the tiktok object from byHashtag will return a corrupted link. Thus the video downloaded will be corrupted as well.

**The buggy code**
```
from TikTokApi import TikTokApi
import random

# SEE https://github.com/davidteather/TikTok-Api/issues/311#issuecomment-721164493

api = TikTokApi()
count = 1

hashtag = api.byHashtag("covid", count=count)
print(hashtag[0]['video']['downloadAddr'])

trending = api.trending(1)
print(trending[0]['video']['downloadAddr'])
```
**Expected behavior**
The link that is printed by hashtag should be working as well.

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version 3.6.3

**Additional context**

**Comment by davidteather** [comment]
See [this](https://github.com/davidteather/TikTok-Api/issues/311#issuecomment-721164493)
