### ISSUE TITLE
Access to Douyin - Chinese TikTok

### ISSUE THREAD

**Issue by Kikiss18** [davidteather/TikTok-Api#323]
Hello,

Thanks for this TikTok Api. It's working pretty well,
Is it possible to have access to Chinese version of TikTok, Douyin? 
I tried by username with username "Nikejdi" (Nike Chinese account)... it's not working.

Thanks!

**Comment by davidteather** [comment]
Unfortunately not. If you're able to watch videos on Douyin on the web browser I may be able to create a fork of this project to support it. I would be looking for something like [this](https://www.tiktok.com/foryou) from what I can tell it seems like you must download the app.
