### ISSUE TITLE
[FEATURE_REQUEST] - Basic user statistic

### ISSUE THREAD

**Issue by selff** [davidteather/TikTok-Api#324]
Is it possible to get basic user statistics using this Tiktok-api ?
which can be seen on the user page view-source:https://www.tiktok.com/@someusername
{"followingCount":2369,"followerCount":68100000,"heartCount":0,"videoCount":1263,"diggCount":0,"heart":4200000000}

**Comment by davidteather** [comment]
You can use
```
api.getUser("therock")
```

the data is contained under the stats key
