### ISSUE TITLE
UserPosts are not working

### ISSUE THREAD

**Issue by muneeb331** [davidteather/TikTok-Api#33]
Trying the following code from the example.

from TikTokApi import TikTokapi

# Starts The Api Class
api = TikTokapi("C:\\Tfs\\Projects\\TimeBucksCode\\tiktok\\browsermob-proxy-2.1.4-bin\\browsermob-proxy-2.1.4\\bin\\browsermob-proxy.bat")

# The Number of trending TikToks you want to be displayed
results = 10

userPosts = api.userPosts("khaleelabdullah_")

for tiktok in userPosts:
    print(tiktok)

#print(len(trending))

api.quit_browser()

User posts are not loading, probably they have changed something

![image](https://user-images.githubusercontent.com/58471630/70769498-b6fb8380-1da4-11ea-8e04-2f5eed399659.png)

**Comment by davidteather** [comment]
I'll have a look at it later. 

My guess is that they are now detecting selenium better than before and blocking content.

**Comment by davidteather** [comment]
@muneeb331 

Just released a new update to the api along with fixing the other methods this one is fixed and will allow for easier access.
