### ISSUE TITLE
[BUG] - Duplicate data when running get.Trending

### ISSUE THREAD

**Issue by farout69** [davidteather/TikTok-Api#333]
When running getTrending.py from the example file, i get duplicate data in my output. I changed the count to 200 to get a larger dataset and many ID's are being listed twice. Would this be an issue with the API or something on my end?

I have included the code used as well as an excel file which has the output data and a pivot showing the duplicates.

```
from TikTokApi import TikTokApi

# Starts TikTokApi
api = TikTokApi.get_instance()

# The Number of trending TikToks you want to be displayed
results = 200

# Returns a list of dictionaries of the trending object
trending = api.trending(results)

# Loops over every tiktok
for tiktok in trending:
    # Prints the id of the tiktok
    print(tiktok["id"])

print(len(trending))
```

[getTrending_Output.xlsx](https://github.com/davidteather/TikTok-Api/files/5515738/getTrending_Output.xlsx)

**Comment by davidteather** [comment]
Looks like it's a cookie issue with TikTok you can use the following code in the meantime. I'll be releasing a package update soon
```
from TikTokApi import TikTokApi
import random
api = TikTokApi.get_instance()
did = random.randint(1111111,9999999)

tiktoks = api.trending(count=300, custom_did=str(did)
```
