### ISSUE TITLE
Error: Can only run one Playwright at a time.

### ISSUE THREAD

**Issue by the-data-mogul** [davidteather/TikTok-Api#336]
Hi, 

I tried to find this in the open and closed issues on GitHub but am not able to. I am seeing this error when I try to use the api in Jupyter Notebook. I tried to update the chromedriver as well. No luck.

**Comment by davidteather** [comment]
Use
```
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()
```

**Comment by the-data-mogul** [comment]
import nest_asyncio
nest_asyncio.apply()

from playwright import sync_playwright
playwright = sync_playwright().start()

Thank you for the response. Are the above lines mandatory as well?

**Comment by davidteather** [comment]
Can you provide your code?

You may need the nest_asyncio, but I'm not certain as I haven't used Jupyter

**Comment by the-data-mogul** [comment]
I am afraid there might be an issue in my python setup, I will get back to you soon. Thank you for your prompt responses!
