### ISSUE TITLE
[INSTALLATION] -  Failed building wheel for greenlet

### ISSUE THREAD

**Issue by ek8terina** [davidteather/TikTok-Api#337]
**Describe the error**
Super new to coding in python, most of my experience is in R so I might just be installing incorrectly, but I keep getting an error building wheel for greenlet after running pip install TikTokApi in the terminal.

**The buggy code**
pip install TikTokApi

Please insert the code that is throwing errors or is giving you weird unexpected results.

**Error Trace (if any)**

Put the error trace below if there's any error thrown.

```
 Building wheel for greenlet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
```

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - TikTokApi Version [e.g. 3.3.1] - if out of date upgrade before posting an issue

**Additional context**

Put what you have already tried. Your problem is probably in the closed issues tab already.
I tried creating different environments but everything seems to have errors installing greenlet. Searched for similar solved issues but couldn't find anything, pretty sure it's something I'm messing up somewhere, but I'm a complete python noob and can't seem to figure it out. Would appreciate any help!

**Comment by ek8terina** [comment]
Needed to install Xcode developer tools

**Comment by davidteather** [comment]
I'll add that in the readme thanks!

**Comment by mikegrep** [comment]
ERROR: Failed building wheel for greenlet
Same issue python3.6.9 on Ubuntu 18.04 iv virtualenv I try and out virtual env same result.
