### ISSUE TITLE
[BUG] - getUser() stopped working

### ISSUE THREAD

**Issue by mjaensch** [davidteather/TikTok-Api#338]
**Describe the bug**

Today the getUser() function stopped working for me. The request returns an empty string and therefore TikTokApi throws an exception.

**The buggy code**
TikTokApi 3.7.5:
```
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()
user = api.getUser('charlidamelio')
```

TikTokApi 3.6:
```
from TikTokApi import TikTokApi
api = TikTokApi()
user = api.getUser('charlidamelio')
```

**Error Trace (if any)**
```
Invalid Response
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 162, in getData
    return r.json()
  File "/home/user/.local/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/tiktok/tiktokhelper.py", line 33, in addUser
    data = api.getUser(uniqueId)
  File "/home/user/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 1010, in getUser
    return self.getData(url=api_url, **kwargs)["userInfo"]
  File "/home/user/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 170, in getData
    raise Exception("Invalid Response")
Exception: Invalid Response
```

**Desktop (please complete the following information):**
 - OS: Windows 10 & Ubuntu 18.04
 - TikTokApi Version: 3.6 & 3.75

**Comment by davidteather** [comment]
Affects methods associated with getting an object
* getTikTokById
* getMusicObject
* getHashtagObject
* getUser

All endpoints that end in /detail might be getting deprecated soon.

**Comment by davidteather** [comment]
Hi!
I can't directly replicate your issue do you mind running the following code so I know what has to be updated? It's probably a region deprecation thing with their servers.
```
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()

try:
  api.getTikTokById('6879200674786184449')
except:
  print("TikTokById failed")

try:
  api.getMusicObject("6850266942448683782")
except:
  print('Get music failed')

try:
  api.getHashtagObject('funny')
except:
  print("Get hashtag failed")
```

**Comment by mjaensch** [comment]
I tried your test code and all three api calls fail.
I also tried the code after installing the version from your latest fix 8f6765623c5e1192aa7b36c6fac4d1cff06cd8eb, but it still fails.

**Comment by cesarblancg** [comment]
I tried your test code from Spain using versions 3.6 and the latest. It works.

**Comment by davidteather** [comment]
@cesarblancg Does it still work for you? The endpoints stopped working for me now.

The problem is that the getUser endpoint requires a secUid now, which is problematic because I used that endpoint to get the secUid of a profile. I've got a few guesses and I'll label this as help wanted as it might be a more involved issue than I previously thought. 

All the secUids that I can find have "MS4wLjABAAAA" in the string and I'm assuming that may correspond to "@" in a hashing algorithm they use. It would be much appreciated if other people want to help me figure out how TikTok is calculating this secUid value because from what I can tell it's not being retrieved by an API endpoint so the method has to be contained somewhere in the code on the frontend, the only problem is it's heavily obfuscated.

**Comment by cesarblancg** [comment]
> @cesarblancg Does it still work for you? The endpoints stopped working for me now.
> 
> The problem is that the getUser endpoint requires a secUid now, which is problematic because I used that endpoint to get the secUid of a profile. I've got a few guesses and I'll label this as help wanted as it might be a more involved issue than I previously thought.
> 
> All the secUids that I can find have "MS4wLjABAAAA" in the string and I'm assuming that may correspond to "@" in a hashing algorithm they use. It would be much appreciated if other people want to help me figure out how TikTok is calculating this secUid value because from what I can tell it's not being retrieved by an API endpoint so the method has to be contained somewhere in the code on the frontend, the only problem is it's heavily obfuscated.

For my works fine now, but maybe they're deploying slowly across all their regions. The secUids are cookies?

**Comment by davidteather** [comment]
They're probably deploying region-specific then. The secUid is a specific UID for a given user on the platform. My guess is they use some hashing algorithm to convert the username into the secUid in [this](https://sf16-scmcdn-va.ibytedtos.com/goofy/tiktok/web/node/_next/static/1.0.3.279/pages/share/user.js) script which handles user functions.

**Comment by davidteather** [comment]
Seems like they reverted the change they made earlier today. I've updated the endpoint to use the newer ones as the getUser method doesn't seem to require a secUid for the time being.
