### ISSUE TITLE
[BUG] - ERROR:root:Converting response to JSON failed response is below (probably empty)

### ISSUE THREAD

**Issue by xdNiBoR** [davidteather/TikTok-Api#344]
So yesterday my code worked fine, saved it and got to it today again. None of my programs using tiktokAPI are working. I am getting the same bug on all of them. 

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()

TikTokUserName = "danielhow01"
results = 500


UserLikedVideos = api.userLikedbyUsername(username=TikTokUserName, count=results)


for tiktok in UserLikedVideos:  
    Like_File = open("linksToLikedVideos.json", "a")
    idOfLikedVideo = tiktok['id']
    usernameOfLikedVideo = tiktok['author']['uniqueId']
    Like_File.write("\nhttps://www.tiktok.com/@" + usernameOfLikedVideo + "/video/" + idOfLikedVideo)
    Like_File.close()


print(idOfLikedVideo)
print(usernameOfLikedVideo)

```

**Expected behavior**

Well, the ID and username of 500 liked videos from a user are writen to a file. 
I added "https://www.tiktok.com/@" etc to make it a link. 

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
ERROR:root:Expecting value: line 1 column 1 (char 0)
ERROR:root:Converting response to JSON failed response is below (probably empty)
Traceback (most recent call last):
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 162, in getData
    return r.json()
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Robin/Desktop/PyCharmProjects/TikTokV2/Get TikTok by URL.py", line 7, in <module>
    test = api.getTikTokById(id = Id, language='en', proxy=None)        # test is een dict
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 894, in getTikTokById
    return self.getData(url=api_url, **kwargs)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 169, in getData
    raise Exception("Invalid Response")
Exception: Invalid Response

```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version 3.7.7

**Additional context**
Downloaded it yesterday, excuse me for my bad english and code. I am not a pro. 

Is this some sort of TikTok banned me for accessing there info to much to quick?

**Comment by Justylol** [comment]
All TikTok requests returns 200 and 'illegal request...' in content for now. So app cant decode such content to json and return error

**Comment by xdNiBoR** [comment]
> All TikTok requests returns 200 and 'illegal request...' in content for now. So app cant decode such content to json and return error

Can you explain this a little more? Why could I do it yesterday? I dont get it. @Justylol

**Comment by xdNiBoR** [comment]
I also ran your demo program again
`from TikTokApi import TikTokApi
api = TikTokApi.get_instance()

results = 10

trending = api.trending(count=results)

for tiktok in trending:
    # Prints the id of the tiktok
    print(tiktok['id'])

print(len(trending))`

And this gives the exact same error

**Comment by xdNiBoR** [comment]
Tried reinstalling the module aswell

**Comment by Justylol** [comment]
I think tiktok just added new protection and all requests are now returning error, thats all.

**Comment by xdNiBoR** [comment]
> I think tiktok just added new protection and all requests are now returning error, thats all. It starts 3-4 hours ago.

So just wait till @davidteather has fixid it? Its not on my side?

**Comment by Justylol** [comment]
Yes, i think so

**Comment by xdNiBoR** [comment]
Oke lets hope @davidteather sees this then

**Comment by hoylemd** [comment]
Also seeing this.  Here's hoping @davidteather can get around it.  If you need help, I can make some time for it today!

**Comment by xdNiBoR** [comment]
> Also seeing this. Here's hoping @davidteather can get around it. If you need help, I can make some time for it today!

Hey, can you add functionality to? I really want a feature to see who is following an account. I could sponsor it.
@hoylemd

**Comment by hoylemd** [comment]
@xdNiBoR maybe, but I think we should focus on getting the main api working first.

**Comment by xdNiBoR** [comment]
@hoylemd yes ofcourse, that would be great ;). Sad I cant help out a lot... still learning a lot

**Comment by davidteather** [comment]
#342 Should fix this on residential networks, but I'm having trouble getting it to pass tests on GitHub servers

**Comment by iSTARsa** [comment]
its not responding JsonResp so the problem i think in the m.tiktok api {m.tiktok.com/api/}
not in the codes

**Comment by davidteather** [comment]
Hey, releasing a new update that will temporarily fix this. See [this](https://github.com/davidteather/TikTok-Api/pull/342#issuecomment-727009300) comment for more information on how to create your own verifyFp parameter if it stops working.

Consolidating this issue to #347
