### ISSUE TITLE
[BUG] - 'set_async' import error

### ISSUE THREAD

**Issue by JulianRubinstein** [davidteather/TikTok-Api#349]
Hey everyone,

I was using the 3.6.0 version for a while and everything was working great untill a few days ago I started getting this response back when running the app:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 471, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 425, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

so I decided to upgrade to version 3.7.8 and now whenever I run the code I get the following error:

```
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from TikTokApi.browser import set_async
ImportError: cannot import name 'set_async' from 'TikTokApi.browser' (/home/julian/.local/lib/python3.7/site-packages/TikTokApi/browser.py)

```
I've tried both on Windows and Ubuntu and using python 3.7 and 3.8. All seem to give the same error 'set_async' error. Any ideas?

 - OS: [Ubuntu 18.04]
 - TikTokApi Version [3.7.8]

Thanks for any help!

**Comment by Xodarap** [comment]
I had a similar issue and fixed it by doing this:
```
    loop = asyncio.ProactorEventLoop()
    asyncio.set_event_loop(loop)
    # use api
    TikTokApi.__instance = None
```
I think this messes with the singleton aspect of the API though; see the last line. It would be nice if there was a better way to do this.

**Comment by JulianRubinstein** [comment]
It says asyncio has not attribute "ProactorEventLoop". Are you sure thats correct? Is this the regular asyncio python package?

**Comment by Xodarap** [comment]
Yes, it's part of the regular package but which things are available depends on your platform. See https://docs.python.org/3.6/library/asyncio-eventloops.html

Here's the code which works for me:

```
def get_user(username, count):
    if sys.platform == 'win32':
        loop = asyncio.ProactorEventLoop()
        asyncio.set_event_loop(loop)
    api = TikTokApi.get_instance()
    return api.byUsername(username, count)

**Comment by davidteather** [comment]
If you want I've started maintaining a pyppeteer fork [here](https://github.com/TikTokApi-Pyppeteer/TikTok-Api-Pyppeteer)
