### ISSUE TITLE
[BUG] - User API updated

### ISSUE THREAD

**Issue by Xodarap** [davidteather/TikTok-Api#350]
```
from TikTokApi import TikTokApi
api = TikTokApi()
api.byHashtag('ben', custom_verifyFp="...") # works
api.byUsername('ben', custom_verifyFp="...") # fails
```

I noticed that on the website they are using numeric IDs instead of the user string. I haven't figured out if that's the root cause of this.

**Comment by davidteather** [comment]
Are you getting any errors thrown by the code?

My byUsername seems to be working fine on the latest version of the package, maybe they're rolling out changes again?

**Comment by Xodarap** [comment]
Yeah the errors are intermittent. I'm still trying to figure out what's going on here.

The error which gets thrown is here, because res does not have a "hasMore":
```
if not res["hasMore"] and not first:

**Comment by davidteather** [comment]
Ah yeah I was getting that error when a captcha validation was being prompted. You probably have to slow your requests made. You might be able to get around that by using a list of different verifyFp?

**Comment by Xodarap** [comment]
It seems like I also need a custom_did? Not sure why.

**Comment by Xodarap** [comment]
I've confirmed that the following line has both worked and not worked. It's able to get the secUid correctly, so I don't think it's an issue with it expecting a captcha. 
`api.getUserObject('therock', custom_verifyFp='verify_khgy7u5g_41BRrq9U_AjGW_49J3_8Y0m_Ubbo8FpbweS7', did = '559798762', count=30)`

I'm guessing there's some new requirement rolling out and depending on which server you get it may or may not work?

**Comment by Xodarap** [comment]
I think there's something wrong with the signing process:

1. Start with a URL known to work: `https://m.tiktok.com/api/item_list/?aid=1988&app_name=tiktok_web&device_platform=web&referer=&user_agent=Mozilla%2F5.0+(Windows+NT+10.0%3B+Win64%3B+x64)+AppleWebKit%2F537.36+(KHTML,+like+Gecko)+Chrome%2F86.0.4240.198+Safari%2F537.36&cookie_enabled=true&screen_width=3440&screen_height=1440&browser_language=en-US&browser_platform=Win32&browser_name=Mozilla&browser_version=5.0+(Windows+NT+10.0%3B+Win64%3B+x64)+AppleWebKit%2F537.36+(KHTML,+like+Gecko)+Chrome%2F86.0.4240.198+Safari%2F537.36&browser_online=true&ac=4g&timezone_name=America%2FLos_Angeles&page_referer=https:%2F%2Fwww.tiktok.com%2F@benthamite&priority_region=&verifyFp=verify_khgyofu6_YP8cEg4o_QpRA_4lbj_89kv_LOaIzzExQcAs&appId=1233&region=US&appType=m&isAndroid=false&isMobile=false&isIOS=false&OS=windows&did=6894770323305154053&count=30&id=6745191554350760966&secUid=MS4wLjABAAAAM3R2BtjzVT-uAtstkl2iugMzC6AtnpkojJbjiOdDDrdsTiTR75-8lyWJCY5VvDrZ&maxCursor=0&minCursor=0&sourceType=8&language=en`
2. Generate signature for it with Python. I got `_02B4Z6wo00f01TGyUMwAAIBBO0PooLDrPCUxo1RAABPF99`
3. Generate signature for it by using dev tools in the browser on TikTok.com. I got `_02B4Z6wo00d014I2IVwAAICAahF4-9PqRmOCFyXAAL8u91`
4. Notice that the second URL works if you append the signature but the first one doesn't.

I figured we could just do `page.goto('https://www.tiktok.com/')` before evaluating the signature but that doesn't seem to work. I wonder if `byted_acrawler` is now looking directly at your verifyFp or something?

**Comment by davidteather** [comment]
Signing is based somewhat on user agent and the user agent used in python is not the same as a chrome web driver. 

If you modify the code to log the result from byHashtag to print the res variable before res[‘itemList’] you should see a json response that doesn’t have itemList in it because it wants further captcha validation

**Comment by Xodarap** [comment]
How do you know that it wants further captcha validation? When I browse TikTok on the browser using the same verifyFp it doesn't ask me for a captcha.

**Comment by Xodarap** [comment]
Oh, good call: setting the user agent makes the signatures work, at least for those specific URLs. I will keep digging into whether there's a way to  sign generated URLs as well

**Comment by ddupreez2** [comment]
Hey this is an issue for me as well. Getting an error at: if not res["hasMore"] and not first

Possible that there is a fix to this?

**Comment by davidteather** [comment]
Update the API to the latest version. There's better error handling now which should give you a better idea of how to proceed. Most likely it's a custom_verifyFp issue
