### ISSUE TITLE
[BUG] - Memory leak - system crashes

### ISSUE THREAD

**Issue by pibvbp** [davidteather/TikTok-Api#352]
The script runs well, but fills the RAM memory after a couple of minutes and crashes the system.
Didn't happen before the update to the last version.

CODE:
```
def get_tiktoks(api,tickers):
    for t in tickers:
            try:
                tmp = api.byHashtag(t, count=9999999999, language='en') #can change the number of tiktoks
                tdf = pd.DataFrame.from_dict(tmp)
                tdf = tdf[~tdf.duplicated(subset='id', keep='first')] #delete duplicates
                tdf = tdf.reset_index(drop=True)
                
                tmpdf = pd.read_csv(fileName, index_col=0)
                tmpdf = tmpdf.append({'ticker': t, 'count': len(tdf.index)}, ignore_index=True) #count and append
                tmpdf.to_csv(fileName)
            except:
                print('Error with ticker', t)
```
Additional info:
I am able to run the script only using shell (ipython). if I try using a Jupiter notebook I get an error saying:
"Can only run one Playwright at a time".

**Comment by davidteather** [comment]
Memory leak might be caused by playwright. if you want to use the following I've started maintaining a pyppeteer fork [here](https://github.com/TikTokApi-Pyppeteer/TikTok-Api-Pyppeteer)
