### ISSUE TITLE
[BUG] - Multithread

### ISSUE THREAD

**Issue by cesarblancg** [davidteather/TikTok-Api#353]
**Describe the bug**

I was using the 3.6 version, and when I update it to the last one, my code crashed because now this API doesn't allow multithreaded.
From now on this API won't allow it?
**Desktop (please complete the following information):**
 - OS: Windows 10 and debian 10
 - TikTokApi Version 3.7.8

**Comment by davidteather** [comment]
Playwright is a little bit strange with threads. You can either use an external signer which you can look at in the examples folder. or I've started maintaining a pyppeteer fork [here](https://github.com/TikTokApi-Pyppeteer/TikTok-Api-Pyppeteer)
