### ISSUE TITLE
Is it possible to provide an API for uploading?

### ISSUE THREAD

**Issue by konglai** [davidteather/TikTok-Api#355]
I checked all the APIs, and it seems that there is no upload video function..
Is it possible to provide an API for uploading?

**Comment by lionneclement** [comment]
For uploading  use get_Video_By_DownloadUR
`video = self.api.get_Video_By_DownloadURL(tiktok['video']['downloadAddr'])
            with open("video.mp4", "wb") as out:
                out.write(video)`

**Comment by tnusser** [comment]
I don't see how this uploads a video - In my understanding this downloads the video and writes that to a file. 
Is there a way to actually create a TikTok by uploading a video file using the API?

**Comment by cupiditys** [comment]
> I don't see how this uploads a video - In my understanding this downloads the video and writes that to a file. Is there a way to actually create a TikTok by uploading a video file using the API?

theres no built in way to this api but it is possible manually, kinda complicated

**Comment by davidteather** [comment]
Not currently
