### ISSUE TITLE
[FEATURE_REQUEST] - Access to live chat

### ISSUE THREAD

**Issue by merlinfuchs** [davidteather/TikTok-Api#356]
**Is your feature request related to a problem? Please describe.**
There is currently no way to access the chat of a tiktok livestream and subscribe to chat messages.

**Describe the solution you'd like**
Make it possible to access the chat of a tiktok livestream including access to new messages.

**Describe alternatives you've considered**

**Additional context**

**Comment by zerodytrash** [comment]
Here is a Node.js module that can access the live chat: https://github.com/zerodytrash/TikTok-Livestream-Chat-Connector
Maybe someone can translate it to python.

**Comment by davidteather** [comment]
Closing
Use @zerodytrash 's library in js
Or use @isaackogan library in python [TikTokLive](https://github.com/isaackogan/TikTokLive) and maybe checkout my [video](https://www.youtube.com/watch?v=307ijmA3_lc) on how to use it
