### ISSUE TITLE
[BUG] - if not res["hasMore"] and not first: KeyError: 'hasMore'

### ISSUE THREAD

**Issue by benstanford** [davidteather/TikTok-Api#357]
**Describe the bug**

Api.Trending doesn't work (returns error)

**The buggy code**

```
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()
trending = api.trending(count=1)
for i in trending:
    print(i)
```

**Expected behavior**

Program was supposed to scrape 1 TikTok from the trending page and display the TikTok's info.

**Error Trace (if any)**

```
Traceback (most recent call last):
  File "C:\Users\REDACTED\Desktop\tiktok.py", line 34, in <module>
    trending = api.trending(count=1)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokApi\tiktok.py", line 261, in trending
    if not res["hasMore"] and not first:
KeyError: 'hasMore'
```

**Desktop (please complete the following information):**
 OS: Windows 10
 TikTokApi Version: 3.7.9

**Additional context**

This worked fine yesterday, I didn't touch the code at all (only upgraded to Python 3.9).

**Comment by davidteather** [comment]
You're probably making too many requests or on a suspicious IP address. You could try to go to TikTok.com and try to watch some TikToks and see if a manual captcha solve might fix it. Or, you may want to consider using a proxy. luminati.io seems to work nicely for my rapidapi service

**Comment by benstanford** [comment]
> You're probably making too many requests or on a suspicious IP address. You could try to go to TikTok.com and try to watch some TikToks and see if a manual captcha solve might fix it. Or, you may want to consider using a proxy. luminati.io seems to work nicely for my rapidapi service

Tried 2 different VPNs & mobile data, problem still persists.

**Comment by thanhnguyen1121** [comment]
I face the same issue

**Comment by benstanford** [comment]
Has anyone found a fix?

**Comment by benstanford** [comment]
Now getting a new error:

`raise Exception("Invalid Response")
Exception: Invalid Response`

**Comment by davidteather** [comment]
Update the API to the latest version. There's better error handling now which should give you a better idea of how to proceed. Most likely it's a custom_verifyFp issue

**Comment by benstanford** [comment]
> Update the API to the latest version. There's better error handling now which should give you a better idea of how to proceed. Most likely it's a custom_verifyFp issue

Is your custom_verifyFp "MONITOR_WEB_ID" or "s_v_web_id"? Also, what is a did? Where can I get it?

**Comment by davidteather** [comment]
It is the s_v_web_id a did is just a randomly generated numeric string.
```
did = random.random(111111111111,99999999999)
```
