### ISSUE TITLE
Exception: Invalid Response

### ISSUE THREAD

**Issue by septfish** [davidteather/TikTok-Api#358]
It worked well before, but now it reports this exception Exception: Invalid Response. Is my machine blocked?

**Comment by rorysmith85** [comment]
I am having the same issue? Does anyone know what is happening?

**Comment by tintinmovie** [comment]
@rorysmith85 @septfish 
I was able to fix this using the latest release: 3.7.9

https://github.com/davidteather/TikTok-Api/releases/tag/V3.7.9

**Comment by dylancaponi** [comment]
3.7.9 Causes
```
    raise not_installed_error(f'"{self.name}" browser was not found.')
Exception:
================================================================================
"webkit" browser was not found.
Please complete Playwright installation via running

    "python -m playwright install"

================================================================================
```

for me.

**Comment by tintinmovie** [comment]
@dylancaponi  Run in your console - `python -m playwright install`

**Comment by dylancaponi** [comment]
@tintinmovie After running that command and trying again I get:

**Comment by tintinmovie** [comment]
@dylancaponi Could you post the full console output?

**Comment by tintinmovie** [comment]
I found a quick fix (don't know how permanent)

https://github.com/davidteather/TikTok-Api/issues/362#issuecomment-730036497

**Comment by dylancaponi** [comment]
This fix does not seem to work for me. I tried just that line and then removing every mention of the cookie.

**Comment by tintinmovie** [comment]
Haven't tried this yet, but add the mentions of the cookie back in.

Open up https://www.tiktok.com/ and using Chrome Developers Tool, look under the Application tab. Go to cookies.

Look for the cookie `s_v_web_id` which should be set to something like `verify_XXXXXXXXXXXXXXXXXXXXXX` 

Copy that cookie and replace the existing `verify_XXX` cookie in `"Cookie": "s_v_web_id=" + kwargs.get("custom_verifyFp", "verify_khgp4f49_V12d4mRX_MdCO_4Wzt_Ar0k_z4RCQC9pUDpX"),`

**Comment by davidteather** [comment]
You should just be able to pass the verify_Fp parameter to all method calls of the TikTokApi it should have the same effect

**Comment by davidteather** [comment]
Update the API to the latest version. There's better error handling now which should give you a better idea of how to proceed. Most likely it's a custom_verifyFp issue
