### ISSUE TITLE
Exception: Invalid Response

### ISSUE THREAD

**Issue by septfish** [davidteather/TikTok-Api#362]
from TikTokApi import TikTokApi
api = TikTokApi()
userPosts = api.userPosts(
        "6745191554350760966",
        "MS4wLjABAAAAM3R2BtjzVT-uAtstkl2iugMzC6AtnpkojJbjiOdDDrdsTiTR75-8lyWJCY5VvDrZ",
        30,
    )
 print(userPosts)

The above is my code, and an error is reported during operation:
Converting response to JSON failed response is below (probably empty)
Exception: Invalid Response,
Can anyone help me, how to solve this problem, I can’t solve this problem even if I switch proxy

**Comment by tintinmovie** [comment]
I was able to fix this using the latest release: 3.7.9


https://github.com/davidteather/TikTok-Api/releases/tag/V3.7.9

**Comment by hoai97nam** [comment]
many thanks @tintinmovie 
I was confused, but you helped me realise my problem <3

**Comment by septfish** [comment]
> I was able to fix this using the latest release: 3.7.9
> 
> https://github.com/davidteather/TikTok-Api/releases/tag/V3.7.9

I updated the 3.7.9 version pip install TikTokApi --upgrade, I have a new problem when using the getUser function

j_raw = t.split('<script id="__NEXT_DATA__" type="application/json" crossorigin="anonymous">')[1].split("</script>")[0]
IndexError: list index out of range

Error when using userPosts
if not res["hasMore"] and not first:
KeyError:'hasMore'

Printed res returns the result:
{'code': '10000','from':'','type':'verify','version':'','region':'va','subtype':'slide','detail' : 'CkzP * X-z179ed8 * q61zsKs6Dg9TSowY26eI1hd-ToJDqkZiv9M3tLzkN3KbTMQYgPR7LUdM16hY7breE086cTneQrsQI1MUoIU * s5DihRmboZ3pRujEI * hr-FNfSq7wcOw9zwjuDB3D4XDbbheDSPa93ZJ0tZySrS6gW8QDcgkH6BRVumDSqQovxHsnmVqN-6WCanR * tnAmFj8PNjnFz * cVOnxeQsjuMAhF7rz97oRqq7XuSwR6KagQFLnDgF7XJOsRgiOMlzZmzjyt7WyZyDISuHgfPv537hDHkFB6S', 'verify_event': '', 'fp': 'verify_khgp4f49_V12d4mRX_MdCO_4Wzt_Ar0k_z4RCQC9pUDpX', 'scene': ''}

**Comment by thanatos11** [comment]
> > I was able to fix this using the latest release: 3.7.9
> > https://github.com/davidteather/TikTok-Api/releases/tag/V3.7.9
> 
> I updated the 3.7.9 version pip install TikTokApi --upgrade, I have a new problem when using the getUser function
> 
> j_raw = t.split('<script id="__NEXT_DATA__" type="application/json" crossorigin="anonymous">')[1].split("</script>")[0]
> IndexError: list index out of range
> 
> Error when using userPosts
> if not res["hasMore"] and not first:
> KeyError:'hasMore'
> 
> Printed res returns the result:
> {'code': '10000','from':'','type':'verify','version':'','region':'va','subtype':'slide','detail' : 'CkzP * X-z179ed8 * q61zsKs6Dg9TSowY26eI1hd-ToJDqkZiv9M3tLzkN3KbTMQYgPR7LUdM16hY7breE086cTneQrsQI1MUoIU * s5DihRmboZ3pRujEI * hr-FNfSq7wcOw9zwjuDB3D4XDbbheDSPa93ZJ0tZySrS6gW8QDcgkH6BRVumDSqQovxHsnmVqN-6WCanR * tnAmFj8PNjnFz * cVOnxeQsjuMAhF7rz97oRqq7XuSwR6KagQFLnDgF7XJOsRgiOMlzZmzjyt7WyZyDISuHgfPv537hDHkFB6S', 'verify_event': '', 'fp': 'verify_khgp4f49_V12d4mRX_MdCO_4Wzt_Ar0k_z4RCQC9pUDpX', 'scene': ''}

i have the same issue

**Comment by Meetmetha** [comment]
> > I was able to fix this using the latest release: 3.7.9
> > https://github.com/davidteather/TikTok-Api/releases/tag/V3.7.9
> 
> I updated the 3.7.9 version pip install TikTokApi --upgrade, I have a new problem when using the getUser function
> 
> j_raw = t.split('<script id="__NEXT_DATA__" type="application/json" crossorigin="anonymous">')[1].split("</script>")[0]
> IndexError: list index out of range
> 
> Error when using userPosts
> if not res["hasMore"] and not first:
> KeyError:'hasMore'
> 
> Printed res returns the result:
> {'code': '10000','from':'','type':'verify','version':'','region':'va','subtype':'slide','detail' : 'CkzP * X-z179ed8 * q61zsKs6Dg9TSowY26eI1hd-ToJDqkZiv9M3tLzkN3KbTMQYgPR7LUdM16hY7breE086cTneQrsQI1MUoIU * s5DihRmboZ3pRujEI * hr-FNfSq7wcOw9zwjuDB3D4XDbbheDSPa93ZJ0tZySrS6gW8QDcgkH6BRVumDSqQovxHsnmVqN-6WCanR * tnAmFj8PNjnFz * cVOnxeQsjuMAhF7rz97oRqq7XuSwR6KagQFLnDgF7XJOsRgiOMlzZmzjyt7WyZyDISuHgfPv537hDHkFB6S', 'verify_event': '', 'fp': 'verify_khgp4f49_V12d4mRX_MdCO_4Wzt_Ar0k_z4RCQC9pUDpX', 'scene': ''}

Same error for me after upgrading

**Comment by tintinmovie** [comment]
Don't know if this is a permanent fix.

Go to tiktok.py, and at the getUser() function - line 1002. 
Removing `"Cookie": "s_v_web_id=" + kwargs.get("custom_verifyFp", "verify_khgp4f49_V12d4mRX_MdCO_4Wzt_Ar0k_z4RCQC9pUDpX")`
from the requests.get seems to fix it

**Comment by davidteather** [comment]
Update the API to the latest version. There's better error handling now which should give you a better idea of how to proceed. Most likely it's a custom_verifyFp issue

**Comment by davidteather** [comment]
stale
