### ISSUE TITLE
[BUG] - Error in byHashtag seach

### ISSUE THREAD

**Issue by pibvbp** [davidteather/TikTok-Api#366]
**Describe the bug**

When I try to make a search by hashtag (using the Pyppeteer fork) I get an error as shown error.

```
from TikTokApi import TikTokApi
from TikTokApi.browser import set_async
set_async()

api = TikTokApi()
tmp = api.byHashtag('test', count=30, language='en') #can change the number of tiktoks
```

ERROR: 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-fef4fdbe9722> in <module>
      1 api = TikTokApi()
----> 2 tmp = api.byHashtag('test', count=30, language='en')
      3 tmp

c:\miniconda3\envs\botenv\lib\site-packages\TikTokApi\tiktok.py in byHashtag(self, hashtag, count, offset, **kwargs)
    735             res = self.getData(b, **kwargs)
    736 
--> 737             for t in res["itemList"]:
    738                 response.append(t)
    739 

KeyError: 'itemList'
```

**Comment by sipka** [comment]
Same issue here, and I am not running a fork but just vanilla API, the latest version. For example, searching by sound works fine, so it seems to be localised.

**Comment by wying8349** [comment]
I also have the same issue. How did you guys solve this problem?

**Comment by pibvbp** [comment]
haven't solved it yet - waiting for a good idea

**Comment by wying8349** [comment]
> haven't solved it yet - waiting for a good idea

I was also using another scrapper for TikTok and that one also has some problem with scrapping from the hashtag.

**Comment by davidteather** [comment]
Update the API to the latest version. There's better error handling now which should give you a better idea of how to proceed.

**Comment by pibvbp** [comment]
getting the same error with the latest pyppeteer version...
