### ISSUE TITLE
[BUG] - IndexError: list index out of range

### ISSUE THREAD

**Issue by magicub** [davidteather/TikTok-Api#371]
**Description**
I'm trying to get the description of the videos of an user, it had worked for months until last week

**code**

```
from TikTokApi import TikTokApi
api = TikTokApi()

n_videos = 1000
username = 'crisbasabe'
user_videos = api.byUsername(username, count=n_videos)
import pandas as pd

def simple_dict(tiktok_dict):
  to_return = {}
  to_return['user_name'] = tiktok_dict['author']['uniqueId']
  to_return['user_id'] = tiktok_dict['author']['id']
  to_return['video_id'] = tiktok_dict['id']
  to_return['video_desc'] = tiktok_dict['desc']
  to_return['video_time'] = tiktok_dict['createTime']
  to_return['video_length'] = tiktok_dict['video']['duration']
  to_return['video_link'] = 'https://www.tiktok.com/@{}/video/{}?lang=en'.format(to_return['user_name'], to_return['video_id'])  
  to_return['n_likes'] = tiktok_dict['stats']['diggCount']
  to_return['n_shares'] = tiktok_dict['stats']['shareCount']
  to_return['n_comments'] = tiktok_dict['stats']['commentCount']
  to_return['n_plays'] = tiktok_dict['stats']['playCount']  
  return to_return


user_videos = [simple_dict(v) for v in user_videos]
user_videos_df = pd.DataFrame(user_videos)
user_videos_df.to_csv('{}_videos.csv'.format(username),index=False)

```

Usually ia csv file was created without issues

**Error Trace )**

```
# Traceback (most recent call last):
  File "c:/Users/John Mario/hello/tests/test_discover.py", line 7, in <module>
    user_videos = api.byUsername(username, count=n_videos)
  File "C:\Users\John Mario\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 437, 
in byUsername
    data = self.getUserObject(username, **kwargs)
  File "C:\Users\John Mario\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 1000, in getUserObject
    return self.getUser(username, **kwargs)["userInfo"]['user']
  File "C:\Users\John Mario\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 1030, in getUser
    j_raw = t.split('<script id="__NEXT_DATA__" type="application/json" crossorigin="anonymous">')[1].split("</script>")[0]
IndexError: list index out of range
```

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - TikTokApi Version 3.7.9

**Comment by vdemay** [comment]
This means tiktok response is not the one expected: it returns a captcha page instead of the real content. Try to use a custom_verifyFp as parameter of your API methods. see https://github.com/davidteather/TikTok-Api/issues/363

in any cases, some requests are broken for now : see https://github.com/davidteather/TikTok-Api/issues/368

**Comment by thanasakos** [comment]
I encounter a similar error with the getUser, and byUsername endpoints. I even tried with the custom_verifyFp from my browser session, and the problem persists.

**Comment by kami4ka** [comment]
Same with getting video by user.

**Comment by vdemay** [comment]
Here is a captcha before getting user informations. It means the html page is a captcha. try to request from another IP

**Comment by thanasakos** [comment]
Tried that from several different IPs as well, with same result.

**Comment by kami4ka** [comment]
Getting video by hashtag works like a charm, while by username - fails

**Comment by davidteather** [comment]
Update to the latest version of the package it's got better error handling and should give you a better idea of how to proceed

**Comment by magicub** [comment]
After applying the update i'm getting this

ERROR:root:Tiktok wants to display a catcha. Response is:
{"code":"10000","from":"","type":"verify","version":"","region":"va","subtype":"slide","detail":"k3AeP-ShsA7OpGE9jklnbSqqYM*Jqn0VXG0ARRGxizW9ZJl4ZHBiyEp1lzz37aNLmsl1uV2sS0MFIxiXYvWGNyMJ0R4nIxrXJUDg-2YwnlFwfbe1qTHIq4cZsrtmGsTgA9AzAYGNjj8jUC2jqL*88w8BHLRWBcGOCI2rACy39QzKxTmdJl-sLcl-4139-3KFpZtgGGYzwdAoQTEWJue4dgro6tO4oemtD6ra6fqpXizI*z5UkDIw25gwDadZfJMMJ4pm,"scene":""}                                                                                                         "c
Traceback (most recent call last):
  File "c:/Users/John Mario/hello/basabe01.py", line 7, in <module>
    user_videos = api.byUsername(username, count=n_videos)
  File "C:\Users\John Mario\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 482, in byUsername                                                                                                     2,
    return self.userPosts(
  File "C:\Users\John Mario\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 444, in userPosts                                                                                                      4,
    res = self.getData(url=api_url, **kwargs)
  File "C:\Users\John Mario\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 177, in getData                                                                                                        7,
    raise TikTokCaptchaError()
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters
PS C:\Users\John Mario\hello> & "C:/Users/John Mario/AppData/Local/Programs/Python/Python38-32/python.exe" "c:/Users/John Mario/hello/basabe01.py"
ERROR:root:Tiktok wants to display a catcha. Response is:
{"code":"10000","from":"","type":"verify","version":"","region":"va","subtype":"slide","detail":"KHvVtsJgH5R9bGmPz1VirpdUyVGrasoU3PYtjCfJJWcymrLuH70W2TwSXKKPOIW3P6iP9C*bvfkqOit0EV7Fl98jJTWNgAYshFbwEbBVCwdX3P22HDEQkafFf-IIlo9icPUfBrQDJ*DNMGXb*p3uNOzF8tHfQONOG82iFa0JkSDAth1hyC5q6PTK216WwJJl4VQCcZ9W4QSAk6rM8kc7i*Vy8r2IYw6MG9buvWruuuKqi8e60WO*bUCIiyFpLoN2IVAN5zgEjXr1c7rD7x10u*X7t0qab5O4hqMK7KSL","verify_event":"","fp":"verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq","scene":""}
Traceback (most recent call last):
  File "c:/Users/John Mario/hello/basabe01.py", line 7, in <module>
    user_videos = api.byUsername(username, count=n_videos)
  File "C:\Users\John Mario\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 482, in byUsername
    return self.userPosts(
  File "C:\Users\John Mario\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 444, in userPosts
    res = self.getData(url=api_url, **kwargs)
  File "C:\Users\John Mario\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 177, in getData
    raise TikTokCaptchaError()
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters

Can someone guide me on where to setup the proxy or the custom_verifyFp?

**Comment by davidteather** [comment]
Yeah sure. Go to tiktok.com on chrome or something go to watch now then click the security lock on the top by the URL -> cookies -> www.tiktok.com -> s_v_web_id and copy the value of that and then you can pass that value into custom_verifyFp

Ex
```
api.trending(custom_verifyFp="your_s_v_web_id")
```

**Comment by mathigatti** [comment]
I'm getting this same error for get_music_object_full method, the rest of the functions seem to work fine
