### ISSUE TITLE
[BUG] - KeyError: 'challenge'

### ISSUE THREAD

**Issue by kami4ka** [davidteather/TikTok-Api#373]
**Describe the bug**

Getting videos by hashtag throwing exception

**The buggy code**

https://github.com/davidteather/TikTokBot/blob/master/tiktokbot.py

**Expected behavior**

Code works

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
Traceback (most recent call last):
  File "/Users/*****/PycharmProjects/TestProjects/main.py", line 123, in <module>
    res = api.byHashtag(x, count=count, custom_did=did)
  File "/Users/*****k/PycharmProjects/TestProjects/venv/lib/python3.7/site-packages/TikTokApi/tiktok.py", line 744, in byHashtag
    id = self.getHashtagObject(hashtag)["challengeInfo"]["challenge"]["id"]
KeyError: 'challenge'
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - TikTokApi Version [3.7.9]

**Comment by vdemay** [comment]
KeyError on challenge probably means the hashtag you use does not exist on Tiktok side

**Comment by kami4ka** [comment]
My bad. Had a lot of issues while tried to get this script back to work, so forget about it. Thanks!
