### ISSUE TITLE
Getting "Access Denied" when trying to download user videos, only works with trending() method

### ISSUE THREAD

**Issue by kylel06** [davidteather/TikTok-Api#385]
Hi David, I just want to clarify the error reported in #374 and I believe the problem was still there. I think teending() works perfectly but the access was denied for other downloading video methods and the error was there for almost a week. Really wanna know if you might be able to give a solution. Thank you!!!

**Comment by davidteather** [comment]
Just use #374 i'll try to find a fix

**Comment by kylel06** [comment]
Thank you so much!!! Wait for your updates!!
