### ISSUE TITLE
[INSTALLATION] - AttributeError: type object 'TikTokApi' has no attribute 'get_instance'

### ISSUE THREAD

**Issue by ivenkrish** [davidteather/TikTok-Api#387]
**Describe the bug**

AttributeError: type object 'TikTokApi' has no attribute 'get_instance'

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
api = TikTokApi.get_instance()
```

**Expected behavior**

get an api object

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
Traceback (most recent call last):
  File "tiktok.py", line 15, in <module>
    api = TikTokApi.get_instance()
AttributeError: type object 'TikTokApi' has no attribute 'get_instance'
```

**Desktop (please complete the following information):**
 - OS: MacOS Sierra
 - TikTokApi Version - 3.8.1

**Comment by joeyorjohn** [comment]
I'm having the same issue!

**Comment by davidteather** [comment]
Do you have the TikTokApi-pyppeteer package installed? 

Run
```
pip uninstall TikTokApi-pyppeteer
```

Then
```
pip install TikTokApi --upgrade
```

**Comment by joeyorjohn** [comment]
turns out I just needed to update the Tiktok Api package :)

**Comment by nightduck** [comment]
This doesn't fix it for me

**Comment by davidteather** [comment]
@nightduck Make sure you're using python 3.7+

**Comment by AliQansou** [comment]
I am having the same issue although the API is up to date and I am using python 3.8.10.
