### ISSUE TITLE
[INSTALLATION] - Consider using a proxy or a custom_verifyFp as method parameters

### ISSUE THREAD

**Issue by d1alogo** [davidteather/TikTok-Api#390]
Is the proxy mandatory?
Or custom_verifyFp should be enought?
The custom_verifyFp looks passed ok (masked in here for security reasons, if some) 

> from TikTokApi import TikTokApi
>
> def getPost(username, videoId):
>     api = TikTokApi.get_instance()
>     print("https://www.tiktok.com/@"+username +"/video/"+videoId)
>     posts = api.getTikTokByUrl(url="https://www.tiktok.com/@"+username +"/video/"+videoId, custom_verifyFp="verify_########_########_####_####_####_#########OgV")
>     print(posts)
>  
>     return {
>        'status':200,
>        'username': username,
>        'videoId': videoId,
>     }
>
> print(getPost("bellapoarch", "6880957427181735173"))

ERROR:root:Tiktok wants to display a catcha. Response is:
{"code":"10000","from":"","type":"verify","version":"","region":"va","subtype":"slide","detail":"jGD3vmQpj80SCTAGNiTcf4Ue5DagX1MuYqNmZCHehh*eq89Jc7dTmtEdJPilCGsYHZpdEwXcbFF63rePOoej3JPtPTq5wjMl25Mce5jtRfelwGyNDGbZqZqAoKqDGYPpQzynKCM9TcUJ1LBGlB3WABO0J8p4xHdBBRQO0wtBIawKNFKVoau03jCLVybwmZPleYFfTFFrV5LDepeLSkeyJB6u-nonZwczyM9YipZyj9O7hu3Ew0cV5TAQks0OfF*d6c7B4Y4cSllSvgDbOQ0EU5GR3PbbD8w88WdaPqVaXb4.","verify_event":"","fp":"verify_khup4lv1_eZNmkrUV_umyI_40J1_AOba_xMmZAqD1lOgV","scene":""}
ERROR:root:{'tt_webid': '950064287', 'tt_webid_v2': '950064287', 'tt_csrf_token': 'iBtbcbDgdXhRsPEu', 's_v_web_id': 'verify_########_########_####_####_####_#########OgV'}
Traceback (most recent call last):
  File "getTikTokByUrl.py", line 19, in <module>
    print(getPost("bellapoarch", "6880957427181735173"))
  File "getTikTokByUrl.py", line 6, in getPost
    posts = api.getTikTokByUrl(url="https://www.tiktok.com/@"+username +"/video/"+videoId, custom_verifyFp="verify_khup4lv1_eZNmkrUV_umyI_40J1_AOba_xMmZAqD1lOgV")
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 1001, in getTikTokByUrl
    return self.getTikTokById(
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 974, in getTikTokById
    return self.getData(url=api_url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 179, in getData
    raise TikTokCaptchaError()
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha 
Tip: Consider using a proxy or a custom_verifyFp as method parameters

**Desktop (please complete the following information):**
 - OS: FROM mcr.microsoft.com/playwright:focal (docker)
 - TikTokApi Version 3.8.1

**Comment by d1alogo** [comment]
I bet the message "Consider using a proxy or a custom_verifyFp as method parameters" is not precise enought. I bet it should say "proxy AND custom_verifyFP". 

But let's the author talk ...

**Comment by davidteather** [comment]
Proxy isn’t mandatory neither really is custom_verifyFp but if you want to make scaled requests you’ll
Need rotating proxies somewhere and rotating your verify fps

**Comment by divergentideas** [comment]
How do you get a custom_verifyFyp? The tutorial says to use a Log in and get a  s_v_web_id , does anyone know where to find that? (not sure If I'm asking in the right place - not sure about the relationship between the custom_verifyFyp and the s_v_web_id lol

**Comment by srudyanto** [comment]
no s_v_web_id in website cookies

**Comment by d1alogo** [comment]
@davidteather 
Out of "scaled requests", i only made some test request (15? 20?) while installing it, i always get the capcha, even with custom_verifyFp. I think it only worked once or so.

Please, do you know of any free working proxy that works without credit card? Thanks in advance.

**Comment by dwight9339** [comment]
Related question, has anyone found a way to _induce_ a captcha so they can get an updated verify fp?

**Comment by gdevisa** [comment]
I kind of found a work around the blocking, you might still get captcha sometimes, but I expect to get it way less frequently. Basically, the root of the problem is where we are using requests library like in getUser. It's way easier for tiktok and other websites to figure out you're a bot if you are using this library, so instead I am using selenium with chrome driver. The main advantage is that you can make it open the webpage you want and tell it to wait until certain elements of the page you need are loaded and only then it will capture the html and get you the data. If you don't succeed you can try a couple more times and you will get a response.

**Comment by AlexVerrico** [comment]
Posting in case it helps anyone else with the same issue:
I couldn't manage to get it to work using Brave browser to get the cookie, for some reason I had to use Chrome to get the cookie and then it worked perfectly.

**Comment by davidteather** [comment]
> a way to induce captcha

[This](https://sf16-scmcdn-va.ibytedtos.com/goofy/secsdk-captcha/va/2.15.21/index.html) but it doesn't generate valid tokens every time for some reason even with switching IPs maybe browser fingerprinting?

**Comment by davidteather** [comment]
There's a YouTube video linked in the readme which should help you get around this issue
