### ISSUE TITLE
ModuleNotFoundError: No module named 'TikTokApi'

### ISSUE THREAD

**Issue by fernieq** [davidteather/TikTok-Api#395]
# Read Below!!! If this doesn't fix your issue delete these two lines
**You may need to install chromedriver for your machine globally. Download it [here](https://sites.google.com/a/chromium.org/chromedriver/) and add it to your path.**

**Describe the bug**

In my terminal I ran 'pip3 install TikTokApi' but I could not import the library in my py file.

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
# Code Goes Here
from TikTokApi import TikTokapi
```

**Expected behavior**

The API should run without any errors.

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```

**Desktop (please complete the following information):**
 - OS: [I am running it on Mac OS mojave]
 - TikTokApi Version [e.g. 3.3.1] - if out of date upgrade before posting an issue

**Additional context**

**Comment by demon071** [comment]
you can try pip install TikTokApi

**Comment by fernieq** [comment]
Below is the error message I got after running the command line you provided in my terminal:
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting TikTokApi
  Using cached TikTokApi-3.8.1.tar.gz (56 kB)
Requirement already satisfied: requests in /anaconda2/lib/python2.7/site-packages (from TikTokApi) (2.21.0)
ERROR: Could not find a version that satisfies the requirement playwright (from TikTokApi) (from versions: none)
ERROR: No matching distribution found for playwright (from TikTokApi)

**Comment by demon071** [comment]
you can download the zip, install the necessary libraries to use, or try tiktok-api-python

**Comment by fernieq** [comment]
How do it install the necessary libraries? What are the commands? Thanks.

**Comment by demon071** [comment]
pip3 install -r requirements.txt
or 
pip install -r requirements.txt

**Comment by fernieq** [comment]
I downloaded the entire repo base from Git. I then navigated into the folder and did 'pip3 install -r requirements.txt'. Then I got the following error message:
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (2.21.0)
ERROR: Could not find a version that satisfies the requirement playwright (from -r requirements.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for playwright (from -r requirements.txt (line 2))

**Comment by fernieq** [comment]
I am also wondering since I have Mac, do I have to install XCode Developer Tools?

**Comment by demon071** [comment]
You can try 

> I am also wondering since I have Mac, do I have to install XCode Developer Tools?

if you want to try some api then you can try https://github.com/demon071/Tiktok-API-Python using only the requests library

**Comment by fernieq** [comment]
Does the one you provided work the same as the one developed by David?

**Comment by demon071** [comment]
it doesn't have as many options as that of Dvid

**Comment by fernieq** [comment]
according to the readme located in your repo, it only has three methods. Where can I get a full list of the supported methods of your API?

**Comment by demon071** [comment]
Currently there are only 3 methods, I will add more

**Comment by fernieq** [comment]
How do I install playwright? It kept giving me errors.

**Comment by demon071** [comment]
you can search for the solution on google

**Comment by davidteather** [comment]
Closing because it's a playwright issue. I think you do need XCode tools installed
