### ISSUE TITLE
[BUG] - After sending a api.clean_up() method, the script does not complete its work

### ISSUE THREAD

**Issue by studio-salamander** [davidteather/TikTok-Api#396]
After sending a clean_up() method, the script does not complete its work.

```
import time
from collections import defaultdict
from random import uniform

from TikTokApi import TikTokApi


def tiktok_processing(users: list) -> dict:
    api = TikTokApi.get_instance()

    params = defaultdict(dict)
    for username in users:
        try:
            user = api.getUser(username)
            params[username].update(
                follower_count=user['userInfo']['stats']['followerCount'],
                verified=user['userInfo']['user']['verified']
            )
        except IndexError:
            print(f"Data does not received: {username}")

        except Exception as ex:
            print(f"Unknown exception: {ex}")

        time.sleep(uniform(5.0, 10.0))

    api.clean_up()
    # time.sleep(3)
    # api._TikTokApi__instance = None
    # time.sleep(3)

    return params    # this line of code is most often unreachable for a reason unknown to me


if __name__ == "__main__":
    users = [...]
    result = tiktok_processing(users)

```

The MS-Playwright remains a running process. I want to note that sometimes in debug mode the script terminates its work correctly in the 1-2 seconds. I cannot see the pattern of this behavior. What would you advise to do?

 - OS: Ubuntu 18.04 LTS
![image](https://user-images.githubusercontent.com/9484902/100542649-f04a2f00-3253-11eb-8439-e632f8859033.png)
 - TikTokApi Version 3.7.9
Note: version 3.8.1 does not suit me - after upgrading to the latest version, I receive only a captcha, despite the fact that I send request with a custom_verifyFp, taken from a chrome browser (at least, I have not found another way to get a valid value of this parameter). So I had to roll back to the last working version. I should note that the error made in the title of this post is also observed in version 3.8.1

**Comment by davidteather** [comment]
> after upgrading to the latest version, I receive only a captcha

Is this still the case with version 3.8.3?

The API is designed to only be called once without manually calling the cleanup method. I'd recommend making a global TikTokApi instance and not doing it within the tiktok_processing method if possible. There's some weird things with playwright you could try to use selenium with `api = TikTokApi.get_instance(use_selenium=True)` if the issue persists

**Comment by studio-salamander** [comment]
> Is this still the case with version 3.8.3?

Version 3.8.3 has nothing to do with it. You just released it today) And I was talking about version 3.8.1.
I'll try with your recommendations and new version. Thanks.

There is one more moment. 
Some proxies require compliance with their own ssl-certificates. For example, the Luminati Proxy Manager that I use. However, you do not have the ability to add the verify/cert parameter to the get method. So far, only one method interests me - getUser()
And it would be nice to be able to pass a parameter for the ssl-certificate to it.

I experimented here and came to this solution, that worked great for me:

script.py
```
user = api.getUser(
    username,
    custom_verifyFp='some_custom_verifyFp',
    proxy=proxy_host_port,
    cert=conf.PROXY_SSL_CERT    # '/path/to/ssl-cert'
)
```

TikTokApi/tiktok.py
```
r = requests.get(
    "https://tiktok.com/@{}?lang=en".format(username),
    headers={
        ...
    },
    proxies=self.__format_proxy(kwargs.get("proxy", None)),
    cookies=self.get_cookies(**kwargs),
    verify=kwargs.get("cert", True)
)
```
(I'm not sure that True by default is the right solution, but it suits me)

This isn't exactly what the standard requests.get () call requires, but it's the only way to work. I did not understand the reasons why this is so, to be honest )

This is so - food for thought )

And, here's another, I thought about get_cookies()

```
def get_cookies(self, **kwargs):
    did = kwargs.get("did", str(random.randint(10000, 999999999)))
    if not kwargs.get("custom_verifyFp"):
        if self.custom_verifyFp:
            verifyFp = self.custom_verifyFp
        else:
            verifyFp = "verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq"
    else:
        verifyFp = kwargs.get('custom_verifyFp')

    force_verify_fp = {
        "tt_webid": did,
        "tt_webid_v2": did,
        "tt_csrf_token": "".join(
            random.choice(string.ascii_uppercase + string.ascii_lowercase)
            for i in range(16)
        )
    }
    if kwargs.get("force_verify_fp_on_cookie_header", False):
        force_verify_fp.update(s_v_web_id=verifyFp)

    return force_verify_fp
```
(I apologize for doing code review :))

**Comment by studio-salamander** [comment]
@davidteather thanks - with the new library update I don't even need a proxy )
But when the script ends, an error is raised:
```
Exception ignored in: <greenlet.greenlet object at 0x7f539e513290 (otid=0x7f53b0318870) dead>
Traceback (most recent call last):
  File "/home/andy/.local/share/virtualenvs/tiktok_recon-W7inMTXw/lib/python3.7/site-packages/playwright/main.py", line 92, in <lambda>
  File "/home/andy/.local/share/virtualenvs/tiktok_recon-W7inMTXw/lib/python3.7/site-packages/playwright/connection.py", line 128, in run_sync
  File "/home/andy/.local/share/virtualenvs/tiktok_recon-W7inMTXw/lib/python3.7/site-packages/playwright/transport.py", line 36, in run_sync
  File "/usr/lib/python3.7/asyncio/base_events.py", line 566, in run_until_complete
  File "/usr/lib/python3.7/asyncio/base_events.py", line 540, in run_forever
AttributeError: 'NoneType' object has no attribute '_set_running_loop'
```
(yes, I use pipenv)

I understand that this is not your problem and is happening in asyncio, but I inform you just in case )

**Comment by studio-salamander** [comment]
> verify=kwargs.get("cert", True)

Checked
Yes, if kwargs does not have a cert key, need to set this param to False )
