### ISSUE TITLE
[BUG] - playwright.helper.Error: Host system is missing dependencies!

### ISSUE THREAD

**Issue by helmassaoudi** [davidteather/TikTok-Api#399]
I use the api.byUsername() in a python script
Everything was working fine until lately i get this error : 
playwright.helper.Error: Host system is missing dependencies!
Missing libraries are:
      libvpx.so.6
      libicui18n.so.66
      libicuuc.so.66
      libwoff2dec.so.1.0.2
      libjpeg.so.8

I don't know how to fix this. Please help 
PS: i run my python script in a virtualenv

**Comment by davidteather** [comment]
You gotta install the dependencies you can find them [here](https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic) in playwright's dockerfile. You can also try with selenium `api = TikTokApi.get_instance(use_selenium=True)`

**Comment by cynde** [comment]
any solution?
