### ISSUE TITLE
How to make a tiktok login using this code

### ISSUE THREAD

**Issue by umeshdepale** [davidteather/TikTok-Api#4]
Hey! how to login in tiktok website and get cookies of user

**Comment by davidteather** [comment]
Do you mean you want to log into a TikTok account?
Or do you just want to access the most popular or a specific TikTok user's videos?

**Comment by umeshdepale** [comment]
I want a system where i login any tiktok account and get the access like session and cookies. Mean I just want Login with TikTok system in my website.

**Comment by davidteather** [comment]
So you want like one of the sign in google options, but for TikTok?

As of now that's not possible with this API. It just finds trending and searches for users like it does in a browser.

**Comment by reliefs** [comment]
Bump

**Comment by davidteather** [comment]
TikTok's login page ALWAYS has a captcha test. It's a low priority for me to develop an algorithm to pass their captcha.

**Comment by davidteather** [comment]
I'm adding wontfix for now, but might later on.

**Comment by reliefs** [comment]
https://github.com/NorthenFox/TikTokPy/issues/2

**Comment by virginsince1997** [comment]
We can use a CAPTCHA bypass system, deathbycaptcha?
