### ISSUE TITLE
[BUG] - raise EmptyResponseError & stops program execution

### ISSUE THREAD

**Issue by grzegorzdeveloper** [davidteather/TikTok-Api#402]
**Describe the bug**

Hi I added the CustomFp to where I grab tiktoks by id and it's working up to 70 or 90 TikTok (with a 30 second sleep between each one) but then I get a raise emptyresponseerror and it stops the program running.

Is there a fix to this or a way to handle the error to just wait and retry until it works?

**The buggy code**

                        tiktok = api.getTikTokById(tiktok_id, custom_did=did, custom_verifyFp=custom_verifyFP) #Error here
                        if "code" in tiktok:
                            if tiktok["code"] == 10000:
                                #sleep
                                print("Captcha failed, retrying in 20 seconds..")
                                time.sleep(20)

                        if "statusCode" in tiktok:
                            if tiktok["statusCode"] != 0:
                                #skip this tiktok
                                nexttiktok = True

**Expected behavior**

error to be printed out and to retry requesting the tiktok again

**Error Trace** (some parts replaced with ###)

```
    tiktok = api.getTikTokById(tiktok_id, custom_did=did, custom_verifyFp=custom_verifyFP)
  File "C:\Python38\lib\site-packages\TikTokApi\tiktok.py", line 978, in getTikTokById
    return self.getData(url=api_url, **kwargs)
  File "C:\Python38\lib\site-packages\TikTokApi\tiktok.py", line 189, in getData
    raise EmptyResponseError(
TikTokApi.exceptions.EmptyResponseError: Empty response from Tiktok to https://m.tiktok.com/api/item/detail/?aid=1988&app_name=tiktok_web&device_platform=web&referer=https%3A%2F%2Fwww.tiktok.com%2F&user_agent=Mozilla%252F5.0%2B%28iPhone%253B%2BCPU%2BiPhone%2BOS%2B12_2%2Blike%2BMac%2BOS%2BX%29%2BAppleWebKit%252F605.1.15%2B%28KHTML%2C%2Blike%2BGecko%29%2BVersion%252F13.0%2BMobile%252F15E148%2BSafari%252F604.1&cookie_enabled=true&screen_width=1806&screen_height=650&browser_language=&browser_platform=&browser_name=&browser_version=&browser_online=true&ac=4g&timezone_name=&appId=1233&appType=m&isAndroid=False&isMobile=False&isIOS=False&OS=windows&page_referer=https%3A%2F%2Fwww.tiktok.com%2F&itemId=6899155380073401602&language=en&verifyFp=verify_###########################1PA&did=3#######0&_signature=_02B4###################8
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - TikTokApi Version [e.g. 3.8.2] - if out of date upgrade before posting an issue

**Comment by MStudioBuildInc** [comment]
Try change verifyFp and wait some time

**Comment by davidteather** [comment]
There's a YouTube video in the readme that explains how to get a custom_verifyFp and another workaround which may help you. I haven't had to use a large request delay with it
