### ISSUE TITLE
getTikTokById issue

### ISSUE THREAD

**Issue by ziyueluo** [davidteather/TikTok-Api#411]
Hi Davy,
When I tied with **selenium** with getTikTokById: 
tk = api.getTikTokById(id,did=did,proxies=proxies,custom_verifyFp=verifyFP)
it returns the following error, but other methods are working fine( such as trending, byHashtag)
Do you have any idea why this is happening ?
Thanks!

ERROR:root:TikTok response: {
    statusCode: -1,
    itemInfo: {}
} 
ERROR:root:Converting response to JSON failed
TikTokApi.exceptions.JSONDecodeFailure: TikTok sent invalid JSON back

**Comment by startsts** [comment]
I confirm the issue.  Please any advice how to hotfix that

**Comment by davidteather** [comment]
Try the following `api = TikTokApi.get_instance(use_test_endpoints=True)` it should work for at least now
