### ISSUE TITLE
All byHashtag, by Sound, discover(), trending() DO NOT Work...

### ISSUE THREAD

**Issue by serenat96** [davidteather/TikTok-Api#413]
Hi David,

When I tried all methods that returned tiktoks under a hashtag, a music seed, on the discover list or on trending, they did not work all at once. The returned error is "Tiktok sending invalid JSON back''/"Empty response". I was wondering if you may know what's going on and if you encountered the same issues? Thank you so much for your help!

**Comment by ziyueluo** [comment]
Same issue here

**Comment by serenat96** [comment]
I just tried the new version 3.8.4 but it seems like the above issue was still there. Thought probably Tiktok updated something on its end.

**Comment by serenat96** [comment]
I think it worked now, though I did not really know why. I'll close the issue now.

**Comment by davidteather** [comment]
No worries! The new package update was probably the fix I imagine. You may want to try out the api = TikTokApi.get_instance(use_test_endpoints=True)

**Comment by ziyueluo** [comment]
Thanks David! Also, could we use selenium when downloading tiktok videos? I asked in the thread #411 and was wondering if there might be a fix.

**Comment by yswtrue** [comment]
byHashtag still not works
