### ISSUE TITLE
[BUG] - EmptyResponseError

### ISSUE THREAD

**Issue by JohnTYH** [davidteather/TikTok-Api#417]
# Read Below!!! If this doesn't fix your issue delete these two lines
**You may need to install chromedriver for your machine globally. Download it [here](https://sites.google.com/a/chromium.org/chromedriver/) and add it to your path.**

**Describe the bug**

**The buggy code**
from TikTokApi import TikTokApi
import random
api = TikTokApi.get_instance()
custom_did = str(random.randint(10000, 999999999))

results = 2

# Since TikTok changed their API you need to use the custom_verifyFp option. 
# In your web browser you will need to go to TikTok, Log in and get the s_v_web_id value.
#trending = api.trending(count=results, custom_verifyFp="")
hashtag_videos = api.byHashtag('covid', count=1, custom_did=custom_did, custom_verifyFp='verify_kidz7cgg_Qyz7RECI_o3vI_4fjk_BDCA_uPzl1O1jjQVX')

for tiktok in hashtag_videos:
    data = api.get_Video_By_TikTok(tiktok,custom_did=custom_did,custom_verifyFp='verify_kidz7cgg_Qyz7RECI_o3vI_4fjk_BDCA_uPzl1O1jjQVX')
    print(tiktok)
    with open("test.mp4", 'wb') as o:
        o.write(data)
    print('success')
Please insert the code that is throwing errors or is giving you weird unexpected results.

```
# Code Goes Here
```

**Expected behavior**

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```
![image](https://user-images.githubusercontent.com/42569121/101739511-932b6480-3b02-11eb-83c6-678adf324434.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - TikTokApi Version [e.g. 3.3.1] - 3.8.5

**Additional context**

**Comment by JohnTYH** [comment]
This error is also present using https://github.com/davidteather/TikTok-Api/blob/master/examples/downloadTikTok.py code as well.

**Comment by davidteather** [comment]
Your custom verifyFp is probably invalid you can generate a new verifyFp [here](https://sf16-scmcdn-va.ibytedtos.com/goofy/secsdk-captcha/va/2.15.21/index.html) but this seems to have a cooldown and browser fingerprinting so it's not always valid.

You can also pass the `api = TikTokApi(use_test_endpoints=True)` which seem to have less security on verifyFp although it's untested for downloading videos.

**Comment by davidteather** [comment]
A new version I just released may fix this for you

**Comment by bmusuko** [comment]
thanks for this info, I experience this problem for the past 2 days. Use `api = TikTokApi(use_test_endpoints=True)` will fix this problem and success in download videos

**Comment by rnyPlanet** [comment]
> thanks for this info, I experience this problem for the past 2 days. Use `api = TikTokApi(use_test_endpoints=True)` will fix this problem and success in download videos

can you share the complete code?

**Comment by bmusuko** [comment]
> can you share the complete code?

`api = TikTokApi.get_instance(use_selenium=True, use_test_endpoints=True)`
but sometimes chapta error appear randomly

**Comment by rnyPlanet** [comment]
> `api = TikTokApi.get_instance(use_selenium=True, use_test_endpoints=True)`
> but sometimes chapta error appear randomly

Thank you)

**Comment by JohnTYH** [comment]
Hmm, I managed to download videos using byUsername. However, byHashtag still returns an emptyresponseerror. does anyone knows how to solve that?

**Comment by novemberdude** [comment]
Hey everyone, I also got the empty response error, and in the *tiktok.py* file, I change `BASE_URL = "https://m.tiktok.com/"` to `BASE_URL = "https://t.tiktok.com/"` and it works!

**Comment by rnyPlanet** [comment]
> Hmm, I managed to download videos using byUsername. However, byHashtag still returns an emptyresponseerror. does anyone knows how to solve that?

https://github.com/davidteather/TikTok-Api/issues/426#issuecomment-747821334

**Comment by davidteather** [comment]
> Hey everyone, I also got the empty response error, and in the _tiktok.py_ file, I change `BASE_URL = "https://m.tiktok.com/"` to `BASE_URL = "https://t.tiktok.com/"` and it works!

Which is what `TikTokApi.get_instance(use_test_endpoints=True)` should do
