### ISSUE TITLE
[FEATURE_REQUEST] - What you want here

### ISSUE THREAD

**Issue by mikegrep** [davidteather/TikTok-Api#420]
**Describe the solution you'd like**
Hi I am wondering its have a function (method,calss) to return all new tiktok videos in range and with fileter hashtag uploaded same day when the search is made.Thanks

**Describe alternatives you've considered**
 a function (method,calss) to return all new tiktok videos in range and with some fileter uploaded same day when the search is made.

**Comment by yswtrue** [comment]
Hope to add a function to get who is following the target user.

**Comment by mzaboss** [comment]
Scrape usernames list from followers.

**Comment by davidteather** [comment]
> Hope to add a function to get who is following the target user.

and 
> Scrape usernames list from followers.

File new issues and I'll follow up, author of this issue forgot to change the title name.

> return all new tiktok videos in range and with fileter hashtag uploaded same day when the search is made.Thanks

You can define your own function to do this, although it's more of a workaround as it's not supported by TikTok. Here would be the flow of the function
```
hashtags = api.byHashtag('funny', count=2000)

# iterate through all elements in hashtags
# remove ones that have a createTime of more than 24 hours ago
```
