### ISSUE TITLE
[BUG] - Downloading video by DownloadURL/TikTok from array returns "Access denied" html file

### ISSUE THREAD

**Issue by whalecore** [davidteather/TikTok-Api#422]
**Bug description**

Trying to download videos by random/specific hashtags, it returns a html code with error instead. Same trouble with music downloads.

**The code I was trying to use:**

```python
hashtags = api.discoverHashtags()
chosen_hashtag = random.choice(hashtags)['cardItem']['title']
videos_by_hashtag = api.byHashtag(chosen_hashtag, count=10)
chosen_video = random.choice(videos_by_hashtag)

video = api.get_Video_By_TikTok(chosen_video, language='en')

with open('video.mp4', 'wb') as output:
    output.write(video)

```

**Error I'm getting written inside video.mp4**

```html
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;v16&#45;web&#46;tiktok&#46;com&#47;video&#47;tos&#47;useast2a&#47;tos&#45;useast2a&#45;ve&#45;0068c004&#47;2362532506c24a66be8a02a69273732d&#47;&#63;" on this server.<P>
Reference&#32;&#35;18&#46;e527bcd4&#46;1607970961&#46;2bc87a4
</BODY>
</HTML>

```

Is it possible that it's trying to get video from US servers and banning me because of my location (Russia)? I tried to use US proxy and VPN though, no result. But somehow it downloads videos I get from **api.trending** method with no problems at all.

**Desktop:**
 - OS: Windows 10
 - TikTokApi Version: 3.8.6

**Comment by rnyPlanet** [comment]
same problem

**Comment by TylerIlunga** [comment]
+1

**Comment by tarkhil** [comment]
same here

**Comment by tarkhil** [comment]
I've found something. It must me useful though I have no idea on how to use it.

`api = TikTokApi.get_instance(proxy='socks5://logn:password@working_proxy:1080/')`

did not yield in using the proxy at all! No error, just, according to tcpdump, all https traffic goes to 2.20.254.98.

next attempt goes to 2.20.254.129

I've also registered traffic to 188.43.76.26 and has no slightest idea on the cause.

**Comment by davidteather** [comment]
Hey the following script seems to work for me
```
from TikTokApi import TikTokApi
import string
import random

api = TikTokApi.get_instance(use_test_endpoints=True)

custom_did = ''.join(random.choice(string.digits) for num in range(19))

t = api.byHashtag('funny', custom_did=custom_did)[0]

with open("test.mp4", 'wb') as o:
    o.write(api.get_Video_By_TikTok(t, custom_did=custom_did))
```

**Comment by jp-wagner** [comment]
@davidteather I'm running my code in the docker container you provided now so playwright works, however I still get "Access denied" when running your example script. This never happened before as long as the dids matched, can you replicate this?

**Comment by davidteather** [comment]
There's also a YouTube video in the readme that explains how to get a custom_verifyFp and another workaround although the code above should still work.
