### ISSUE TITLE
[FEATURE_REQUEST] - Logic for Retrieving TikTok Comments

### ISSUE THREAD

**Issue by taylorbreannaray** [davidteather/TikTok-Api#423]
Hi @davidteather,

I have been testing out this unofficial API. I think what you have here is great! However, I couldn't help but wonder if there was logic added to retrieve the comments associated with each TikTok. As someone doing research, having access to such important metadata (and sentiment, if you will) would be especially helpful in my endeavors. Will this be added in the near future if it is not already?

**Comment by taylorbreannaray** [comment]
Any word on when this might be implemented? Or, alternatively, how one might implement it with the existing code? I presume the endpoint for comments does exist?

**Comment by davidteather** [comment]
Currently you have to be logged in to get the comments. Logging in isn’t currently a function supported by this package

**Comment by taylorbreannaray** [comment]
Ah, I see. That makes sense. I think this package could greatly benefit from having the ability to pull TikTok comments, but I am impressed with what is already here nonetheless. Plus, I'm sure you are quite busy as it is.

Thanks for getting back to me!

**Comment by davidteather** [comment]
Yeah it's something I've been looking into adding user login & comment stuff in the future however it's kinda a pain
