### ISSUE TITLE
[BUG] - getTikTokbyID does not work

### ISSUE THREAD

**Issue by kylel06** [davidteather/TikTok-Api#426]
Hi David,

When I tried getTikTokbyId() today, it sent back the error message “invalid JSON back”. I was wondering if you experienced the same issue and if there would be anyway to fix it.  Thank you!!

**Comment by serenat96** [comment]
Same issue here. Without getTikTokbyID(), it seems like we couldn't find a way to download videos properly. Really appreciate a solution. Thank you!

**Comment by serenat96** [comment]
For better reference, here is the error showing up:
-----------------------------------------------------------------------------------------------------
ERROR:root:TikTok response: {
    statusCode: -1,
    itemInfo: {}
} 
ERROR:root:Converting response to JSON failed
ERROR:root:Expecting property name enclosed in double quotes: line 2 column 5 (char 6)
Traceback (most recent call last):
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\TikTokApi\tiktok.py", line 196, in getData
    json = r.json()
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\requests\models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "D:\Program Files (x86)\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files (x86)\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files (x86)\Anaconda3\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 5 (char 6)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/Work/Tool/tiktok/download_tt1.py", line 35, in <module>
    tk = api.getTikTokById(k,custom_did=did,proxies=proxies,custom_verifyFp="verify_26eb251893a7fe9c4692b83ae29b7a6b")
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\TikTokApi\tiktok.py", line 999, in getTikTokById
    return self.getData(url=api_url, **kwargs)
  File "D:\Program Files (x86)\Anaconda3\lib\site-packages\TikTokApi\tiktok.py", line 217, in getData
    raise JSONDecodeFailure() from e
TikTokApi.exceptions.JSONDecodeFailure: TikTok sent invalid JSON back
------------------------------------------------------------------------------------------------------

I would really appreciate a solution! Thanks David!

**Comment by ziyueluo** [comment]
I found the same issue. Any solutions?

**Comment by davidteather** [comment]
> any solutions

You can try `api = TikTokApi(use_test_endpoints=True)` it may work however TikTok's servers are having issues right now

**Comment by serenat96** [comment]
Hi David, I tried. However, it did not work neither. It showed the error TikTok wants to display a captcha but I indeed passed on the verifyfp parameter after moving a puzzle.

**Comment by serenat96** [comment]
Did you use api = TikTokApi(use_test_endpoints=True) to successfully get a tiktok by using getTikTokbyID()?

**Comment by serenat96** [comment]
Also, I noticed the other issue #425 and tried it myself. I got the same error "empty response". In addition, Trending() returned the same error as well. So I believe there might be something changed on TikTok's end?

**Comment by ziyueluo** [comment]
Still did not work though with api = TikTokApi(use_test_endpoints=True). Really appreciate a feasible solution. Thanks!

**Comment by davidteather** [comment]
The following works for me
```
from TikTokApi import TikTokApi
import string
import random

api = TikTokApi.get_instance(use_test_endpoints=True)

print(api.getTikTokById('6907312030219341061'))
```

I'd suggest checking if you can access TikTok's site on the webbrowser or try to use a proxy.

**Comment by ziyueluo** [comment]
Hi Davy,
When I tried with use_test_endpoints=True ,
It would return the error :
ERROR:root:Tiktok wants to display a catcha. 
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha 
Tip: Consider using a proxy or a custom_verifyFp as method parameters

I tried with a new cookie and using proxy but none of them working. And I can access the websites.

**Comment by kylel06** [comment]
I experienced the same issue. The error “Consider using a proxy or a custom_verifyFp as method parameters” always showed up when I set use_test_endpoints=True. I indeed refreshed the cookie and could browse the website though.

**Comment by pibvbp** [comment]
Same here with byHashtag search.
I get an empty JSON:
```
ERROR:root:TikTok response: {statusCode: 0,body: {userData: {},statusCode: -1,shareUser: {}}} 
ERROR:root:Converting response to JSON failed
ERROR:root:Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

when using:
```
api = TikTokApi.get_instance(use_selenium=True, custom_verifyFp=s_v_web_id, use_test_endpoints=True)
test = api.byHashtag('TEST', count=999999, language='en', custom_verifyFp=s_v_web_id)
```

**Comment by davidteather** [comment]
Seems to be an issue with selenium see #434 playwright is working for me
