### ISSUE TITLE
[INSTALLATION] -   ERROR: Failed building wheel for greenlet

### ISSUE THREAD

**Issue by mikegrep** [davidteather/TikTok-Api#429]
**Describe the error**

  ERROR: Failed building wheel for greenlet
  Running setup.py clean for greenlet
Failed to build greenlet
Installing collected packages: urllib3, typing-extensions, selenium, pyee, idna, greenlet, chardet, certifi, selenium-stealth, requests, playwright, TikTokApi
    Running setup.py install for greenlet ... error
    ERROR: Command errored out with exit status 1:

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - TikTokApi Version [e.g. 3.8.6] - if out of date upgrade before posting an issue

**Additional context**
I try to install tiktokapi on virtualenv however its I have this issue with installation.I use python 3.6.9

**Comment by mikegrep** [comment]
**compilation terminated.
    error: command 'i686-linux-gnu-gcc' failed with exit status 1**

**Comment by davidteather** [comment]
[playwright-python](https://github.com/microsoft/playwright-python) only supports python versions 3.7+ you can either upgrade or if you plan on using selenium clone the repository, remove playwright as a dependency and install from there
