### ISSUE TITLE
Does TikTokApi currently work at all?

### ISSUE THREAD

**Issue by tarkhil** [davidteather/TikTok-Api#431]
Hello

Looking at issues and results of my attempts to download files, I cannot understand if something is wrong with my setup or TikTok just made a strong move against TikTokApi.

Was anyone be able to download a video recently?

**Comment by anwar3606** [comment]
Here is my stack trace 

```log
ERROR:root:TikTok response: 
Traceback (most recent call last):
  File "C:/Users/anwar/Desktop/TikTokScrapper/main.py", line 10, in <module>
    trending = api.trending(count=results, custom_verifyFp="")
  File "C:\Users\anwar\Desktop\TikTokScrapper\venv\lib\site-packages\TikTokApi\tiktok.py", line 336, in trending
    res = self.getData(url=api_url, **kwargs)
  File "C:\Users\anwar\Desktop\TikTokScrapper\venv\lib\site-packages\TikTokApi\tiktok.py", line 213, in getData
    ) from None
TikTokApi.exceptions.EmptyResponseError: Empty response from Tiktok to https://m.tiktok.com/api/item_list/?aid=1988&app_name=tiktok_web&device_platform=web&referer=&root_referer=&user_agent=Mozilla%252F5.0%2B%28iPhone%253B%2BCPU%2BiPhone%2BOS%2B12_2%2Blike%2BMac%2BOS%2BX%29%2BAppleWebKit%252F605.1.15%2B%28KHTML%2C%2Blike%2BGecko%29%2BVersion%252F13.0%2BMobile%252F15E148%2BSafari%252F604.1&cookie_enabled=true&screen_width=373&screen_height=1456&browser_language=&browser_platform=&browser_name=&browser_version=&browser_online=true&ac=4g&timezone_name=&appId=1233&appType=m&isAndroid=False&isMobile=False&isIOS=False&OS=windows&count=10&id=1&secUid=&maxCursor=0&minCursor=0&sourceType=12&appId=1233&region=US&priority_region=US&language=en&verifyFp=&did=8270505825469808366&_signature=_02B4Z6wo00f01sCOYMAAAIBCyn.YrIUtz2rAn2RAAPAMa7

```

**Comment by davidteather** [comment]
Best practice code example that should be working
```
from TikTokApi import TikTokApi
import string
import random

proxy = "some_proxy_service_like_luminati.io"
custom_did = ''.join(random.choice(string.digits) for num in range(19))
# custom_did should be provided to all calls you intend to download a video from

# Class constructor to use a custom_did persistently, could lead to TikTok detecting that specific did
# I personally recommend re-generating it after you're done parsing a specific response from TikTok
api = TikTokApi.get_instance(use_test_endpoints=True, proxy=proxy, custom_did=custom_did)

# Usage
top_funny = api.byHashtag('funny')
for tiktok in top_funny:
    tiktok_bytes = api.get_Video_By_TikTok(tiktok)

# Class constructor without a class custom_did
api = TikTokApi.get_instance(use_test_endpoints=True, proxy=proxy)

# Usage
top_funny = api.byHashtag('funny', custom_did=custom_did)
for tiktok in top_funny:
    tiktok_bytes = api.get_Video_By_TikTok(tiktok, custom_did=custom_did)
```

**Comment by nuqz** [comment]
> Here is my stack trace
> 
> ```
> ERROR:root:TikTok response: 
> Traceback (most recent call last):
>   File "C:/Users/anwar/Desktop/TikTokScrapper/main.py", line 10, in <module>
>     trending = api.trending(count=results, custom_verifyFp="")
>   File "C:\Users\anwar\Desktop\TikTokScrapper\venv\lib\site-packages\TikTokApi\tiktok.py", line 336, in trending
>     res = self.getData(url=api_url, **kwargs)
>   File "C:\Users\anwar\Desktop\TikTokScrapper\venv\lib\site-packages\TikTokApi\tiktok.py", line 213, in getData
>     ) from None
> TikTokApi.exceptions.EmptyResponseError: Empty response from Tiktok to https://m.tiktok.com/api/item_list/?aid=1988&app_name=tiktok_web&device_platform=web&referer=&root_referer=&user_agent=Mozilla%252F5.0%2B%28iPhone%253B%2BCPU%2BiPhone%2BOS%2B12_2%2Blike%2BMac%2BOS%2BX%29%2BAppleWebKit%252F605.1.15%2B%28KHTML%2C%2Blike%2BGecko%29%2BVersion%252F13.0%2BMobile%252F15E148%2BSafari%252F604.1&cookie_enabled=true&screen_width=373&screen_height=1456&browser_language=&browser_platform=&browser_name=&browser_version=&browser_online=true&ac=4g&timezone_name=&appId=1233&appType=m&isAndroid=False&isMobile=False&isIOS=False&OS=windows&count=10&id=1&secUid=&maxCursor=0&minCursor=0&sourceType=12&appId=1233&region=US&priority_region=US&language=en&verifyFp=&did=8270505825469808366&_signature=_02B4Z6wo00f01sCOYMAAAIBCyn.YrIUtz2rAn2RAAPAMa7
> ```

I have the same problem. Test endpoints worked for a while a few days ago, but now it do not work at all (the service responding with empty response).

**Comment by mal730** [comment]
Same problem.

`TikTokApi.exceptions.EmptyResponseError: Empty response from Tiktok`

**Comment by jp-wagner** [comment]
> Best practice code example that should be working
> 
> ```
> from TikTokApi import TikTokApi
> import string
> import random
> 
> proxy = "some_proxy_service_like_luminati.io"
> custom_did = ''.join(random.choice(string.digits) for num in range(19))
> # custom_did should be provided to all calls you intend to download a video from
> 
> # Class constructor to use a custom_did persistently, could lead to TikTok detecting that specific did
> # I personally recommend re-generating it after you're done parsing a specific response from TikTok
> api = TikTokApi.get_instance(use_test_endpoints=True, proxy=proxy, custom_did=custom_did)
> 
> # Usage
> top_funny = api.byHashtag('funny')
> for tiktok in top_funny:
>     tiktok_bytes = api.get_Video_By_TikTok(tiktok)
> 
> # Class constructor without a class custom_did
> api = TikTokApi.get_instance(use_test_endpoints=True, proxy=proxy)
> 
> # Usage
> top_funny = api.byHashtag('funny', custom_did=custom_did)
> for tiktok in top_funny:
>     tiktok_bytes = api.get_Video_By_TikTok(tiktok, custom_did=custom_did)
> ```

Is this example working for you with selenium too? Can't get it to work unfortunately, same goes for the pyppeteer fork and playwright doesn't run on my OS.

**Comment by tokjii** [comment]
It seems like it is not working at the moment. See some of my findings on https://github.com/carcabot/tiktok-signature/issues/106#issuecomment-749267815

Long story short - the website appears to be broken. 

We got this server, feel free to join and discuss https://discord.gg/HmYmtdX

**Comment by xianfengsong** [comment]
the website is broken, https://m.tiktok.com/api/item_list/ returns empty content
it seems that you must log in to get more videos

**Comment by nuqz** [comment]
> the website is broken, https://m.tiktok.com/api/item_list/ returns empty content
> it seems that you must log in to get more videos

I confirm this. The same situation.

**Comment by rnyPlanet** [comment]
> I confirm this. The same situation.

use_test_endpoints=True
https://github.com/davidteather/TikTok-Api/issues/422#issuecomment-748549814

**Comment by rnyPlanet** [comment]
```
api = TikTokApi.get_instance(use_test_endpoints=True)

results = 1
trending = api.trending(count=results,
                        custom_verifyFp="verify_FF",
                        custom_did=custom_did)
```
works great

**Comment by davidteather** [comment]
> the website is broken 

Yes, but t.tiktok.com is working somewhat for some people

switch the host from m.tiktok.com to t.tiktok.com or with this API use `api = TikTokApi.get_instance(use_test_endpoints=True)`

**Comment by AlmogRnD** [comment]
following

**Comment by tokjii** [comment]
> ```
> custom_did = ''.join(random.choice(string.digits) for num in range(19))
> trending = api.trending(count=results,
>                         custom_verifyFp="verify_FF",
>                         custom_did=custom_did)
> ```

I think there is no need for the randomized string and the `Fp`. It works without that too.

**But I get the exact same videos every time**. This used to be different. You'd sometimes get duplicates on consecutive calls but now it's like getting the same 10 out of 15 videos randomly.

Am I seeing ghosts or is it the same for you?

**Comment by rnyPlanet** [comment]
> I think there is no need for the randomized string and the `Fp`. It works without that too.
> 
> **But I get the exact same videos every time**. This used to be different. You'd sometimes get duplicates on consecutive calls but now it's like getting the same 10 out of 15 videos randomly.
> 
> Am I seeing ghosts or is it the same for you?

I have not tried without verify_. yes also, two or three videos constantly

**Comment by davidteather** [comment]
> two or three videos constantly

I haven't investigated this yet, but I would imagine it's related to [TikTok](https://tiktok.com/foryou) they're only displaying 2 videos on each request

**Comment by Sanney146** [comment]
Hello @davidteather,
I looked at the best practice code you postet a few comments earlier.
Can you provide a concrete example or link me to a place where "custom_did" is explained?
I do not really understand what can be substituted for the variable, and I did not find anything in the docu.

Thanks in advance!

**Comment by davidteather** [comment]
Hey TikTok's desktop's site is back up let me know if you're still having issues. I updated the package to be consistent with a few new changes

**Comment by nuqz** [comment]
> Hey TikTok's desktop's site is back up let me know if you're still having issues. I updated the package to be consistent with a few new changes

@davidteather great news! thank you very much.

**Comment by cameronmhall** [comment]
I'm getting a similar issue, videos download find using trending method but byUsername and byHashtag it says the videos are corrupt

**Comment by gauravdattjoshi** [comment]
For me only one thing worked I went to the TikTok.py file in TikTok Api Package Folder and changed the BASE_URL from "m.tiktok.com" to "t.tiktok.com".
