### ISSUE TITLE
[INSTALLATION] - ERROR: Failed building wheel for greenlet   Running setup.py clean for greenlet Failed to build greenlet

### ISSUE THREAD

**Issue by mikegrep** [davidteather/TikTok-Api#432]
**Describe the error**

standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/sh -c apt-get update && apt-get install -y python3-pip' returned a non-zero code: 1
when i try to install on docker cpu intel i368 ubuntu 18.04 Docker version 19.03.6, build 369ce74a3c

ERROR: Failed building wheel for greenlet   Running setup.py clean for greenlet Failed to build greenlet
when I try to install with pip on the machine python 3.6.9 Ubutu 18.04 i368 I have instaled pythond-dev package.

**Comment by davidteather** [comment]
playwright-python requires 3.7+ I suggest you upgrade the version to 3.7
