### ISSUE TITLE
[BUG] - Selenium EmptyBodyResponse 

### ISSUE THREAD

**Issue by 11348** [davidteather/TikTok-Api#434]
It use this api link and found noting when using selenium 

https://t.tiktok.com/api/item_list/?aid=1988&app_name=tiktok_web&device_platform=web&referer=&root_referer=&user_agent=Mozilla%252F5.0%2B%28Windows%2BNT%2B10.0%253B%2BWin64%253B%2Bx64%29%2BAppleWebKit%252F537.36%2B%28KHTML%2C%2Blike%2BGecko%29%2BChrome%252F87.0.4280.88%2BSafari%252F537.36&cookie_enabled=true&screen_width=800&screen_height=600&browser_language=&browser_platform=&browser_name=&browser_version=&browser_online=true&ac=4g&timezone_name=&appId=1233&appType=m&isAndroid=False&isMobile=False&isIOS=False&OS=windows&count=10&id=6601281089016627201&type=1&secUid=MS4wLjABAAAAKNEV4Vcuz8kAyhqmBlX3AP5fF_aR5LclGua97AbbonUnOkO1cntxK2at5ckXrOzk&maxCursor=0&minCursor=0&sourceType=8&appId=1233&region=US&priority_region=US&language=en&verifyFp=verify_kiyln3y7_3b8TVbqA_VgI8_4ZwY_9iRt_ngQTVmzw3Ek3&did=3056616273580482526&_signature=_02B4Z6wo00f01oPbhegAAIBAuDuNaVTE.RaD2qFAAP8m72

It use this api link and found something when using playwright

https://t.tiktok.com/api/item_list/?aid=1988&app_name=tiktok_web&device_platform=web&referer=&root_referer=&user_agent=Mozilla%252F5.0%2B%28iPhone%253B%2BCPU%2BiPhone%2BOS%2B12_2%2Blike%2BMac%2BOS%2BX%29%2BAppleWebKit%252F605.1.15%2B%28KHTML%2C%2Blike%2BGecko%29%2BVersion%252F13.0%2BMobile%252F15E148%2BSafari%252F604.1&cookie_enabled=true&screen_width=1017&screen_height=969&browser_language=&browser_platform=&browser_name=&browser_version=&browser_online=true&ac=4g&timezone_name=&appId=1233&appType=m&isAndroid=False&isMobile=False&isIOS=False&OS=windows&count=10&id=6601281089016627201&type=1&secUid=MS4wLjABAAAAKNEV4Vcuz8kAyhqmBlX3AP5fF_aR5LclGua97AbbonUnOkO1cntxK2at5ckXrOzk&maxCursor=1608282035000&minCursor=0&sourceType=8&appId=1233&region=US&priority_region=US&language=en&verifyFp=verify_kiyln3y7_3b8TVbqA_VgI8_4ZwY_9iRt_ngQTVmzw3Ek3&did=3253550925844519027&_signature=_02B4Z6wo00f01nwNf2QAAIBCdvzHCUajvQJ8HHvAAMDu96

**Comment by davidteather** [comment]
TikTok's site is broken when logged out go to https://www.tiktok.com/foryou and it only shows 2 TikTok's. You can try `api = TikTokApi.get_instance(use_test_endpoints=True)` and that may work for you however I'll be investigating some things later today

**Comment by davidteather** [comment]
Replicated the issue, my assumption is that selenium is being detected now. Will investigate further

**Comment by pibvbp** [comment]
anyone was able to solve this?

**Comment by tkuye** [comment]
I found a fix by using the use_test_endpoints param and that worked for me

**Comment by mathiskaddouri** [comment]
Can't make it works with Selenium, even when playing with `use_test_endpoints`. Does it's still works for someone with selenium ?

**Comment by davidteather** [comment]
Selenium deprecated
