### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: '/home/pc/tiktokbot/TikTok-Api/venv/lib/python3.9/site-packages/playwright/driver/playwright-cli'

### ISSUE THREAD

**Issue by mikegrep** [davidteather/TikTok-Api#436]
**Describe the bug**
After install tiktok api  on ubuntu 18.04 python3.9 i run on this problem after trying to set python -m playwright install

pip install playwright:
equirement already satisfied: playwright in ./venv/lib/python3.9/site-packages (0.162.2)
Requirement already satisfied: pyee>=8.0.1 in ./venv/lib/python3.9/site-packages (from playwright) (8.1.0)
Requirement already satisfied: greenlet==1.0a1 in ./venv/lib/python3.9/site-packages (from playwright) (1.0a1)
Requirement already satisfied: typing-extensions in ./venv/lib/python3.9/site-packages (from playwright) (3.7.4.3)

**Comment by davidteather** [comment]
Seems like it’s having an issue with your virtual environment I recommend checking the microsoft/playwright-python issues for help

**Comment by mikegrep** [comment]
I post a issue thank you
