### ISSUE TITLE
Script is working (thanks!) but connects through unknown ip instead of proxies. Luminati.io issue?

### ISSUE THREAD

**Issue by coder39248583** [davidteather/TikTok-Api#437]
My Luminati.io proxies have exclusivity for the tiktok.com domain. When I visit other domains, however, the connection may be routed through alternate proxies that don't have exclusivity. Is that what's happening here? Am I seeing connections to ibytedtos.com?

And finally, Is it going to negatively impact things if connections to tiktok.com and ibytedtos.com are being routed through separate IP addresses?

Thanks again for all your work!

**Comment by davidteather** [comment]
> the connection may be routed through alternate proxies that don't have exclusivity

Yeah from what I understand this is true.

> Is that what's happening here?

Not sure, the package should only be connecting through subdomains of tiktok.com the script needed from ibytedtos.com is cached in the package. You could try to add `t.tiktok.com` as a domain to be restricted on your IPs not sure how luminati.io works they might not cover subdomains

**Comment by Sanney146** [comment]
Hello @coder39248583 ,
could you post the working script? I am currently having problems with writing a working script, even though it looks right in my eyes (you can see it in my post history). Thanks!

**Comment by coder39248583** [comment]
> @davidteather 
> Not sure, the package should only be connecting through subdomains of tiktok.com the script needed from ibytedtos.com is cached in the package. You could try to add `t.tiktok.com` as a domain to be restricted on your IPs not sure how luminati.io works they might not cover subdomains

When I visit a TikTok page in my normal browser and view the network activity, the page makes numerous requests to each of the following domains (and various subdomains of each):

**tiktok.com** (html, json, mp4) (sends cookie)
**tiktokv.com** (json, octet-stream)
**tiktokcdn.com** (js, jpeg, font-woff, octet-stream, png, otf)
**byteoversea.com** (html, js, json, octet-stream) (sends cookie: MONITOR_WEB_ID & ttwid)
**ibytedtos.com** (js, mp4, octet-stream, svg, png)

I don't know how the browser in this script works, but does it make those same requests?

> @Sanney146 
> could you post the working script? I am currently having problems with writing a working script, even though it looks right in my eyes (you can see it in my post history). Thanks!

Unfortunately my script stopped working shortly after I posted here, and I tweaked it to try to get it to work, but as best I remember I originally did this:

`myproxy = "http://username:password@proxyaddress:port"
custom_did = ''.join(random.choice(string.digits) for num in range(19))
api = TikTokApi.get_instance(use_test_endpoints=True, proxy=myproxy, custom_did=custom_did)
tiktoks = api.byUsername(user, count=6, proxy=myproxy, custom_did=custom_did)`

After that stopped work (for all proxies at the same time), I replaced the custom_did with the **tt_webid_v2** values from the cookies for each given proxy, and it started working again for a short time, but then, again, all the proxies stopped working at the same time. It's like TikTok knows they're all related, somehow.

**Comment by coder39248583** [comment]
@Sanney146 wrote:
> could you post the working script? I am currently having problems with writing a working script, even though it looks right in my eyes (you can see it in my post history). Thanks!

This is working for me at the moment:

```python
api = TikTokApi.get_instance(use_test_endpoints=True, proxy=myproxy, custom_did=mycustom_did, force_verify_fp_on_cookie_header=True, custom_verifyFp=myverify)
tiktoks = api.byUsername(user, count=6, proxy=myproxy, custom_did=mycustom_did, force_verify_fp_on_cookie_header=True, custom_verifyFp=myverify)
for tiktok in tiktoks:
    videodata = api.get_Video_By_TikTok(tiktok, proxy=proxy, custom_did=mycustom_did)
```

Where:
**user** = the username of a tiktok user with a public profile
**myproxy** = "http://username:password@proxyaddress:port"
**mycustom_did** = the **tt_webid_v2** value from the cookie when I visit tiktok.com in a browser using that particular proxy
**myverify** = the **s_v_web_id** value from the cookie when I visit tiktok.com in a browser using that particular proxy

Let me know if that works for you if you can.

**Comment by davidteather** [comment]
> I don't know how the browser in this script works, but does it make those same requests?

It depends on what you're doing. If you're just requesting the json from TikTok and saving them somewhere it would just be `t.tiktok.com` or `m.tiktok.com` depending on if you have `use_test_endpoints=True`

If you're downloading videos it would probably make a request to another one of these domain names, not really sure which though. I'm assuming it would be `tiktokv.com`

**Comment by coder39248583** [comment]
Thank you for taking the time to answer. I appreciate it. :thumbsup:
