### ISSUE TITLE
[QUESTION] Is there a way to change the trending tiktok based on a logged in user?

### ISSUE THREAD

**Issue by KennyYe** [davidteather/TikTok-Api#44]
@davidteather

Everything is working fine.

But the trending tiktoks being received are ones you would see if you weren't logged into the website.  

If I log into the tiktok website, the trending content complete changes.

So is there a way to log into an account throught the API?

**Comment by davidteather** [comment]
There’s currently not a way to log into tiktok with this api. Logging in is the next logical step in this api but I can’t say for sure when it will be available if ever. 

Sorry if you really needed the logger in trending page.
