### ISSUE TITLE
[INSTALLATION] - Your error here

### ISSUE THREAD

**Issue by Lancelot-d** [davidteather/TikTok-Api#445]
**Describe the error**
Hi, I've searched a lot on the internet to solve the problem but I can't definitively install the right libraries. 
If anyone has a solution, it would be really appreciable. 

**The buggy code**

the problem appears on initialization :  self.api = TikTokApi.get_instance(use_test_endpoints=True)

**Error Trace (if any)**

laywright._types.Error: Host system is missing dependencies!

  Missing libraries are:
      libicui18n.so.66
      libicuuc.so.66
      libenchant.so.1

Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

# Error Trace Here
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - TikTokApi Version [3.8.8]

**Comment by davidteather** [comment]
You’ll need to install dependencies [here](https://github.com/microsoft/playwright/blob/master/docs/troubleshooting.md#browser-dependencies)
