### ISSUE TITLE
[BUG] - get_Video_by_TikTok error

### ISSUE THREAD

**Issue by JohnTYH** [davidteather/TikTok-Api#451]
# Read Below!!! If this doesn't fix your issue delete these two lines
**You may need to install chromedriver for your machine globally. Download it [here](https://sites.google.com/a/chromium.org/chromedriver/) and add it to your path.**

**Describe the bug**
Did tiktok change their JSON format, and thus the get_video_by_tiktok function is unable to get the download link?

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
from TikTokApi import TikTokApi
import random

api = TikTokApi.get_instance(use_test_endpoints=True)
did = str(random.randint(10000, 999999999))

results = 1
hashtag = "dance"
hashtag = api.byHashtag(hashtag, count=results, custom_verifyFp="verify_kj7i8md6_wkXuNVqx_sIb5_4Sj8_BxN3_kINCGLZyRZ6n")
data = api.get_Video_By_TikTok(hashtag, custom_did = did, custom_verifyFp='verify_kio46qzi_nTlfIUDT_kIJ0_4cNj_AIlG_BS0YkMUX1rr1')

with open("video.mp4", "wb") as out:
    out.write(data)
```

**Expected behavior**

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```
![image](https://user-images.githubusercontent.com/42569121/103178324-d20c3900-48bc-11eb-94d9-4d810fc03e1c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 [e.g. Windows 10]
 - TikTokApi Version [e.g. 3.3.1] - 3.8.8

**Additional context**

**Comment by davidteather** [comment]
You're passing in an array of a TikTok object.

Change
```
data = api.get_Video_By_TikTok(hashtag, custom_did = did, custom_verifyFp='verify_kio46qzi_nTlfIUDT_kIJ0_4cNj_AIlG_BS0YkMUX1rr1')
```

To
```
data = api.get_Video_By_TikTok(hashtag[0], custom_did = did, custom_verifyFp='verify_kio46qzi_nTlfIUDT_kIJ0_4cNj_AIlG_BS0YkMUX1rr1')
```

**Comment by JohnTYH** [comment]
@davidteather  Hi Sorry to trouble again. Using the code above, when i use 
hashtag = api.byHashtag(hashtag, count=results, custom_verifyFp="verify_kj7i8md6_wkXuNVqx_sIb5_4Sj8_BxN3_kINCGLZyRZ6n")
it returns a corrupted video. However if i add in the custom_did, it returns an empty response. I am already using api = TikTokApi.get_instance(use_test_endpoints=True) and a new verify FP. Is there any way I can fix this?
