### ISSUE TITLE
Can this script notify me when a TikTok im following posts a new video?

### ISSUE THREAD

**Issue by jmartle** [davidteather/TikTok-Api#456]
i'd like to be able to download new tiktok vids as they are being posted of the tiktokers im following

**Comment by davidteather** [comment]
The library is unable to do this. However, you could make a script to kinda do this.

Here's some pseudo code
```
list_of_tiktokers_you_follow = []

for tiktoker in list_of_tiktokers_you_follow 
  t = api.byUsername(tiktoker, count=0)[0]
  if t['createTime'] > 2 minutes ago
    notify & download
    # can either delay 2 mins or add downloaded video IDS to a list or something
```

**Comment by jmartle** [comment]
David, something i dont understand is this:

in your examples you have it as 
`api.byUsername()'

but in the [docs](https://davidteather.github.io/TikTok-Api/docs/tiktok.html#TikTokApi.tiktok.TikTokApi.by_username) the function is named `by_username()`

So, im confused, which function are you calling with `byUsername()` ?

sorry for the noob question

**Comment by davidteather** [comment]
I ended up changing the naming scheme of the methods around a month ago the preferred naming scheme is by_username now but I made this comment like 3 months ago before the naming change
