### ISSUE TITLE
[BUG] - does global proxy setting works?

### ISSUE THREAD

**Issue by tarkhil** [davidteather/TikTok-Api#457]
I attempt to use socks proxy, and write
```
api = TikTokApi.get_instance(proxy='socks5://axxxxxr:pxxxxxxxu@148.xx.xx.212:1080/')
```
but tcpdump shows direct connection.

The same is with https proxy.

Appending proxy=proxy to every TikTokApi works fine

**Comment by davidteather** [comment]
I can't seem to replicate this issue

**Comment by davidteather** [comment]
Closing because stale
