### ISSUE TITLE
Trending is broken

### ISSUE THREAD

**Issue by Xylot** [davidteather/TikTok-Api#46]
The trending function doesn't appear to be working correctly. 
When called, the browser hangs at this screen https://puu.sh/EYb34/7122b7c6f6.png and no errors are produced during the process.

**Comment by davidteather** [comment]
I imagine TikTok once again changed something and will be looking into it in the next couple of days.

**Comment by unseenthings** [comment]
Any movement on this?  I'm seeing the same thing.

**Comment by davidteather** [comment]
The API is currently broken as TikTok is detecting selenium. You may want to look at this. I believe it may still work, but I'm not completely sure.

I will be working on fixing the API in the upcoming days, but like last time there might end up being no progress.

**Comment by unseenthings** [comment]
I've gotten the basic TikTokBot to work (your other code repo) -- I believe it was an issue with the proxy that was causing this issue.  But not this yet...

Is there a way to see what content is in the proxy or moving through it?  I've tried looking at the docs for it and the code from this and the other but haven't really found anything that makes sense to me yet.

Thanks for the update, in any case.

**Comment by hackmoore** [comment]
Just wanted to bump this. Also having issues loading the trending page

**Comment by omaidf** [comment]
Looks like it's broken for me as well.

**Comment by hackmoore** [comment]
From what I can see, they're detecting artificial browsers (selenium/requests) and providing an invalid signature which fails to return useful JSON response. This causes it to never leave the loading graphic.

**Comment by yesaulov** [comment]
Guys, here is idea on how to get correct signature https://github.com/carcabot/tiktok-signature/blob/master/index.js . Trying to migrate that to python+browsermob

**Comment by davidteather** [comment]
@yesaulov  just saw your comment and am working on porting it to python right now! Thanks! A new working release should be out in a few hours.

**Comment by davidteather** [comment]
This is no longer broken. The issue has been fixed in a new update. Run the following command to upgrade.

```
pip install TikTokApi --upgrade
```

**Comment by yuvraj108c** [comment]
> This is no longer broken. The issue has been fixed in a new update. Run the following command to upgrade.
> 
> ```
> pip install TikTokApi --upgrade
> ```

Tried this, still not working
