### ISSUE TITLE
[INSTALLATION] - Error in obtaining video id

### ISSUE THREAD

**Issue by zsan605** [davidteather/TikTok-Api#462]
**Describe the error**

When I try to use the postman to simulate the request for getting video id by url, got the error.

Is there any problem with the header construction? Could someone please help to check it?

**The buggy code**

curl --location --request GET 'https://vm.tiktok.com/ZS7JaJf8/' \
--header 'authority: www.tiktok.com' \
--header 'path: /ZS7JaJf8/' \
--header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
--header 'Accept-Encoding: gzip, deflate' \
--header 'Connection: keep-alive' \
--header 'Host: www.tiktok.com' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36' \
--header 'Cookie: tt_webid_v2=7106389610798808419; tt_webid=7106389610798808419; tt_csrf_token=hHQzYevXutwDqNXN;s_v_web_id=verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq;'

**Error Trace (if any)**

```
<HTML>

<HEAD>
	<TITLE>Access Denied</TITLE>
</HEAD>

<BODY>
	<H1>Access Denied</H1>

	You don't have permission to access
	"&#47;D&#47;2047&#47;808581&#47;000&#47;www&#46;tiktok&#46;com&#47;ZS7JaJf8&#47;" on this server.<P>
		Reference&#32;&#35;18&#46;784bc817&#46;1609892510&#46;1077f834
</BODY>

</HTML>
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - TikTokApi Version [e.g. 3.3.1] - if out of date upgrade before posting an issue

**Additional context**

Put what you have already tried. Your problem is probably in the closed issues tab already.

**Comment by davidteather** [comment]
Maybe make sure your s_v_web_id has been validated by solving a captcha. beyond that, I don't know and am closing the issue because it's not related to the repo
