### ISSUE TITLE
[FEATURE_REQUEST] - Account Names of Commenters

### ISSUE THREAD

**Issue by ETedward** [davidteather/TikTok-Api#463]
**Requested Feature**
Hi! I'm wondering if it's possible to get a feature that scrapes the account names of commenters for an inputted Tiktok.
(or if there is already a function that does this). Would be incredibly helpful!

**Additional context**
One of the use cases is after finding a Tiktok related to recruiting for a right wing extremist group, with hundreds of commenters, would like to be able to scrape the account handles of the commenters for Open Source Investigation / OSINT purposes.

**Comment by davidteather** [comment]
This is something I'd like to implement in the future however right now it's not added because it requires a user login.

**Comment by davidteather** [comment]
Stale
