### ISSUE TITLE
RuntimeError: Cannot run the event loop while another loop is running

### ISSUE THREAD

**Issue by alvesdavidr** [davidteather/TikTok-Api#465]
I submitted #198  - I'm not sure if it fixes this issue, but I did run it in a discord bot with
```
@bot.command()
async def tiktok(ctx: commands.Context, link: str):
    video = api.getTikTokByUrl(link)["itemInfo"]["itemStruct"]["video"]
    print(video)
```
_Originally posted by @crazygmr101 in https://github.com/davidteather/TikTok-Api/issues/115#issuecomment-663991704_

*The Problem:*
Much like the quote referenced, I am trying to utilize the TikTokApi within an async function for Discordpy. However, I am running into trouble with multithreading, as it appears that both Discordpy and TikTokApi both use playwright and therefore the same loop.

For the purposes of this problem, my code is exactly the same as above, with api initialized at the top of the file before a client.run(TOKEN) call for Discordpy is called. All I want is for this async function to fetch some TikTok data.

*Attempted Solutions:*
So far, I've attempted:
- initializing TikTokApi within the async def function
- initializing TikTokApi outside the async def function and using a global variable
- trying both .is_instance() and .is_instance(use_selenium=True)

**Comment by davidteather** [comment]
> trying both .is_instance() and .is_instance(use_selenium=True)

Do you mean get_instance?

**Comment by alvesdavidr** [comment]
> > trying both .is_instance() and .is_instance(use_selenium=True)
> 
> Do you mean get_instance?

Yes, I meant get_instance().

**Comment by davidteather** [comment]
The following code works for me
```
import discord
from discord.ext import commands

from TikTokApi import TikTokApi
api = TikTokApi.get_instance(use_test_endpoints=True, custom_verifyFp="verify_adjaksdjakwj", use_selenium=True)
bot = commands.Bot(command_prefix='>')


@bot.command()
async def ping(ctx):
    data = api.trending()
    await ctx.send(data[0]['author']['uniqueId'])

bot.run('token')
```

![image](https://user-images.githubusercontent.com/34144122/104787456-36504900-5755-11eb-95e5-7aeec42df5a0.png)


Selenium seems to be getting detected so you might see that it sent back invalid json see #434 

[discord.py](https://github.com/Rapptz/discord.py/blob/master/requirements.txt) does not use playwright

**Comment by davidteather** [comment]
#576
