### ISSUE TITLE
[INSTALLATION] - Playwright missing dependencies

### ISSUE THREAD

**Issue by P3rs3ph0ne** [davidteather/TikTok-Api#467]
When launched for the first time the programm returns an error from Playwright, some libraries are missing, however when we try to install them an other error opens up saying that the version doesn't satisfied Playwright

"playwright._types.Error: Host system is missing dependencies!

  Missing libraries are:playwright._types.Error: Host system is missing dependencies!

  Missing libraries are:
      libicui18n.so.66
      libicuuc.so.66
      libgstcodecparsers-1.0.so.0
      libjpeg.so.8
      libenchant.so.1
      libGLESv2.so.2

Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs."
```

**Comment by 42musaev** [comment]
Is there a solution?

**Comment by P3rs3ph0ne** [comment]
> Is there a solution?

I don't know... i've tried numerous things, but none of them works, so i assumed i was gonna use selenuim. however tiktok on web browser (even with agent changer) doesn't allow webscraping.
so if someone has a solution it would be cool

**Comment by davidteather** [comment]
You need to install the dependencies for playwright's browser

You can find their [Dockerfile](https://github.com/microsoft/playwright-python/blob/master/Dockerfile) and install some of the apt get stuff if you're on ubuntu.

If you're on CentOS playwright isn't supported you'll need to use selenium `TikTokApi.get_instance(use_selenium=True)`

**Comment by rdfsx** [comment]
> You need to install the dependencies for playwright's browser
> 
> You can find their [Dockerfile](https://github.com/microsoft/playwright-python/blob/master/Dockerfile) and install some of the apt get stuff if you're on ubuntu.
> 
> If you're on CentOS playwright isn't supported you'll need to use selenium `TikTokApi.get_instance(use_selenium=True)`

but there is no longer a Dockerfile
