### ISSUE TITLE
[BUG] Only #funny works when calling search_by_hashtag

### ISSUE THREAD

**Issue by Xylot** [davidteather/TikTok-Api#47]
The webdriver gets stuck on any hashtags I search apart from funny. No errors are produced during the process.

**Comment by Archoza** [comment]
> The webdriver gets stuck on any hashtags I search apart from funny. No errors are produced during the process.
Have the same problem, also dont working get_trending_hashtags() returns empty list

**Comment by davidteather** [comment]
@Archoza The get_trending_hashtags() method is deprecated as TikTok no longer shows trending hashtags on their homepage. This may be fixed in a future update, but as of now, it is not working.

As for the issue, I imagine TikTok once again changed something and will be looking into it in the next couple of days.

**Comment by Archoza** [comment]
Checked search_by_sound() method, the same situation. Run() closed without errors.

**Comment by Archoza** [comment]
Method search_by_sound() 4 hours ago worked good, but atm it is broken too. Complete without errors.

**Comment by Xylot** [comment]
> @Archoza The get_trending_hashtags() method is deprecated as TikTok no longer shows trending hashtags on their homepage. This may be fixed in a future update, but as of now, it is not working.

In the meantime it might be useful to at least parse out the songs and hashtags from https://www.tiktok.com/discover and supply the user with those through functions like get_discover_hashtags and get_discover_songs

**Comment by Sergey-S-Lebedev** [comment]
Seems like chrome can't load TikTak page at all, neither in case of trending, neither in case of hasgtags.

**Comment by davidteather** [comment]
The API is currently broken as TikTok is detecting selenium. You may want to look at this. I believe it may still work, but I'm not completely sure.

I will be working on fixing the API in the up coming days.
