### ISSUE TITLE
Eror using getHashtag

### ISSUE THREAD

**Issue by chicken-afk** [davidteather/TikTok-Api#471]
Hi david, I tried getHashtag method but it gave me error with statusCode = 0

Here's my code

from TikTokApi import TikTokApi
import pandas as pd
api = TikTokApi.get_instance(use_selenium=True, use_test_endpoints=True)
results = 10
hashtag = 'funny'
trending = api.byHashtag(hashtag, count=results)

Error:

ERROR:root:TikTok response: {statusCode: 0,body: {userData: {},statusCode: -1,shareUser: {}}} 
ERROR:root:Converting response to JSON failed
ERROR:root:Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by davidteather** [comment]
Related to #434
