### ISSUE TITLE
ISO2 geo code parameter for trending data

### ISSUE THREAD

**Issue by eburmicz** [davidteather/TikTok-Api#474]
**Is your feature request related to a problem? Please describe.**
I would like to know if there are any parameters we could utilize to change the way in which we search for data.
For instance, in the api call for e.g. trending data there are a number of references in the call  to the 'US' region e.g. region=US and priority_region=US. Do any of these affect the TIkTok data and can we have a setting to pass these to the api?

For instance I didn't find much in the way of #sea shanty trending data where I am in the UK, which was frontline promoted by TikTok. This comes as a surprise to me - perhaps it isn't over there in the US and is possibly a function of geolocation?

**Describe the solution you'd like**
A parameter to make a call with different ISO2 code call to the API

**Comment by davidteather** [comment]
From what I’ve observed the region parameter doesn’t affect the data returned. (At least a few months ago when I checked it). It’s possible they’ve changed it. 

I believe it’s tied to geolocation IP not region parameter.

**Comment by eburmicz** [comment]
OK so if I use a proxy, does the proxy need to be in the same format used by the 'requests' package i.e. as a dict with http and https proxy IPs?

**Comment by eburmicz** [comment]
I think I can just provide a string to the proxy param.

Have you any tips for using proxies with your lib?

I am having issues with captchas and forbidden requests. I logged in via the proxy and then grabbed the customfp id - it worked once and then I got hit with a captcha second time round.

**Comment by davidteather** [comment]
Use a paid proxy and have multiple proxies chosen from
