### ISSUE TITLE
[INSTALLATION] - Problems with installation in Docker

### ISSUE THREAD

**Issue by 42musaev** [davidteather/TikTok-Api#475]
Please tell me how to run this project in the container created on the python3.8 image (using selenium)

This is my docker file:
```
FROM python:3.8

RUN apt update && apt install -y postgresql-client

RUN pip install uwsgi pipenv==2020.11.15

WORKDIR /opt/code/

COPY Pipfile Pipfile.lock ./

RUN pipenv install --system --deploy --dev

COPY . /opt/code/

CMD ["uwsgi", "./code/uwsgi.ini"]
```
Please tell me how to run this package in this image.

**Comment by davidteather** [comment]
Look at [playwright-python](https://github.com/microsoft/playwright-python/blob/master/Dockerfile)'s dockerfile for reference
