### ISSUE TITLE
[BUG] - byUsername / PlayAddr is not working (Access Denied)

### ISSUE THREAD

**Issue by kaan0nder** [davidteather/TikTok-Api#476]
When I run byUsername method, I get everything correct except playAddr and DownloadAddr.

```
api = TikTokApi.get_instance(request_delay=SLEEP,use_test_endpoints=True,custom_did=custom_did)

            tiktoks = api.byUsername(username=username, count=self.count,
                                     custom_verifyFp=custom_verifyFp)
```

Code gives me playAddr as : 

https://v16-web.tiktok.com/video/tos/useast2a/tos-useast2a-pve-0068/968adca40bf34080a69ece94d289dbf1/?a=1988&br=1878&bt=939&cd=0%7C0%7C1&ch=0&cr=0&cs=0&cv=1&dr=0&ds=3&er=&expire=1611596686&l=20210125114436010234093134211248A7&lr=tiktok_m&mime_type=video_mp4&pl=0&policy=2&qs=0&rc=M3V3OmR3b204MzMzOjczM0ApZ2k7PGk0NTszN2c5OTc5PGcvaHBzLWhfbjRgLS1iMTZzcy8wMDEwYzEtLjQ2MjIzYTM6Yw%3D%3D&signature=cde4e316fe23f48ce395c3820119678e&tk=tt_webid_v2&vl=&vr=

If you enter this, you will see **You don't have permission to access "http://p16-sign-sg.tiktokcdn.com/obj/tos-alisg-p-0037/c28ffc0ffa4240b4b51cc54d1e31d6fd?" on this server.** or **no video with supported format and MIME type found**. How can I fix this ?

**Comment by Nick-Gottschlich** [comment]
Did some experimentation here. If I go to the tiktok.com site we can view the src of the video being played, see:

![image](https://user-images.githubusercontent.com/10564265/105795766-ff4b1600-5f52-11eb-8a2e-2c8014ce791d.png)

This url is: `https://v16-web.tiktok.com/video/tos/useast2a/tos-useast2a-ve-0068c004/21945dbfefbf475fb65150c0da432b4d/?a=1988&br=1760&bt=880&cd=0%7C0%7C1&cr=0&cs=0&cv=1&dr=0&ds=3&er=&expire=1611652637&l=20210126031618010189066018342FE282&lr=tiktok_m&mime_type=video_mp4&pl=0&policy=2&qs=0&rc=amp2cnlpZmR1eTMzPDczM0ApZ2dmODg8OTw5NzdoOTM1ZWdoLzJtYV5fNGFfLS1hMTZzc18wYDNgYi42YjEvMi5iLl46Yw%3D%3D&signature=9ecffdab3a0789ce2c807fa64782b766&tk=tt_webid_v2&vl=&vr=`

And running the api call to the same account, the playAddr that gets returned is:

`https://v16-web.tiktok.com/video/tos/useast2a/tos-useast2a-ve-0068c004/21945dbfefbf475fb65150c0da432b4d/?a=1988&br=1760&bt=880&cd=0%7C0%7C1&cr=0&cs=0&cv=1&dr=0&ds=3&er=&expire=1611652219&l=202101260309200101902092165F2FF3C7&lr=tiktok_m&mime_type=video_mp4&pl=0&policy=2&qs=0&rc=amp2cnlpZmR1eTMzPDczM0ApZ2dmODg8OTw5NzdoOTM1ZWdoLzJtYV5fNGFfLS1hMTZzc18wYDNgYi42YjEvMi5iLl46Yw%3D%3D&signature=6dd2cde397fe13f64fb580e5b1ab54f2&tk=tt_webid_v2&vl=&vr=`

Comparing it looks like the expire token is different:

`expire=1611652637&l=20210126031618010189066018342FE282`

vs

`expire=1611652219&l=202101260309200101902092165F2FF3C7`


and the signature is different

`signature=9ecffdab3a0789ce2c807fa64782b766`

vs

`signature=6dd2cde397fe13f64fb580e5b1ab54f2`

I managed to access the tiktok video as a downloadable html5 video once but now I am continually getting that `no video with supported format and MIME type found`. Maybe tiktok is working towards making it more difficult to download videos.

**Comment by llacb47** [comment]
Of course the signature is different, every time you refresh the page it changes, you are not saying anything helpful here.

**Comment by kaan0nder** [comment]
@Nick-Gottschlich  Strange thing is that I can download the video as bytes. But URL is not working. Really interesting...

**Comment by Nick-Gottschlich** [comment]
> Of course the signature is different, every time you refresh the page it changes, you are not saying anything helpful here. 

Okay? Just trying to experiment with TikTok downloads and see what I find. Are you going to provide a solution yourself or just spend your time being rude to strangers online?

> @Nick-Gottschlich  Strange thing is that I can download the video as bytes. But URL is not working. Really interesting...

That is interesting! Any chance you are willing to share some of your code showing how you did that? I'm curious how you managed to get the file download to work with python.

**Comment by siongui** [comment]
@Nick-Gottschlich I have similar findings as you.

The json data embedded in __NEXT_DATA__ script tag in the page HTML is different by real-man browser viewing and by program. If you use chrome view-source and visit the playAddr embedded in the json data, it works without problem.

I am still trying to find out the difference of HTTP request made by program and by real-man browser viewing. If any findings, I will post here.

**Comment by davidteather** [comment]
Should be working now! I didn't realize the global custom_did was not being set. Should be working now though

**Comment by Sarvar05** [comment]
not working again
