### ISSUE TITLE
How to run the API in FastAPI / in a testing environment

### ISSUE THREAD

**Issue by jaoxford** [davidteather/TikTok-Api#479]
Hi there.

We are trying to add some testing around the API interactions. Namely `getUser`.

We are doing something like this within a FastAPI endpoint.
```python
tik_tok_api = TikTokApi.get_instance()
return tik_tok_api.getUser(handle)
```
This is fine when making this call from the `requests` library. However, when running from FastAPI docs page. Or the FastAPI test client. The response is `Can only run one Playwright at a time.`

Any ideas?

**Comment by jaoxford** [comment]
We figured it out. Pickled the results from the API & set up mocking with a return value which equals the pickle.

**Comment by davidteather** [comment]
> issue with playwright only being able to run once

Does it work now with the latest release? There was some bug fix with playwright running in multitudes resolved. Might still be a threading issue

**Comment by jaoxford** [comment]
I haven't checked since I posted the issue. Will get back to you when I try it.

**Comment by davidteather** [comment]
Think it's a playwright issue
