### ISSUE TITLE
[INSTALLATION] - Unable to run via jupyter notebook

### ISSUE THREAD

**Issue by singhdevshree** [davidteather/TikTok-Api#481]
**_Trying this code:_**
from TikTokApi import TikTokApi
import string
import random
from selenium import webdriver

driver = webdriver.Chrome()
did=''.join(random.choice(string.digits) for num in range(19))

qwe=TikTokApi(use_selenium=True)
feed  = qwe.getUserFeed(qwe.getUser('vtkh2004'), '0')

print(feed)

**_Put the error trace here.

**_I get following error:_**_**
Message: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"F88C5895ED4D52F71FD1414A51B7DDEC","isDefault":true,"type":"default"},"id":1,"name":"","origin":"://"}
  (Session info: chrome=87.0.4280.141)
  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Windows NT 10.0 x86_64)
Message: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"F88C5895ED4D52F71FD1414A51B7DDEC","isDefault":true,"type":"default"},"id":1,"name":"","origin":"://"}
  (Session info: chrome=87.0.4280.141)
  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Windows NT 10.0 x86_64)

Please insert the code that is throwing errors or is giving you weird unexpected results.

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - TikTokApi Version [e.g. 3.3.1] - if out of date upgrade before posting an issue

**Additional context**

Put what you have already tried. Your problem is probably in the closed issues tab already.

**Comment by davidteather** [comment]
probably also related to #576

**Comment by sucduit** [comment]
Hi, David. I am new to this. I tried to run the code in Jupyter notebook. For from TikTokApi import tiktokapi, I got " no module named TikTokApi". I pip install it. How can I fix it?
