### ISSUE TITLE
Comment endpoint signature?

### ISSUE THREAD

**Issue by h4ck1th4rd** [davidteather/TikTok-Api#486]
Hi,

I just wonder how to generate comment endpoint _signature= key for a successful comment via Web API based.

Thank you,
regards.

**Comment by kilua626** [comment]
I've written a node js web server to generate signature for any endpoints required for tiktok web version, sucessfully have posted comments via many tiktok accounts with signature, and surely every of those comments can be seen by others

**Comment by kilua626** [comment]
For a simple test:(some sensitve arguments hidden)
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"url":"https://www.tiktok.com/comment/publish", "referer":"https://www.tiktok.com/", "ua":"ua"}' \
  http://120.55.164.73:8888/api/sign

**Comment by h4ck1th4rd** [comment]
> http://120.55.164.73:8888/api/sign

This is a false information, and over repo bug. Stop promoting your private shit over here.

**Comment by kilua626** [comment]
Why false? It has been working properly! Stop personal attack!OK ?

**Comment by kilua626** [comment]
API docs in more detail below:
http://120.55.164.73:8888/api-docs#/sign/post_api_sign

**Comment by h4ck1th4rd** [comment]
> Why false? It has been working properly! Stop personal attack!OK ?

We don't want your private tools, We want a solution.  Show me codes not private API! 

Note you still promoting your shit over here.

**Comment by kilua626** [comment]
U shit!

**Comment by h4ck1th4rd** [comment]
Solved it.
