### ISSUE TITLE
[BUG] - 2GB in my docker container

### ISSUE THREAD

**Issue by kaan0nder** [davidteather/TikTok-Api#487]
Hi @davidteather ,

When I run this api in my docker server, the image of the file is nearly 2GB. Do we have a chance to reduce it to maybe 400-500 MB ?

**Comment by jaoxford** [comment]
My guess is that all of the dependencies of Playwright & Selenium take up space.

**Comment by davidteather** [comment]
You could probably cut down the 

`FROM mcr.microsoft.com/playwright:focal` release from them although it's not my first priority right now although 2gb is pretty unreasonable
