### ISSUE TITLE
Problem with getuser

### ISSUE THREAD

**Issue by pedrosallun** [davidteather/TikTok-Api#488]
The TikTok desktop had an update and now the API is not working properly anymore. The code getuser is not working anymore

**Comment by AlessandroSpallina** [comment]
same issue here

**Comment by davidteather** [comment]
Please provide your code I tested this yesterday and it was working correctly for me.

**Comment by pedrosallun** [comment]
from TikTokApi import TikTokApi
import pandas as pd

api = TikTokApi()

__author__ = "Jack Bandy"


def simple_dict(tiktok_dict):
    to_return = {}
    to_return["user_name"] = tiktok_dict["author"]["uniqueId"]
    to_return["user_id"] = tiktok_dict["author"]["id"]
    to_return["video_id"] = tiktok_dict["id"]
    to_return["video_desc"] = tiktok_dict["desc"]
    to_return["video_time"] = tiktok_dict["createTime"]
    to_return["video_length"] = tiktok_dict["video"]["duration"]
    to_return["video_link"] = "https://www.tiktok.com/@{}/video/{}?lang=en".format(
        to_return["user_name"], to_return["video_id"]
    )
    to_return["n_likes"] = tiktok_dict["stats"]["diggCount"]
    to_return["n_shares"] = tiktok_dict["stats"]["shareCount"]
    to_return["n_comments"] = tiktok_dict["stats"]["commentCount"]
    to_return["n_plays"] = tiktok_dict["stats"]["playCount"]
    return to_return


# posted by user
n_videos = 300
username = "pedrosallun_"


user_videos = api.byUsername(username, count=n_videos, proxy=None)
user_videos = [simple_dict(v) for v in user_videos]

user_videos_df = pd.DataFrame(user_videos)
user_videos_df.to_csv("{}_videos.csv".format(username), index=False)

**Comment by KonradJanica** [comment]
Changing the `api = TikTokApi()` line to the one instructed in this [video](https://www.youtube.com/watch?t=117&v=zwLmLfVI-VQ&feature=youtu.be&ab_channel=DavidTeather) worked for me.

**Comment by AlessandroSpallina** [comment]
i still have the problem, my purpose is to get my follower list

here the code with getUser method not working: https://0bin.net/paste/XxffU8tL#Qy9AfD1S3li5GjRfJDkX0D9kUthwGbRnq-X7QrOxZmf

**Comment by AlessandroSpallina** [comment]
@davidteather

**Comment by davidteather** [comment]
@AlessandroSpallina Try to add the `use_test_endpoints=True` on the constructor for TikTokApi as shown [here](https://www.youtube.com/watch?t=117&v=zwLmLfVI-VQ&feature=youtu.be&ab_channel=DavidTeather) it doesn't check that the verifyFp is valid as much
