### ISSUE TITLE
Interpretation of JSON files: Heart, Digg, Like

### ISSUE THREAD

**Issue by civicmachines** [davidteather/TikTok-Api#489]
Hi,

Question; The returned JSON file of a video or an author contains among others following fields: HeartCount, Heart, DiggCount, liked. These values seem to overlap many times. Can somebody explain me what they are representing exactly? 

Thanks a lot!

**Comment by davidteather** [comment]
I personally think it might just be a legacy backward compatibility thing for them. As far as I know, they should be the same
