### ISSUE TITLE
[BUG] userPosts() does not return posts

### ISSUE THREAD

**Issue by modelarious** [davidteather/TikTok-Api#49]
Requesting user's posts do not seem to respond when requesting using `api.userPosts(username="username")`

**buggy code**
```
import requests
import random
import string
import urllib.request
import glob
import os
import mimetypes
from TikTokApi import TikTokapi

api = TikTokapi("browsermob-proxy-2.1.4/bin/browsermob-proxy")
print(api.userPosts(username="levelsofpiano"))
```

**Expected behavior**

I would assume a JSON response describing the posts made by the user "levelsofpiano".

**Actual behavior**

Browser loads user's page, but does not load the user's posts.

**Screenshots**

<img width="1613" alt="Screen Shot 2020-01-12 at 9 53 41 AM" src="https://user-images.githubusercontent.com/22161638/72222398-7a48b680-3521-11ea-903a-ed03498dce69.png">

**Desktop (please complete the following information):**
 - OS: OSX 10.12.5
 - Browser: Chrome
 - Version: 79.0.3945.117
 - browsermob version 2.1.4
 - Chrome driver matches Chrome version

**Additional context**

No errors are produced on the console.  I left it running for a good 20 minutes and got no response, so it's safe to say that the program hangs on this command.

**Comment by davidteather** [comment]
The API is currently broken as TikTok is detecting selenium. You may want to look at [this](https://github.com/davidteather/TikTok-Api/releases/tag/V2.2.0). I believe it may still work, but I'm not completely sure. 

I will be working on fixing the API in the up coming days.
