### ISSUE TITLE
['itemInfo']['itemStruct']['video']['downloadAddr']解析的地址403错误

### ISSUE THREAD

**Issue by qbsencom** [davidteather/TikTok-Api#490]
比如目标页面：https://www.tiktok.com/@gordonramsayofficial/video/6910298199769009414

通过Tiktok-api 解析出的地址为：
['itemInfo']['itemStruct']['video']['downloadAddr'] ：
https://v16-web.tiktok.com/video/tos/useast2a/tos-useast2a-pve-0068/963654528533482d8c866df9ec4c38ff/?a=1988&br=2458&bt=1229&cd= 。。。。
该地址好像是错误的。

通过其他方法解析到的地址为：
https://v77.tiktokcdn.com/c5131308bacd840942c996860db437a5/60194de7/video/tos/useast2a/tos-useast2a-pve-0068/bacc3e2097b54451a165972fc13e3cc7/?a=1180&br=2472&bt=1236&cd=。。。。
这个地址可以下载。

这种地址又是怎么获得的？

**Comment by qbsencom** [comment]
`def get_video_no_watermark(self, video_url, return_bytes=1, **kwargs) -> bytes:
....
        # Thanks to @HasibulKabir for pointing this out on #448
        #cleanVideo = (
        #        "https://api2-16-h2.musical.ly/aweme/v1/play/?video_id={}&line=0&ratio=default"
        #        "&media_type=4&vr_type=0"
        #).format(tiktok_html['itemInfo']['itemStruct']['video']['id'])

        cleanVideo = tiktok_html['itemInfo']['itemStruct']['video']['downloadAddr']
        self.text_save(cleanVideo,'video_downloadAddr.txt',mode='a+')
`

**Comment by qbsencom** [comment]
test.py:
from TikTokApi import TikTokApi

#api = TikTokApi.get_instance(use_test_endpoints=True)
api = TikTokApi.get_instance(proxy='127.0.0.1:19180')
data = api.get_video_no_watermark('https://www.tiktok.com/@gordonramsayofficial/video/6910298199769009414?lang=en')
with open("test.mp4", "wb") as out:
    out.write(data)

![微信图片_20210202161403](https://user-images.githubusercontent.com/50788466/106572010-d76f3a00-6572-11eb-8de9-372c03089b2d.png)

**Comment by mandyshen** [comment]
I have the same issue with you. Have you solved the issue? The download address doesn't work when I used get_Video_By_DownloadURL.

**Comment by davidteather** [comment]
Downloading videos should be fixed

**Comment by tuanvn91** [comment]
can anyone tells me the solution to fix this issue
