### ISSUE TITLE
[INSTALLATION] - Google Colab - Could not find a version that satisfies the requirement playwright

### ISSUE THREAD

**Issue by idilkylmz** [davidteather/TikTok-Api#491]
**I can't install package in google colab**

I'm trying this

**!pip install TikTokApi**

And get this

```
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from TikTokApi) (2.23.0)
ERROR: Could not find a version that satisfies the requirement playwright (from TikTokApi) (from versions: none)
ERROR: No matching distribution found for playwright (from TikTokApi)
```

**Desktop**
 - OS: [Linux mint]

**Comment by gdelaserre** [comment]
same issue here, it seems that the playwright library needs to be installed too although not sure how to translate this command in Google Colab

`pip install TikTokApi
python -m playwright install
`

**Comment by gdelaserre** [comment]
Ah, my Google Colab runs Python 3.6.9 Playwright requires Python 3.7+.

**Comment by idilkylmz** [comment]
> Ah, my Google Colab runs Python 3.6.9 Playwright requires Python 3.7+.

Hi Guillaume, how can I change colab's python version?

**Comment by davidteather** [comment]
Not sure if it's changed but [stackoverflow](https://stackoverflow.com/questions/54010692/google-colab-choosing-specific-python-version)

**Comment by mathigatti** [comment]
Hi, I don't know if it helps but [here](https://colab.research.google.com/drive/1SM6getpK7R4uVER54_fl4rJLTjkOdGru#scrollTo=Tgmh-r4oIsH1) I made a working colab for TikTok-Api

**Comment by idilkylmz** [comment]
> Hi, I don't know if it helps but [here](https://colab.research.google.com/drive/1SM6getpK7R4uVER54_fl4rJLTjkOdGru#scrollTo=Tgmh-r4oIsH1) I made a working colab for TikTok-Api

Hi, thank you very much. It helps a lot.

**Comment by idilkylmz** [comment]
> > Hi, I don't know if it helps but [here](https://colab.research.google.com/drive/1SM6getpK7R4uVER54_fl4rJLTjkOdGru#scrollTo=Tgmh-r4oIsH1) I made a working colab for TikTok-Api
> 
> Hi, thank you very much. It helps a lot.



> Hi, I don't know if it helps but [here](https://colab.research.google.com/drive/1SM6getpK7R4uVER54_fl4rJLTjkOdGru#scrollTo=Tgmh-r4oIsH1) I made a working colab for TikTok-Api

Do you know how can I write the output into a csv file?

**Comment by mathigatti** [comment]
Yes, using pandas is the simplest way. I updated the notebook, check the code now.
