### ISSUE TITLE
[INSTALLATION] - Your error here

### ISSUE THREAD

**Issue by Seospectr** [davidteather/TikTok-Api#493]
C:\Users\Admin\Desktop\TikTok-Api-master\TikTok-Api-master\examples>python getTr
ending.py
ERROR:root:TikTok response:
Traceback (most recent call last):
  File "getTrending.py", line 10, in <module>
    trending = api.trending(results)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\TikTokApi\tiktok.py", line 336, in trending
    res = self.getData(url=api_url, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\TikTokApi\tiktok.py", line 213, in getData
    ) from None
TikTokApi.exceptions.EmptyResponseError: Empty response from Tiktok to https://m
.tiktok.com/api/item_list/?aid=1988&app_name=tiktok_web&device_platform=web&refe
rer=&root_referer=&user_agent=Mozilla%252F5.0%2B%28iPhone%253B%2BCPU%2BiPhone%2B
OS%2B12_2%2Blike%2BMac%2BOS%2BX%29%2BAppleWebKit%252F605.1.15%2B%28KHTML%2C%2Bli
ke%2BGecko%29%2BVersion%252F13.0%2BMobile%252F15E148%2BSafari%252F604.1&cookie_e
nabled=true&screen_width=1287&screen_height=1484&browser_language=&browser_platf
orm=&browser_name=&browser_version=&browser_online=true&ac=4g&timezone_name=&app
Id=1233&appType=m&isAndroid=False&isMobile=False&isIOS=False&OS=windows&count=20
&id=1&secUid=&maxCursor=0&minCursor=0&sourceType=12&appId=1233&region=US&priorit
y_region=US&language=en&verifyFp=verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8
zIJTq&did=3190342746506554213&_signature=_02B4Z6wo00f01nNLczgAAIBCebrLV1REeppzWn
eAAPzY41

**Comment by KonradJanica** [comment]
This can be fixed by following the instructions in this video: https://www.youtube.com/watch?t=117&v=zwLmLfVI-VQ&feature=youtu.be&ab_channel=DavidTeather
