### ISSUE TITLE
[FEATURE_REQUEST] - Compatibility with playwright 1.8

### ISSUE THREAD

**Issue by ek8terina** [davidteather/TikTok-Api#497]
Maybe this has been fixed already, but I couldn't find any open issues about this, sorry for any repeats!

I had some issues with using the TikTok API package on Mac OS 11.2 recently after having not used it since early December and kept getting executable path errors even though everything should have been working ([like this](https://github.com/microsoft/playwright/issues/4722)) and it seems like the problem was that the playwright I was running (0.171.1. ) was not compatible with newest Mac OS Big Sur because I then updated to [1.8.0a1](https://pypi.org/project/playwright/1.8.0a1/#migration-from-the-pre-release-versions) (pip install playwright==1.8.0a1) and it started working. I had to update the TikTok API package I was running in order to make it compatible with the newest playwright (see the previous link).

**Describe the solution you'd like**
It would be cool to have an update to fix this without having to do it manually.

**Describe alternatives you've considered**
Selenium or keeping the pre-release playwright probably work just fine as is, just couldn't get either to work on recent mac OS

**Additional context**
Has anyone else using mac OS Big Sur run into this problem and had to do this fix? Happy to explain what fix worked for me in more detail if it's been a problem for anyone else.

**Comment by AnaKuzina** [comment]
Hi, @ek8terina! Can you please tell me how do you solve the issue with playwright? When I did
`pip3 install playwright==1.8.0a1`

I've got this error: 
`cannot import name 'sync_playwright' from 'playwright'`

**Comment by davidteather** [comment]
It's a pretty simple fix on my end, although I'm hesitant to set the playwright requirement to be a pre-release.

You can easily fix this by replacing `from playwright import sync_playwright` with `from playwright.sync_api import sync_playwright` in both tiktok.py and browser.py

**Comment by boscacci** [comment]
Which version of playwright should we really be using for compatibility? I tried `1.8.0a1` and `0.171.1` without success.  I've pip installed the latest version of playwright and forked TikTokApi to implemented those little changes for my immediate purposes, seems like it's working so far

**Comment by stefvanhouten** [comment]
I had the same error and using the solution you provided above yields the following:

`
Traceback (most recent call last):
  File "C:\Users\stef\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\stef\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "D:\devel\uweb_test\scraper\Tiktok.py", line 3, in <module>
    api = TikTokApi.get_instance()
  File "D:\devel\uweb_test\scraper\env\lib\site-packages\TikTokApi\tiktok.py", line 89, in get_instance
    TikTokApi(**kwargs)
  File "D:\devel\uweb_test\scraper\env\lib\site-packages\TikTokApi\tiktok.py", line 56, in __init__
    self.browser = browser(**kwargs)
  File "D:\devel\uweb_test\scraper\env\lib\site-packages\TikTokApi\browser.py", line 81, in __init__
    raise e
  File "D:\devel\uweb_test\scraper\env\lib\site-packages\TikTokApi\browser.py", line 77, in __init__
    self.browser = get_playwright().webkit.launch(
TypeError: launch() got an unexpected keyword argument 'handleSIGINT'
`

**Comment by jacopocecch** [comment]
> I had the same error and using the solution you provided above yields the following:
> 
> `Traceback (most recent call last): File "C:\Users\stef\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 183, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "C:\Users\stef\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 109, in _get_module_details __import__(pkg_name) File "D:\devel\uweb_test\scraper\Tiktok.py", line 3, in <module> api = TikTokApi.get_instance() File "D:\devel\uweb_test\scraper\env\lib\site-packages\TikTokApi\tiktok.py", line 89, in get_instance TikTokApi(**kwargs) File "D:\devel\uweb_test\scraper\env\lib\site-packages\TikTokApi\tiktok.py", line 56, in __init__ self.browser = browser(**kwargs) File "D:\devel\uweb_test\scraper\env\lib\site-packages\TikTokApi\browser.py", line 81, in __init__ raise e File "D:\devel\uweb_test\scraper\env\lib\site-packages\TikTokApi\browser.py", line 77, in __init__ self.browser = get_playwright().webkit.launch( TypeError: launch() got an unexpected keyword argument 'handleSIGINT'`

Same problem on MacOS 11.2.1

**Comment by stefvanhouten** [comment]
I see this issue is also discussed in #506. Seems like there is no sollution as of now.

**Comment by stefvanhouten** [comment]
Downgrading to playwright 0.171.1 seems to do the trick.

**Comment by jacopocecch** [comment]
@stefvanhouten I get this error now:

```
Traceback (most recent call last):
  File "/Users/jacopo/Documents/Tesi/getTrending.py", line 1, in <module>
    from TikTokApi import TikTokApi
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/TikTokApi/__init__.py", line 1, in <module>
    from TikTokApi.tiktok import TikTokApi
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/TikTokApi/tiktok.py", line 7, in <module>
    from playwright.sync_api import sync_playwright
ImportError: cannot import name 'sync_playwright' from 'playwright.sync_api' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playwright/sync_api.py)
```

**Comment by davidteather** [comment]
Hey this issue has been resolved in the latest release. Make sure to upgrade both playwright and TikTokApi the following command will do it for you
`pip install TikTokApi playwright --upgrade`
