### ISSUE TITLE
[FEATURE_REQUEST] - Get s_v_web_id value with Selenium

### ISSUE THREAD

**Issue by kenara** [davidteather/TikTok-Api#499]
In the Quick Start Guide I read

> In your web browser you will need to go to TikTok, Log in and get the s_v_web_id value.

So, I have not even installed or tried TikTok-Api yet, but it seemed like we could just get this with Selenium (I've never used Playwright)

I noticed in Chrome that there are two sets of cookies in TikTok, one for tiktok.com and another for www.tiktok.com, and it is the latter that contains s_v_web_id.

My first try, using `cookies = driver.get_cookies()` failed to retrieve the www.tiktok.com cookies. 

But adding a `sleep(3)` to my function, these other cookies are returned and I was able to get the s_v_web_id value using 
`    cookie = driver.get_cookie('s_v_web_id').get('value')`

As I write this, I'm not in a position to test TikTok-Api, but is there any reason why this cookie can't be added automatically when running the program?

**Comment by MarcoLavoro** [comment]
Hi i am not an expert and i need to get the s_v_web_id.
Can you tell me how to do it with ubuntu?

Thanks in any case for your time :)

**Comment by davidteather** [comment]
You may add this to your TikTokApi to automate the process, however, they are throttled and sometimes need captcha solves mainly when the `test_api_endpoints=True` is not set.

**Comment by bo-tadpol** [comment]
@kenara would you be willing to share example code that allowed you to grab cookies programmatically?

**Comment by kenara** [comment]
Here's what worked for me. But as @davidteather warns, it won't do much good if TikTok Inc. doesn't cooperate. 
`
	# -*- coding: utf-8 -*-
	from selenium import webdriver
	chromedriver = "/usr/local/bin/chromedriver"
	from time import sleep

	def get_tiktok_cookie():
	    options = webdriver.ChromeOptions()
	    options.add_argument('--ignore-certificate-errors')
	    options.add_argument("--test-type")
	    options.add_argument("--headless")
	    options.add_argument("--test-type")
	    options.add_argument("--no-sandbox")
	    options.add_argument("--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36")
	    options.binary_location = "/usr/bin/google-chrome-stable"
	    driver = webdriver.Chrome(chromedriver, chrome_options=options)
	    url = 'https://www.tiktok.com/'
	    driver.get(url)
	    time.sleep(3)
	    cookie = driver.get_cookie('s_v_web_id').get('value')
	    return cookie
`
