### ISSUE TITLE
[BUG] - Empty response from Tiktok

### ISSUE THREAD

**Issue by jaoxford** [davidteather/TikTok-Api#503]
I am trying to call the `byUser` API endpoint with either

```
tik_tok_api = TikTokApi.get_instance()
tik_tok_api.byUsername(handle, 1)
```

Or 
```
tik_tok_api = TikTokApi.get_instance(use_selenium=True)
return tik_tok_api.byUsername(handle, 1)
```
Both of these give me the error `Empty response from Tiktok to https://m.tiktok.com/api/item_list/?aid=1988&app_name=tiktok_web&device_platform=web&referer=&root_referer=&user_agent=Mozilla%252F5.0%2B%28iPhone%253B%2BCPU%2BiPhone%2BOS%2B12_2%2Blike%2BMac%2BOS%2BX%29%2BAppleWebKit%252F605.1.15%2B%28KHTML%2C%2Blike%2BGecko%29%2BVersion%252F13.0%2BMobile%252F15E148%2BSafari%252F604.1&cookie_enabled=true&screen_width=1168&screen_height=1449&browser_language=&browser_platform=&browser_name=&browser_version=&browser_online=true&ac=4g&timezone_name=&appId=1233&appType=m&isAndroid=False&isMobile=False&isIOS=False&OS=windows&count=1&id=6747935906352907269&type=1&secUid=MS4wLjABAAAAv3zolJLlWp-WbKXqSZwVSflDdwcbjPADRG-dhb68k30dQjkFpkRs4HiMvWeeIyVv&maxCursor=0&minCursor=0&sourceType=8&appId=1233&region=US&priority_region=US&language=en&verifyFp=verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq&did=9097006475678094878&_signature=_02B4Z6wo00f01Ulb0UgAAIBDdvNPPswkFIlJStXAADKA23`

Any thoughts on how to fix this? It seems that this API endpoint is broken. And I would like to be able to retrieve TikToks for a given handle.

Is there a possibility that TikTok is blocking requests from us now that there have been too many?

Is there some kind of workaround for this by logging in to TikTok and doing something with VerifyFP (I saw this in other issues).

**Comment by azharmunir43** [comment]
@jaoxford you should try specifying custom_verifyFp param to both calls. I can see from the URL that the default value is used.

`tik_tok_api = TikTokApi.get_instance()
tik_tok_api.byUsername(handle, 1, custom_verifyFp='')`

value for this param can be extracted by logging into our tiktok account using browser and looking for cookies.

![image](https://user-images.githubusercontent.com/14857206/108388673-acead580-7230-11eb-9dce-8bc1246851c2.png)

**Comment by jaoxford** [comment]
@azharmunir43 And if you provide `verifyFp` into the API call it's much more reliable than without?

**Comment by azharmunir43** [comment]
@jaoxford yes as per some recent developments at TikTok's end, we need to specify. I read that in getting started docs [here](https://github.com/davidteather/TikTok-Api#getting-started)

**Comment by jaoxford** [comment]
Thanks. I'll give it a shot!

**Comment by marcelogrsp** [comment]
I am passing the `custom_verifyFp` argument but still getting the same error:

```
    api = TikTokApi.get_instance(use_selenium=True)
    proxyApi = '84.21.188.73:8607'

   data = api.bySound('6764055872055281665', proxy=proxyApi, custom_verifyFp = "verify_d6...73")
```
