### ISSUE TITLE
[INSTALLATION] - Docker file doesn't 

### ISSUE THREAD

**Issue by AnaKuzina** [davidteather/TikTok-Api#506]
I did

`git clone this_repository`

then I made 

`cd TikTok-Api`

and run following command 

`docker build . -t tiktokapi:latest`

Then I run 

`docker run -v TikTokApi --rm tiktokapi:latest python3 my_file.py`

**my_file.py** is placed in the same directory as **Dockerfile** but I've got this error

`python3: can't open file 'my_file.py': [Errno 2] No such file or directory`

Please tell me what did i do wrong? Thanks

PS. there is a really **BIG problem** with newer version of playwright. It doesn't work because it is `from playwright.sync_api import sync_playwright` now. But if I change it in TikTokApi folders in tiktok.py and browser.py I've got an error...

**Comment by davidteather** [comment]
> What am I doing wrong?

My guess is that you created my_file.py after you created the docker container. 

> here is a really BIG problem with newer version of playwright.

Their pypi release is still on the old code seems like they've been refractoring the code for about a month. Utilize version 0.171.1 from pypi until they release a new update.

**Comment by AnaKuzina** [comment]
I've tried this, but then I've got this error and I don't really know what to do with this:

`    tik_tok_api = TikTokApi.get_instance()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 90, in get_instance
    TikTokApi(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 57, in __init__
    self.browser = browser(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/TikTokApi/browser.py", line 83, in __init__
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/TikTokApi/browser.py", line 79, in __init__
    self.browser = get_playwright().webkit.launch(
TypeError: launch() got an unexpected keyword argument 'handleSIGINT'`

Thank you for your help!

**Comment by davidteather** [comment]
I'm going to move this issue to #502 as the docker container might be messed up right now

**Comment by AnaKuzina** [comment]
Thank you! I will create new file. What should I do with the 

`TypeError: launch() got an unexpected keyword argument 'handleSIGINT` ?

Thank you for your help!

**Comment by davidteather** [comment]
Not really sure what the solution to that is right now, my guess is maybe something weird with playwright. What was your code in my_file.py

**Comment by AnaKuzina** [comment]
It is not related to my code, because even if I use code from **Quick Start Guide** there is still this issue.
