### ISSUE TITLE
Looks like the options be override at this line.

### ISSUE THREAD

**Issue by FavorMylikes** [davidteather/TikTok-Api#515]
https://github.com/davidteather/TikTok-Api/blob/02a3ffdc48735e6991a81ebeeb3a4f46f65d8546/TikTokApi/browser_selenium.py#L28-L35

**Comment by davidteather** [comment]
Yep, this is intended so that you can set them by using the browser_args param from the line above what you highlighted `args = kwargs.get("browser_args", [])`
