### ISSUE TITLE
how to get a correct x-signature

### ISSUE THREAD

**Issue by thewoz** [davidteather/TikTok-Api#516]
Hi,
I have a list of video link previously saved in the following format:

https://p77-sign-sg.tiktokcdn.com/obj/tos-maliva-p-0068/f7c128e9235d44868591b4f1771c3360_1586091718?x-expires=1613397600&x-signature=qPHNNUjatu%2BL3OWF96rh7ve6sts%3D

If I try to download it I will get a 403 error.
Checking the video's link on the Tiktok page I saw that the link has changed.

https://p77-sign-sg.tiktokcdn.com/obj/tos-maliva-p-0068/f7c128e9235d44868591b4f1771c3360_1586091718?x-expires=1614733200&x-signature=rtsHOyJ5iK6uFXOgzMJ108abEbo%3D

from what I understand the "expires" field is the unix-timestamps and I can change it accordingly.
but what about the "x-signature" field?

some one can help?

**Comment by davidteather** [comment]
To download a video you'll need to make sure the custom_did field is the same for the request and download. You can find more information in a YouTube video linked on the readme

**Comment by khoubeibouthour** [comment]
@thewoz did you get an answer to this?

**Comment by baqmxdsny** [comment]
I also have the same problem, how to solve the video thumbnail expiration problem, how to fake x-signature
