### ISSUE TITLE
Documentation on Trending videos needed

### ISSUE THREAD

**Issue by ialiman** [davidteather/TikTok-Api#518]
Hello, I cannot locate any documentation pertaining to what page you are scraping when calling the getTrending method. The reason this is important is that, while the results seem plausible, I cannot reproduce any of the results when I am using the iOS app. Tried several configurations (new user, friend as user, me as user) and I am not seeing the same results. 

- Is there documentation on the trending method, and if so, kindly provide.
-

**Comment by davidteather** [comment]
There is no getTrending method on this package it’s just trending. There is no iOS app run by me (the author of this package). Please contact the app developer with any questions

**Comment by ialiman** [comment]
my apologies.  Still, what page/module is trending() scraping? Thank you!

**Comment by davidteather** [comment]
https://www.tiktok.com/foryou?lang=en
