### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ariel042cohen** [davidteather/TikTok-Api#52]
Do you know how can I get video views count? I only see on the api likes count, shares count and comment count.

**Comment by davidteather** [comment]
The view count is not included in the server response to fetching the TikTok.  You may want to look at [this](https://github.com/davidteather/TikTok-Api/releases/tag/V2.2.0) version of the ap. It could be modified pretty easily to support view count. That version of the API probably also still works unlike the current version.
