### ISSUE TITLE
API Support for sending and receiving messages

### ISSUE THREAD

**Issue by senic35** [davidteather/TikTok-Api#53]
Hi. Are you planning on adding API support for sending and receiving messages? Would this even be possible? Thanks for your response.

**Comment by davidteather** [comment]
It may be possible in the future, as I would like to add logging into an account in the future, but it's not my main focus as right now the api is broken.

**Comment by jayayy** [comment]
Hi Is there any update to this after 5 years? I cannot see any entry in the developer guide for direct messaging using tiktok
