### ISSUE TITLE
Posting video's

### ISSUE THREAD

**Issue by quintendewilde** [davidteather/TikTok-Api#535]
Would video posting be possible for this project?

I would like to make an automated daily poster with content that's added to a folder automatically. 

Or is this beyond the scope for this API?

**Comment by davidteather** [comment]
It's currently impossible with the api but it's something I'd like to implement in the future

**Comment by megapro17** [comment]
> It's currently impossible with the api but it's something I'd like to implement in the future

You checked https://github.com/AeonLucid/AndroidNativeEmu?

**Comment by davidteather** [comment]
> You checked https://github.com/AeonLucid/AndroidNativeEmu?

No, it seems too resource expensive and if I were to implement this feature I would use the web app uploading endpoint

**Comment by megapro17** [comment]
> No, it seems too resource expensive and if I were to implement this feature I would use the web app uploading endpoint

But it is reliable method that can't be fixed by tiktok easily. External endpoint only for those who need these methods?

**Comment by davidteather** [comment]
> But it is reliable method that can't be fixed by tiktok easily. External endpoint only for those who need these methods?

Feel free to open a PR making use of the tool for uploading videos preferably in a separate class and file

**Comment by kilua626** [comment]
I’ve dev an app to post comment successfully via web api endpoints,I believe posting videos also possible

**Comment by sutyrin** [comment]
@davidteather thanks for great software, it's of great use! 

Video posting seems to be possible via web for quite a long time already, what's needed to extend api that way?

**Comment by davidteather** [comment]
> what's needed to extend the api to work that way?

Supporting user login in the library and there might be a different way to sign those urls.

**Comment by davidteather** [comment]
Stale issue
