### ISSUE TITLE
[FEATURE_REQUEST] - Getting analytics of your own tiktok page

### ISSUE THREAD

**Issue by 8auu** [davidteather/TikTok-Api#536]
**Is your feature request related to a problem? Please describe.**
Currently we are managing a large number of tiktok pages, and it would be very handy to be able to gather insights on the mass amount of videos we post. 

**Describe the solution you'd like**
It would be amazing if it was possible to return a number of views for each video, or use the tiktok analytics page to gather views.

**Comment by davidteather** [comment]
Videos views should be included in the TikTok dictionary the package returns should be under the stats key

**Comment by davidteather** [comment]
Would have to be logged in to see tiktok analytics page, but worksarounds for just public views
