### ISSUE TITLE
[BUG] - cannot switch to a different thread

### ISSUE THREAD

**Issue by mjh-jason** [davidteather/TikTok-Api#537]
Multiple user cookies cannot be used at the same time

**Comment by davidteather** [comment]
Please provide example code

**Comment by mjh-jason** [comment]
> Please provide example code

Sorry, I have solved it. Thank you very much
But I want to ask you another question：
“"TikTok blocks this request displaying a Captcha \nTip: Consider using a proxy or a custom_verifyFp as method parameters"”


My code：
from TikTokApi import TikTokApi
from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route('/method', methods=['POST'])
def method():
    content = request.json
    user = content.get("user")
    api = TikTokApi.get_instance(custom_verifyFp = user,external_signer="http://127.0.0.2:5000/sign",use_test_endpoints=True)
    method = request.json.get("method")
    params = request.json.get("params", {})
    aaa = getattr(api,method,None)
    if aaa is None:
        return jsonify(code=201, data=[], err_msg="Method does not exist")
    else:
        try:
            result = aaa(**params)
            # api.clean_up()
            return jsonify(code=200, data=result)
        except Exception as err:
            err_msg = str(err)
            return jsonify(code=201, data=[], err_msg=err_msg)



if __name__ == '__main__':
    app.run(debug=False,port=5001)

**Comment by mjh-jason** [comment]
When I call a method ‘by_username’，I'll report this error

**Comment by davidteather** [comment]
If you're making too many requests TikTok will show a captcha, use random verifyFps and proxies and that's the most you can do. the by_username method also makes an HTML call which does require proxies to get around. You can try the other methods if you have a secUid & userId already

**Comment by mjh-jason** [comment]
> If you're making too many requests TikTok will show a captcha, use random verifyFps and proxies and that's the most you can do. the by_username method also makes an HTML call which does require proxies to get around. You can try the other methods if you have a secUid & userId already

OK, thank you very much
