### ISSUE TITLE
[FEATURE_REQUEST] - Get Followers List

### ISSUE THREAD

**Issue by tman915** [davidteather/TikTok-Api#538]
Would it be possible to have something that returns a list of your followers?

Infohats has something like this but it only returns about 200 results:

https://api.infohats.com/api-docs/#/Data%20from%20TikTok/get_live_user_follower_list

**Comment by llacb47** [comment]
Impossible, not implemented in the web API

**Comment by davidteather** [comment]
Would be apart of #120
