### ISSUE TITLE
[BUG] "Exception: Could not locate user/hashtag ID: Tried 10 times"

### ISSUE THREAD

**Issue by Giuliagiorgi** [davidteather/TikTok-Api#54]
Hi, thank you for your time and effort in this.

I tried to run the various examples scripts you provided, only getTrending.py works. The other raises the exception in the title ("Exception: Could not locate user/hashtag ID: Tried 10 times"), as if the id was None.
The same with scripts written by me, only trending works fine.

Using:
- Python: 3.7
- OS: Windows 10
- Browser: Firefox 72.0.2 (64 bit)

**Comment by hiamlegend** [comment]
Getting the same error. Hi @davidteather any update on this please?

**Comment by davidteather** [comment]
The API is currently broken as TikTok is detecting selenium. You may want to look at this. I believe it may still work, but I'm not completely sure.

I will be working on fixing the API in the upcoming days.
