### ISSUE TITLE
[BUG] - search_for_music and search_for_users methods does not return results

### ISSUE THREAD

**Issue by nikolamajmunovic** [davidteather/TikTok-Api#543]
**Describe the bug**

search_for_music and search_for_users methods do not return results, always empty arrays

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
TikTokApi.get_instance().search_for_music('say so', 5)

TikTokApi.get_instance().search_for_users('baka prase', 5)
```

**Expected behavior**

To get 5 songs or users, regarding the method we are using.

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
No trace error
```

**Desktop (please complete the following information):**
 - OS: [macOS Mojave]
 - TikTokApi Version [3.9.4]

**Comment by davidteather** [comment]
Fixed now update your package with `pip install TikTokApi --upgrade` see #549 for the Pr that fixed it
