### ISSUE TITLE
Is this API support like and follow?

### ISSUE THREAD

**Issue by gunomnifluencer** [davidteather/TikTok-Api#55]
Hello,

Just ask can I use this API to follow and to like their 3 last post?

thanks

**Comment by webqart** [comment]
I have a ready-made solution, write to telegram @peppa100

**Comment by davidteather** [comment]
This API does not currently support this function or even logging in as a function at all. I would like to add logging in the future of this project, but that's not my main focus as of now because the API is broken.

**Comment by gunomnifluencer** [comment]
Hello,
Thanks for reply,

If not objection, could you give me some tutorial how to create API like this? So that, probably I can help you to develop this API. To be honest I really need tiktok API to like and follow, for some experiment. 

I would appreciate it

Many Thanks.
