### ISSUE TITLE
[BUG] - byUsername

### ISSUE THREAD

**Issue by alzeric** [davidteather/TikTok-Api#550]
**Describe the bug**

byUsername throws a list index out of range error

**The buggy code**

```
api = TikTokApi.get_instance()
userData = api.byUsername('belleryanooo52', count=10)
```

**Expected behavior**

Return user

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
(This is the tail end of it... appears to be printing out the entire html in the console)
```
              // Check that service workers are supported
              if ('serviceWorker' in navigator) {
              // Use the window load event to keep the page load performance
              window.addEventListener('load', function() {
                navigator.serviceWorker.register('/sw.js').catch(function() {
                  console.log('Service worker registration failed');
                });
              });
            }
            </script></html>
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\TikTokApi\tiktok.py", line 1209, in get_user
    j_raw = t.split(
IndexError: list index out of range

During handling of the above exception, another exception occurred:
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - TikTokApi Version: 3.9.4

**Additional context**

**Comment by alzeric** [comment]
Couple things

1.) They've added a nonce attribute to all <script and <link tags (gets assigned in the <head tag
2.) secUid has been moved to the jsonldList object


This quick fix will get things back up and running...
**get_user function**
`t = r.text

        try:
            nonce_start = '<head nonce="'
            nonce_end = '">'
            nonce = t.split(nonce_start)[1].split(nonce_end)[0]
            j_raw = t.split(
                '<script id="__NEXT_DATA__" type="application/json" nonce="%s" crossorigin="anonymous">' % nonce
            )[1].split("</script>")[0]`

**Comment by MuffinFox** [comment]
fix for all functions parsing script tag content: https://github.com/MuffinFox/TikTok-Api/commit/57fefee960498e73704de4949602244b9cc29d5a
