### ISSUE TITLE
Max retries exceeded

### ISSUE THREAD

**Issue by ravi35663** [davidteather/TikTok-Api#552]
api = TikTokApi.get_instance(use_test_endpoints=True, use_selenium=True)
tiktoks = api.by_username("officialraveenatandon", count=5000)
print(tiktoks)

HTTPSConnectionPool(host='tiktok.com', port=443): Max retries exceeded with url: /@officialraveenatandon?lang=en (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1091)')))

OS ubuntu 16.04

**Comment by zbtzero7** [comment]
I also got the same issue, have you  been able to solve this? @ravi35663 
TTPSConnectionPool(host='tiktok.com', port=443): Max retries exceeded with url..

**Comment by christ0224** [comment]
same issue,have you solved it?

**Comment by ravi35663** [comment]
In some countries TikTok is banned . You can use VPN to run this API .
My issue is resolved  by doing this .

**Comment by ravi35663** [comment]
@zbtzero7  and @felixwann  hope this will resolve your issues if tiktok is banned in your country .

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
