### ISSUE TITLE
[BUG] - Your Error Here

### ISSUE THREAD

**Issue by nikolamajmunovic** [davidteather/TikTok-Api#553]
**Describe the bug**

Method discover_music fail, get an error.

**Expected behavior**

To get a list of the songs.

**Error Trace (if any)**

```
ERROR:root:TikTok response: {statusCode: 0,body: [{ exploreList: [] },{ exploreList: [] },{ exploreList: [] },]}\nERROR:root:Converting response to JSON failed\nERROR:root:Expecting property name enclosed in double quotes
```

**Desktop (please complete the following information):**
 - OS: [MacOS Mojave]
 - TikTokApi Version [3.9.5]

**Comment by davidteather** [comment]
See #434
