### ISSUE TITLE
[BUG] - by_username() function not working

### ISSUE THREAD

**Issue by omkar2810** [davidteather/TikTok-Api#554]
**Describe the bug**

While using the API, the by_username() method throws an error and is unable to scrape the user timeline.

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
# Code Goes Here

from TikTokApi.tiktok import TikTokApi
custom_verifyFp = 'verify_kmceg6q6_PBtL1C8n_Gzvg_46bO_BsAj_pcuRDPbUE3II'
did = "".join(random.choice(string.digits) for num in range(19))
api = TikTokApi.get_instance(custom_verifyFp=custom_verifyFp, custom_did=did, use_test_endpoints=True, use_selenium=True)
tiktoks = api.by_username("scottsreality", count=5000)
```

**Expected behavior**

The function should return the timeline of the user with the given username.

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here

 "TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters"
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version 3.9.4

**Additional context**

**Comment by alzeric** [comment]
Make sure you're updated to the latest version of TikTokAPI 
https://github.com/davidteather/TikTok-Api/pull/551

(Not sure the version incremented with that fix)

**Comment by davidteather** [comment]
Yep you're on package version 3.9.4 latest is 3.9.5

Also selenium is kinda bugged playwright gets detected less
