### ISSUE TITLE
is it possible to view my private liked photos via API?

### ISSUE THREAD

**Issue by callahanmccarthy** [davidteather/TikTok-Api#558]
Trying to list my liked photos using this, but they're private and I don't want to make them public. is there a way to login/use a cookie to be able to do that?

**Comment by davidteather** [comment]
This package currently does not support any login of a TikTok user

**Comment by kilua626** [comment]
I’ve dev an app to post comment using cookies exported from browsers, an app to auto login via browsers, an app to auto register accounts and a Nodejs api server to calc endpoint signatures
