### ISSUE TITLE
error with web driver

### ISSUE THREAD

**Issue by gunomnifluencer** [davidteather/TikTok-Api#56]
Hello, 
What webdriver you actually used on your api?

if gecko / firefox why I got message when I run : example/getTrending.py,

> 
> C:\xampp\htdocs\tiktokpy\examples>python getTrending.py
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
>     self.process = subprocess.Popen(cmd, env=self.env,
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "getTrending.py", line 4, in <module>
>     api = TikTokapi("C:/xampp/htdocs/tiktokpy/browsermob/bin/browsermob-proxy.bat", headless=False)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 53, in __init__
>     self.driver = webdriver.Chrome(chrome_options=chromeProfile)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
>     self.service.start()
>   File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
>     raise WebDriverException(
> selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

how to resolve this error?

**Comment by Quintenvw** [comment]
download your chrome browser's version of chromedriver.exe and add it to the path you're using.

**Comment by davidteather** [comment]
Yeah, Quintenvw is correct you have to make sure you have chromedriver installed and added to your path. There's specific installation instructions in the readme file.
