### ISSUE TITLE
It does not support mobile links [BUG] - Your Error Here

### ISSUE THREAD

**Issue by KsKurly** [davidteather/TikTok-Api#561]
When I copy the link from the desktop it works fine, but if I copy the link on mobile it says can't support url.

![image](https://user-images.githubusercontent.com/82128838/114578260-bb5ed780-9c4a-11eb-9a56-7d6f4b3bb1b8.png)

![image](https://user-images.githubusercontent.com/82128838/114578394-d3365b80-9c4a-11eb-8adb-8e0c8f94d3a9.png)

 - OS: [Windows 10]
 - TikTokApi Version 3.9.5

**Comment by alzeric** [comment]
This is not a bug

Currently the get_tikotk_by_url function only supports Web URLs not Mobile URLs

This if statement in particular explains why it's erroring out on you.
`        if "@" in url and "/video/" in url:
            post_id = url.split("/video/")[1].split("?")[0]
        else:
            raise Exception(
                "URL format not supported. Below is an example of a supported url.\n"
                "https://www.tiktok.com/@therock/video/6829267836783971589"
            )`

**Comment by alzeric** [comment]
Here is a workaround you can do.... (Keep in mind i'm not 100% certain on all the variations of Mobile URLs so you may need to adjust and add more checks to the new IF statement

```
    def get_tiktok_by_url(self, url, **kwargs) -> dict:
        """Returns a dictionary of a TikTok object by url.


        Parameters
        ----------
        url: The TikTok url you want to retrieve
            This currently doesn't support the shortened TikTok
            url links.
        """
        (
            region,
            language,
            proxy,
            maxCount,
            did,
        ) = self.__process_kwargs__(kwargs)
        kwargs["custom_did"] = did
        custom_did = kwargs.get("custom_did", None)
        if "@" in url and "/video/" in url:
            post_id = url.split("/video/")[1].split("?")[0]
        elif "//vm." in url:
            r = requests.get(
                url,
                allow_redirects=True
            )
            if "/v/" in r.url:
                post_id = r.url.split("/v/")[1].split("?")[0].split(".")[0]
            else:
                raise Exception(
                    "URL format not supported. Below is an example of a supported url.\n"
                    "https://m.tiktok.com/v/6949654648684907781.html"
                )
        else:
            raise Exception(
                "URL format not supported. Below is an example of a supported url.\n"
                "https://www.tiktok.com/@therock/video/6829267836783971589"
            )

        return self.getTikTokById(
            post_id,
            **kwargs,
        )
```
