### ISSUE TITLE
[BUG] - Your Error HereTikTokApi.exceptions.TikTokNotFoundError: TikTok returned a response indicating the entity is invalid

### ISSUE THREAD

**Issue by tarkhil** [davidteather/TikTok-Api#562]
# Read Below!!! If this doesn't fix your issue delete these two lines
**You may need to install chromedriver for your machine globally. Download it [here](https://sites.google.com/a/chromium.org/chromedriver/) and add it to your path.**

Every request yields an error

```
    userPosts = api.userPosts( author['user_id'], author['unique_id'], count=3000 )
```

**Expected behavior**

Serveral days ago, it returned a list of posts

**Error Trace (if any)**

```
Traceback (most recent call last):
  File "load_videos.py", line 58, in <module>
    userPosts = api.userPosts( author['user_id'], author['unique_id'], count=3000 )
  File "/home/tarkhil/.local/share/virtualenvs/tiktok-80xSTSAj/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 547, in user_posts
    res = self.getData(url=api_url, **kwargs)
  File "/home/tarkhil/.local/share/virtualenvs/tiktok-80xSTSAj/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 262, in get_data
    raise TikTokNotFoundError(
TikTokApi.exceptions.TikTokNotFoundError: TikTok returned a response indicating the entity is invalid

```

**Desktop (please complete the following information):**
 - OS:Ubuntu 18.04.5 LTS
 - TikTokApi Version 3.9.5

**Additional context**

Looks like they've changed it again

**Comment by davidteather** [comment]
Not sure what your author variable object looks like but the following code is working for me.

```
author = api.trending()[0]['author']
user_posts = api.user_posts( author['uniqueId'], author['secUid'], count=3000 )
```
