### ISSUE TITLE
TikTok Sound Summary Count

### ISSUE THREAD

**Issue by eburmicz** [davidteather/TikTok-Api#565]
Is there a way to get the summary statistic for a TikTok sound, i.e. how many total sounds there currently are. This would be mega helpful for tracking changes over time.

**Comment by davidteather** [comment]
See [get_music_object_full](https://davidteather.github.io/TikTok-Api/docs/tiktok.html#TikTokApi.tiktok.TikTokApi.get_music_object_full)

**Comment by eburmicz** [comment]
Thanks David.
