### ISSUE TITLE
Using TikTokApi on Raspberry Pi4 does not work because of playwright-python

### ISSUE THREAD

**Issue by smoshsimp** [davidteather/TikTok-Api#568]
playwright-python does not currently work on raspberry pi 4s with webkit

https://github.com/microsoft/playwright-github-action/issues/33

There is a dockerfile for chromium working on raspberry pi4s and playwright-python, but the TikTokApi appears to require more than just that browser. https://github.com/glops/playwright-rpi4

Is there a way to adjust how playwright-python is used in the TikTokApi to allow for raspberry pi 4 compatibility?

Thankyou!

**Comment by akorchyn** [comment]
hi, any updates on this?

**Comment by akorchyn** [comment]
> hi, any updates on this?

Playwright officially supports pi starting from 1.17, but you have to use docker-container for it Ubuntu 20.04 ARM64.

**Comment by davidteather** [comment]
^ docker is probably your best bet
