### ISSUE TITLE
just a dummy question relating TikTok Api @davidteather

### ISSUE THREAD

**Issue by mediaBuzzz** [davidteather/TikTok-Api#57]
Hi @davidteather, I'm a newbie on coding, spending pretty much time a day on learning python. Currently, I have a task to set up an application on my website that would be able to interact with the TikTok users' content. Like a user of my website would enter his/her username and the application displays his/her TikTok posts, then the user, let's say, chooses some of his/her posts and I get links to the posts that the user would have chosen. 

So the question is can your TikTok-API help somehow on the task I currently have. And yes, I know this is pretty dummy and is just a pain in the ass but every single help or hint is highly appreciated. Thanks in advance.

**Comment by davidteather** [comment]
Yeah my Api is unable to help with that. It doesn’t support users logging into tiktok at the moment and is NOT a very efficient solution and you would need a massive amount of servers.

**Comment by mediaBuzzz** [comment]
do you have any source that would help with my task? I mean any tutorial, github topic, anything.
