### ISSUE TITLE
[FEATURE_REQUEST] - Adding "verify" as a parameter in the requests.

### ISSUE THREAD

**Issue by bmader12** [davidteather/TikTok-Api#571]
When using proxy servers some require to pass a "verify=False" into the request.get() statement.

Currently verify is not passed into the requests statement, this does not allow me to use a proxy.
Let me know if there another way around this.

**Comment by dylancaponi** [comment]
@davidteather This can be closed. Thank you!

Working for me with:
```
    api = TikTokApi.TikTokApi.get_instance(
        custom_verifyFp=custom_verifyfp,
        use_test_endpoints=True,
        requests_extra_kwargs={"verify": False}
    )
```

**Comment by davidteather** [comment]
See #577 just released the new version with this capability
