### ISSUE TITLE
[BUG] - by_hashtag and get_hashtag_object both fail when using Selenium

### ISSUE THREAD

**Issue by bmader12** [davidteather/TikTok-Api#572]
**Describe the bug**
When using selenium, at least  by_hashtag and get_hashtag_object fail. 
If Selenium is not used, these two objects work as expected it is just when Selenium=True. 
Changing out proxies, use_test_endpoints, custom_verifyFp doesn't seem to impact the response.

According to the error trace, TikTok responds with a useless string:
 {statusCode: 0,body: {userData: {},statusCode: -1,shareUser: {}}} 

Running this on a VM and testing locally on windows 10, which is why I am using Selenium, not the other option. 

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
import requests
from TikTokApi import TikTokApi
import logging

custom_verifyFp= 'value here'

api = TikTokApi.get_instance(use_selenium=True, use_test_endpoints=True)
r = api.by_hashtag('MyNeutrogenaMoment', count=30, custom_verifyFp=ip)
print(r)
```

**Error Trace (if any)**

```
ERROR:root:TikTok response: {statusCode: 0,body: {userData: {},statusCode: -1,shareUser: {}}} 
ERROR:root:Converting response to JSON failed
ERROR:root:Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\TikTokApi\tiktok.py", line 264, in get_data
    json = r.json()
  File "C:\Anaconda\lib\site-packages\requests\models.py", line 889, in json
    return complexjson.loads(
  File "C:\Anaconda\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Anaconda\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

**Desktop (please complete the following information):**
 - OS: windows 10
 - TikTokApi Version 3.9.5

**Additional context**

**Comment by davidteather** [comment]
Selenium has been getting detected for awhile unfortunately I haven't been able to solve it.
