### ISSUE TITLE
[BUG] - get_recommended_tiktoks_by_video_id is not working 

### ISSUE THREAD

**Issue by hyex** [davidteather/TikTok-Api#573]
**Describe the bug**

`get_recommended_tiktoks_by_video_id` function is not working

**The buggy code**

```
from TikTokApi import TikTokApi

api = TikTokApi()

videos = api.getRecommendedTikToksByVideoID('6948902431724014853')
print(videos)
```

**Expected behavior**

Print recommended TikTok video list 

**Error Trace (if any)**
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    videos = api.getRecommendedTikToksByVideoID('6948902431724014853')
  File "/Library/Python/3.8/site-packages/TikTokApi/tiktok.py", line 1008, in get_recommended_tiktoks_by_video_id
    maxCursor = res["maxCursor"]
KeyError: 'maxCursor'
```

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - TikTokApi Version  3.9.5

**Additional context**

I think it might have something to do with #520, could you check it?
Thank you.

**Comment by davidteather** [comment]
Looks like they changed the structure to stop using cursors and are instead using hasMore which is what they've been using on the more common endpoints for some time now. I should be able to fix it in at most ~2 weeks I got finals coming up but should find some time in the next few days
