### ISSUE TITLE
[FEATURE_REQUEST] - Option to use playwright async api

### ISSUE THREAD

**Issue by GreenCobalt** [davidteather/TikTok-Api#576]
**Is your feature request related to a problem? Please describe.**
Trying to use this api with a discord bot which requires it to be inside an async function. playwright says that I need to use the async api but I can't find an option to switch to it.

**Describe the solution you'd like**
Add async support for playwright

**Describe alternatives you've considered**
well there pretty much are none.

**Additional context**
not really any

**Comment by Mikami382** [comment]
Bump. 
This needs to happen, I need to use async so that it the API won't block other running procceses.

**Comment by ldantas05** [comment]
Bump.
The discord API does not really give me any other choice than to use Async

**Comment by davidteather** [comment]
V6 fully async
