### ISSUE TITLE
[FEATURE_REQUEST] - query on view count not trending

### ISSUE THREAD

**Issue by testuser22323** [davidteather/TikTok-Api#581]
It seems that the statistics are limited to either a unique id search or whats on the trending tab. Im looking to pull top n video id's by view count, is this a solution that can be added as a function?

**Comment by davidteather** [comment]
Don't think you can do this from the website or even the app as far as I'm aware so I don't think this is possible. If someone can link how to view this elsewhere on the mobile or web app I'll reopen.
