### ISSUE TITLE
Can't connect to Browsermob-Proxy

### ISSUE THREAD

**Issue by marco-ita** [davidteather/TikTok-Api#59]
**Describe the bug**

Followed all your instruction but still getting the following an error

**The buggy code**

`from TikTokApi import TikTokapi

# Starts T
api = TikTokapi("/Applications/Anaconda/anaconda3/lib/python3.7/site-packages/browsermob-proxy/bin/browsermob-proxy")

# The Number of trending TikToks you want to be displayed
results = 10
trending = api.trending(results)

for tiktok in trending:
    # Prints the text of the tiktok
    print(tiktok['itemInfos']['text'])

print(len(trending))
api.quit_browser()`

**Error**

`---------------------------------------------------------------------------
ProxyServerError                          Traceback (most recent call last)
<ipython-input-52-ebb48f4e1bea> in <module>
      2 
      3 # Starts T
----> 4 api = TikTokapi("/Applications/Anaconda/anaconda3/lib/python3.7/site-packages/browsermob-proxy/bin/browsermob-proxy")
      5 
      6 # The Number of trending TikToks you want to be displayed

/Applications/Anaconda/anaconda3/lib/python3.7/site-packages/TikTokApi/tiktok.py in __init__(self, browsermobDirectory, headless, manualSignature)
     25             path=browsermobDirectory, options=dictf)
     26         # "browsermob-proxy/bin/browsermob-proxy"
---> 27         self.server.start()
     28         time.sleep(1)
     29         self.proxy = self.server.create_proxy()

/Applications/Anaconda/anaconda3/lib/python3.7/site-packages/browsermobproxy/server.py in start(self, options)
    125             if count == retry_count:
    126                 self.stop()
--> 127                 raise ProxyServerError("Can't connect to Browsermob-Proxy")
    128 
    129     def stop(self):

ProxyServerError: Can't connect to Browsermob-Proxy`

**Desktop (please complete the following information):**
 - OS: [macOS Mojave 10.14.6]
 - Browser [chrome]
 - Version [79.0.3945.130 (Official Build) (64-bit)]

**Additional context**

Downloaded all the files that you recommend including browsermob (and created the right folder) and also geckodriver

Spent hours and still cant get it to work.
Thanks.

**Comment by davidteather** [comment]
It’s definitely an issue with your path you’re using a absolute path you might want to try relative path to your executive file if it’s not working.  

Currently the api isn’t working so there’s issues behind connecting to browsermob.
