### ISSUE TITLE
[BUG] - Playwright AttributeError

### ISSUE THREAD

**Issue by YeYuDao** [davidteather/TikTok-Api#591]
```
from TikTokApi.tiktok import TikTokApi
import random
import string

if __name__ == '__main__':
    custom_verifyFp = 'verify_komqqc0y_kK6lAKPF_628t_4c72_80Ph_Oet624Z3G6KR'
    did = "".join(random.choice(string.digits) for num in range(19))
    api = TikTokApi.get_instance(custom_verifyFp=custom_verifyFp, custom_did=did, use_test_endpoints=True,
                                 use_selenium=False, proxy="https://127.0.0.1:1081")
    tiktoks = api.by_username("scottsreality", count=5)
```

### The program can run when it run on Pycharm,but it throw error when it run as exe(completed pyinstaller).

![6a665178be5d68a37331a18865b194c](https://user-images.githubusercontent.com/19714317/118371212-18e59b80-b5de-11eb-91d2-1ada879625f3.png)

**Comment by davidteather** [comment]
Seems like more of an issue with playwright python you might have more luck on their issues page

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
