### ISSUE TITLE
[FEATURE_REQUEST] - Latest Posts are not fetched

### ISSUE THREAD

**Issue by sudopower** [davidteather/TikTok-Api#593]
**Is your feature request related to a problem? Please describe.**
Tiktok sends the latest posts embedded in the page HTML source like below

`{"props":{"initialProps":{"statusCode":0,"$wid":"<masked>","$host":"www.tiktok.com","$pageUrl":"/@<masked>?is_copy_url=1\u0026is_from_webapp=v1","$fullUrl":"https://www.tiktok.com/@<masked>?is_copy_url=1\u0026is_from_webapp=v1",`

Posts older than a few hours are received just fine.

**Describe the solution you'd like**
It would be nice if this props node from the page could be added to get_user_page fn

**Describe alternatives you've considered**
Setup up a recurring script to pull it later, once it's old enough to appear in the item_list TikTok API

**Additional context**
The reason I need the latest post is.
I populate the stats delta, in the current situation, the deltas are populated much later,
since the API doesn't return them, but are available on the platform.

**Comment by aimadnet** [comment]
You can use the mobile api to fetch posts

**Comment by coder39248583** [comment]
@sudopower 

The **api.get_user** method fetches the props object from the embedded HTML as you describe, and returns the pageprops child object.

 ```json
{
    "props": {
        "initialprops": {  }, 
        "pageprops": { "the_returned_object" } 
    } 
}
```
From what I can tell the returned "pageprops" object includes information about (what I assume to be) the user's 6 most recent posts. The "initialprops" object is not included but does not seem to contain any information about user posts.
