### ISSUE TITLE
how to get the tiktok video link without watermark？

### ISSUE THREAD

**Issue by finyone** [davidteather/TikTok-Api#60]
Does the tiktok-api project  get tiktok video link without watermark? 
thanks.

**Comment by hackmoore** [comment]
This is likely impossible, it's viable that the only way to get the videos would be through a direct API call which then would apply the watermark (or the watermark is applied on the video when uploaded).

**Comment by davidteather** [comment]
I haven't been able to find a video link without the water mark. I imagine they save the videos with the water mark on upload to save processing power. And either way as hackmoore said it's definitely not open to the public.

**Comment by davidteather** [comment]
I found a way to get the video without watermark, but it's currently written in php you can find the repo [here](https://github.com/TufayelLUS/TikTok-Video-Downloader-PHP/blob/master/index.php). I'll be looking at porting this code to python, but I don't know much php.

**Comment by hackmoore** [comment]
This is super helpful for me! I'm familiar with both python and PHP so if @davidteather, you want to put it on the back burner, I'll translate the code to a python file.

**Comment by davidteather** [comment]
Changed with version 3.1.4 upgrade your package and use the get_Video_No_Watermark method
