### ISSUE TITLE
[BUG] - Captcha on byHashtag

### ISSUE THREAD

**Issue by rocailler** [davidteather/TikTok-Api#600]
Hi. I can't skip captcha :( 
byUsername is working. I was trying everything... 

```
class Config:
    custom_verifyFp = "..."
    did = ''.join(random.choice(string.digits) for num in range(19))
    useragent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) 
            Chrome/91.0.4472.77 Safari/537.36'


api = TikTokApi().get_instance(custom_verifyFp=Config.custom_verifyFp,
                                   use_test_enpoints=True,
                                   custom_did=Config.did,
                                   logging_level=logging.DEBUG)

tiktoks_all = api.byHashtag('item', count=999)

```

error:
<class 'TikTokApi.exceptions.TikTokCaptchaError'>, TikTokCaptchaError('TikTok blocks this request displaying a Captcha \nTip: Consider using a proxy or a custom_verifyFp as method parameters'), <traceback object at 0x7fe410bea140>)

ERROR:root:Tiktok wants to display a catcha. Response is:
{"code":"10000","from":"","type":"verify","version":"","region":"va","subtype":"slide","detail":"uLsErJq5w*wVS8EhDDwrtwxt5BK1MkwZZ0I9u8CrHUgMUDVpcI1dcSV*7JzHLuMaACkmG7dULZjBQgg9sd60gWvCy1GWLJqTYPYYdT7t3mL-5uTQnTn884PD9EFRKP5BHFmcHp6-l3jqk-jCeR*R40DeE28MsewVMTjN5d7xDpzpyDAqagvJ*2qMOJ6nJDJIRpFnD2AwvbRxVgd7NlY9s61DDJQG0zUMjMHBfjb2eFwaXdyGX8DgSacDQndSDBl7bPayXeDQZlLbob9iaqAG9P6RPv4tiIvjbmTENRT8AUh1oRIls0TdBj00Z2ad1PCMT5Us46IMzAU44r0OPqEfL1EnpEU5SRKrjSkua9rulaa2cf-3xRCYaISl2m5xpFvO7m6k*GERK3zg6*cCOVPj62-rVRYrbb1W6WIllrbAlA..","verify_event":"","fp":"verif_khr3jabg_V7ucdslq_Vrw9_AJ1b_Ks706M8zIJTq","scene":"","verify_ticket":"","channel_mobile":"","sms_content":"","mobile":"","email":""}
ERROR:root:{'tt_webid': '6693507440346895246', 'tt_webid_v2': '6693507440346895246', 'tt_csrf_token': 'XjNSClEkSuzHDviV'}

**Comment by jp-wagner** [comment]
Same here. byHashtag as well as byUsername are not working anymore even with a verifyFp from http://sf16-scmcdn-va.ibytedtos.com/goofy/secsdk-captcha/va/2.15.21/index.html.

**Comment by Samungas** [comment]
Same here, tried different verifyFp  / added proxies.

**Comment by nardo-leo** [comment]
Stuck with _TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha_ when calling `byUsername()` and `user_posts()` functions.

**Comment by paige-pruitt** [comment]
Same here: I'm getting the captcha pretty much every time when calling the `item_list` api endpoint (which is called in `byUsername` and `user_posts`).

**Comment by paige-pruitt** [comment]
These are actually not all truly captchas. It seems like sometimes Tiktok is throwing a 500 error.
I am seeing the following in the body of the response for some requests:

```html
 <body>
    <div class="context-m">
      <div class="info">
        <img src="https://s16.tiktokcdn.com/musical/resource/mtact/static/images/tiktok-logo/status-m-6.png" alt="tiktok" class="news-logo">
        
  <div class="title-m">500 Server Error</div>
  <div class="desc-m">
    Something is wrong on our end. We apologize for any inconvenience and should be back soon. Please try again.
  </div>
      </div>
      <div class="download-btn-m"><a href="https://go.onelink.me/bIdt">Try Again</a></div>
    </div>
  </body>
```

**Comment by 18272841175** [comment]
I have the same problem

**Comment by 18272841175** [comment]
> 这些实际上并不都是真正的验证码。似乎有时 Tiktok 会抛出 500 错误。
> 我在某些请求的响应正文中看到以下内容：
> 
> ```
>  <体> 
>     < DIV 类=”上下文米“ > 
>       < DIV 类=”信息“ > 
>         < IMG  SRC =” https://s16.tiktokcdn.com/musical/resource/mtact/static/images/tiktok-logo/ status-m-6.png " alt =" tiktok " class =" news-logo " >
>         
>   < div  class =" title-m " > 500服务器错误</ div > 
>   < div  class =" desc-m " >
>     我们这边出了点问题。对于给您带来的不便，我们深表歉意，应该很快就会回来。请再试一次。
>   </ DIV > 
>       </ DIV > 
>       < DIV 类= “下载-BTN-M ” > <一个 HREF =“ https://go.onelink.me/bIdt ” >重试</一> </ DIV > 
>     </ div > 
>   </正文>
> ```

Hello, has the problem been solved

**Comment by jp-wagner** [comment]
Seems to work again on 3.9.8. Thanks @davidteather !

**Comment by teogenesmoura** [comment]
Also working here, thank you very much @davidteather!

**Comment by paige-pruitt** [comment]
I'm still getting the TikTok Server errors I posted above but they are definitely inconsistent. Is anyone else experiencing the same?

**Comment by Juan-Rivera** [comment]
> I'm still getting the TikTok Server errors I posted above but they are definitely inconsistent. Is anyone else experiencing the same?

Yeah still experiencing it myself :/

**Comment by dhl284** [comment]
Getting the same error, but it seems fixed when I upgraded the package to 3.9.9

**Comment by Shiro-LK** [comment]
@dhl284  Is it working only if use_test_endpoint=True ? Because when I am doing this and then try to download the video, the video is doing 385 octet so nothing. Am I the only one ?

**Comment by davidteather** [comment]
Yeah so hashtag makes a direct HTTP call to get the ID, which is prone to getting hit with captchas more often.
