### ISSUE TITLE
[BUG] - s_v_web_id is missing

### ISSUE THREAD

**Issue by gg4u** [davidteather/TikTok-Api#610]
I cannot find any  `s_v_web_id` key in the cookies.

Not sure if tiktok use different key names depending on login type:
I logged in via facebook.

Could you please show how to pass the credentials that are needed ?

Possibly, using selenium (I do have issues with playwright, likely due to using an old operating system).

thanks!

**Comment by LuminazLK** [comment]
same issue

**Comment by jsalisbury731** [comment]
I had the same issue yesterday. I was logging in via QR code scanned on my mobile device. Logging in this way skips the captcha, which I believe is needed to get the s_v_web_id cookie. If you try logging in with your username or email address and password, you should get the captcha which will then produce the cookie you need.

**Comment by syrom** [comment]
Had the same problem.... sos, thanks to @jsalisbury731 for the very useful tip to skip the QR code and log in with the phone number - this made a s_v_web_id cookie appear again.
However, still getting error messages (while the same script ran with no problem yesterday): 
"_.... raise TikTokCaptchaError()
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters_"
I do call with the custom_verifyFp (stored in v_emp_web_id):
`api = TikTokApi.get_instance(custom_verifyFp=v_tmp_web_id, request_delay = 10)`
Anyone able to share any thoughts on this ?

**Comment by jsalisbury731** [comment]
> Anyone able to share any thoughts on this ?

I was getting the same error last night, and then this morning it worked for a period of time. It is not working again for me, but I suspect it is an IP throttling issue. I am implementing time.sleep() into my scripts that I'm hoping will help once I'm able to access the videos via the Api again. Hopefully someone else can help explain how to resolve this TikTokCaptchaError() issue...

**Comment by syrom** [comment]
@jsalisbury731 : thx for sharing your experience again. That's what I would call a perfect blend of good and bad news. I will try to test once more tomorrow, in the course of the day. If I see any recurring pattern, I'll report....

**Comment by Skytail-afk** [comment]
I had the same issue today, By normally, I use proxy IP and change it when getting the captcha error but today I get the error, and changing proxy IP isn't working.

**Comment by mina9999** [comment]
me too. idk how to fix . Tiktok wants to display a catcha. Response is: error is annoying. im using proxy too.

**Comment by davidteather** [comment]
Yeah it seems like they're deprecating s_v_webid. V3.9.9 has some more avoidance techniques. Might be worth upgrading to that.

**Comment by gtechzilla** [comment]
I struggled with this for a few hours. What worked for me is to ensure that i log in with the username and password.I mean literally. If you had created an account by using your email directly it wont work. If you are in such a situation,logout and choose create new account using email,type in your email and set a password.It won't allow you to use the same username so just be ready to change that. When done log in and if you now check your cookies you will find the s_v_web_id

**Comment by mina9999** [comment]
https://www.youtube.com/watch?v=1udviRhJ1tY

**Comment by davidteather** [comment]
Not sure it's needed anymore with V5
