### ISSUE TITLE
when I follow user on tiktok website,tiktok always return back watch_status:0,what it is meaning about watch_status?why tiktok return watch_status:0?

### ISSUE THREAD

**Issue by ztever** [davidteather/TikTok-Api#611]
**Describe the error**

Put the error trace here.

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - TikTokApi Version [e.g. 3.3.1] - if out of date upgrade before posting an issue

**Additional context**

Put what you have already tried. Your problem is probably in the closed issues tab already.

**Comment by davidteather** [comment]
I'm not sure what you mean, this package doesn't support logged in interactions.
