### ISSUE TITLE
[BUG] - It seems that a  csrf_session_id is now needed in cookies

### ISSUE THREAD

**Issue by vdemay** [davidteather/TikTok-Api#612]
`userPosts` endpoint stops to work on my side since several hours. 
According to my first investigations, It seems a new cookie is now needed : csrf_session_id

I tried to fix that but was not able to make it work again for now

**Comment by vdemay** [comment]
Continuing investiguation, it seems this cookie in somehow linked to the x-secsdk-csrf-token header

**Comment by dylancaponi** [comment]
For me, `byUsername` has not been working for 3 days which calls `userPosts`.
`getUser` continues to function without issue.

I'm Uuing identical code (minus the actual function call) and the same `verifyfp`.

**Comment by teogenesmoura** [comment]
same here! Can't fetch posts using the byUsername method

**Comment by ejxtreme512** [comment]
same here - having issues

**Comment by davidteather** [comment]
#613 / Version 3.9.9 fixes this :)

**Comment by dylancaponi** [comment]
I think TikTok has made another change. 3.9.9 fixed things for 12 days but now `userPosts` is triggering captcha response again while `byUsername` is not. Same verifyfp, same code.

**Comment by dylancaponi** [comment]
@vdemay What was your process for discovering which extra keys were required for the call to succeed?

I'm digging around in inspector and trying to compare the network call my browser is making to the one made by `get_data` but it's pretty messy.

**Comment by davidteather** [comment]
> `byUsername` is triggering captcha response again while `getUser` ** is not. Same verifyfp, same code. 

Due to the way TikTok exposes data `by_username` has to make a HTML request to find the secUid & user id of the username which is more likely to get detected than the API requests. `get_user` this information is provided
