### ISSUE TITLE
Using different proxies to make requests but still getting error [Tiktok wants to display a catcha]

### ISSUE THREAD

**Issue by zbtzero7** [davidteather/TikTok-Api#615]
proxies= [..]  //List of proxies
api = TikTokApi.get_instance(**use_test_endpoints=True**) 
 for loop:
            user_videos = api.byUsername(username, count =n_videos, region ="PK",**proxy=proxies[i]**, language='en')

ERROR:root:Tiktok wants to display a catcha. Response is:
{"code":"10000","from":"","type":"verify","version":"","region":"sg","subtype":"slide","detail":"KOhViXRctvUqJRvJlXDrErnPG7*NbSks3Z4yUYkHidC0vcmh2RU4-KfszIifRE6yLwWH2Uvhl5O-zDPGaVqh1wxc4PTEZjbf8yzOfStxY*llTXFvb-WT0nU8M-d2QpgM-pdFLFiUKW8ZJeuvNbfVaxPUeqtyBVLvXpR06tUd7EGJy0Bz125H-MOGPwT5g3kMLUi2LCKb9rooZZ3t1A58juuIvhixdKK4PtqoLcj8SVc56MotgSUHtHlk7ErVDrvdvHak9M1r7aMfHsVz5uRkfMYlrtgyU2gRPn0mqxshgB9KE7hrjsaRay0Vphs-MJWJnoJ62lthM6FEwx22Ghc50TWnLgRlMov0v9AUsp2iSfc*CKvS4h78MnctVUEoUBFk448GGba*cN3UUtSuaCmXyJWQG-MqQJVZEyo.","verify_event":"","fp":"verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq","scene":"","verify_ticket":"","channel_mobile":"","sms_content":"","mobile":"","email":""}
ERROR:root:{'tt_webid': '7557659015042569959', 'tt_webid_v2': '7557659015042569959', 'tt_csrf_token': 'TNscNSsyCYAEEfph'}
GetVideoDetails Exception:  TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters

**Comment by djmarioka** [comment]
Hi,

I've got the same issue, could you fix it?. 

Thanks.

**Comment by Juan-Rivera** [comment]
Having this issue with proxies as well.

**Comment by zbtzero7** [comment]
Yeah still experiencing it

**Comment by mina9999** [comment]
me too please fix this. 

Tiktok wants to display a catcha. Response is:
Jun 18 13:23:26 vmi538808.contaboserver.net python[16493]: {"code":"10000","from":"","type":"verify","version":"","region":"sg","subtype":"slide","detail":"p8nkiqni96haXI2VVM43kxs2IJwT7X5TrX9xKNTiAHKZ*2Y*GOfsDl2K3IZANNkxgV2ZLK5QX-MupIj*L3DQUQHxUhAk0rnNGUpoKzixo4oSD0z3rptJ5RX-vu8I46S5qFCkVButYLhvCdXPI-fA*-YFv6F5fKjQHs32qRNz6vnmh8ZUO14N3-ZrKi7KBQnpdjMWmZOb*GCU*94VhAlMjyBQYbqhDBT03dbbkPBlwNuMrxhXcU-7bd69SnUOapbhXHgFjnXTnwPtiHxecMEizMGy*9P1ugeu81bC8Yc1Q*PmXQvv7j9giUDZh*Ana54AGH5JEX6fkjpkAS4Y5Q5MhHVRNQm7j5Pvg6nttRvWivfpN0Jav9aDlH*fKUF49sTo8d0M6NF6min9-OSr9iQSw9wPca8au8RGOkg.","verify_event":"","fp":"verify_kq1zc3c7_hYFi41sC_nbkl_4BPH_9Flh_uOrli7F3Jo9m","scene":"","verify_ticket":"","channel_mobile":"","sms_content":"","mobile":"","email":""}
Jun 18 13:23:26 vmi538808.contaboserver.net python[16493]: [2021-06-18 13:23:26] [ERROR] root: {'tt_webid': '4527750574570371440', 'tt_webid_v2': '4527750574570371440', 'csrf_session_id': 'f46e0f0070bd48b6a989e594c7439288', 'tt_csrf_token': 'tEdMBICnSpCSxJQM'}
Jun 18 13:23:26 vmi538808.contaboserver.net python[16493]: [2021-06-18 13:23:26] [WARNING] tiktok: Captcha error, retrying..

**Comment by mina9999** [comment]
@vdemay hi can you please fix it for us again thank you<3 sorry for the ping

**Comment by mina9999** [comment]
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]: [2021-06-18 14:56:04] [ERROR] root: Tiktok response:
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:  <!DOCTYPE html>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]: <html>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:     <Head>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         <meta charset="utf-8">
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         <title>TikTok</title>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         <link rel="shortcut icon" type="image/x-icon" id="favicon">
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         <meta name="screen-orientation" content="portrait">
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         <meta name="x5-orientation" content="portrait">
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         <meta name="format-detection" content="telephone=no">
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimum-scale=1, maximum-scale=1, minimal-ui, viewport-fit=cover">
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         <meta name="apple-mobile-web-app-capable" content="yes">
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         <meta name="applicable-device" content="pc,mobile"/>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         <link rel="dns-prefetch" href="https://sf16-scmcdn-va.ibytedtos.com" />
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         <script async src="https://sf16-scmcdn-va.ibytedtos.com/goofy/log-sdk/collect/collect-tcpy.js"></script>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         <script>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             const option = {"title":"tiktok-verify-page","iid":"0","did":"0","app_name":"tiktok","aid":1284,"favicon":"https://s16.tiktokcdn.com/musical/resource/mtact/static/images/tiktok-logo/logo.png","mobileIcons":["https://s16.tiktokcdn.com/musical/resource/mtact/static/images/tiktok-logo/tiktok_m.png","https://s16.tiktokcdn.com/musical/resource/mtact/static/images/tiktok-logo/tiktok_m2x.png","https://s16.tiktokcdn.com/musical/resource/mtact/static/images/tiktok-logo/tiktok_m3x.png"],"icons":["https://s16.tiktokcdn.com/musical/resource/mtact/static/images/tiktok-logo/tiktok_w.png","https://s16.tiktokcdn.com/musical/resource/mtact/static/images/tiktok-logo/tiktok_w2x.png","https://s16.tiktokcdn.com/musical/resource/mtact/static/images/tiktok-logo/tiktok_w3x.png"],"region":"va","type":"slide","verifyConfig":{"code":10000,"type":"verify","subtype":"slide","fp":"verify_ef0180a43927ff8fb19ffc7d9f901135","region":"va","detail":"SLo07D9SPnsSklvmcAn02pXwr-7*tdEWGFsIp9YvQARD8vDKhf1n3EyOMg6Qz4WR9S-qDTOPiatOcCnXISem2FOu0nvJ8X8OXWbwz5ErfJC55PN1B9vSU8Q9i9niyFKk1CYwWdAp66eiFXjYjeDMTsamkwkzs9LmK7gFCezj8vUtDLlkgneVVHvYsxUiee2iKtZvMTC*iFbIgGAAA*VuNBTdFLpTT4A3uSKG*YWP5*O4c0mpyUVyuqsu8jtaaERumJfVwYVksmZu5jqgxzn6-8xlyTKseKvnGviO5NLeRp6Ol*VwKJhp3AKvSCM34TEjEWK-dJ97Venfwoion9PA8lkXZ4iYieZtoZ0DVO5C0wQyHNjrpjZj5LvM-CTFnAhnCA.."},"lang":"en"};
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             if(!option.region) {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 option.region = 'va';
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             var verifyTime = new Date().getTime();
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             (function(win, export_obj) {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 win['TeaAnalyticsObject'] = export_obj;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 if (!win[export_obj]) {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                     function _collect() {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                         _collect.q.push(arguments);
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                     }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                     _collect.q = _collect.q || [];
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                     win[export_obj] = _collect;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 win[export_obj].l = +new Date();
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             })(window, 'collectEvent');
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             window.collectEvent('page.init', {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 app_id: option.region === 'cn' ? 2018 : 2740,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 channel: option.region === 'boe' ? 'cn' : option.region,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 log: true,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             });
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             window.collectEvent('page.start');
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             window.collectEvent('page.verify_page_load', {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 aid: option.aid,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 product_host: location.host,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 product_path: location.pathname,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 time: new Date().getTime(),
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 is_success: 0,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 duration: new Date().getTime() - verifyTime
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             })
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             window.onbeforeunload = function () {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 window.collectEvent(document.readyState === 'complete' ? 'page.verify_page_close' : 'page.verify_page_load_close', {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                     product_host: location.host,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                     product_path: location.pathname,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                     aid: option.aid,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                     time: new Date().getTime(),
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                     fp: (document.cookie.match(/s_v_web_id=(\w+)/) || [])[1],
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                     is_success: Number(!!window.verify_is_success)
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 })
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         </script>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         <script src="https://sf16-scmcdn-va.ibytedtos.com/goofy/sec_sdk_build/3.1.3/captcha/index.js"></script>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         <script async src="https://sf16-muse-va.ibytedtos.com/obj/eden-va2/fviylclsjeh7bogubfbd/tt-webapp/starling.browser.js"></script>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:     </Head>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:     <body>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         <div class="content">
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             <div class="app_icon"></div>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             <div class="verify-wrap">
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 <div id="verify-ele"></div>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             </div>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             <p class="page-desc" id="verifyEle"></p>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         </div>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:     </body>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:     <style>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         html, body {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             min-height: 500px;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         body {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             background: #EDF0F5;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             display: flex;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         .content {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             width: 300px;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             margin: auto;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         .verify-wrap {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             min-height: 306px;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         @media (min-width: 1281px) {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             .content {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 width: 380px;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             .verify-wrap {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 min-height: 386px;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         .captcha_verify_container {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             border: 1px solid #E8E8E8;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         .captcha_verify_container #verify-bar-close {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             display: none;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         .app_icon img {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             margin-bottom: 20px;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         .page-desc{
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             margin-top: 32px;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             font-family: PingFangSC-Medium;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             font-size: 12px;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             color: #505050;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             line-height: 19px;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         .page-desc span {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             font-family: 'PingFangSC-Regular';
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             color: #505050;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:     </style>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:     <script>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         const pageDescKey = 'user_verify_page_description';
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         const ua = navigator.userAgent;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         const isMobile = /Android|webOS|iPhone|iPod|BlackBerry|Windows Phone|iPad/i.test(ua);
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         const hosts = {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             cn: '//verify.snssdk.com',
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             boe: '//boe-verify.snssdk.com',
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             sg: '//verify-sg.byteoversea.com',
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             va: '//verification-va.byteoversea.com'
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         };
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         window.TTGCaptcha.init({
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:           commonOptions: {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             aid: option.aid || 0,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             did: '0',
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             iid: '0',
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:           },
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:           captchaOptions: {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             ele: 'verify-ele',
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             host: hosts[option.region],
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             lang: option.lang.match(/zh/) ? 'zh-Hant' : option.lang,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             region: option.region,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             app_name: option.app_name || '',
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             hideCloseBtn: true,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             successCb: successCb,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             feedbackSubmitCb: feedbackSubmitCb,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             autoClose: false
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:           },
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         });
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         window.onload = function () {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             window.verify_is_success = true;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             document.querySelector('#favicon').href = option.favicon;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             document.title = option.title || 'security verification';
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             const icon = isMobile ? option.mobileIcons : option.icons;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             if (option.icons || true) {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 let img = document.createElement('img');
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 img.srcset = `${icon[0]} 1x,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                     ${icon[1]} 2x,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                     ${icon[2]} 3x`;
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 img.alt = 'app logo';
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 img.src = icon[0];
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 document.querySelector('.app_icon').appendChild(img);
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             window.collectEvent(location.href === document.referrer ? 'page.verify_page_refresh' : 'page.verify_page_init', {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 duration: new Date().getTime() - verifyTime,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 aid: option.aid,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 region: option.region,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 fp: (document.cookie.match(/s_v_web_id=(\w+)/) || [])[1],
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 is_success: 1,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 product_host: location.host,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 product_path: location.pathname,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             })
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             const starling = new Starling({
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 api_key: '5dc26cf008d511e9b571e1bc0c9e23b5',
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 namespace: 'Captcha',
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 locale: option.lang,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 zone: (option.region || 'SG').toUpperCase(),
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 test: false,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 fallbackLang: ['en'],
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             });
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             starling.load((texts) => {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 let desc = document.querySelector('#verifyEle');
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 desc.innerText = texts[pageDescKey];
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             });
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             window.TTGCaptcha.render({
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 verify_data: JSON.stringify({
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                   subtype: option.type,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                   ...(option.verifyConfig || {}),
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 })
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             });
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             // tt embed iframe
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             if (window.self !== window.top && window.name.indexOf('__tt_embed__') !== -1) {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 const resizeData = JSON.stringify({
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                     signalSource: window.name,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                     height: 600,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 });
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 window.parent.postMessage(resizeData, '*');
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         function successCb() {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             location.reload();
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         function feedbackSubmitCb() {
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             window.TTGCaptcha.render({
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 verify_data: JSON.stringify({
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                   subtype: option.type,
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                   ...(option.verifyConfig || {}),
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:                 })
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:             });
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:         }
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]:     </script>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]: </html>
Jun 18 14:56:04 vmi538808.contaboserver.net python[12064]: [2021-06-18 14:56:04] [WARNING] tiktok: Captcha error, retrying..

also this error is new i think.

**Comment by davidteather** [comment]
You should provide a custom_verifyFp to the constructor method. There’s a YouTube guide linked in the readme on how to set this up. Also make sure you’re on latest version :)

**Comment by mina9999** [comment]
(redenv) root@vmi538808:~# pip install TikTokApi -U
Requirement already satisfied: TikTokApi in ./redenv/lib/python3.8/site-packages (3.9.9)
also im using  custom_verifyFp too.

**Comment by davidteather** [comment]
Can you provide the code that you’re running?

**Comment by mina9999** [comment]
i send u on discord. please check it thank u so much bro.

**Comment by christ0224** [comment]
the same issue,i used 2000 proxies but still getting error 'Tiktok wants to display a catcha' when I was getting tiktoks by hashTag:
```python
verifyFp = "verify_kpmcz8p3_y9T6gEOu_4j9z_4KlF_8TZB_lZjUCnEiY1My"
count = 30
tag = "cat"
suffix = ""
proxy_list = {
# proxy list json:
# ...
}
password = ""

print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))
    for val in proxy_list:
        proxy_server = "https://"+suffix+val+":"+password
        api = TikTokApi().get_instance(proxy=proxy_server, custom_verifyFp='verify_kq26ic1n_0ueLrNHd_hLDo_4Jip_BwJW_JdyKfCNt7IQp')
        try:
            tiktoks = api.byHashtag(tag, count=count)
            j = json.dumps(tiktoks)
            print("\033[0;32;40m Proxy Server: " + proxy_server + " works!\033[0m")
            curTime = time.strftime("%Y-%m-%d-%H-%M-%S", time.localtime())
            file_path = "./results/getTiktoksByHashtag_" + tag + "_" + curTime + ".json"
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(str(j))
                print("\033[0;32;40m Scrap file was successfully created in:  " + file_path + " \033[0m")
            api.clean_up()
            break
        except Exception as e:
            print("\033[1;31m Proxy Server: " + proxy_server + " doesn't work , trying to use the next server...\033[0m")
            print(e)
            time.sleep(3)
            api.clean_up()
            continue
    print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))
```

**Comment by dylancaponi** [comment]
@felixwann Proxies are not enough. Follow the docs and add a verifyFp: https://www.youtube.com/watch?v=zwLmLfVI-VQ

**Comment by mina9999** [comment]
we find a fix for this error check https://github.com/davidteather/TikTok-Api/issues/627 and also watch https://youtu.be/MgjorCvPzxg
