### ISSUE TITLE
Can't import the Tiktokapi library

### ISSUE THREAD

**Issue by ab-databeat** [davidteather/TikTok-Api#62]
**Describe the bug**

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by davidteather** [comment]
Install it with
```
pip install TikTokApi
```

Import it as such
```
from tiktok import TikTokapi
```

If that doesn't work provide code please. This API isn't functioning right now.

**Comment by imsurajsharma** [comment]
` from tiktok import TikTokap`i

> ModuleNotFoundError: No module named 'tiktok'``

I got this error while importing your package. I installed via `pip install TikTokApi
` and when I try to import this package it shows error.

**Comment by imsurajsharma** [comment]
@davidteather Please resolve this issue.

**Comment by davidteather** [comment]
Try
`
from TikTokApi import TikTokapi
`

**Comment by imsurajsharma** [comment]
@davidteather I resolved that issue by myself. There is another issue of SSL

**Comment by davidteather** [comment]
Yeah the api right now isn’t working.

**Comment by imsurajsharma** [comment]
Okay, I will fix your API on my own and send it back to you.

**Comment by jacobsilverman** [comment]
if you do fix this let me know :D
