### ISSUE TITLE
[BUG] - get_Video_By_TikTok(tiktok) download access denied

### ISSUE THREAD

**Issue by konka95git** [davidteather/TikTok-Api#620]
When trying to download TikTok videos using get_Video_By_TikTok(tiktok) method , I saved the output in mp4 format. However, when I open the file in the console, it shows

```
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;v16&#45;web&#46;tiktok&#46;com&#47;video&#47;tos&#47;useast2a&#47;tos&#45;useast2a&#45;ve&#45;0068c003&#47;2d8a15f15a1843e5a34f2a20bd0079bb&#47;&#63;" on this server.<P>
Reference&#32;&#35;18&#46;27c58848&#46;1623861418&#46;34d4cc3
</BODY>
</HTML>
```

**Part of my code**

```
        tiktokData = api.get_Video_By_TikTok(tiktok)
        with open(str(index) + ".mp4", "wb") as out:
            out.write(tiktokData)
```

**Desktop:**
 - OS: [e.g. Windows 10]
 - TikTokApi Version [3.9.9] 

Thanks in advance if anyone knows how to fix this problem.

**Comment by gabiherman** [comment]
Same issue here!

**Comment by agusart** [comment]
still same issue here!

**Comment by mrmps** [comment]
See https://github.com/davidteather/TikTok-Api/issues/646

**Comment by twitter-79** [comment]
sadly the solution in #646 does not work for me. If I use the workaround (with selenium) I get invalid JSON back:
TikTok response: {
    statusCode: -1,
    itemInfo: {}
}

any ideas?

**Comment by davidteather** [comment]
Think this should be fixed now (unless you're using selenium, which has been getting detected for some time now unfortunately :\)
