### ISSUE TITLE
[FEATURE_REQUEST] - Get videos by Topic

### ISSUE THREAD

**Issue by kicks66** [davidteather/TikTok-Api#622]
TikTok recently updated with a new section of their app called "Topics":

![IMG_8083](https://user-images.githubusercontent.com/4125092/122529957-e502f900-d015-11eb-9398-5dd0d3decfc6.PNG)

Clicking on a Topic opens up a new infinite-scrolling stream of videos within that particular Topic. These videos do not have hashtags or particular descriptors that define them as being part of a Topic.

I'd like to know if its possible to find the routes which create this list of videos, and if its possible to integrate this into the API?

**Comment by davidteather** [comment]
Not sure if this is possible because this package only uses the website API requests as of now.

**Comment by SuperSonicHub1** [comment]
You actually can access topics from the web client if you look at the left sidebar.
The URL structure is `https://www.tiktok.com/topics/<topic>`, with the topics being:
* gaming
* comedy
* food
* dance
* beauty
* animals
* sports

A request is them made to `https://us.tiktok.com/api/topic/item_list/?topic=<topic>` to get the data necessary. I've attached a HAR for reference.
[www.tiktok.com_Archive [22-07-22 16-55-41].har.txt](https://github.com/davidteather/TikTok-Api/files/9172192/www.tiktok.com_Archive.22-07-22.16-55-41.har.txt)
