### ISSUE TITLE
How to generate _Siganture for comment endpoint.

### ISSUE THREAD

**Issue by h4ck1th4rd** [davidteather/TikTok-Api#624]
Hi,

I willing to pay anyone who's able to generate _Signature key for a successful comment via web app.

Thank you,
regards.

Tele: https://t.me/JosecLee

**Comment by a1d4r** [comment]
_signature is already included in URL. To get comments you have to provide `sessionid` cookie from your browser after you logged in.

**Comment by h4ck1th4rd** [comment]
> _signature is already included in URL if you are using wrapper from this repo. To get comments you have to provide `sessionid` cookie from your browser after you logged in.

I am not trying to get comments, am trying to Post a comment. :/ and I know its required a cookie including sessionid indeed. pffsss..
