### ISSUE TITLE
[BUG] - TikTok blocks this request displaying a Captcha

### ISSUE THREAD

**Issue by Alex-Laparra** [davidteather/TikTok-Api#627]
**Description of the bug**
Systematic captcha error when using by_username method. Error message advises using proxy or a custom_verifyFp but this bug would also appear after a while in previous versions for which I had tried using proxy or a custom_verifyFp without success until a new version eventually fixed this issue. And this has happened quite a few times actually so I suppose you might know how to fix it again now. When you do, I'd be glad if you could explain how you did it, so I can fix it myself in the future and upload pull request quickly since I use your API on a daily basis.

**The buggy code**

```
from TikTokApi import TikTokApi as t
api = t.get_instance()
k = api.by_username("")
```

**Error Trace**

```
ERROR:root:Tiktok wants to display a catcha. Response is:
{"code":"10000","from":"","type":"verify","version":"","region":"va","subtype":"slide","detail":"GDIqyl9SLA5lVSsn4JVxPJ2cYRgDuhDP2NBDA0FqMagtMGQB8TGV2kpodkbZzjHKYcgIzsCRQbF60HRg3l9Qauc2Do6mMa-0Zg5zDKWegm2X6nPmvd0*iT3sZKcm1jeSXuYDR8MliQ8C-w5slo0ucQ-I1mouIfpZAPBvtuqCaLlitjnBe-x9821RxB7KI1poAlO19vIyMqX4daxORf7eHrqKoJv7CA03WhiLzQT0*0mhfkO1deNBCczMZ6SIL6hTp6aUbCoqz51dHuiKM-cGG*WHzU*snEBYxNaixbl84PVCwRqDYF1byBZiBDJ8jU50uDiiJ53EL3dtYdXtcoWBr6Q8F1Cly-FTFBOuwusDQEbR*bKMA23oExlFHGvq2mAlpYmzG*v-6mvF64wPNe1i1xh-qHQPS3zWJxo.","verify_event":"","fp":"verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq","scene":"","verify_ticket":"","channel_mobile":"","sms_content":"","mobile":"","email":""}
ERROR:root:{'tt_webid': '1637611630395385016', 'tt_webid_v2': '1637611630395385016', 'csrf_session_id': '13d94c933ff245fd8bf4696164422b16', 'tt_csrf_token': 'vAtEBuHpdiZmCVUk'}
Traceback (most recent call last):
  File "C:\Users\me\Documents\0_Projet\herer\testt\bug.py", line 4, in <module>
    k = api.by_username(us)
  File "C:\Users\me\AppData\Roaming\Python\Python37\site-packages\TikTokApi\tiktok.py", line 603, in by_username
    **kwargs,
  File "C:\Users\me\AppData\Roaming\Python\Python37\site-packages\TikTokApi\tiktok.py", line 563, in user_posts
    res = self.get_data(url=api_url, **kwargs)
  File "C:\Users\me\AppData\Roaming\Python\Python37\site-packages\TikTokApi\tiktok.py", line 279, in get_data
    raise TikTokCaptchaError()
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha 
Tip: Consider using a proxy or a custom_verifyFp as method parameters
```

**Desktop**
 - OS: Windows 10
 - TikTokApi Version : 3.9.9

**Comment by mina9999** [comment]
please fix it i have same problem. im using proxies too.

**Comment by alanblue2000** [comment]
Have you seen this, his tutorial, https://www.youtube.com/watch?v=zwLmLfVI-VQ&t=117s
Let us know if you get it working

**Comment by Alex-Laparra** [comment]
> Have you seen this, his tutorial, https://www.youtube.com/watch?v=zwLmLfVI-VQ&t=117s
> Let us know if you get it working

doesn't work

**Comment by christ0224** [comment]
same

**Comment by lafritte57** [comment]
Same thing here, I tried with different s_v_web_id cookie values but also with several proxies and the problem persists.

**Comment by dylancaponi** [comment]
Chiming in that

I think TikTok has made another change. 3.9.9 fixed things for 12 days but now `byUsername` ** is triggering captcha response again while `getUser` ** is not. Same verifyfp, same code.

These are the keys in the return header, not sure if any are new:
```
dict_keys(['Server', 'Content-Type', 'X-Ware-Csrf-Token', 'Tt_stable', 'X-Tt-Logid', 'Access-Control-Expose-Headers', 'x-tt-trace-host', 'Content-Encoding', 'Content-Length', 'X-Origin-Response-Time', 'X-Akamai-Request-ID', 'Date', 'X-Cache', 'Connection', 'Vary', 'Set-Cookie', 'X-Cache-Remote', 'X-Parent-Response-Time', 'x-tt-trace-tag', 'Server-Timing'])
```

**Comment by mina9999** [comment]
i think we can bypass this but im still not sure https://captchaforum.com/threads/bypass-tiktok-captcha.1205/

**Comment by Alex-Laparra** [comment]
> I think TikTok has made another change. 3.9.9 fixed things for 12 days but now `byUsername` is triggering captcha response again while `getUser` is not. Same verifyfp, same code.

Exactly what I was thinking, tiktok keeps changing their verification methods, it's very annonying. I'll try to look into it and see if I can fix it myself, but I've only started learning coding recently so it might take me some time.

**Comment by Alex-Laparra** [comment]
> i think we can bypass this but im still not sure https://2captcha.com/blog/tiktok-captcha

Haven't looked into it that much yet, but if it works, David should definitely implement it.

**Comment by Alex-Laparra** [comment]
It seems to work just fine right now. I'm gonna leave this issue open for 24 more hours just in case it gets buggy again.

**Comment by mina9999** [comment]
did u changed your code? tell us too

**Comment by Alex-Laparra** [comment]
> did u changed your code? tell us too

Haven't changed anything, it just works now for some reason. Try to chek with your code, should work too.

**Comment by mina9999** [comment]
i find a way to bypass captcha and my bot working fine now. the new verifyfp is shorter than old one and it works fine.

**Comment by mina9999** [comment]
![12312313123](https://user-images.githubusercontent.com/28566705/123206852-a8ca0f80-d4d1-11eb-8484-6198054e8031.jpg)

**Comment by lafritte57** [comment]
> It seems to work just fine right now. I'm gonna leave this issue open for 24 more hours just in case it gets buggy again.

On my side it still doesn't work... Are you using a different proxy or something?

**Comment by aecollier** [comment]
Hello! I've been following along with this issue hoping to solve mine, but no luck. I haven't been able to scrape in two weeks without getting this Captcha error. I've tested with and without the custom_verify_Fp, and used the custom_verify_Fp at both the instance and method levels. I've tried running on different networks, I've completely cleared my cache and gotten new sv_web_id values immediately before running code, and it's not working with any api methods I've called (I'm working with trending, by_hashtag, by_username, by_sound). My api wasn't up to date at first but also hasn't worked since updating. Haven't tried a proxy but have run on a separate VPN connection. Here's the buggy code, hopefully someone will have some leads on this!
`from TikTokApi import TikTokApi
import json

v = 'verify_kqb4t0nl_WmfI8Wsi_AiNx_4n2Z_AQFq_vVMh9w32JL5j'

api = TikTokApi.get_instance(custom_verifyFp = v, use_test_endpoints = True) # tried with the custom_verifyFp here and also below

results = 100
hashtag = 'indigenous'
full_dic = api.by_hashtag(custom_verifyFp = v, hashtag = hashtag,count = results)
print(full_dic)`

**Comment by Alex-Laparra** [comment]
> > It seems to work just fine right now. I'm gonna leave this issue open for 24 more hours just in case it gets buggy again.
> 
> On my side it still doesn't work... Are you using a different proxy or something?

It worked for a short period of time but doesn't work anymore I'm afraid

**Comment by Alex-Laparra** [comment]
Still not working as of now

**Comment by mina9999** [comment]
@Alex-Laparra this will fix all captcha errors https://youtu.be/MgjorCvPzxg just watch it. im using firefox btw but i think on others works too.

**Comment by Alex-Laparra** [comment]
> @Alex-Laparra this will fix all captcha errors https://youtu.be/MgjorCvPzxg just watch it. im using firefox btw but i think on other Web browsers works too.

Hey! First thing thanks! 
I'm doing everything you're doing in the tutorial but when I click on an other music link after deleting all the cookies, I'm not getting a captcha and I'm using Firefox too. But would there be a way to automate this? I'm currently in the process of creating an app using this api and this process is bit laborious for a random user so it'd be better if the problem were to be fixed at the source because at some times the verifyFp wasn't needed and then Tiktok changed stuff with their servers and David or some guy with a pull request would fix the problem but then the problem would appear again and this has happened many many times already. So a permanent fix would be so cool. I'm gonna try and look at the code to fix it myself but I mean I've just recently started coding recently so I might not find a solution. 
But thanks again for your kind help!

**Comment by mina9999** [comment]
on Discover click on a music 
![image](https://user-images.githubusercontent.com/28566705/124217292-59a55f80-db0d-11eb-84ce-7b5d65356ddf.png)
also you have to be already on a music link then delete your cookies. it will show you the captcha and do the captcha and copy it.

**Comment by Alex-Laparra** [comment]
> on Discover click on a music 
> ![image](https://user-images.githubusercontent.com/28566705/124217292-59a55f80-db0d-11eb-84ce-7b5d65356ddf.png)
> also you have to be already on a music link then delete your cookies. it will show you the captcha and do the captcha and copy it.
> 

I've repeated this process like ten times but I'm not getting the captcha, when i click on a an other music link, it directly takes me to that page

**Comment by mina9999** [comment]
if you delete your cookies from tiktok you will get captcha always.
use this verify_f59ff756e4e331c2b798fb7b4928c6de 
also do u have discord?

**Comment by mina9999** [comment]
when you dont get captcha it means you didnt delete your cookies.

**Comment by Alex-Laparra** [comment]
> if you delete your cookies from tiktok.com you will get captcha always.
> use this verify_f59ff756e4e331c2b798fb7b4928c6de 
> also do u have discord?

Well I can swear to you i'm not getting any captcha 😂. Yes my discord is Twelvanoff#9987. Thanks for the verifyFp, will try it now

**Comment by Alex-Laparra** [comment]
> when you dont get captcha it means you didnt delete your cookies. 

But i did

**Comment by mina9999** [comment]
That verifyfp works or not?

**Comment by Alex-Laparra** [comment]
You verifyFp works fine thanks. How long does it usually last?

**Comment by mina9999** [comment]
see? it will work just delete all your cookies then.
go to this website about:preferences#privacy then go to the manage data... and then search for tiktok and then click on remove all shown and then save changes and then once again click on remove. also dont close the tiktok music link when you are deleting your cookies.

**Comment by Alex-Laparra** [comment]
> see? it will work just delete all your cookies then.
> go to this website about:preferences#privacy then go to the manage data... and then search for tiktok and then click on remove all shown and then save changes and then once again click on remove. also dont close the tiktok music link when you are deleting your cookies.

Still doesn't work on my end sorry. I will try a few times again but I still don't get the captcha. Maybe it has something to do with the new European Laws about cookies and stuff. What country are you from? Cause I'm from France

**Comment by mina9999** [comment]
middle eat but my vpn is from germany haha.

**Comment by mina9999** [comment]
i will add you on discord and when you need verifyfp u can dm me i will give you always. we should wait till david fix this.

**Comment by Alex-Laparra** [comment]
> i will add you on discord and when you need verifyfp u can dm me i will give you always. we should wait till david fix this.

Thank you!

**Comment by lafritte57** [comment]
> @Alex-Laparra this will fix all captcha errors https://youtu.be/MgjorCvPzxg just watch it. im using firefox btw but i think on other Web browsers works too.

Hey! Thanks a lot for this workaround and for taking the time to make a how-to video.

However, as for @Alex-Laparra, I never get the captcha window despite all my attempts and after following your tutorial and advice to the letter (deleting cookies via Dev Tools and via about:preferences). I have tried on different browsers (chrome, firefox, brave, opera) but the same result, even in private browsing.

On the other hand, the verifyFp that you communicated works perfectly!

What is strange (and maybe a clue) is that I am also in France.

**Comment by felixwann** [comment]
> @Alex-Laparra this will fix all captcha errors https://youtu.be/MgjorCvPzxg just watch it. im using firefox btw but i think on other Web browsers works too.

First of all thank you very much! Your tutorials really helped me, at least today my boss won't give me a hard time!

**Comment by davidteather** [comment]
Okay I'm going to close this issue because of changed made in V4.0.0 only things that I can really suggest are
* use a proxy
* try to use multiple verifyFps if it's being difficult

**Comment by getsec** [comment]
lmfao . Imagine asking the maintainer to bypass captchas for you...
