### ISSUE TITLE
[FEATURE_REQUEST] - tiktoks without watermark.

### ISSUE THREAD

**Issue by ahmed103** [davidteather/TikTok-Api#628]
It would be awesome if we can find a solution to download tiktoks without watermark.
for people waiting for this feature to be fixed, i created a script to download tiktoks without watermark, the script also support using proxies , and can run with or without gui.
I also created an executable release.
Check out this link :
https://github.com/ahmed103/Tiktok-no-watermark

**Comment by messivite** [comment]
How can I download no wm video?

**Comment by Zipdox** [comment]
The link you posted just uses snaptik.app
https://github.com/ahmed103/Tiktok-no-watermark/blob/master/selenuim_utils.py#L66

**Comment by ahmed103** [comment]
Yup , just you can integrate it easily when you want to massively scrap videos without watermark since you can use a proxy

**Comment by Zipdox** [comment]
Relying on an external service is not the scope of this project

**Comment by cantonalex** [comment]
Any update on this?

**Comment by haris1998-web** [comment]
@ahmed103 If you could demonstrate how to use your code here

**Comment by ahmed103** [comment]
Everything is in readme file https://github.com/ahmed103/Tiktok-no-watermark/blob/master/Readme.md

**Comment by jcohenho** [comment]
@ahmed-zekri can you share your actual method for how to get non-watermarked videos? I.e. How you are making requests to TikTok and finding the video without the watermark, not just how to use your API.

**Comment by ahmed-zekri** [comment]
subprocess.call('tiktok_no_water_mark.py -ng -url "tiktok video url" -o "output file name" -p "your proxy "', shell=True)
and put the two files tiktok_no_water_mark.py and selenuim_utils.py at the same directory with your code base.
don't forget to install all requirements using requirements.txt

**Comment by Zipdox** [comment]
> @ahmed-zekri can you share your actual method for how to get non-watermarked videos? I.e. How you are making requests to TikTok and finding the video without the watermark, not just how to use your API.

He just queries someone's API. His code doesn't actually do it itself.

**Comment by jcohenho** [comment]
@Zipdox I think they are the creator of that API - It seems like @ahmed-zekri is not willing to share their methods.

**Comment by Zipdox** [comment]
> @Zipdox I think they are the creator of that API - It seems like @ahmed-zekri is not willing to share their methods.

I highly doubt that.

**Comment by davidteather** [comment]
Their script just takes the links and runs them through https://snaptik.app/en

**Comment by M1kep** [comment]
@davidteather It looks like https://github.com/Evil0ctal/Douyin_TikTok_Download_API/blob/6ecd2e93b32309ba7bc4f2c4d9c8b03c2cb4c582/scraper.py#L192-L202 is able to do this? Is the `aweme.snssdk.com` also a 3rd party? `snsdk.com` redirects to `toutiao.com` which is owned by ByteDance, so possibly legitimate?

**Comment by whqwert** [comment]
https://github.com/Evil0ctal/Douyin_TikTok_Download_API/blob/main/scraper.py#L395

https://tiktokv.com/aweme/v1/feed/?aweme_id=<id\>
No-watermark URLs are stored in `aweme_list[0].video.play_addr.url_list`

**Comment by Ahelsamahy** [comment]
I managed to make a class that can download trending tiktok videos without the watermark
``` python
import asyncio
import aiohttp
from TikTokApi import TikTokApi
from yt_dlp import YoutubeDL
import os
from datetime import datetime

class TikTokDownloader:
    def __init__(self, ms_token):
        self.ms_token = ms_token
        # Ensure the download directory with today's date exists
        self.download_directory = datetime.now().strftime("%Y-%m-%d")
        os.makedirs(self.download_directory, exist_ok=True)
        self.ydl_opts = {
            "format": "best",
            "outtmpl": os.path.join(self.download_directory, "%(title)s.%(ext)s")
        }

    async def get_video_url_list_and_desc(self, video_id):
        url = f"https://api16-normal-c-useast2a.tiktokv.com/aweme/v1/feed/?aweme_id={video_id}"
        async with aiohttp.ClientSession() as session:
            async with session.get(url) as response:
                if response.status == 200:
                    data = await response.json()
                    url_list = data["aweme_list"][0]["video"]["play_addr"]["url_list"]
                    description = data["aweme_list"][0]["desc"]
                    return url_list, description
                else:
                    print("Failed to retrieve video URL list")
                    return [], ""

    async def download_video(self, url_list, video_title):
        # Pass metadata options to YoutubeDL
        for url in url_list:
            try:
                with YoutubeDL(self.ydl_opts) as ydl:
                    ydl.download([url])
                print(f"Download successful for {video_title}")
                break
            except Exception as e:
                print(f"Failed to download {video_title} from {url}, trying next URL.")
                continue

    async def trending_videos(self):
        async with TikTokApi() as api:
            await api.create_sessions(
                ms_tokens=[self.ms_token],
                num_sessions=1,
                sleep_after=3,
                headless=False,
                suppress_resource_load_types=["image", "media", "font", "stylesheet"],
            )

            async for video in api.trending.videos():
                url_list, description = await self.get_video_url_list_and_desc(video.id)
                video_title = f"{video.author.username}_{video.id}"

                if url_list:
                    await self.download_video(url_list, video_title)

if __name__ == "__main__":
    ms_token = ""  # get your own ms_token from your cookies on tiktok.com
    downloader = TikTokDownloader(ms_token)
    asyncio.run(downloader.trending_videos())

```
Thanks to https://github.com/n0l3r/tiktok-downloader/blob/265506741d5d489f19fca8657c6a74ad9a006fa2/index.js#L124
