### ISSUE TITLE
[FEATURE_REQUEST] - Accessing private tik toks

### ISSUE THREAD

**Issue by alanblue2000** [davidteather/TikTok-Api#629]
Unable to access private tik toks.

Running V.3.9.9 - have manually entered verifyFp cookie from logged in account with access to private content in question; working fine for public tik toks but for privates just runs and stops with no triggered error messages.

I know variations of this topic have been discussed in past, any functionality as of June 2021?

Also noticed class TikTokUser which seems relevant. Any help appreciated.

**Comment by davidteather** [comment]
Currently the package doesn't support any logged in functions
