### ISSUE TITLE
tiktok_api.byHashtag  itemList error

### ISSUE THREAD

**Issue by 18272841175** [davidteather/TikTok-Api#630]
File "/home/cadmin/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 960, in by_hashtag
    for t in res["itemList"]:
KeyError: 'itemList'

code：
tiktok_api.byHashtag('shopcider',count=2000)

**Comment by gabiherman** [comment]
Also having this bug, replicates for any by_Hashtag with a count over 35.

**Comment by eric-hochberger** [comment]
Have you tried using version 3.9.9.1? This error no longer shows up for me using that version, however I'm consistently getting under 100 results now regardless of the count specified.

**Comment by wangzsPalpitate** [comment]
> 您是否尝试过使用 3.9.9.1 版？使用该版本不再出现此错误，但是无论指定的计数如何，我现在始终获得低于 100 个结果。

Me, too, can only get 75 data

**Comment by wangzsPalpitate** [comment]
> 您是否尝试过使用 3.9.9.1 版？使用该版本不再出现此错误，但是无论指定的计数如何，我现在始终获得低于 100 个结果。

Have you solved it

**Comment by wangzsPalpitate** [comment]
> 也有这个错误，复制任何计数超过 35 的 by_Hashtag。

Have you solved it？

**Comment by dylancaponi** [comment]
I think this issue was solved by 3.9.9.1 and can be closed.

There is a separate issue for now only getting a reduced number of hashtag results: https://github.com/davidteather/TikTok-Api/issues/637
