### ISSUE TITLE
byHashtag not working anymore

### ISSUE THREAD

**Issue by jp-wagner** [davidteather/TikTok-Api#631]
Like the title states, byHashtag is not working for me anymore at least for more than the first few tiktoks. Sorry if this is too vague, I haven't had time to look into it much. I'm mainly trying to find out if others are having the same problem as well. byUsername seems to be working fine. Any input/help is appreciated!

**Comment by 18272841175** [comment]
me too

**Comment by JorgeVF01** [comment]
I use `api = TikTokApi.get_instance(custom_verifyFp="...", use_test_endpoints=True)` and it works for me, however sometimes it returns outdated results, e.g. with `api.discover_hashtags()` .

**Comment by llacb47** [comment]
idk who came up with the idea that t stands for test but it's not true.

**Comment by jp-wagner** [comment]
> I use `api = TikTokApi.get_instance(custom_verifyFp="...", use_test_endpoints=True)` and it works for me, using `use_test_endpoints=True` will work with almost every `custom_verifyFp` string, however that pings with TikTok's test servers so sometimes you could get outdated results, e.g. with `api.discover_hashtags()` .

This is exactly what I use. Still, not getting a response after the first few TikToks with byHashtag. Are you sure you're getting a proper response when using:
`api.byHashtag(hashtag, count=2000, custom_verifyFp=self.custom_verifyFp, custom_did=self.did)`

**Comment by jp-wagner** [comment]
> > > I use `api = TikTokApi.get_instance(custom_verifyFp="...", use_test_endpoints=True)` and it works for me, using `use_test_endpoints=True` will work with almost every `custom_verifyFp` string, however that pings with TikTok's test servers so sometimes you could get outdated results, e.g. with `api.discover_hashtags()` .
> > 
> > 
> > This is exactly what I use. Still, not getting a response after the first few TikToks with byHashtag. Are you sure you're getting a proper response when using:
> > `api.byHashtag(hashtag, count=2000, custom_verifyFp=self.custom_verifyFp, custom_did=self.did)`
> 
> Would be easier helping you if you paste the response you are getting.

Two proper responses then:

`{'statusCode': 0, 'cursor': '105', 'hasMore': False}`

**Comment by JorgeVF01** [comment]
> > > > I use `api = TikTokApi.get_instance(custom_verifyFp="...", use_test_endpoints=True)` and it works for me, using `use_test_endpoints=True` will work with almost every `custom_verifyFp` string, however that pings with TikTok's test servers so sometimes you could get outdated results, e.g. with `api.discover_hashtags()` .
> > > 
> > > 
> > > This is exactly what I use. Still, not getting a response after the first few TikToks with byHashtag. Are you sure you're getting a proper response when using:
> > > `api.byHashtag(hashtag, count=2000, custom_verifyFp=self.custom_verifyFp, custom_did=self.did)`
> > 
> > 
> > Would be easier helping you if you paste the response you are getting.
> 
> Two proper responses then:
> 
> `{'statusCode': 0, 'cursor': '105', 'hasMore': False}`

Searching in closed issues maybe your verifyFp has expired or you are reaching a limit of queries. See #539

**Comment by jp-wagner** [comment]
> Searching in closed issues maybe your verifyFp has expired or you are reaching a limit of queries. See #539

Assuming you still use the verifyFp from http://sf16-scmcdn-va.ibytedtos.com/goofy/secsdk-captcha/va/2.15.21/index.html neither of those should be the case, as I've tried it with 20 different cookies from different proxies. Limit was usually around 2000 and I'm not getting close to that.

**Comment by jp-wagner** [comment]
Now please let me know if you're able to get the usual 2000 TikToks (byHashtag(count=2000)) or if your program only runs fine because you have your count set to like 20.

**Comment by JorgeVF01** [comment]
> @JorgeVF01
> Now please let me know if you're able to get the usual 2000 TikToks (byHashtag(count=2000)) or if your program only runs fine because you have your count set to like 20.

I had the same verifyFp like for the last 5 days and it worked with 50 TikToks, I refreshed the verifyFp and the first time I got 100 TikToks but now it can handle less than 50.

**Comment by jp-wagner** [comment]
@JorgeVF01 
Yes that's what I thought, seems to be a universal problem.

**Comment by davidteather** [comment]
@llacb47 
> idk who came up with the idea that t stands for test but it's not true.
May I ask what you believe the `t.tiktok.com` domain is for?

It seems like maybe TikTok is being more rigourous on IPs for verifyFps? I'm using an older one that I had to do captcha for and it seems to work fine with `use_test_endpoints=False`

**Comment by 18272841175** [comment]
On my side, the mistake is:
  File "/home/cadmin/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 960, in by_hashtag
    for t in res["itemList"]:
KeyError: 'itemList'

**Comment by jp-wagner** [comment]
> @llacb47
> 
> > idk who came up with the idea that t stands for test but it's not true.
> > May I ask what you believe the `t.tiktok.com` domain is for?
> 
> It seems like maybe TikTok is being more rigourous on IPs for verifyFps? I'm using an older one that I had to do captcha for and it seems to work fine with `use_test_endpoints=False`

Thank you so much, this seems to work. Closing!

**Comment by davidteather** [comment]
> On my side, the mistake is:
>   File "/home/cadmin/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 960, in by_hashtag
>     for t in res["itemList"]:
> KeyError: 'itemList'

Yeah I’ll be releasing a fix for that soon

**Comment by 18272841175** [comment]
> > 在我这边，错误是：
> > 文件“/home/cadmin/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py”，第960行，在by_hashtag 
> > for t in res["itemList"]：
> > KeyError: 'itemList'
> 
> 是的，我很快就会发布修复程序

Thank you very much

**Comment by gabiherman** [comment]
Thanks so much for developing this package! When do you think the fix will be released? Just wondering due to a deadline I have :)

**Comment by a1d4r** [comment]
> Thanks so much for developing this package! When do you think the fix will be released for the itemList KeyError? Just wondering due to a deadline I have :)

I think you have to check nightly branch :)

**Comment by jp-wagner** [comment]
@davidteather Seems like `use_test_endpoints=False` doesn't work anymore and `use_test_endpoints=True` only gets 20 or so TikToks with byHashtag. Any fixes you are aware of? Appreciate the effort, thank you!
