### ISSUE TITLE
Do I need chromedriver inside Docker? Or should I pull playwright's image

### ISSUE THREAD

**Issue by alvaroserrrano** [davidteather/TikTok-Api#634]
### Discussed in https://github.com/davidteather/TikTok-Api/discussions/633

<div type='discussions-op-text'>

<sup>Originally posted by **alvaroserrrano** June 25, 2021</sup>
I would like to use a Docker container for an application. I am currently installing chromedriver inside the docker container because the api said "chromedriver needs to be in path". Is this step really necessary? Could that be the reason why I am having a conflict with playwright to which I get the log ```"please run python -m install playwright"``` (which does not make sense). I have also seen people say that there is a conflict between playwright and pyppeteer, but I do not think my problem is related to that.

As of right now I am installing requirements as usual and the running python -m playwright install, which I believe is redundant and not really necessary. 

Also, I can see that Dockerfile of the api pulls from the microfts/playwright image and then installs python3-pip. Do I have to use this in my Dockerfile? My base image is FROM python3.8. Perhaps I should create a virtual environment inside the container?

Thanks a lot for your help</div>

**Comment by davidteather** [comment]
I don't think the base of `python3.8` will work because for playwright to work is needs some system wide dependencies so it's probably better just to pull from playwright.
