### ISSUE TITLE
Access Denied- hashtag video play address (playAddr) is different from trending

### ISSUE THREAD

**Issue by Muhammad-Abbas786** [davidteather/TikTok-Api#636]
### Hashtag Video play address is not in a supported format

I'm working on a virtual env and install TikTok-API using the command
`pip install TikTokApi` 
after that when I tried to execute the below command it didn't install anything(it didn't show anything on the terminal)
`python -m playwright install`

after that when I run a python file to get trending video it executes perfectly and it provides the video play address(playAddr) in the given format below which plays the video perfectly.
`https://v16m.tiktokcdn.com/bf6fd3347f360e59f73e61e006a79784/60db6d3c/video/tos/useast2a/tos-useast2a-pve-0068/39d2303d79954e9b86f2b1974b67dfa0/?a=1233&br=1800&bt=900&cd=0%7C0%7C1&ch=0&cr=0&cs=0&cv=1&dr=0&ds=3&er=&l=202106291257530101890741013C11A9D8&lr=tiktok_m&mime_type=video_mp4&net=0&pl=0&qs=0&rc=anhuNzRmdDhyNjMzNzczM0ApaDQ8ZDw0O2Q3NzdlNjNkNGcvNWtiXmltL15gLS1kMTZzczUyYDY0NDEvXzQtLV8xNC46Yw%3D%3D&vl=&vr=`
but when I tried to get the hashtag video play address it provides the address in the given format
`https://v16-web.tiktok.com/video/tos/useast2a/tos-useast2a-pve-0068/895e3eeb356c4b00830617514f0e177b/?a=1988&br=1242&bt=621&cd=0%7C0%7C1&ch=0&cr=0&cs=0&cv=1&dr=0&ds=3&er=&expire=1624993263&l=202106291300050101150790571E11455B&lr=tiktok_m&mime_type=video_mp4&net=0&pl=0&policy=2&qs=0&rc=am5uamk4a3FkNDMzNzczM0ApOWZlOjQ5ZDxkN2lkZGc8NGcuXzBhcy4uL2xgLS1kMTZzcy4wYy8wYi9jYzA0LzMwLTE6Yw%3D%3D&signature=65f51987fc4949529f5ccb015d143da2&tk=tt_webid_v2&vl=&vr=`
by hitting this URL on the firefox browser it shows the message 

> No video with supported format and MIME type found

kindly guide me on how do I get a supported video URL address

The part of the code I'm using is 

`api = TikTokApi.get_instance(custom_verifyfp=verifyfp, use_test_endpoints=True, custom_did=did)`
`count = 10`
`tag = input("Enter Hashtag :\n")`
`tiktoks = api.byHashtag(tag, count=count)`

Also, how can I get the country name from where the video is uploaded?
Thanks and Regards,

**Comment by surenjanath** [comment]
I'm getting 403 error code when using requests and same with browser used trending sounds and same error when trying to play the video

**Comment by tommywxd** [comment]
same issue here

**Comment by ThomasThatcher** [comment]
Same issue here

**Comment by TeemoHQ** [comment]
Same issue here

**Comment by oneamanorgy** [comment]
I'm just trying to pull a list of profile urls sourced from .com/tag/anytag, and stop copying profile urls after a certain result of video as it could be 100,000's Not sure what to do.

**Comment by davidteather** [comment]
There might've been a few issues with downloading videos earlier, updated a new release with some new naming conventions. Feel free to read about how to convert and upgrade [V4.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V4.0.0)

The URLS might differ and they all have expirations tied to them so you'll have to download them using library functions.
