### ISSUE TITLE
Im getting an error accessing the api

### ISSUE THREAD

**Issue by one-loop** [davidteather/TikTok-Api#638]
**Describe the bug**

When I run the default code to get trending tiktoks, i get an error instead

  **The buggy code**

```
from TikTokApi import TikTokApi

verifyFp = "verify_kqrwj2pj_vXrxzDbH_FkNQ_4WMC_BfiM_AtILtDTices5"
api = TikTokApi.get_instance(custom_verifyFp=verifyFp, use_test_endpoints=True)

tiktoks = api.trending()
print(tiktoks)
```

**Expected behavior**
Im expecting to get trending tiktoks for a project I'm working on

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
Traceback (most recent call last):
  File "D:\Programming\Python\CONTENT BOT\tiktok bot.py", line 22, in <module>
    tiktoks = api.trending()
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\TikTokApi\tiktok.py", line 341, in trending
    if not res["hasMore"] and not first:
KeyError: 'hasMore'
[Finished in 17.359s]
```

**Desktop (please complete the following information):**
 - OS: e.g. Windows 10
 - TikTokApi Version e.g. 3.3.1 - if out of date upgrade before posting an issue

**Comment by llacb47** [comment]
update to latest version of the package

**Comment by one-loop** [comment]
Ok thank you, I had to fix some playwright issues but it worked 🙂
