### ISSUE TITLE
[INSTALLATION] - Your error here

### ISSUE THREAD

**Issue by one-loop** [davidteather/TikTok-Api#639]
Is there a way of routing the python through a proxy and getting trending tik toks in another country (e.g. UK). I know the documentation says something about using a proxy, but there is no code example for it. Can someone please provide a code example on how you would get trending tik toks from a different country?

**Comment by davidteather** [comment]
`TikTokApi.get_instance(proxy="https://0.0.0.0:8080")` further information on the [docs](https://davidteather.github.io/TikTok-Api/docs/TikTokApi/tiktok.html)
