### ISSUE TITLE
[BUG] - get_recommended_tiktoks_by_video_id appears to return unrelated video regardless of id parameter

### ISSUE THREAD

**Issue by benfwalla** [davidteather/TikTok-Api#640]
**Describe the bug**

I've been playing around with `get_recommended_tiktoks_by_video_id()`, and the method is returning a slightly random list of TikTok videos that have nothing to do with the videos I input. I've tried multiple video IDs that have no relation to one another, and I noticed that I'm getting the same response videos. 

I reviewed the [source code](https://github.com/davidteather/TikTok-Api/blob/d4b912f49a26b5dbfc19fc55bf40e5758e6ef966/TikTokApi/tiktok.py#L996) of this function, and I noticed that the `id` parameter isn't even used in the function. This could be me misreading the code, or a contributor forgot to replace something while testing. 

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()

api.get_recommended_tiktoks_by_video_id('6966201066727820549', 2)
api.get_recommended_tiktoks_by_video_id('6811320489248558341', 2)
```

**Expected behavior**

I expected the method to return a unique list of TikTok videos that are reasonably related to the input video id based on TikTok's algorithm.

**Error Trace (if any)**

No errors: just unexpected behavior

**Desktop (please complete the following information):**
 - OS: macOS Big Sur (Version 11.4)
 - TikTokApi Version [e.g. 3.3.1] - 3.9.9.1

**Comment by davidteather** [comment]
I suspect this is a limitation of TikToks servers. I doubt the recommended videos differ too much from each other and probably just show trending or something.

**Comment by benfwalla** [comment]
@davidteather - what are your thoughts on the `id` parameter in your function not being referenced anywhere? Again, I could be misreading it, but that looks like a telling sign that your TikTok endpoint doesn't have any knowledge of what video id I'm passing.

**Comment by davidteather** [comment]
Ah yeah I didn't realize it wasn't referenced anywhere anymore.
I looked at TikTok's website and their API request also no longer passed in a video ID, and the section has been renamed to "Browse more For You videos". So I guess it's just doing a trending API call instead but is still `/recommend` so I don't know what they're doing with their naming convention.

**Comment by benfwalla** [comment]
That stinks. Maybe I'll take a deeper look into TikTok and see if there was something that replaced it! In the meantime, I recommend removing the function from this library.
