### ISSUE TITLE
[BUG] - Cannot switch to a different thread

### ISSUE THREAD

**Issue by alvaroserrrano** [davidteather/TikTok-Api#641]
I keep getting the error: "Cannot switch to a different thread" every time that I run this function. I have related issues but none of them contained a working solution. Moving the api inside the function does not solve it. Using monkey.patchall() did not solve it either
```
class TikTokFunctions:
    api: TikTokApi = TikTokApi.get_instance(use_test_endpoints=True)
    def get_tiktok_by_username(
        self, username: str, results: int, from_date: Optional[date]
    ) -> List[Dict[str, Any]]:
        tiktoks = self.api.by_username(username, count=results)
        print(tiktoks)
```

**Comment by Auth0rM0rgan** [comment]
@davidteather @alvaroserrrano, I am facing the same problem, and `monkey.patchall()` or moving the API inside of the method is not working. any solution?

**Comment by davidteather** [comment]
#576
