### ISSUE TITLE
AttributeError: type object 'TikTokApi' has no attribute 'get_instance'

### ISSUE THREAD

**Issue by etale-cohomology** [davidteather/TikTok-Api#643]
After successfully running `pip install TikTokApi`, I try running:

```Python
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()
```

but I get:

```
Traceback (most recent call last):
  File "tt00.py", line 2, in <module>
    api = TikTokApi.get_instance()
AttributeError: type object 'TikTokApi' has no attribute 'get_instance'
```

I also tried `pip36 install TikTokApi --upgrade`, but it didn't help.

**Comment by jumbo77** [comment]
Same Problem

**Comment by Merkie** [comment]
same issue

**Comment by davidteather** [comment]
Only thing I can think of is maybe if you're accidentally using [this](https://github.com/avilash/TikTokAPI-Python) package which kinda uses the same name as mine. If that doesn't work try to make a virtual environment for python.

**Comment by etale-cohomology** [comment]
@davidteather No, I'm not, that package isn't even installed

**Comment by nightduck** [comment]
I also can't get it to work on my default system (Ubuntu Focal with python3.6)

I can, however, get it working in a Docker container based on python:3, which uses python3.9

**Comment by davidteather** [comment]
You have to be on python 3.7+ older versions

Didn’t realize people were using 3.6
