### ISSUE TITLE
Can't import the Tiktokapi library

### ISSUE THREAD

**Issue by shikk** [davidteather/TikTok-Api#644]
Describe the bug

Can't import the Tiktokapi library, error msg is "ModuleNotFoundError: No module named 'TikTokAPI' "

The buggy code

from TikTokApi import TikTokapi
api = TikTokapi.get_instance()

error trace:
`
Traceback (most recent call last):
  File "/Users/shikk/Documents/vue_workspace/python/tiktok/tik_donwloader.py", line 1, in <module>
    from TikTokApi import TikTokapi
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/TikTokApi/__init__.py", line 1, in <module>
    from TikTokAPI.tiktokapi import TikTokAPI
ModuleNotFoundError: No module named 'TikTokAPI'
`

Expected behavior

Screenshots

none

Desktop (please complete the following information):

OS:  Mac OS
Browser safari
Version   12.1.1 

Additional context

1、 I have installed all necessary libraries from ' requirement.txt ',
2、It also does not work : "from tiktok import TikTokapi" 
3、And library 'playwright ' is installed too.

**Comment by JAVAB3ANS** [comment]
do `from TikTokApi import TikTokApi` that should work
