### ISSUE TITLE
Add a function that automatically retrieves the verifyFp parameter

### ISSUE THREAD

**Issue by wangzsPalpitate** [davidteather/TikTok-Api#647]
Thank you very much for your project. It would be a great experience for me to add a function to automatically retrieve the verifyFp parameter, since verifyFp can expire, resulting in captcha or error during the crawl

**Comment by wangzsPalpitate** [comment]
from playwright.sync_api import sync_playwright as playwright
import json


def get_verify():
    with playwright() as pw:
        webkit = pw.webkit.launch(timeout=10000,headless=True)
        context = webkit.new_context()  # 需要创建一个 context
        page = context.new_page()  # 创建一个新的页面
        page.goto("http://icanhazip.com/")
        print(page.content())
        page.goto("https://www.tiktok.com/")
        # 保存状态
        storage = context.storage_state()
        print(storage)
        webkit.close()
        for i in storage['cookies']:
            if 's_v_web_id' in json.dumps(i):
                print(i.get('value'))
                return i.get('value')

if __name__ == '__main__':
    get_verify()

this is my code

**Comment by BarBQ-code** [comment]
Hey @wangzsPalpitate I copied your code, and it seems to work on the first run, but then it can't find the cookie, does it work consistently for you? Or do you know why I encounter this problem?

**Comment by davidteather** [comment]
Just so people are aware verifyFp is kinda like a captcha token so if TikTok detects that you're doing this it'll give you an invalid or useless verifyFp.

**Comment by wangzsPalpitate** [comment]
> 嘿@wangzsPalpitate我复制了你的代码，它似乎在第一次运行时可以工作，但是它找不到 cookie，它对你来说是否始终如一？或者你知道我为什么会遇到这个问题吗？

You need to add a proxy, which does not get the cookie every time

**Comment by getsec** [comment]
@wangzsPalpitate . Just write a wrapper to log into to Tiktok from your machine using requests, or something like playwright or selenium.

**Comment by davidteather** [comment]
Not sure verifyFp needed anymore with V5
