### ISSUE TITLE
Find most popular tiktok videos for hashtag

### ISSUE THREAD

**Issue by socialmediaguy** [davidteather/TikTok-Api#65]
Hi,
How do i use this to find most popular videos for a given hashtag? 

Can anyone help me ith a quick script and usage syntax? 

thanks so much

**Comment by socialmediaguy** [comment]
@davidteather

**Comment by socialmediaguy** [comment]
sorry it is nto a bug but feature request. i don't know how to change it now

**Comment by davidteather** [comment]
I have plans to search for by hashtag in the future, but right now the function is broken. There's a new version of the api that has the other functions working right now.

**Comment by dehidehidehi** [comment]
> I have plans to search for by hashtag in the future, but right now the function is broken. There's a new version of the api that has the other functions working right now.

Thanks for the follow-up, I did notice a prior version of your code did have this function. The search by hashtags would be a great feature

**Comment by davidteather** [comment]
Added with byHashtag('funny') in the new update. Upgrade with the following command.

```
pip install TikTokApi --upgrade
```
