### ISSUE TITLE
'TikTokApi' object has no attribute 'region'tagtagtagtag

### ISSUE THREAD

**Issue by michael01810** [davidteather/TikTok-Api#652]
When I tried 
api.by_hashtag('test')

or a few other functions, I got the error:  'TikTokApi' object has no attribute 'region'tagtagtagtag

However, api.get_user('test') works for me

A few other functions that run into the 'region' error

api.by_trending()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-f4af7f86df90> in <module>
----> 1 api.by_trending()

~\anaconda3\lib\site-packages\TikTokApi\tiktok.py in by_trending(self, count, **kwargs)
    424             }
    425             api_url = "{}api/recommend/item_list/?{}&{}".format(
--> 426                 BASE_URL, self.__add_url_params__(), urlencode(query)
    427             )
    428             res = self.get_data(url=api_url, **kwargs)

~\anaconda3\lib\site-packages\TikTokApi\tiktok.py in __add_url_params__(self)
   1653             "device_platform": "web_mobile",
   1654             # "device_id": random.randint(),
-> 1655             "region": self.region or "US",
   1656             "priority_region": "",
   1657             "os": "ios",

AttributeError: 'TikTokApi' object has no attribute 'region'

**Comment by davidteather** [comment]
Should be fixed [V4.0.1](https://github.com/davidteather/TikTok-Api/releases/tag/V4.0.1)

**Comment by michael01810** [comment]
Really appreciate this David, also got your LinkedIn reply. I was able to
get v 4.0.1 but unfortunately having the same problem (get_user works but
most of the other functions are getting the 'region' error). Will take a
look on my end as well to see if I can figure this out.

[image: image.png]

**Comment by esteebie** [comment]
Hi there, I am having the same issue. get_user() works fine but nothing else.

I am using Anaconda rather than the venv suggested, so don't know if there is some complication with playwright or whether sync/async should be imported?

Commenting out the 'region' line in tiktok.py that causes the error results in similar errors for 'width', 'height' etc and then in line 235 _'TikTokApi' object has no attribute 'browser'_ - which seems a bit more fundamental!?

Any help much appreciated.

Thanks

**Comment by esteebie** [comment]
Thanks, all good except on PC visual studio won't run the activate command! Guessing you didn't have the issue on your mac!?

>activate
The command activate was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\activate"

>.\activate

.\activate : File C:\Users\User\env\Scripts\activate.ps1 cannot be loaded. The 
file C:\Users\User\env\Scripts\activate.ps1 is not digitally signed. You        
cannot run this script on the current system.

**Comment by esteebie** [comment]
Got it to work by running virtualenv in command prompt and running python script from in there... except now it's stopped working, I suspect because it's blocking the verifyFP token generated for my machine/IP address. Very frustrating!

**Comment by mina9999** [comment]
https://github.com/davidteather/TikTok-Api/issues/672

**Comment by Evanskip31** [comment]
Why you'll closing these questions so early without a working answer?
