### ISSUE TITLE
Please follow Semver

### ISSUE THREAD

**Issue by pierreminiggio** [davidteather/TikTok-Api#661]
Hello !
Just noticed that the byUsername method got renamed to by_username recently.
Would be apreciated if that change was specified in one of the releases (looked into them, haven't seen a mention of that renamed method).

And since it's a breaking change, it would probably have been best to make that change in a major version (cf  SemVer https://semver.org/).

Also, thanks for that awesome library ! It saved me a lot of time to build stuff I wanted to see alive ! ♥

**Comment by davidteather** [comment]
[V4.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V4.0.0)

> Fully deprecate old naming convention
> ### How to update from V3 to V4
>1. Replace all camel case functions with snake case)
>      Ex: `getUserObject` -> `get_user_object`
>2. Change `custom_did` to `custom_device_id`
>      This change better reflects what's going on in the frontend.
