### ISSUE TITLE
[BUG] - Your Error Here

### ISSUE THREAD

**Issue by MuhammedEminK** [davidteather/TikTok-Api#664]
from TikTokApi import TikTokApi, tiktok, tiktokuser

verifyFp = "verify_ksacm7aa_SFqFv3KS_pyXm_4tmt_9gDa_PaiwczFdnXud"
custom = 2000
api = TikTokApi.get_instance(custom_verifyFp=verifyFp,custom=custom,use_test_endpoints=True, )

tiktoks = api.trending()

for i in tiktoks:
    print(i["author"]["uniqueId"])

only gets @tiktok as user

**Comment by davidteather** [comment]
#665
