### ISSUE TITLE
[BUG] - Your Error Here

### ISSUE THREAD

**Issue by MuhammedEminK** [davidteather/TikTok-Api#666]
from TikTokApi import TikTokApi, tiktok
import string
import random
verifyFp = "verify_kqy6jjat_z1LBe7j9_phoI_**************"
did = "".join(random.choice(string.digits)for num in range(19))
result = 1000
api = TikTokApi.get_instance(count=result,custom_verifyFp=verifyFp,use_test_endpoints=True,custom_did=did)
tiktoks = api.trending()
for i in tiktoks:
	print(i['music']['playUrl'])
----------------------------------------------------------------------------------------------------------------------------------------------
'TikTokApi' object has no attribute 'trending'  before that, uniqueID was always giving as tiktok, i deleted tiktokapi and reloaded, i deleted playwright and reloaded but y-same error continues

**Comment by shshnk158** [comment]
Hi @MuhammedEminK , its not api.trending(), there is no method with trending, use **api.by_trending()** instead of **api.trending()**
