### ISSUE TITLE
[FEATURE_REQUEST] - Get download_url instead of bytes

### ISSUE THREAD

**Issue by AlberLC** [davidteather/TikTok-Api#667]
**Is your feature request related to a problem? Please describe.**
It would be very useful to work with the download_url instead of bytes. Example: in Telegram I can instantly send the video by sending the download_url. Sending bytes is very slow.

**Describe the solution you'd like**
```
def get_download_url_by_url(self, video_url, **kwargs) -> bytes:
    """Downloads a TikTok video download_url by a URL

    ##### Parameters
    * video_url: The TikTok url to download the video from
    """
    (
        region,
        language,
        proxy,
        maxCount,
        device_id,
    ) = self.__process_kwargs__(kwargs)
    kwargs["custom_device_id"] = device_id

    tiktok_schema = self.get_tiktok_by_url(video_url, **kwargs)
    return tiktok_schema["itemInfo"]["itemStruct"]["video"]["downloadAddr"]
```

**Comment by llacb47** [comment]
yes, but the URL expires

**Comment by AlberLC** [comment]
Yes, but is faster send a string by http instead bytes. Then receiver can download and send the video. Telegram send the video with a url, for example.

**Comment by davidteather** [comment]
Download url is in the video dictionary
