### ISSUE TITLE
Add a feature to get the user's favorited sounds

### ISSUE THREAD

**Issue by ellali824** [davidteather/TikTok-Api#67]
I want to write a program that involves getting a tik tok's user's favorite sounds. I was wondering if you could add this feature?

**Comment by davidteather** [comment]
I currently don't have plans to add any plans to add a user login system in the near future.

If you're asking about getting any user's favorite sounds, it doesn't look like I can do that at least from desktop, so a work around might be just to get a list of the user's tiktoks and the "favorite" sounds are the ones that are used the most.
