### ISSUE TITLE
How to use proxy with api key or access token?

### ISSUE THREAD

**Issue by Incher25** [davidteather/TikTok-Api#671]
Hi,
I try to use TikTokApi via Zenscrape proxy, so according it's documentation I must provide my api key as one of request's headers.
Here is a request example from zenscrape.com:

```
import requests

headers = { 
    "apikey": "xxxxxxxxxxxx"
}

params = (
   ("url","https://freegeoip.app/json/"),
);

response = requests.get('https://app.zenscrape.com/api/v1/get', headers=headers, params=params);
print(response.text)
```
And it works fine, but is it possible to pass proxy api key into TikTokApi.get_instance() or api.by_username() method? Or should I fork TikTokApi library and modify some request methods to make it work?

**Comment by Aditya-Rajgor** [comment]
I am having a similar kind of problem. 
I have proxies that require passing the `verify` param which takes the verification file path inside the `requests.get` method.
We have the option to pass other params for the requests but I don't know how to use that

```python
api = TikTokApi()
api.proxy = 'ip:port'
api.requests_extra_kwargs = ?
```

Have you solved your issue? @Incher25
