### ISSUE TITLE
'TikTokApi' object has no attribute 'region'

### ISSUE THREAD

**Issue by ahmerafzal** [davidteather/TikTok-Api#672]

**Comment by diego7319** [comment]
me too
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 1087, in get_tiktok_by_id
    BASE_URL, self.__add_url_params__(), urlencode(query)
  File "/usr/local/lib/python3.8/dist-packages/TikTokApi/tiktok.py", line 1653, in __add_url_params__
    "region": self.region or "US",
AttributeError: 'TikTokApi' object has no attribute 'region`

**Comment by diego7319** [comment]
Im using the version 3.9.8 as a workaround, other versions above 3.9.8 give me AttributeError 'width' error and the last one 4.0.1 AttributeError region , pip install TikTokApi==3.9.8 works

**Comment by ahmerafzal** [comment]
Hello diego7319
with version 3.9.8 i am facing this issue
<launching> /ms-playwright/webkit-1530/pw_run.sh --inspector-pipe --headless --no-startup-window --proxy=http://138.128.59.225:9154
<launched> pid=6326
[pid=6326][err] /ms-playwright/webkit-1530/pw_run.sh: line 21:  6340 Killed                  WEBKIT_FORCE_COMPLEX_TEXT="1" "$MINIBROWSER" "$@"
[pid=6326] <process did exit: exitCode=137, signal=null>
[pid=6326] starting temporary directories cleanup
[pid=6326] finished temporary directories cleanup

**Comment by ahmerafzal** [comment]
If i use selenium "use_selenium=True"
facing this problem:
'TikTokApi' object has no attribute 'width'

**Comment by diego7319** [comment]
> If i use selenium "use_selenium=True"
> facing this problem:
> 'TikTokApi' object has no attribute 'width'

im using this package between a docker container with flask

`FROM mcr.microsoft.com/playwright:focal
ADD . /code
WORKDIR /code
RUN apt-get update && apt-get install -y python3-pip
RUN pip3 install requests flask TikTokApi==3.9.8 gevent
RUN python -m playwright install`

**Comment by a-donat** [comment]
I'm having the same issue

**Comment by Bolive84** [comment]
Me too same issue

**Comment by mina9999** [comment]
hi i have fix for error 'TikTokApi' object has no attribute 'width' and 'TikTokApi' object has no attribute region.
so first of all do python -m pip install 'tornado<5' 'notebook<5.7.9' 
and then do python -m pip install jupyterhub==0.9.0 or pip install jupyterhub==0.9.0 
enjoy<3.
