### ISSUE TITLE
[BUG] - "TikTokApi.exceptions.TikTokNotFoundError: Challenge/User] X does not exist" while it exists

### ISSUE THREAD

**Issue by SalamanderKrajza** [davidteather/TikTok-Api#674]
**Describe the bug**
While I am trying to get multiple objects with this api by using methods in loop it sometimes throws `TikTokNotFoundError: [Challenge/User] X does not exist`
Then, if code is restarted without any changes API is sometimes able to get desired data without this error

**The buggy code**
```py
for cnt, hashtag in enumerate(list_of_hashtags):
    print(f'{cnt}/{len(list_of_hashtags)} - {hashtag}')
    hashtag_object = api.get_hashtag_object(hashtag)
```

The same thing is with method by_username

**Expected behavior**
1. Getting desired object 
2. Get correct description of error, (f.e. `Unable to get data for [Challenge/User] X` instead of `[Challenge/User] X does not exist`

**Enviroment:**
 - Windows 10
 - TikTokApi==4.0.1
 - Code executed in virtual enviroment (With package installed by pip, without docker)

**Additional context**
For some cases i was able to fix this problem with adding "Try-Except" solution to retrying if data is not gathered while executing code first time:
```py
try:
    hashtag_object = api.get_hashtag_object(hashtag)
except:
    try:
        time.sleep(3)
        hashtag_object = api.get_hashtag_object(hashtag)
    except:
        try:
            time.sleep(30)
            hashtag_object = api.get_hashtag_object(hashtag)
        except:
            hashtag_object = None
```

However, this "fix" wasn't work with all cases (sometimes even waiting 30s was not enough to get desired results)

**Comment by davidteather** [comment]
Consolidating all discussion about `x-tt-params`, user_posts, and anything else related to this update to #695 for easier collaboration
