### ISSUE TITLE
KeyError: 'hasMore'

### ISSUE THREAD

**Issue by surenjanath** [davidteather/TikTok-Api#681]
**Describe the bug**

```
from TikTokApi import TikTokApi

api = TikTokApi.get_instance()
device_id = api.generate_device_id()
tiktoks = api.by_sound('6966808242676599558', count=10,custom_device_id=device_id)
```

**Expected behavior**
It was working a couple hours ago and now .. it's not 

**Error Trace (if any)**
```
File "/usr/local/lib/python3.7/dist-packages/TikTokApi/tiktok.py", line 858, in by_sound
    if not res["hasMore"]:
KeyError: 'hasMore'
```

Ok only this giving hasMore error. 
the method by_trending works ...
okay by_trending only returning 5 videos alone

**Comment by weavewillG** [comment]
I'm facing the same issue.

**Comment by weavewillG** [comment]
looks like the `/api/music/item_list` endpoint now requires `msToken`.
@davidteather any idea how to generate that token?

**Comment by surenjanath** [comment]
i ssee u trying something .. the mstoken is same as the xmst. it's stored in local storage

**Comment by surenjanath** [comment]
okay so what i've found is if u make normal request using 

```
header = {
'authority': 'm.tiktok.com',
'method': 'GET',
'scheme': 'https',
'accept': '*/*',
'accept-encoding': 'gzip, deflate, br',
'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36',
'x-tt-params' <MUST INCLUDE THIS>: 
}

url = 'https://m.tiktok.com/api/music/item_list/?msToken=....&X-Bogus=....&_signature=....'
r = requests.get(url, headers= header, allow_redirects= True)
r.json()
```

it works.. it must have the x-tt-params though.. they seemed to convert the musicID and count everything into a hash code :/

**Comment by martmalo** [comment]
when this will be fixed?

**Comment by alma359** [comment]
I have the same problem now.

**Comment by davidteather** [comment]
Consolidating all discussion about `x-tt-params`, user_posts, and anything else related to this update to #695 for easier collaboration
