### ISSUE TITLE
[BUG] - User Posts Breaking

### ISSUE THREAD

**Issue by isaackogan** [davidteather/TikTok-Api#685]
TikTok released a breaking error where the "ttwid" cookie is now required or **user requests** will fail.
The page for info about this is https://cookiedatabase.org/cookie/tiktok/ttwid/.

This is an example of the cookie value:
`1%7CHroxlZ5x7BxbDPCT5DPZnmKD5QOiwYNYG6PonvRcEDA%7C1630633125%7C6f27900c837adbe282f60db0b20ed571699e8ecbe4ab4ab979b4077f9d812e57`

Does this format ring any bells for anyone? Ideally we need to be able to create this cookie with the TikTok-Api client, or, input the cookie ourselves.

**Comment by asportnoy** [comment]
Copying over the info I found earlier (from above):
> The cookie is generated from a post request to https://www.tiktok.com/ttwid/check/ (set-cookie header). That request requires a `fid` parameter but I can't tell what generates that.

**Comment by MuffinFox** [comment]
I already implemented fetching ttwid, but that was not the solution.
It seems this only a blocking issue (again), suddenly it worked again for limited time. I think proxies are detected and then ip is banned. Also happens for user and music endpoints. For by_sound the endpoint was changed, see referenced ticket.

**Comment by MuffinFox** [comment]
see #690 for recent changes.

**Comment by davidteather** [comment]
Consolidating all discussion about `x-tt-params`, user_posts, and anything else related to this update to #695 for easier collaboration

**Comment by etale-cohomology** [comment]
@MuffinFox How did you implement fetching the ttwid? I do it by sending a GET request to the main page (tiktok.com). But I suspect sure there's an API-only way.
