### ISSUE TITLE
How can I get all videos posted by a specific user?

### ISSUE THREAD

**Issue by pyon-yx** [davidteather/TikTok-Api#686]
I tried to use user_posts(). Since this function supports count and cursor, I thought that I could use cursor for the pagination.
But whatever I set for cursor, I can get the same result (list of videos).
I want it should work in this way.
If a user posted 1000 videos, when I set count=30 and cursor=0, it will return the first 30 videos(from the 1st to the 30th).
When I set count=30 and cursor=1, then it will return the second 30 videos(from the 31st to the 60th),
But it does not work in this way.
Would you like to tell me how I can get the all videos posted by a specific user?
(According to the comment, I can get up to 2000 videos. What if over 2000 videos?)

**Comment by djmarioka** [comment]
I'd like to know how to get all the Tik Tok user's videos, also. 

Could you help us, David?.

Thanks for your great work.

**Comment by PhanNN** [comment]
@pyon-yx the cursor has the meaning as start position
if you want get the next page, you should pass the "cursor" from the prev response and create new request 

![image](https://user-images.githubusercontent.com/11443776/133714044-66956109-6db4-4053-bc27-b0698db70688.png)
For example: the first request, I pass cursor = 0, get 30 items, response will contain hasMore = true (has more data) and the next cursor (cursor = 31)
So for the second request, I will pass cursor = 31 and get next 30 items, ...

**Comment by pyon-yx** [comment]
@PhanNN I made it working. Thanks for your reply.

**Comment by magicub** [comment]
it used to be easier, actually there was an article about it https://towardsdatascience.com/how-to-collect-data-from-tiktok-tutorial-ab848b40d191
