### ISSUE TITLE
[BUG] - by_sound - empty result

### ISSUE THREAD

**Issue by MuffinFox** [davidteather/TikTok-Api#688]
due to some major tiktok changes `by_sound` is not returning results anymore.

empty response of api:

`
{'statusCode': 0}
`

Current state of investigation:

- first page of videos is rendered using __NEXT_DATA__ initial props
- subsequent api requests pass parameters using `x-tt-params` header (somehow encoded)
- ttwid cookie might be needed, page calls /ttwid/check (see also issue #685 )

**Comment by surenjanath** [comment]
here i've wrote this : [Medium TikTok Scrape](https://medium.com/@surenjanath.singh/scraping-hidden-api-with-python-requests-eg-tiktok-80f2daea8e5)
whenever @davidteather updates this.. just manually scrape it for time being :) 
I've found it don't need the cookie, also you would have to manually load the page and get the x-tt-params

**Comment by davidteather** [comment]
Consolidating all discussion about `x-tt-params`, user_posts, and anything else related to this update to #695 for easier collaboration
