### ISSUE TITLE
tiktok api object has no attribute byHashtag

### ISSUE THREAD

**Issue by udithanuwanw** [davidteather/TikTok-Api#689]
Hi got this error when run ,tiktok downloader

tiktok api object has no attribute byHashtag

**Comment by Syahrol13** [comment]
Try using by_hashtag() instead

**Comment by hwasiti** [comment]
This worked for me. Thanks @Syahrol13

**Comment by heiver13** [comment]
hello, I had the same error and with @hwasiti contribution I solved it but now I get the following error:

File "C:\Users\lenovo\Desktop\art\tiktokbot.py", line 163, in <module>
    b = api.get_Video_By_DownloadURL(
AttributeError: 'TikTokApi' object has no attribute 'get_Video_By_DownloadURL'

**Comment by Syahrol13** [comment]
@heiver13, use get_tiktok_by_url() instead. Most functions now use small letter after the update. you can check in the code for confirmation.

**Comment by heiver13** [comment]
ok, corrected but now I have this bug:
results[x]['itemInfos']['video']['urls'][0], custom_did=did)
KeyError: 'itemInfos'

**Comment by Syahrol13** [comment]
can i see your code?

**Comment by heiver13** [comment]
yes, https://github.com/davidteather/TikTokBot

**Comment by Syahrol13** [comment]
This is the same case as issue #296 i think, maybe you can check there.
