### ISSUE TITLE
[BUG] - user_posts endpoint does not work anymore

### ISSUE THREAD

**Issue by vdemay** [davidteather/TikTok-Api#690]
It seems tiktok changes the way to make request to get the list of user post. 

now request has the following format: 
https://m.tiktok.com/api/post/item_list/?msToken=_____&X-Bogus=_____&_signature=_____

I'm going to investigate this deeper, but any help is appreciated

**Comment by iTingle** [comment]
the same question, still have no idea

**Comment by MuffinFox** [comment]
they changed it to same format as used for music videos, with x-tt-params header and obfuscated payload. see #688 for initial investigation, i guess it will be a lot of try and error to find the correct key / iv for encrypting the params.

**Comment by callMeMakerRen** [comment]
x-bugus seems generate by `window.byted_acrawler.frontierSign("aaa") => {X-Bogus: 'RkWhY1g5s/20PSyl'}` ,not sure what param is needed ,keep search

**Comment by MuffinFox** [comment]
some more insights:

- for initialisation of parameter encryption there is a call to window._$jsvmprt(a, b, c) with some hardcoded string (key?)
- window._fetch is a patched fetch which adds some additional functionality
- crypthojs lib is used for obfuscation

**Comment by fracogno** [comment]
https://www.influencerhunters.com/apis/tt/user/info?token=GQ96yJKZn3hWpQVz&username=fedez

**Comment by fracogno** [comment]
https://www.influencerhunters.com/apis/tt/user/posts?token=GQ96yJKZn3hWpQVz&depth=2&username=addisonre

**Comment by davidteather** [comment]
Consolidating all discussion about `x-tt-params`, user_posts, and anything else related to this update to #695 for easier collaboration
