### ISSUE TITLE
[BUG] - API no longer works 

### ISSUE THREAD

**Issue by hellsing23** [davidteather/TikTok-Api#691]
Your API stopped working today, it doesn't return anything. Am I alone with such a situation?

**Comment by zurdok1280** [comment]
I have the same situation : (

**Comment by Dila-kun** [comment]
Stopped here to. error code:
api.byUsername(user_name, 55)
  File "C:\Python39\lib\site-packages\TikTokApi\tiktok.py", line 614, in by_username
    return self.userPosts(
  File "C:\Python39\lib\site-packages\TikTokApi\tiktok.py", line 583, in user_posts
    if not res["hasMore"] and not first:
KeyError: 'hasMore'

**Comment by RobinvLeeuwen** [comment]
I'm in the same situation, last time i tried the code was 2 week ago then i did work properly.

**Comment by Critters** [comment]
Ditto, at about 4am EST on the 13th Sep the API failed and continues to not work.

**Comment by Leg1tt** [comment]
Although I might be wrong, I'm sure that this is a captcha prompt error and is not the API being broke. I haven't tried using a proxy as of yet, but it may be worth trying to use one, just in case.

**Comment by theflofly** [comment]
Same issue on the user_page endpoint.

**Comment by hingston** [comment]
@Leg1tt not working on prxoies as well

**Comment by fracogno** [comment]
https://www.influencerhunters.com/apis/tt/user/posts?token=GQ96yJKZn3hWpQVz&depth=2&username=addisonre

**Comment by jeremyhaile** [comment]
@fracogno you probably don't want to post your API token publicly here.

**Comment by JorjanLLT** [comment]
@jeremyhaile maybe he just want us to buy and use the api product, these days the TikTok-Api and Scraper can't work , it always fail, we can only wait them fix

**Comment by yswtrue** [comment]
same problem

**Comment by Remiphilius** [comment]
Same issue here

**Comment by Xsnipe2Z** [comment]
same here

**Comment by mina9999** [comment]
please fix it.i cant wait anymore xd.

**Comment by JetLei** [comment]
request header has add params 'x-tt-params',it is a encrypt param

**Comment by ExtReMLapin** [comment]
> 
> 
> request header has add params 'x-tt-params',it is a encrypt param

This is the JS function adding it.
Have fun ! ;)

```javascript
          return i.a.wrap((function (e) {
            for (; ; ) switch (e.prev = e.next) {
              case 0:
                return o = k.length > 2 && void 0 !== k[2] ? k[2] : {
                },
                a = k.length > 3 ? k[3] : void 0,
                c = o.method,
                u = void 0 === c ? 'get' : c,
                p = o.easyRisk,
                h = void 0 !== p && p,
                v = Object(r.a) (o, [
                  'method',
                  'easyRisk'
                ]),
                _ = t,
                'post' === u && (v.headers ? v.headers['content-type'] || (v.headers['content-type'] = 'application/x-www-form-urlencoded') : v.headers = {
                  'content-type': 'application/x-www-form-urlencoded'
                }, v.data || (v.data = null)),
                m = w(_),
                e.t0 = g,
                e.t1 = g,
                e.t2 = {
                },
                e.next = 12,
                f.a.riskParams(h);
              case 12:
                e.t3 = e.sent,
                e.t4 = (0, e.t1) (e.t2, e.t3),
                e.t5 = n,
                b = (0, e.t0) (e.t4, e.t5),
                E = m ? {
                }
                 : b,
                m && (v.headers = g(g({
                }, v.headers), {
                }, {
                  'x-tt-params': Object(d.a) (b)
                })),
                y = s.a.request(g({
                  url: a ? encodeURI(_) : _,
                  params: E,
                  method: u
                }, v)),
                e.next = 24;
                break;
              case 21:
                S = _.includes('?') ? '&' : '?',
                _ += ''.concat(S, 'request_from=server'),
                y = l.a.request(g({
                  url: a ? encodeURI(_) : _,
                  params: n,
                  method: u
                }, v));
              case 24:
                return e.next = 26,
                y.catch((function (e) {
                  var t,
                  n = e.response;
                  e.message;
                  return {
                    data: {
                      statusCode: (null === n || void 0 === n || null === (t = n.data) || void 0 === t ? void 0 : t.statusCode) || - 1,
                      body: {
                      }
                    }
                  }
                }));
              case 26:
                return O = e.sent,
                C = O.data,
                e.abrupt('return', C);
              case 29:
              case 'end':
                return e.stop()
            }
          }), e)
```

**Comment by bayhax** [comment]
> > request header has add params 'x-tt-params',it is a encrypt param
> 
> This is the JS function adding it.
> Have fun ! ;)
> 
> ```js
>           return i.a.wrap((function (e) {
>             for (; ; ) switch (e.prev = e.next) {
>               case 0:
>                 return o = k.length > 2 && void 0 !== k[2] ? k[2] : {
>                 },
>                 a = k.length > 3 ? k[3] : void 0,
>                 c = o.method,
>                 u = void 0 === c ? 'get' : c,
>                 p = o.easyRisk,
>                 h = void 0 !== p && p,
>                 v = Object(r.a) (o, [
>                   'method',
>                   'easyRisk'
>                 ]),
>                 _ = t,
>                 'post' === u && (v.headers ? v.headers['content-type'] || (v.headers['content-type'] = 'application/x-www-form-urlencoded') : v.headers = {
>                   'content-type': 'application/x-www-form-urlencoded'
>                 }, v.data || (v.data = null)),
>                 m = w(_),
>                 e.t0 = g,
>                 e.t1 = g,
>                 e.t2 = {
>                 },
>                 e.next = 12,
>                 f.a.riskParams(h);
>               case 12:
>                 e.t3 = e.sent,
>                 e.t4 = (0, e.t1) (e.t2, e.t3),
>                 e.t5 = n,
>                 b = (0, e.t0) (e.t4, e.t5),
>                 E = m ? {
>                 }
>                  : b,
>                 m && (v.headers = g(g({
>                 }, v.headers), {
>                 }, {
>                   'x-tt-params': Object(d.a) (b)
>                 })),
>                 y = s.a.request(g({
>                   url: a ? encodeURI(_) : _,
>                   params: E,
>                   method: u
>                 }, v)),
>                 e.next = 24;
>                 break;
>               case 21:
>                 S = _.includes('?') ? '&' : '?',
>                 _ += ''.concat(S, 'request_from=server'),
>                 y = l.a.request(g({
>                   url: a ? encodeURI(_) : _,
>                   params: n,
>                   method: u
>                 }, v));
>               case 24:
>                 return e.next = 26,
>                 y.catch((function (e) {
>                   var t,
>                   n = e.response;
>                   e.message;
>                   return {
>                     data: {
>                       statusCode: (null === n || void 0 === n || null === (t = n.data) || void 0 === t ? void 0 : t.statusCode) || - 1,
>                       body: {
>                       }
>                     }
>                   }
>                 }));
>               case 26:
>                 return O = e.sent,
>                 C = O.data,
>                 e.abrupt('return', C);
>               case 29:
>               case 'end':
>                 return e.stop()
>             }
>           }), e)
> ```

how to call it ?

**Comment by davidteather** [comment]
Consolidating all discussion about `x-tt-params`, user_posts, and anything else related to this update to #695 for easier collaboration
