### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by ageof** [davidteather/TikTok-Api#694]
Hi I hope I'm right with you and you can help me.
I have an Android app reverse engineering and sniffed the traffic with Charles Proxy,
but the app seems to communicate via WSS or RTSP (I don't know exactly) in some places
and my question is how can I sniff this traffic? Thanks so much :)
This is the project: https://github.com/ageof/MyDlink-API-Python/

**Comment by davidteather** [comment]
Not sure, this only does web endpoints
