### ISSUE TITLE
[Help Wanted] - Fixing the Package

### ISSUE THREAD

**Issue by davidteather** [davidteather/TikTok-Api#695]
Hey, I've been trying to fix the API, one of the things I'm running into is generating the `x-tt-params` header. I currently have code semi-working for getting user posts except for this header. I'll be pushing my current code to the [nightly](https://github.com/davidteather/TikTok-Api/tree/nightly) branch, but it'll likely only be focused on user_posts breaking the other functions temporarily (but they're already broken so 🤷 ) it's just meant as a way to collaborate.

## Important Information
@MuffinFox pointed out on #690
> * for initialisation of parameter encryption there is a call to window._$jsvmprt(a, b, c) with some hardcoded string (key?)
>  * window._fetch is a patched fetch which adds some additional functionality
>  * crypthojs lib is used for obfuscation

@asportnoy on #685 about ttwid (which isn't my current main focus)
> * The cookie is generated from a post request to https://www.tiktok.com/ttwid/check/ (set-cookie header). That request requires a fid parameter but I can't tell what generates that.
> * I also noticed this new script which seems relevant to the changes: https://www.tiktok.com/acrawler/webmssdk.js I was able to partially de-obfuscate that with http://jsnice.org/.

## Things I've noticed
* Appears they're signing urls using a different algorithm for `_signature` url parameter.
* `ttwid` doesn't really seem to matter (at least for user_posts)
* Whatever tokens they're checking don't seem to expire
* VerifyFp doesn't seem to exist on the initial calls of at least user_posts anymore

## Priorities
1. Figure out how `x-tt-params` is being generated

## Related Issues (with more information and potentially more help)
I've closed these and linked to this, sorted by most relevant to least relevant
* #690 
* #685 
* #691
* #688 
* #693 
* #681 
* #674

**Comment by JetLei** [comment]
![1631850761(1)](https://user-images.githubusercontent.com/58629508/133721478-22dfdb19-c80d-4194-90a0-c449c620ef4d.png)
![1631850786(1)](https://user-images.githubusercontent.com/58629508/133721509-51f70dc3-14f7-478a-aa0d-cd8de6c72205.png)
I konw this function is encryption function ,but My JS is poor

**Comment by callMeMakerRen** [comment]
i try to resign the link`https://t.tiktok.com/api/post/item_list/?msToken=xxx=&X-Bogus=xxx`,use the old sign function`window.byted_acrawler.sign({ "url":urlT }),` and the useragent is same as old origin link,and turn out the old sign function is still ok,we just need find way to gen x-tt-params 
x-bugus seems generate by window.byted_acrawler.frontierSign("aaa") => {X-Bogus: 'RkWhY1g5s/20PSyl'} ,not sure what param is needed ,keep search

**Comment by JetLei** [comment]
The original API can be used by adding'x-tt-params'

**Comment by ExtReMLapin** [comment]
In this kind of situation, you can be sure, there are people from tiktok's engineering team watching this issue.

If you really want to get the API to work you should probably organize and work together with a little more privacy.


Now, about the x-tt-params code I posted in the previous issue, here is what gets inside `b`

`"x-tt-params": Object(d.a)(b)`


```json
aid: [CENSORED INT]
app_language: "fr"
app_name: "tiktok_web"
battery_info: BatteryManager {charging: true, chargingTime: 0, dischargingTime: Infinity, level: 1, onchargingchange: null, …}
browser_language: "fr-FR"
browser_name: "Mozilla"
browser_online: true
browser_platform: "Win32"
browser_version: "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"
cookie_enabled: true
count: 30
cursor: "0"
device_id: "[UINT64 CENSORED]"
device_platform: "web_pc"
focus_state: true
history_len: 4
is_fullscreen: false
is_page_visible: true
language: "fr"
os: "windows"
priority_region: "FR"
referer: ""
region: "FR"
root_referer: undefined
screen_height: 1440
screen_width: 2560
secUid: "[BASE64 CENSORED]"
timezone_name: "Europe/Paris"
verifyFp: "verify_[CENSORED]"
[[Prototype]]: Object
```

**Comment by mina9999** [comment]
i think we need to set verifyfp and tt_csrf_token.

**Comment by boiio** [comment]
about _signature url parameter.
the douyin(tiktok china version) use this html to generate.
https://github.com/boiio/douyin_downloader/blob/master/signature.html

i'm use this in my personal douyin-scraperand still work.
Don't know if it will help,maybe just a samename parameter,gl.

**Comment by JetLei** [comment]
> about _signature url parameter.
> the douyin(tiktok china version) use this html to generate.
> https://github.com/boiio/douyin_downloader/blob/master/signature.html
> 
> i'm use this in my personal douyin-scraper and still work.
> Don't know if it will help,maybe just a samename parameter,gl.

The new encryption function has been changed

**Comment by davidteather** [comment]
@carcabot has replicated the signing function in javascript with a docker container in their repository. 
* [javascript](https://github.com/carcabot/tiktok-signature/blob/master/javascript)
* [example trending.py](https://github.com/carcabot/tiktok-signature/blob/master/examples/trending.py)

**Comment by kira0x1** [comment]
> @carcabot has replicated the signing function in javascript with a docker container in their repository.
> 
> * [javascript](https://github.com/carcabot/tiktok-signature/blob/master/javascript?rgh-link-date=2021-09-20T19%3A51%3A05Z)
> * [example trending.py](https://github.com/carcabot/tiktok-signature/blob/master/examples/trending.py?rgh-link-date=2021-09-20T19%3A51%3A05Z)

This is perfect, works for me using jsdom.

**Comment by zvictor** [comment]
Looking at his code it seems that all he is doing differently is sending `x_tt_params` to all requests, but in order to generate that value he first calls `window.genXTTParams` in a TikTok page.

https://github.com/carcabot/tiktok-signature/blob/2177e53ab3201bbad33aa8867c7f1b395d99d72e/index.js#L119-L121

**Comment by kira0x1** [comment]
> Looking at his code it seems that all he is doing differently is sending `x_tt_params` to all requests, but in order to generate that value he first calls `window.genXTTParams` in a TikTok page.
> 
> [carcabot/tiktok-signature@`2177e53`/index.js#L119-L121](https://github.com/carcabot/tiktok-signature/blob/2177e53ab3201bbad33aa8867c7f1b395d99d72e/index.js#L119-L121)

yeah that was the problem, the api changed where now instead of sending the old params directly you have to encrypt them and send them encrypted as an x-tt-params header.

and also sending a param with mstoken, xbogus, and the signature

**Comment by isaackogan** [comment]
> Observation:
> 
> * When ttwid cookie is included in brower cookies, FYP works with currently library implementation
> * When I remove ttwid from my browser cookies, FYP shows as the fake version
> 
> How is ttwid generated?

I've managed to fix by_trending on my own version. Will create a PR!

**Comment by lazezo2** [comment]
the api changed where now instead of sending the old params directly you have to encrypt them and send them encrypted as an x-tt-params header.
and also sending a param with mstoken, xbogus, and the signature

how to generate x-tt-params???

**Comment by xtekky** [comment]
why not just use mobile api @davidteather its smoother than web, there are some sigs but because of old version compatibility, versions like v2.4.7 still work and have no security at all or a lot of bypasses. All endpoints like userinfo are much more detailed etc..
