### ISSUE TITLE
[BUG] - if not res["hasMore"] and not first: KeyError: 'hasMore'

### ISSUE THREAD

**Issue by Syahrol13** [davidteather/TikTok-Api#696]
Description:
Everytime I tried to use by_username() function, i'll encounter this error. It was working last week,, now i cant even get a single post using this function. The bug return the value if not res["hasMore"] and not first:
KeyError: 'hasMore'

buggy code:
The buggy code is by_username() function.

Expected:
The code is expected to return the user TikTok posts data.

Error Trace:
if not res["hasMore"] and not first:
KeyError: 'hasMore'

 OS: Windows 10
 TikTokApi Version : 4.0.1

**Comment by Scarlet06** [comment]
I've got the same error also by running the example "get_a_users_videos.py" on my machine which is a windows 10 and TikTokApi Version: 4.0.1

**Comment by adj97** [comment]
I've got the same issue with by_username. It looks like this method calls to `user_posts` and then breaks on line 588. I've tried to reconstruct the real TikTok api request but can't manually construct the right url params. I bet the real TikTok api has been updated and no longer responds with the same schema, i.e. no "hasMore" attribute

**Comment by fracogno** [comment]
It seems that it works here [Link](https://www.influencerhunters.com/apis/tt/user/posts?token=GQ96yJKZn3hWpQVz&depth=2&username=fedez)

**Comment by mina9999** [comment]
@fracogno it dosnt work anymore it only have 100 units per day.

**Comment by fracogno** [comment]
@mina9999 if you pay they give you more

**Comment by Syahrol13** [comment]
> I've got the same issue with by_username. It looks like this method calls to `user_posts` and then breaks on line 588.
> I've debugged the code and looked at the URL response from line 582 of tiktok.py, and this has a response code of 0 with no content.

I got the same result as you

**Comment by Syahrol13** [comment]
> @fracogno it dosnt work anymore it only have 100 units per day.

so you are saying this not free anymore? Limited to certain quota only?

**Comment by Scarlet06** [comment]
> > @fracogno it dosnt work anymore it only have 100 units per day.
> 
> so you are saying this not free anymore? Limited to certain quota only?

But that's strange: I've the same error even if I do something like 2 requests per day... Is the limit of 100 for every TikTok-Api user?

**Comment by fracogno** [comment]
@Scarlet06 @Syahrol13 
Send an email to marco@influencerhunters.com and you'll receive a free trial token with 50 units per day.

**Comment by Syahrol13** [comment]
> @Scarlet06 @Syahrol13
> Send an email to [marco@influencerhunters.com](mailto:marco@influencerhunters.com) and you'll receive a free trial token with 50 units per day.

How long do you think the free trial will last?

**Comment by sidorovphilipp** [comment]
Hello, I experience this issue as well. It's still not solved. Upgading to latest version not helped and changing custom verify ID.

**Comment by fracogno** [comment]
@sidorovphilipp @Syahrol13 Have a look [here](https://www.influencerhunters.com/docs.html)  They offer stable APIs at a cheap price. Free trial for 1 week

**Comment by davidteather** [comment]
Consolidating to #695 #699 looks like a promising fix I'll investigate further later.
