### ISSUE TITLE
[BUG] - Be trending is getting only the first 6 items

### ISSUE THREAD

**Issue by GeorgeHulpoi** [davidteather/TikTok-Api#697]
**Describe the bug**

The by_trending method has a problem with the `count` parameter, looks like it's always 6.

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()
trending = api.by_trending(count=20, custom_verifyFp="...")

for tiktok in trending:
    print(tiktok['id'])

print(len(trending))
```

**Expected behavior**

To have 20 elements in dict.

**Error Trace (if any)**
--

**Desktop (please complete the following information):**
 - OS: Win 10
 - TikTokApi Version 4.0.1

**Comment by fracogno** [comment]
They made it working [here](https://www.influencerhunters.com/docs.html)

**Comment by GeorgeHulpoi** [comment]
> They made it working [here](https://www.influencerhunters.com/docs.html)

isn't supposed to be free?

**Comment by davidteather** [comment]
With the new changes I’m able to get 10 but not beyond that. I’ll be looking for a fix

**Comment by tokjii** [comment]
Anything new on the trending? I can't find differences between my requests and the normal website's request. Maybe there is some parameter hidden in the signature or the likes?

**Comment by amberallergy** [comment]
> Anything new on the trending? I can't find differences between my requests and the normal website's request. Maybe there is some parameter hidden in the signature or the likes?

Hi!
This one seems to work and pretty easy to try it out, they offer free token at the first.
Also work on different social media platforms.
Here is the website https://www.influencerhunters.com/docs.html

**Comment by steppenvieh** [comment]
Hi - for me the get_trending function only gets 3 videos which are all from tiktok itself... Is there any news on the method?

**Comment by sepkov** [comment]
I can get only 10 too

**Comment by lrzhang12** [comment]
Same issue here, also, latest version of the api doesn't have trending module.

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
