### ISSUE TITLE
[BUG]from tiktok import TikTokapi ModuleNotFoundError: No module named 'tiktok'

### ISSUE THREAD

**Issue by kmrabhay** [davidteather/TikTok-Api#70]
**Describe the bug**
I installed lib using the command below. but its not getting imported. I am using python3.6 and installed the lib in a virtual env on ubuntu.
pip install TikTokApi

**The buggy code**
from tiktok import TikTokapi

**Expected behavior**

ModuleNotFoundError: No module named 'tiktok'

**Comment by willjorey** [comment]
@davidteather I have the same problem as well

**Comment by Xodarap** [comment]
I believe the instructions are wrong. See #71

**Comment by davidteather** [comment]
Yeah it should be
`from TikTokApi import TikTokapi`
but the api is broken right now. Due to changes made by TikTok near the start of this year.
