### ISSUE TITLE
[BUG] - API Not Working with Proxies

### ISSUE THREAD

**Issue by radonys** [davidteather/TikTok-Api#704]
**Describe the bug**

The TikTok API isn't working with Rotational Proxies (probably due to IP change for each request made). Shows Captcha when used with Proxies.

**Expected behavior**

Should work fine with proxies like before.

**Desktop (please complete the following information):**
 - OS: UBUNTU 20.04 (GCP)
 - TikTokApi Version 4.0.2

**Comment by fracogno** [comment]
It seems that it works [here](https://www.influencerhunters.com/docs.html)

**Comment by amberallergy** [comment]
Hi!
This one seems to work and pretty easy to try it out, they offer free token at the first.
Also work on different social media platforms.
Here is the website https://www.influencerhunters.com/docs.html

**Comment by radonys** [comment]
Nope. Still waiting on one.

**Comment by davidteather** [comment]
Try V6

**Comment by zakrian07** [comment]
await api.create_sessions(proxies=proxy,ms_tokens=[ms_token], num_sessions=1, sleep_after=3)  [TikTokApi Sessions] An error occurred:
<class 'KeyError'>
0
please help me with this   async with TikTokApi() as api:
            await api.create_sessions(proxies=proxy,ms_tokens=[ms_token], num_sessions=1, sleep_after=3)
    except Exception as e:
        print("[TikTokApi Sessions] An error occurred:")
        print(type(e))
        print(e)
        return  # Exit the function here to avoid proceeding

**Comment by zakrian07** [comment]
any update on this ?
