### ISSUE TITLE
[BUG] - by_username() TikTok returned a response indicating the entity is invalid

### ISSUE THREAD

**Issue by klauria22** [davidteather/TikTok-Api#711]
**Describe the bug**

Using the by_username() function to get a dict of a users videos causes the error "TikTok returned a response indicating the entity is invalid"

**The buggy code**

```
video_dict = api.by_username(user, count=count, custom_did=did, custom_verifyFp=verifyFp)
```

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
Traceback (most recent call last):
  File "C:/Users/kevin/PycharmProjects/tiktokcompilations/main.py", line 125, in main
    download_videos(chosen_user, number_of_videos)
  File "C:/Users/kevin/PycharmProjects/tiktokcompilations/main.py", line 21, in download_videos
    video_dict = api.by_username(user, count=count, custom_did=did, custom_verifyFp=verifyFp)
  File "C:\Users\kevin\tiktokcompilations\lib\site-packages\TikTokApi\tiktok.py", line 635, in by_username
    **kwargs,
  File "C:\Users\kevin\tiktokcompilations\lib\site-packages\TikTokApi\tiktok.py", line 595, in user_posts
    res = self.get_data(url=api_url, send_tt_params=True, **kwargs)
  File "C:\Users\kevin\tiktokcompilations\lib\site-packages\TikTokApi\tiktok.py", line 302, in get_data
    "TikTok returned a response indicating the entity is invalid"
TikTokApi.exceptions.TikTokNotFoundError: TikTok returned a response indicating the entity is invalid
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version 4.0.4

**Comment by fracogno** [comment]
It seems that they made it working [here](https://www.influencerhunters.com/docs.html)

**Comment by MuffinFox** [comment]
For reproducing this issue, please add more information like the username which is not found.

**Comment by klauria22** [comment]
> 
> 
> For reproducing this issue, please add more information like the username which is not found.

this happens regardless of what username I use. I have a separate function that picks out a random trending user, and so far it's tried over 80 different usernames and all of them return the same error when entered into the by_username function. Not sure what other information I could give to help reproduce the issue

**Comment by davidteather** [comment]
If you’re able to I recommend using user_posts instead of by_username since secUid and userId should be returned on the tiktok objects returned from trending. 

This is a more ideal approach as by_username performs a http request to try to extract secUID and userId which is more prone to error, compared to just supplying these values directly.

**Comment by klauria22** [comment]
> 
> 
> If you’re able to I recommend using user_posts instead of by_username since secUid and userId should be returned on the tiktok objects returned from trending.
> 
> This is a more ideal approach as by_username performs a http request to try to extract secUID and userId which is more prone to error, compared to just supplying these values directly.

I switched by_username() to user_posts(), but it's still giving me the same error

```
Traceback (most recent call last):
  File "C:/Users/kevin/PycharmProjects/tiktokcompilations/main.py", line 139, in main
    download_videos(chosen_user, number_of_videos)
  File "C:/Users/kevin/PycharmProjects/tiktokcompilations/main.py", line 33, in download_videos
    video_dict = api.user_posts(id, secUID, count=count)
  File "C:\Users\kevin\tiktokcompilations\lib\site-packages\TikTokApi\tiktok.py", line 595, in user_posts
    res = self.get_data(url=api_url, send_tt_params=True, **kwargs)
  File "C:\Users\kevin\tiktokcompilations\lib\site-packages\TikTokApi\tiktok.py", line 302, in get_data
    "TikTok returned a response indicating the entity is invalid"
TikTokApi.exceptions.TikTokNotFoundError: TikTok returned a response indicating the entity is invalid
```

**Comment by MuffinFox** [comment]
Is the example script https://github.com/davidteather/TikTok-Api/blob/master/examples/demo_user_pager.py working for you? Can you provide url and raw response from TikTok-Api.get_data for further debug? Maybe you are just passing wrong params?

**Comment by klauria22** [comment]
> 
> 
> Is the example script https://github.com/davidteather/TikTok-Api/blob/master/examples/demo_user_pager.py working for you? Can you provide url and raw response from TikTok-Api.get_data for further debug? Maybe you are just passing wrong params?

The example script gives the same error

```
Traceback (most recent call last):
  File "C:/Users/kevin/PycharmProjects/tiktokcompilations/main.py", line 298, in <module>
    for page in pager:
  File "C:\Users\kevin\tiktokcompilations\lib\site-packages\TikTokApi\tiktok.py", line 714, in get_user_pager
    **kwargs,
  File "C:\Users\kevin\tiktokcompilations\lib\site-packages\TikTokApi\tiktok.py", line 684, in user_page
    return self.get_data(url=api_url, send_tt_params=True, **kwargs)
  File "C:\Users\kevin\tiktokcompilations\lib\site-packages\TikTokApi\tiktok.py", line 307, in get_data
    "TikTok returned a response indicating the entity is invalid"
TikTokApi.exceptions.TikTokNotFoundError: TikTok returned a response indicating the entity is invalid
```

The url used by get_data() is:

https://t.tiktok.com/api/post/item_list/?aid=1284&app_name=tiktok_web&device_platform=web_mobile&region=US&priority_region=&os=ios&referer=&root_referer=&cookie_enabled=true&screen_width=1314&screen_height=641&browser_language=en-us&browser_platform=iPhone&browser_name=Mozilla&browser_version=Mozilla%252F5.0%2B%28iPhone%253B%2BCPU%2BiPhone%2BOS%2B12_2%2Blike%2BMac%2BOS%2BX%29%2BAppleWebKit%252F605.1.15%2B%28KHTML%2C%2Blike%2BGecko%29%2BVersion%252F13.0%2BMobile%252F15E148%2BSafari%252F604.1&browser_online=true&timezone_name=America%252FNew_York&is_page_visible=true&focus_state=true&is_fullscreen=false&history_len=6&language=en&count=20&id=6745191554350760966&type=1&secUid=MS4wLjABAAAAM3R2BtjzVT-uAtstkl2iugMzC6AtnpkojJbjiOdDDrdsTiTR75-8lyWJCY5VvDrZ&cursor=0&sourceType=8&appId=1233&region=US&language=en


Also I want to add that the by_username() function was working fine for the past few months, and just started giving me this error recently and I haven't made any changes to the code/params.

**Comment by MuffinFox** [comment]
Are you setting `aid=1284` by yourself?

**Comment by klauria22** [comment]
> 
> 
> Are you setting `aid=1284` by yourself? That is not done by the lib and wont work.

`aid=1284` was working for a few weeks with no issues. Setting it back to 1988 does fix demo_user_pager.py, but setting 'aid=1284` is to fix the bug where by_trending() only returns videos from @tiktok. So I guess I can get trending users, or download videos, but not both?

**Comment by MuffinFox** [comment]
Just set your custom aid for trending, and keep lib default for user_pager and it will work.
