### ISSUE TITLE
[BUG] - PROXY feature does not work

### ISSUE THREAD

**Issue by mjablonsky** [davidteather/TikTok-Api#719]
PROXY feature stoped working staring from TikTokApi-4.0.3. It was working fine before in stable proxy environment (proxy connected to cellular network)

proxy =  "https://10.1.4.xx:3128"

I'm getting following error:

Error Error performing TLS handshake: An unexpected TLS packet was received.
=========================== logs ===========================
navigating to "https://www.tiktok.com/@redbull", waiting until "load"
============================================================

My proxy logs:
1632916489.233   2221 10.1.4.11 TCP_TUNNEL/200 102169 CONNECT tiktok.com:443 - HIER_DIRECT/103.136.221.164 -
1632916489.667      0 10.1.4.11 NONE/400 3725 NONE error:invalid-request - HIER_NONE/- text/html
1632916506.822   2133 10.1.4.11 TCP_TUNNEL/200 102535 CONNECT tiktok.com:443 - HIER_DIRECT/103.136.221.164 -
1632916507.243      0 10.1.4.11 NONE/400 3725 NONE error:invalid-request - HIER_NONE/- text/html

Before it was working fine. Not it works only without proxy, what is an issue because I monitor some my accounts which are pretty large.

Many thanks in advance for fixing this soon.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - TikTokApi-4.0.4

**Comment by MuffinFox** [comment]
This happens for some time, prior latest fixes. It seems to be the result of tiktoks proxy blocking. You tried your proxies already manually eg with `google-chrome --proxy-server=...`  and visiting some tiktok profile? The blocking mechanism seems respond in different ways, eg by resetting connection (ERR_CONNECTION_RESET) or sending some random json which is not even parseable.

**Comment by MuffinFox** [comment]
see #704 for related issue

**Comment by mjablonsky** [comment]
> see #704 for related issue

Many thanks - you are right. I think that Tiktok implements this kind of protection - it hangs first 2 requests, but after it works. I didnt expect such sophisticated way of firewalling)) Thanks again.

**Comment by minakovskiy** [comment]
> > see #704 for related issue
> 
> Many thanks - you are right. I think that Tiktok implements this kind of protection - it hangs first 2 requests, but after it works. I didnt expect such sophisticated way of firewalling)) Thanks again.

Can you please describe, what you did, to make your code work? #704 is closed, it is no solution there

**Comment by mjablonsky** [comment]
> > > see #704 for related issue
> > 
> > 
> > Many thanks - you are right. I think that Tiktok implements this kind of protection - it hangs first 2 requests, but after it works. I didnt expect such sophisticated way of firewalling)) Thanks again.
> 
> Can you please describe, what you did, to make your code work? #704 is closed, it is no solution there

The problem is following - TikTok is blocking API requests by some sadistic way - bulshitting parser in response or dropping https protocol. Other words - TikTik does not cooperate as they said officially before. They cause problems to people who does deep analytics - because tiktok's analytics is nothing.
this API works better ( the code of API is correct) then tiktok's load is lower ( at day time) and your IP not in block list. Its very easy to get to this list - 3 sequential attempts  and you are here. So, I'm very dissapointed by TikTik's approach to community - we didt sell good analytics service and they didnt support community's efforts to build it. So, solution is to find low load time and use proxy. And use code with retry's and exception processing - at low load time it connects and works from 2-3 attempts. 
Hope, it makes situation a little bit clear.
