### ISSUE TITLE
[BUG] - ERROR:asyncio:Task exception was never retrieved

### ISSUE THREAD

**Issue by M00000n** [davidteather/TikTok-Api#722]
**Describe the bug**
Sometimes when I request all user posts, playwright will crash, especially if the user has some large number of posts.

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
user_post = api.user_posts(user_id, secUid, cursor=0, count=video_count)
```

**Expected behavior**

The api returns all posts of that user.

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-1071' coro=<Route.continue_() done, defined at C:\Program Files\Python39\lib\site-packages\playwright\_impl\_network.py:224> exception=Error('Target page, context or bTraceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\playwright\_impl\_network.py", line 242, in continue_
    await self._channel.send("continue", cast(Any, overrides))
  File "C:\Program Files\Python39\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Program Files\Python39\lib\site-packages\playwright\_impl\_connection.py", line 57, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Target page, context or browser has been closed
```

**Desktop:**
 - OS: Windows 10 x64
 - TikTokApi Version 4.0.4
 - Python 3.9.6
 - Playwright 1.15.2

**Comment by MuffinFox** [comment]
Are you receiving any posts in this error case? In which environment (eg. python shell, api, framework) is this error reproducible for you?

**Comment by M00000n** [comment]
No, in this case I don't receive any posts. The error is reproducable in the python shell. I found out that this error only appears sometimes when I request all posts from a user with many posts (eg 1100). Soemtimes it works, sometimes not. But only when the number of posts is high. I never had this error when requesting all posts from users with less posts (eg 100). I suppose that playwhright crashes because it can't handle that much.

**Comment by davidteather** [comment]
#576
