### ISSUE TITLE
[BUG] - by_username() hangs in, without any error

### ISSUE THREAD

**Issue by terror2012** [davidteather/TikTok-Api#723]
**Describe the bug**

I've used this code a couple months ago and it worked flawlessly, but now, it just hangs.
I've also tried the old executable that I had, and the response is a lot of js/html, and an error regarding captcha. It looks like it started to return html code of the page, rather than the data.
But with the current code, there's no output, it can stay up to 5-10 minutes (after which I force shut down) and it wouldn't display any errors

**The buggy code**

```
    def __init__(self):
        self.api = TikTokApi.get_instance(generate_static_device_id=True)
    def getClips(self):
        self.clipList = self.api.by_username(username=self.username, count=self.clipCount)
        print(self.clipList)
        self.statusInstance.set(f"Got {len(self.clipList)} clips...")
```

self.username is the tiktok @ username, and the count is set to 20

**Expected behavior**

A dictionary of posts from that user, which I can then use to download the specific videos

**Error Trace (if any)**

No errors, that's the actual issue

**Desktop (please complete the following information):**
OS: Windows 10
TiktokApi: 3.9.9
Using tkinter as the GUI

**Additional context**

A couple months ago, it worked perfectly as expected, getting the post list from by_username, downloading the actual clip using self.api.get_Video_By_TikTok(clip) but right now, I can't even get the list of clips

**Comment by M00000n** [comment]
You aren't using the newest version of the package. Upgrade your installatiuon to v4.0.4.
