### ISSUE TITLE
[BUG] - custom_verifyFp is useless because s_v_web_id does not exist any more in cookies.

### ISSUE THREAD

**Issue by mjblski** [davidteather/TikTok-Api#724]
It seems to be that TikTok had changed auth system because s_v_web_id cookie does not exist any more. Also, User cookie has changed - take a look into document.cookie in Dev tools in browser - its brand new structure.

So, API does not work for deep analysis, because it requires auth on TikTok. All our cron stuff and robots need to be checked - here is no data. 

Help with this auth isses will be very appreciated.

**Comment by mina9999** [comment]
this is so sad.

**Comment by davidteather** [comment]
It’s midterm season so I’ve been pretty busy I’ll try to work on this sometime late this week or this weekend if I’ve got time

**Comment by Aditya-Rajgor** [comment]
@mjblski Did they really change? I can still see the s_v_web_id is in the cookies folder inside the 'www.tiktok.com'. Try using VPN and then find the id, it may work. 

*Date - 21 October 2021*

**Comment by martmalo** [comment]
![image](https://user-images.githubusercontent.com/77250222/139641912-5515a27f-a379-4aa9-bdb6-40783ccaedc7.png)
 I still have the cookie.

**Comment by mjblski** [comment]
> ![image](https://user-images.githubusercontent.com/77250222/139641912-5515a27f-a379-4aa9-bdb6-40783ccaedc7.png) I still have the cookie.

Just clear cookies in browser in Dev tools and relogin&reauth. No cookie.

**Comment by mjblski** [comment]
> @mjblski Did they really change? I can still see the s_v_web_id is in the cookies folder inside the 'www.tiktok.com'. Try using VPN and then find the id, it may work.
> 
> _Date - 21 October 2021_

VPN has no connection to TT auth mechanism. Just delete cookies and reauth.

**Comment by mjblski** [comment]
> It’s midterm season so I’ve been pretty busy I’ll try to work on this sometime late this week or this weekend if I’ve got time

great. because cookies on people's hands will expire soon and this issue will become a serious problem. it still works, but soon it will stop - TT supports old cookies till they expire - to not crush auth servers in massive reauth. could you, please, find a time for this issue. thanks in advance.

**Comment by adiantek** [comment]
verify still exists in other places, like in URL to some requests. Don't remember now the parameter name, but the value starts with "verify_".

**Comment by radturkin** [comment]
had same issue was able to resolve it by opening tiktok.com in an incognito window using chromium browser

**Comment by verymucho** [comment]
Cookie doesn't show up on Firefox for me but it does on Chrome incognito (also had to disable the LocalCDN extension for TikTok for it to show).

**Comment by Xosmond** [comment]
On chrome, its there but it doest matter using it, still raises error

**Comment by mjblski** [comment]
> On chrome, its there but it doest matter using it, still raises error

yes. it does not work. I've stopped using this api. just a waisted time(

**Comment by Ninjaman494** [comment]
I found a way to get a valid `s_v_web_id` cookie set. I found [this issue comment](https://github.com/davidteather/TikTok-Api/issues/390#issuecomment-737622565) with a link that you can use to manually fill out a captcha and get the cookie:
https://sf16-scmcdn-va.ibytedtos.com/goofy/secsdk-captcha/va/2.15.21/index.html

**NOTE:** The comment says that the cookie isn't always valid so it might take a couple tries to get a valid `s_v_web_id` value.

@davidteather Is it worth adding this link to the README?

**Comment by davidteather** [comment]
Not sure it isn't needed anymore with V5.0.0

**Comment by janith-jware** [comment]
I am using V5. But I still get the following error.
```
Tiktok wants to display a captcha.
Response:
{"code":"10000","from":"","type":"verify","version":"","region":"va","subtype":"slide","detail":"b1212xmz-BSqLWFrA*vLwHTu6GSGzhBWDYzp1clzZlB7Z1C9O5FF09R2ZNitPl8gvS5xdexQNC0eQ11t3sNx40g9HeEVbAkKgNQ7ZZ3c*ZS89-SW82PEO11mKqHQBt-8haSYGhcm4Ul6B1CVZqDUd2uLqhgXY8CPncIp9KM4gRnEyawYxhye1B8aFntZrN8y0NlNTBS4A9mjTt93xv1hIN93wqDIStxmKFeABIyj2gTuth-eT4nkqHhwmGPni93pWr6Ft4XVPGq3l0FP11E8qiWZf0vYCPBbIGhRNUh36SoXYSzd*UtOi1d6ppEvfZ2yehYAPqwwUrLBnpAKgFuj1aIScR4QCbVTCt8kncCIwfh6LnBrDPLCA48oJFx8Boie4rJakrvMGOiMSH8YSWa6EG4B509g6qJ5vhaAdVsF1Qp7ARTLGac.","verify_event":"","fp":"verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq","scene":"","verify_ticket":"","channel_mobile":"","sms_content":"","mobile":"","email":""}
Cookies:
{'tt_webid': '9711235959354242128', 'tt_webid_v2': '9711235959354242128', 'csrf_session_id': 'f13eaa63c850775d4b068b969d8891ff', 'tt_csrf_token': 'IyKHpeaZMzqCjpYc', 'ttwid': None}
URL:
https://m.tiktok.com/api/challenge/item_list/?aid=1988&app_name=tiktok_web&device_platform=web_mobile&region=US&priority_region=&os=ios&referer=&cookie_enabled=true&screen_width=368&screen_height=1384&browser_language=en-us&browser_platform=iPhone&browser_name=Mozilla&browser_version=Mozilla%2F5.0+%28iPhone%3B+CPU+iPhone+OS+12_2+like+Mac+OS+X%29+AppleWebKit%2F605.1.15+%28KHTML%2C+like+Gecko%29+Version%2F15.4+Mobile%2F15E148+Safari%2F604.1&browser_online=true&timezone_name=Asia%2FCalcutta&is_page_visible=true&focus_state=true&is_fullscreen=false&history_len=5&language=en&count=30&challengeID=1697657584273413&cursor=0&verifyFp=verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq&device_id=9711235959354242128&_signature=_02B4Z6wo00f01BGRP4gAAIBAG2CH5CNPY6gRgDsAAGYZ4c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Janith\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\api\hashtag.py", line 117, in videos
    res = self.parent.get_data(path, **kwargs)
  File "C:\Users\Janith\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\tiktok.py", line 308, in get_data
    raise CaptchaException(
TikTokApi.exceptions.CaptchaException: TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verify_fp as method parameters
```

How can I overcome this? s_v_web_id cookie is no longer available in tiktok. @davidteather

**Comment by wmcnally** [comment]
@davidteather @janith-jware any updates on the CaptchaException issue?

**Comment by pvizan-artefact** [comment]
Getting the same error than @janith-jware. I did not manage to use the API at all, after trying a [ScrapingAnt proxy](https://scrapingant.com/free-proxies/), a `s_v_web_id `cookie provided by [this link](https://sf16-scmcdn-va.ibytedtos.com/goofy/secsdk-captcha/va/2.15.21/index.html), and a combination of both. Also tried to pass the parameter `use_test_endpoints=True`. Providing the three parameters would in my case result in this error:

`requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.tiktok.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))`

None of the options, either combined or separately, ended up working.

The code I was trying to run was the following:

```
user = api.user(username="therock")
for video in user.videos():
    print(video.id)
```

**Comment by LilSherlock** [comment]
still not working I have the same issue, when I try to make the request I have the same error 

`Traceback (most recent call last):
  File "main.py", line 15, in <module>
    main()
  File "main.py", line 8, in main
    for video in user.videos():
  File "/home/xd/.local/lib/python3.8/site-packages/TikTokApi/api/user.py", line 153, in videos
    self.__find_attributes()
  File "/home/xd/.local/lib/python3.8/site-packages/TikTokApi/api/user.py", line 282, in __find_attributes
    for u in self.parent.search.users(self.username):
  File "/home/xd/.local/lib/python3.8/site-packages/TikTokApi/api/search.py", line 105, in search_type
    api_response = Search.parent.get_data(
  File "/home/xd/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 352, in get_data
    raise CaptchaException(0, None,
TikTokApi.exceptions.CaptchaException: 0 -> TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verify_fp as method parameters`

**Comment by terrok9** [comment]
Issue still relevant and not solved. I recommend using https://github.com/Russell-Newton/TikTokPy instead

**Comment by tayyabmaqsood** [comment]
@davidteather any update?
