### ISSUE TITLE
[INSTALLATION] - Async context

### ISSUE THREAD

**Issue by xXZyzzXx** [davidteather/TikTok-Api#733]
**
Hello I am using this library in a Django project and when I connect to an instance and try to get a record from the database I got an error that I cannot call from the async context.
Why is this happening and how do I completely change the code to asynchronous or synchronous? (both will work for me)**

Put the error trace here.

**cls.__api = TikTokApi.get_instance(
                custom_verifyFp=verify_fp, use_test_endpoints=True, custom_device_id=did,
            )
   records = Setting.objects.all()**

Please insert the code that is throwing errors or is giving you weird unexpected results.

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
You cannot call this from an async context - use a thread or sync_to_async.

```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version 4.0.4 - if out of date upgrade before posting an issue

**Additional context**

How to use it with async content?

**Comment by davidteather** [comment]
#576
