### ISSUE TITLE
DEPRECATION ALRET - tiktok is moving to "sigi"

### ISSUE THREAD

**Issue by dvird** [davidteather/TikTok-Api#735]
tiktok is changing the way data is going to be avail on her website:

please check that logic:
https://github.com/ctaity/ms-tiktok/blob/main/src/tiktok.controller.ts

next_data is going to be deprecated soon

tiktok is moving from Next.js to sigi.js
https://github.com/sigi-framework/sigi

within 1-2 weeks the way of how this library parsing data wont be valid anymore

**Comment by Jingo91** [comment]
Hey, is it still somehow possible to get the data of a profile? Or do we need to wait, until this one is fixed?

**Comment by davidteather** [comment]
Works on V5.0.0
