### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by oofsamy** [davidteather/TikTok-Api#741]
Hey, I tried using the TikTokApi but it told me to use a proxy, so I added a proxy that I know it works by pinging it in terminal `ping 105.174.40.54` (I have about 20-30 proxies to use, I don't care if I put a single one in here) and it prints this 
![image](https://user-images.githubusercontent.com/61066276/139698510-542a5a36-6ff6-4ca4-9649-42724ea46eb8.png), but when using it, it says it cannot connect to the proxy? 
![image](https://user-images.githubusercontent.com/61066276/139698961-1e618e9a-42ee-4a0f-8fe7-e01954306fb6.png)

**Comment by davidteather** [comment]
Look into V6
