### ISSUE TITLE
[FEATURE_REQUEST] - Function to generate requests.get kwargs

### ISSUE THREAD

**Issue by zulc22** [davidteather/TikTok-Api#747]
**Is your feature request related to a problem? Please describe.**
i'm writing a scraper based on this library, and i'd like to have control of running requests.get so i can display a progress bar while downloading videos, but to do that i would have to messily copy and paste code from get_bytes() to do it differently.

**Describe the solution you'd like**
a function that generates the kwargs passed to requests.get (minus the url param), like get_bytes() does

**Describe alternatives you've considered**
adding a progress bar to tiktokapi would be an alternative solution to my problem, but that would lock people using tiktokapi to a CLI interface for that one thing, and a function like i am describing could solve other problems and allow for the library to be integrated in more kinds of applications programmed in python.

**Comment by davidteather** [comment]
You should have more flexibility in V6, let me know if you need more tooling around it
