### ISSUE TITLE
[ImportError]

### ISSUE THREAD

**Issue by KevinSig** [davidteather/TikTok-Api#75]
Hi David, 

Thanks for making this! I am however having some issues with importing, I am consistently getting this issue "ImportError: cannot import name 'TikTokApi' from 'TikTokApi' (/usr/local/lib/python3.7/site-packages/TikTokApi/__init__.py)" 

Any idea why?

Thanks for your effort!

**Comment by davidteather** [comment]
What code are you running?

**Comment by KevinSig** [comment]
Im running getTrending.py

**Comment by davidteather** [comment]
I just realized I didn't have one of the required packages in the install_requires for the package.
You can either do
```
pip install TikTokApi --upgrade
```

or just do
```
pip install pyppeteer
```

And hopefully this should fix your issue.

**Comment by KevinSig** [comment]
Wow! You are amazing, that did it! Thanks for being so responsive. As a side note: any chance I would be able to do a search by hashtag? I saw an open issue before but wanted to see your thoughts. 

Thanks again.

**Comment by davidteather** [comment]
Yeah I'm trying to add a search by hashtag. I've had it in previous versions, but right now I've been having an issue getting the signature to work for that endpoint.

**Comment by Nicocarello** [comment]
Hey david,

I ran those two lines and I'm still getting the same error. Do you know what could be the issue?
