### ISSUE TITLE
ERROR: The request could not be satisfied

### ISSUE THREAD

**Issue by zurdok1280** [davidteather/TikTok-Api#750]
The TikTok API isn't working, 
ERROR:root:Tiktok response: 
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Bad request.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: YDg97PShlKvMCvORQQRIBUZ6DGm5DhyGtMNTZvQ3_q2yRs___8dpLA==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

**Comment by ucmuller** [comment]
I'm getting the same error.
Is it because I can't authenticate with cookies anymore?

**Comment by zurdok1280** [comment]
this problems is when run api.by_username

**Comment by alma359** [comment]
I also started getting this error

**Comment by sazwan9602** [comment]
Having same issue as well.

**Comment by sedanijay** [comment]
having same issue @davidteather

**Comment by DigitalApeMedia-DS** [comment]
any advice to solver this issue @davidteather

**Comment by Atidhaya** [comment]
I have the same issue as well.

**Comment by fs-akjha** [comment]
@davidteather Getting same issue please look into this.

**Comment by Namine4** [comment]
Same issue for me too! Can't get past the Captcha.

"TikTok blocks this request displaying a Captcha 
Tip: Consider using a proxy or a custom_verifyFp as method parameters"

I am already using custom_verifyFp.

`from TikTokApi import TikTokApi
import logging
api = TikTokApi.get_instance(logging_level=logging.INFO, custom_verifyFp="cookie")
print(api.by_username("username", count=1, custom_verifyFp="cookie"))`

**Comment by Alex-Laparra** [comment]
until david updates it, use @BeatRoy 's pull request guys, fixed it for me

**Comment by InfluencerHunters** [comment]
As already pointed out, the call is failing due to the Captcha request. 
In fact, Tiktok has been very active in the current months in blocking these kind of requests from bots (and should not expect things to get better)

**Comment by zurdok1280** [comment]
@BeatRoy version its works!, great job

**Comment by BeatRoy** [comment]
@InfluencerHunters That is correct but without my fix none of the requests work on my machine because CloudFront does not like the host header.

**Comment by Namine4** [comment]
Can someone help me out here. I'm still getting the same error, but I don't think I grabbed the new branch correctly (new to this). I'm working in a VS Code Terminal on Windows 10.
`python -m pip uninstall TikTokApi`
`git clone https://github.com/BeatRoy/TikTok-Api.git`
`cd TikTok-API`
`python setup.py install`

**Comment by LauraBMo** [comment]
> Can someone help me out here. I'm still getting the same error, but I don't think I grabbed the new branch correctly (new to this). I'm working in a VS Code Terminal on Windows 10. `python -m pip uninstall TikTokApi` `git clone https://github.com/BeatRoy/TikTok-Api.git` `cd TikTok-API` `python setup.py install`
> 
> `from TikTokApi import TikTokApi` `api = TikTokApi.get_instance(custom_verifyFp="cookie")` `print(api.by_username("username", count=1, custom_verifyFp="cookie"))`

@Namine4, you are missing checking out to the right branch:
...
 `cd TikTok-API` 
`git checkout fix/403-error-cloudfront`
`python setup.py install`
...

**Comment by sazwan9602** [comment]
> Can someone help me out here. I'm still getting the same error, but I don't think I grabbed the new branch correctly (new to this). I'm working in a VS Code Terminal on Windows 10. `python -m pip uninstall TikTokApi` `git clone https://github.com/BeatRoy/TikTok-Api.git` `cd TikTok-API` `python setup.py install`
> 
> `from TikTokApi import TikTokApi` `api = TikTokApi.get_instance(custom_verifyFp="cookie")` `print(api.by_username("username", count=1, custom_verifyFp="cookie"))`

Pulling from fix/403-error-cloudfront won't solve issue with api.by_username()
Tiktok has changed new api params to get user posts, so api.by_username can't be use anymore, besides if you try this https://try.playwright.tech/?e=screenshot-async&l=python and pass any tiktok urls, you might get timeout error. Somehow playwright can't access tiktok domain anymore

**Comment by pierreminiggio** [comment]
just a comment so i get notified

**Comment by davidteather** [comment]
Might have been fixed in V4.1.0, but cloudfront workaround in #768

**Comment by alma359** [comment]
For me it is fixed

**Comment by pierreminiggio** [comment]
Fixed for me as well, thanks !
