### ISSUE TITLE
[INSTALLATION] - Deploy TikTok-Api into Docker on Heroku

### ISSUE THREAD

**Issue by impossibleno1** [davidteather/TikTok-Api#756]
I want to deploy a project that has TikTok-Api on **Heroku** but Heroku does not support **playwright**, and I have an error when using the TikTok-API module.
Can I run my project with TikTok-API in Docker?

**Comment by hrynkodev** [comment]
Yep, you could do that, just ensure you use this image as base
`mcr.microsoft.com/playwright:v1.17.0-focal` it already contains all needed playwright dependencies, node and python, the only con of this is size around 2GB, but if that fits, you're good to go with that image

**Comment by BrentGarcia** [comment]
@impossibleno1 were you able to get this working? I have been having all sorts of issues with playwright when deploying. I tried the buildpacks, manual ssh -> installation and all sorts of other things. Using docker was going to be my next attempt. Would love to hear if you had any success.

**Comment by impossibleno1** [comment]
> 

@BrentGarcia I haven't done that yet, because I use free account on Heroku (free 500MB)

**Comment by hrynkodev** [comment]
@impossibleno1 you could try out digital ocean, as I know they have a free trial

**Comment by davidteather** [comment]
Search for deploying playwright with heroku or use container
