### ISSUE TITLE
is_digg ??

### ISSUE THREAD

**Issue by BeAsphyxia** [davidteather/TikTok-Api#758]
Hey there, i want to know what "is_digg" means..

due on my devices when i like a post it shows up this ( THIS DOESNT SAVE THE LIKE )
**status_code":0,"is_digg":1**

but on the browser / www.tiktok.com i get this ( THIS DOES SAVE THE LIKE )
**status_code":0,"is_digg":0**

I unliked around 3k videos in 2 days just you to know.

Hope you guys can help me ; Also comment / follow works on website and on app ( On these ones it does show "is_digg" = 0 )

**Comment by BeAsphyxia** [comment]
> is_digg = 1 is caused by a bad device (not enabled by xlog) or bad headers (wrong signature) or a bad proxy

Thanks for replying to me, what could cause a " bad device " // Currently using my iPhone 12 ( The other day it let me like 3 videos only )
And bad headers wouldn't make sense as im not making the request, its being done by the tiktok app so.

**Comment by davidteather** [comment]
I believe is_digg is 0/1 depending on if the user who made the request liked the video or not. But I could be wrong, haven’t dug into it too much. 

This library will always return 0 since it doesn’t support user authenticated requests, but it seems like you’re doing something else :)

**Comment by BeAsphyxia** [comment]
Exactly i took a look on the requests from android app and when i liked a video on the request it appeared is_digg = 1 ( ban? )
Meanwhile i comment or follow and it appears is_digg = 0 ( unban? )

So i was wondering why my account is actually getting is_digg = 0 on mobile app when liking a post.
Only happens that when im liking a video ( MOBILE APP )
On browser it's always is_digg = 0

**Comment by aimadnet** [comment]
> Exactly i took a look on the requests from android app and when i liked a video on the request it appeared is_digg = 1 ( ban? ) Meanwhile i comment or follow and it appears is_digg = 0 ( unban? )
> 
> So i was wondering why my account is actually getting is_digg = 0 on mobile app when liking a post. Only happens that when im liking a video ( MOBILE APP ) On browser it's always is_digg = 0

Like api is a sensitive endpoint, you can try to login for example on web and like a video, you will get is_digg=0, change user agent of your browser and like a different video, you will get is_digg=1.

same thing for mobile, if something wrong, bad x-gorgon, device not enabled... you will get is_digg=1

**Comment by BeAsphyxia** [comment]
My point here is that i actually don't know what's going on with my tiktok account or why im getting is_digg=1 on an account but on other account i don't get that ; 

Would you explain me about x-gorgon , device not enabled?

**Comment by aimadnet** [comment]
> My point here is that i actually don't know what's going on with my tiktok account or why im getting is_digg=1 on an account but on other account i don't get that ;
> 
> Would you explain me about x-gorgon , device not enabled?

- x-gorgon is a mobile security token, it's used to sign api requests.

- for "device not enabled", when you register a new device on mobile using device registration api, it's not enabled by default, you can login but you can't follow and like videos, you need to do other api calls to enable the device like xlog.

**Comment by BeAsphyxia** [comment]
I understand, do you know where i could check if "device is enabled" ?

Now on browser i get is_digg = 1 when this morning it was 0

**Comment by aimadnet** [comment]
> I understand, do you know where i could check if "device is enabled" ?
> 
> Now on browser i get is_digg = 1 when this morning it was 0

there is no api to check if device is enabled.

you can try this on your browser, logout/login then like a video, if you still getting is_digg = 1 then it's an account issue.

**Comment by BeAsphyxia** [comment]
Thanks in case it was an account issue would you know how much time does it take to get that bug / error / glitch gone?

**Comment by aimadnet** [comment]
> Thanks in case it was an account issue would you know how much time does it take to get that bug / error / glitch gone?

few days I think

**Comment by BeAsphyxia** [comment]
Should i let the account sit for a few days without no login / use or it doesn't matter.
Also thank you so much for the help

**Comment by aimadnet** [comment]
> Should i let the account sit for a few days without no login / use or it doesn't matter. Also thank you so much for the help

Yah just stop using the account for a moment, you welcome!

**Comment by BeAsphyxia** [comment]
Thanks, will logout from the account for 5 days and will see
