### ISSUE TITLE
[BUG] - Captcha issue on get_suggested_users_by_id (more specifically get_data I think?)

### ISSUE THREAD

**Issue by mdunham64** [davidteather/TikTok-Api#764]
I have been having the Captcha exception issue recently on select method calls and I want to know if its an error on my end, or if others have been experiencing it lately. I am using both a custom verify_Fp and proxy.  

I have been trying to use the `get_suggested_users_by_id` method and that has been giving me the captcha exception. I think this issue may not be my implementation/usage of this library because I have been using other methods such as `search_for_users` and I have no issues.

I went to other issues and saw similar issue/solutions to this captcha issue and after looking at BeatRoy's branch, his version seems to only fix specific methods that are separate from `get_suggested_users_by_id` which uses `get_data` to formulate the GET request. 

I am using this API for a final project of mine for a course and this method is the bread and butter of what I need. Hopefully I can get it working before finals roll around... haha

**Comment by kang-yaowen** [comment]
Did you solve this problem? How to solve it

**Comment by mdunham64** [comment]
I did, the exception handling was over broad in `get_data` and I had issues with my proxy. The thrown exception was a captcha issue, but the root cause was my Proxy server being misconfigured. After the recent updates to the API, there is more robust exception handling, so I decided to resolve the issue.
