### ISSUE TITLE
[FEATURE_REQUEST] - Maybe you could use this api to get nwm video

### ISSUE THREAD

**Issue by MiraUMR** [davidteather/TikTok-Api#771]
https://api-h2.tiktokv.com/aweme/v1/play/?video_id=

**Comment by davidteather** [comment]
Think this is what we used to get no watermark a while ago, but the video_id is not the same as the web ID version. And the only way to get this was look at the bytes of the mp4 which had this as metadata but that was removed from the mp4 for videos after a specific date.
