### ISSUE TITLE
[BUG] - Any way to search videos? discover_type and get_recommended_tiktoks_by_video_id don't work?

### ISSUE THREAD

**Issue by TDKorn** [davidteather/TikTok-Api#773]
**Describe the bug**

Hoping to use the API to search videos by keyword/by related videos. Neither of these methods seem to work for me, not sure if I'm using it incorrectly though?

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
api.discover_type('cats','video') or api.discover_type('cats','videos')
api.get_recommended_tiktoks_by_video_id(6998735264382323973)
```

**Expected behavior**

Return tiktoks that match keyword or are related to the video provided

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
**When calling get_recommended_tiktoks_by_video_id**
  raise GenericTikTokError(
TikTokApi.exceptions.GenericTikTokError: TikTok sent an unknown StatusCode of 10404

**When calling discover_type**
ERROR:root:TikTok response:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\{}\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokApi\tiktok.py", line 596, in discover_type
    data = self.get_data(url=api_url, **kwargs)
  File "C:\Users\{}\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokApi\tiktok.py", line 375, in get_data
    raise EmptyResponseError(
TikTokApi.exceptions.EmptyResponseError: Empty response from Tiktok to https://m.tiktok.com/api/discover/video/?aid=1988&app_name=tiktok_web&device_platform=web_mobile&region=GB&priority_region=&os=ios&referer=&root_referer=&cookie_enabled=true&screen_width=1906&screen_height=1389&browser_language=en-gb&browser_platform=iPhone&browser_name=Mozilla&browser_version=Mozilla%252F5.0%2B%28iPhone%253B%2BCPU%2BiPhone%2BOS%2B12_2%2Blike%2BMac%2BOS%2BX%29%2BAppleWebKit%252F605.1.15%2B%28KHTML%2C%2Blike%2BGecko%29%2BVersion%252F13.0%2BMobile%252F15E148%2BSafari%252F604.1&browser_online=true&timezone_name=America%252FToronto&is_page_visible=true&focus_state=true&is_fullscreen=false&history_len=28&language=en&discoverType=0&needItemList=False&keyWord=cats&offset=0&count=28&useRecommend=False&language=en&verifyFp=verify_kxchlsbf_WFpZVfAJ_SNz8_4LyS_BEDc_3ZTXG4ByLVGQ&device_id=0842180027718472485&_signature=_02B4Z6wo00f01.bV9hwAAIBBVdKdxt-dSR.2xPKAAJwU35
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version 4.1.0

**Additional context**

**Comment by Incher25** [comment]
I get the similar error while running get_tiktok_by_id():


> $ python3 get_tiktok_by_id.py 6886847135426301185
> Traceback (most recent call last):
>   File "/var/.../scripts/TikTok/get_tiktok_by_id.py", line 16, in <module>
>     tiktok = json.dumps(api.get_tiktok_by_id(id=tiktokId))
>   File "/usr/local/lib/python3.7/dist-packages/TikTokApi/tiktok.py", line 1206, in get_tiktok_by_id
>     return self.get_data(url=api_url, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/TikTokApi/tiktok.py", line 366, in get_data
>     statusCode, f"TikTok sent an unknown StatusCode of {statusCode}"
> TikTokApi.exceptions.GenericTikTokError: TikTok sent an unknown StatusCode of 10204

get_tiktok_by_id.py:

```
import sys
import json
from TikTokApi import TikTokApi

use_test_endpoints=None
api = TikTokApi.get_instance(use_test_endpoints=use_test_endpoints)
tiktok = json.dumps(api.get_tiktok_by_id(id=tiktokId))
print(tiktok)
```

- TikTokApi Version 4.1.0
- OS: Ubuntu 18.04

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
