### ISSUE TITLE
[BUG] - 'TikTokApi' object has no attribute 'getSuggestedUsersbyIDCrawler'     

### ISSUE THREAD

**Issue by Blast06** [davidteather/TikTok-Api#774]
# Read Below!!! If this doesn't fix your issue delete these two lines
**You may need to install chromedriver for your machine globally. Download it [here](https://sites.google.com/a/chromium.org/chromedriver/) and add it to your path.**

**Describe the bug**

**The buggy code**

Please insert the code that is throwing errors or is giving you weird unexpected results.

```
# Code Goes Here

seed_users = ['tiktok', 'washingtonpost', 'charlidamelio', 'chunkysdead']
seed_ids = [api.get_user(user_name)['userInfo']['user']['id']
            for user_name in seed_users]
suggested = [api.getSuggestedUsersbyIDCrawler(
    count=20, startingId=s_id) for s_id in seed_ids]
```

**Expected behavior**

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here

Traceback (most recent call last):
  File "g:\desktop\pp\pp\pp\tiktok_demo.py", line 55, in <module>  
    suggested = [api.getSuggestedUsersbyIDCrawler(
  File "g:\ppp\ppppp\PYTHON\ppp\tiktok_demo.py", line 55, in <listcomp>
    suggested = [api.getSuggestedUsersbyIDCrawler(
AttributeError: 'TikTokApi' object has no attribute 'getSuggestedUsersbyIDCrawler'      


```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version 4.1.0

**Additional context**

**Comment by davidteather** [comment]
That method has been deprecated as of v4.1.0

**Comment by Blast06** [comment]
ok, but is there another method or way to get that exact same data?
