### ISSUE TITLE
[BUG] - How do i get comments

### ISSUE THREAD

**Issue by kang-yaowen** [davidteather/TikTok-Api#776]
# Why remove the video comment method and how do I get the comment

**Describe the bug**

After I updated V4.1.0, I found that comments could not be obtained, and then I found that there is no video_comment method in the new version. I thought that the comment data would be obtained in user_page, but I found that I was wrong, there is no comment data, then how should I get the comment

**Desktop (please complete the following information):**
 - OS: [ Windows 10]
 - TikTokApi Version [ 4.1.0]

**Comment by davidteather** [comment]
Comments have never been able to be retrieved with this API, unless they were included in some meta-data somewhere but I don't have knowledge of this existing
