### ISSUE TITLE
[BUG] - TikTokApi.exceptions.JSONDecodeFailure: TikTok sent invalid JSON back

### ISSUE THREAD

**Issue by luad1234** [davidteather/TikTok-Api#777]
**Describe the bug**

When attempting to scrape trending hashtags I get hit with the error "TikTokApi.exceptions.JSONDecodeFailure: TikTok sent invalid JSON back"

**Additional context**
````
verifyFp = ""

api = TikTokApi.get_instance(custom_verifyFp=verifyFp)
````
I already have verifyFp added to my code.

What is strange is that I have another script that i use to scrape emails and that script works fine but this one is failing to run.

**Comment by davidteather** [comment]
Can you provide more of the code you're running? Rather than just how you're initializing the library?

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
