### ISSUE TITLE
[BUG] - TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha

### ISSUE THREAD

**Issue by kevit-dhairya-bapodra** [davidteather/TikTok-Api#778]
**Describe the bug**

I am trying to scrape posts from profile using your code, but getting 10000 error code. I did a bit of debugging and found out that the issue is maybe due to invalid _signature. I have already tried with custom_verifyFp and also proxy as well as VPN but facing the same error.Also, I am able to open the profile in browser without loging, so my IP isn't blocked and it isn't displaying any captcha.

**The buggy code**

```
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()
results = 10

# Since TikTok changed their API you need to use the custom_verifyFp option.
# In your web browser you will need to go to TikTok, Log in and get the s_v_web_id value.
trending = api.by_trending(count=results, custom_verifyFp="")

for tiktok in trending:
    # Prints the id of the tiktok
    print(tiktok['id'])

print(len(trending))
```

**Error Trace (if any)**

```
{'code': '10000', 'from': '', 'type': 'verify', 'version': '', 'region': 'va', 'subtype': 'slide', 'detail': 'Om4r-6OL8ecuWLMH8SchRcSS*vOeX31LKaHuFj5Peq9G0Xs6exPK3AvgF4YYrtxCmogpSWm77DlG2fI-cWlFiLmJslx131cJwD2PyDCDPGdpK4spDr*yIGkjnisc*NUc-tCvThVSlL4bbWdo*iD9Kr7zUb8RHkIq*iSpfvTNMvliuLSjFDp17FDnrJ-jWT9uiXSYTg5Gg1-VUmEU1O14CvK66X6wBIH9LvN-l2fbmRalRMnFTz9O5lR7*BCOXSkRqf3ayX-N222kiUfR3hDgHC70tocZUsPmS1vb4lnVw8qUsvPy2jf2oFLeelwW1x4N6q49EDJAelLbcznZeq0kZ3LpXHkxUlYLOLghRxlIwGlXC5oM3r5FdvRGvz-VAt0w242xhX-DyWL*nFmpO*7C*MMeMb0HiKDB', 'verify_event': '', 'fp': 'verify_3367e439432b62d07dc6348cfd4068e7', 'scene': '', 'verify_ticket': '', 'channel_mobile': '', 'sms_content': '', 'mobile': '', 'email': ''}
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - TikTokApi Version [e.g. 3.3.1] - 4.1.0

**Additional context**

**Comment by kang-yaowen** [comment]
I also encountered the same problem, I tried to replace verifyFp to solve the problem, but it didn't work

**Comment by vdemay** [comment]
Same for me! It seems something changes on tiktok side

**Comment by BK-Go-Python** [comment]
I also encountered the same problem

**Comment by JetLei** [comment]
same for me

**Comment by Blast06** [comment]
same here.

**Comment by BK-Go-Python** [comment]
It's fine. Is yours all right？

**Comment by davidteather** [comment]
Seems to be working for mine without a proxy on a residential IP. If you're still facing this issue if you could provide more information that might help.

**Comment by remillou** [comment]
This works fine for me but can't manage to make work by_username() even with custom_verifyFp or a proxy since wednesday even though it was working before :(

**Comment by mdunham64** [comment]
I had this error a few weeks ago. Make sure your proxy is working appropriately (that was my original issue). If you haven't recently changed your verifyFp, update it only after solving a captcha puzzle manually. Other than that the problem more or less fixed itself for me over the course of a week.

**Comment by botcoder-sys** [comment]
by_username is not working for me right now even with custom_verifyFp. Let me know if there is any fix for this

**Comment by angelopouloschristos** [comment]
after using by_username() method, i get spammed with HTML response from tiktok and 
`TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters
`
even if i use custom settings

**Comment by angelopouloschristos** [comment]
here is what i execute : 
`from TikTokApi import TikTokApi
api = TikTokApi.get_instance()

results = 100

# Since TikTok changed their API you need to use the custom_verifyFp option.
# In your web browser you will need to go to TikTok, Log in and get the s_v_web_id value.
trending = api.by_username("addisonre", count=results)

for tiktok in trending:
    # Prints the id of the tiktok
    print('https://www.tiktok.com/@xxx/video/'+tiktok['id'])

print(len(trending))
`
[response.txt](https://github.com/davidteather/TikTok-Api/files/7792725/response.txt)

**Comment by an-dev** [comment]
@kevit-dhairya-bapodra It would be nice to know why this was closed without resolution. 

Is it related to #735? Has the issue even been identified? Is the project still mantained?

**Comment by kevit-dhairya-bapodra** [comment]
@an-dev The issue was resolved once I changed verifyFp and now it is working fine for me.

**Comment by angelopouloschristos** [comment]
This ha

> @an-dev The issue was resolved once I changed verifyFp and now it is working fine for me.

Please, post what you did put in the file & command to make it work.
It is not working for me whatever i try and I DID NOT abuse request to tiktok to be blocked ...

Post solution please or re-open the issue

**Comment by botcoder-sys** [comment]
I am sorry how this issue is closed whereas I am not able to run the api. Please provide the solution

**Comment by grydev** [comment]
try to open the API instance like that:
verifyFp = "verify_blablabla"
api = TikTokApi.get_instance(custom_verifyFp=verifyFp, use_test_endpoints=True)

**Comment by angelopouloschristos** [comment]
> try to open the API instance like that: verifyFp = "verify_blablabla" api = TikTokApi.get_instance(custom_verifyFp=verifyFp, use_test_endpoints=True)

same error ... 
I've spend hours on it, even buying proxy's / VPS / using VPN / Changing IP ... 
Nothing seem to work when tiktok decide to.
I also find out that there is some moments that it is working for a reason but cannot tell when exactly.

For example, if you try to get user video ID : 

from TikTokApi import TikTokApi

verifyFp = "verify_6bf4a64c73db43a8ea231f92114a7a56"
api = TikTokApi.get_instance()

results = 100

# Since TikTok changed their API you need to use the custom_verifyFp option.
# In your web browser you will need to go to TikTok, Log in and get the s_v_web_id value.
trending = api.by_username("addisonre", count=results, custom_verifyFp=verifyFp)

for tiktok in trending:
    # Prints the id of the tiktok
    print('https://www.tiktok.com/@xxx/video/'+tiktok['id'])

print(len(trending))

like this ... you will find out that it work 1 time of out 100 ... for no reason ...

**Comment by grydev** [comment]
> > try to open the API instance like that: verifyFp = "verify_blablabla" api = TikTokApi.get_instance(custom_verifyFp=verifyFp, use_test_endpoints=True)
> 
> same error ... I've spend hours on it, even buying proxy's / VPS / using VPN / Changing IP ... Nothing seem to work when tiktok decide to. I also find out that there is some moments that it is working for a reason but cannot tell when exactly.
> 
> For example, if you try to get user video ID :
> 
> from TikTokApi import TikTokApi
> 
> verifyFp = "verify_6bf4a64c73db43a8ea231f92114a7a56" api = TikTokApi.get_instance()
> 
> results = 100
> 
> trending = api.by_username("addisonre", count=results, custom_verifyFp=verifyFp)
> 
> for tiktok in trending: print('[https://www.tiktok.com/@xxx/video/'+tiktok['id']](https://www.tiktok.com/@xxx/video/'+tiktok%5B'id'%5D))
> 
> print(len(trending))
> 
> like this ... you will find out that it work 1 time of out 100 ... for no reason ...

You have to add custom_verifyFp=verifyFp into the instance where you create the api.

api = TikTokApi.get_instance(custom_verifyFp=verifyFp) #maybe also add use_test_endpoints=True
results = 100

trending = api.by_username("addisonre", count=results)

**Comment by angelopouloschristos** [comment]
I'm still getting the same Captcha/Proxy thing ...
I can't understand why it is not working for me, it seem so strange 


`from TikTokApi import TikTokApi

verifyFp = "verify_9d02b66b-3921-483f-9efc-83d903215089"
api = TikTokApi.get_instance(custom_verifyFp=verifyFp) #maybe also add use_test_endpoints=True
results = 100

trending = api.by_username("addisonre", count=results)

for tiktok in trending:
    # Prints the id of the tiktok
    print('https://www.tiktok.com/@xxx/video/'+tiktok['id'])

print(len(trending))
`

**Comment by botcoder-sys** [comment]
@angelopouloschristos I am using custom_verifyFp and using by.username() method and still I am getting the captcha error. It is not working for me as well

**Comment by angelopouloschristos** [comment]
@davidteather please, re-open the issue so poeple can see it instead  of openning new issues with the same problem

**Comment by botcoder-sys** [comment]
@angelopouloschristos A bit of update. Previously, it was working without any proxy change or anything but right now, I am trying to send request until it succeeded and by.username() woks once after 20-30 tries and also changing proxy helps. Whereas earlier, by.username() was working with the first try but now the if the program keep on trying it works for once after 30 tries and for the rest of the time I get this error. I am still trying with custom_verifyFP and changing proxies sometimes get the request succeeded. Thanks 
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters

**Comment by angelopouloschristos** [comment]
> @angelopouloschristos A bit of update. Previously, it was working without any proxy change or anything but right now, I am trying to send request until it succeeded and by.username() woks once after 20-30 tries and also changing proxy helps. Whereas earlier, by.username() was working with the first try but now the if the program keep on trying it works for once after 30 tries and for the rest of the time I get this error. I am still trying with custom_verifyFP and changing proxies sometimes get the request succeeded. Thanks TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha Tip: Consider using a proxy or a custom_verifyFp as method parameters

Happy to see you got the same issue like me, yea it work once every X try's ... 
Waiting for someone to solve the issue but meanwhile, i will just make a batch-file that spam the request hahahaah ... what else "easy" should we do
