### ISSUE TITLE
region and language not working!

### ISSUE THREAD

**Issue by ckqweo** [davidteather/TikTok-Api#779]
At first I changed the language and region parameters and ran the code.
```python
results = 10
language = "tr"
region = "TR"
trending = api.by_trending(results, language , region)  # Results:  tr/TR
```

Then I tested again with different language and region parameters, but the language of the videos remained "tr" and the region did not change.

```python
results = 10
language = "en"
region = "US"
trending = api.by_trending(results, language , region ) # Results:  tr/TR
```

I think the problem must be with the cookies. Is there a way to change the cookies or fix this problem?

**Comment by davidteather** [comment]
Unfortunately, I haven't been able to ever get the lang&region to update correctly. As far as I can tell it's only based on your IP region, so if you want US results you'll have to use a US proxy
