### ISSUE TITLE
Runtime error in Example

### ISSUE THREAD

**Issue by xvariable** [davidteather/TikTok-Api#78]
Hi David,
thanks for making this, I´m really looking forward to the hashtag- API. 

In the meantime I updated my version of TikTokApi and now I get a runtime error when running the example code. Do you have any idea why?
Thank you so much in advance!
Julia

![Bildschirmfoto 2020-05-10 um 18 49 15](https://user-images.githubusercontent.com/10835521/81505438-648ca780-92ef-11ea-9d79-0cf3749b56db.png)

**Comment by davidteather** [comment]
What TikTokApi version are you running? 

You can run the following to find out the version
```
pip show TikTokApi
```

**Comment by xvariable** [comment]
I´m running version 3.0.1. I´ve set up a new environment in Anaconda just for this test (python 3.7.7). All dependencies of are installed.

**Comment by davidteather** [comment]
I imagine it’s an error with anaconda or python notebook because it works without those

**Comment by xvariable** [comment]
Indeed, you are right. Here is a description of the error: https://github.com/spyder-ide/spyder/issues/7096

Thank you so much! I switched to PyCharm and it works fine now. :)
