### ISSUE TITLE
[BUG] - Error:root:TikTok Response

### ISSUE THREAD

**Issue by sspchunduri** [davidteather/TikTok-Api#781]
ERROR:root:TikTok response: {statusCode: 0,body: {userData: {},statusCode: -1,shareUser: {}}} 
ERROR:root:Converting response to JSON failed
ERROR:root:Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

api = TikTok.get_instance(use_test_endpoints=True,custom_verifyFp=verifyFp,request_delay=delay)
tag = "hello"
tiktoks = api.by_hashtag(f'{tag}', count=count, custom_verifyFp=verifyFp)

f = open("file.json", "w")

for t in tiktoks:
 x = json.dumps(t)
 print(x, file=f)

f.close()

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
