### ISSUE TITLE
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha

### ISSUE THREAD

**Issue by ckqweo** [davidteather/TikTok-Api#782]
ERROR:root:Tiktok wants to display a catcha. Response is:
{"code":"10000","from":"","type":"verify","version":"","region":"va","subtype":"slide","detail":"9CxsJVqSOr3eA0qi2oaQGaZ7jKU4owZhodmNScizgWebzliTQ9kVvHcJWMzA9CUij-EXuq5TVrZTK5l4p*1sud4sjhUknZRcUZHrqKJAeBlL2mZAJ9N*PBkARK1UsMU3Rcy2AvDVx7crHAegdA7xhmM9w7bOEcxw2Q7AE39Aj5YQFD6tke7eOwEbeJd3SrDAIH7W1ZuMDQ22S6rrqLZWwk0iu6m7sIkPac9C-OdEze9-KRiFhKV1OJPjw1*-U7HznKWhrIw6Ggvh0FGCPK6LuwSspWxHGe*bJ650wM4D8giiCu8ejjkK64jrB-pzEc0psqO8C9WDYBIVlgVf430kqmY5ZwvHyghZeyPO0KC83GyJYGVhx-e*sPi6*wKvGq-4OC0Ar5uJScuohNZTzgcwGbcqUXuJ7CMycx4qqyS*UmSB5J5TFPE.","verify_event":"","fp":"verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq","scene":"","verify_ticket":"","channel_mobile":"","sms_content":"","mobile":"","email":""}
ERROR:root:{'tt_webid': '8560152714148130852', 'tt_webid_v2': '8560152714148130852', 'csrf_session_id': '409d25cfbbfda9175f32656d10a01323', 'tt_csrf_token': 'zIWkEVNASTGHnldV', 'ttwid': None}
Traceback (most recent call last):
  File "D:\pythonProjects\tiktok\main.py", line 10, in <module>
    tiktoks_all = api.by_hashtag("test",count=30,offset =0)
  File "D:\pythonProjects\tiktok\venv\lib\site-packages\TikTokApi\tiktok.py", line 1089, in by_hashtag
    res = self.get_data(url=api_url, **kwargs)
  File "D:\pythonProjects\tiktok\venv\lib\site-packages\TikTokApi\tiktok.py", line 310, in get_data
    raise TikTokCaptchaError()
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha 
Tip: Consider using a proxy or a custom_verifyFp as method parameters

**Comment by isaackogan** [comment]
It says it all in the error.

> TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters

**Comment by Tyrannas** [comment]
I get the exact same error only when using by_hashtag method, when i'm using by trending it works fine.

Example that works:

```python
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()

trending = api.by_trending(count=10, custom_verifyFp=my_sv_web_id)

for tiktok in trending:
    # Prints the id of the tiktok
    print(tiktok['id'])
```

Example that doesn't and produce the catcha error:

```python
from TikTokApi import TikTokApi
api = TikTokApi.get_instance()

trending = api.by_hashtag("funny", count=10, custom_verifyFp=my_sv_web_id)

for tiktok in trending:
    # Prints the id of the tiktok
    print(tiktok['id'])
```

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
