### ISSUE TITLE
[INSTALLATION] - CONVERTING program to exe file not working

### ISSUE THREAD

**Issue by ghost** [davidteather/TikTok-Api#783]
I am a program that allows users to download the tik tok using the API through the tkinter module. And everytime I try to switch it to a exe file using pyinstaller or auto-py-to-exe it gives me some sort of playright error. I have tried everyting and it doesnt work. Can someone please help! Thanks!
![error](https://user-images.githubusercontent.com/67206248/147626687-e9d33e80-4168-4621-85f2-eb0573dad0eb.png)

**Comment by akorchyn** [comment]
Welll, you have to install browsers for playwright
Basically, you can run **python3 -m playwright install**. Once it download you can try to run your program again. Also, you may be required to install some dependencies that system is missing. If so run:
**python3 -m playwright install-deps**

Hope it helps.

**Comment by akorchyn** [comment]
![image](https://user-images.githubusercontent.com/42449190/147698636-ea9f95f9-0206-4f43-b9d5-4afd45902eea.png)
Please, take a look for an instruction how to bundle it with the executable for playwright:
https://playwright.dev/python/docs/intro#pyinstaller

**Comment by dillythecoder** [comment]
@akorchyn do you think its something I have to include within the py file

**Comment by davidteather** [comment]
Not sure, probably playwright issue

**Comment by ArtDanger** [comment]
Hello, everybody. Could to try this:

1.  Run this commands in terminal (venv): 

> pip install --upgrade pip
> pip install playwright
> playwright install

2. Recording this code(this solution from playwright [issues](https://github.com/microsoft/playwright-python/issues/342):

```
from sys import modules
from os import listdir, path
from pathlib import Path
from typing import Union


def get_executable_path() -> Union[str, None]:
 
    parent_folder = Path(modules['playwright'].__file__).parent / 'driver' / 'package' / '.local-browsers'

    if not path.exists(parent_folder):
        return None

    child_folders = [name for name in listdir(parent_folder) if path.isdir(parent_folder / name) and name.strip().lower().startswith('chromium')]

    if len(child_folders) != 1:
        return None

    chromium_folder = child_folders[0]

    return parent_folder / chromium_folder / 'chrome-win' / 'chrome.exe'

==============================================================================

with TikTokApi() as api:
    
    api._get_cookies = get_executable_path

```

3. And call this comand in terminal (venv)

> pyinstaller -y -F main.py --add-data "venv/lib/site-packages/playwright/driver;playwright/driver"

Best regards!
