### ISSUE TITLE
ERROR:root:TikTok response: 

### ISSUE THREAD

**Issue by sspchunduri** [davidteather/TikTok-Api#784]
ERROR:root:TikTok response: 

 tag: FreshForEveryone failed! 	[2021-12-29 11:05:11.050282] 

Exception: Empty response from Tiktok to https://t.tiktok.com/api/challenge/item_list/?aid=1988&app_name=tiktok_web&device_platform=web_mobile&region=US&priority_region=&os=ios&referer=&root_referer=&cookie_enabled=true&screen_width=1677&screen_height=1063&browser_language=en-us&browser_platform=iPhone&browser_name=Mozilla&browser_version=Mozilla%252F5.0%2B%28iPhone%253B%2BCPU%2BiPhone%2BOS%2B12_2%2Blike%2BMac%2BOS%2BX%29%2BAppleWebKit%252F605.1.15%2B%28KHTML%2C%2Blike%2BGecko%29%2BVersion%252F15.4%2BMobile%252F15E148%2BSafari%252F604.1&browser_online=true&timezone_name=UTC&is_page_visible=true&focus_state=true&is_fullscreen=false&history_len=16&language=en&count=35&challengeID=1651381170119749&type=3&secUid=&cursor=0&priority_region=&verifyFp=verify_kxrf0wfk_J3x5Fz4v_Q6v7_4lFh_BlPa_WveltnvBdV7q&device_id=6977548409901630545&_signature=_02B4Z6wo00f01AuVw2QAAIBCND1dEP4IbPQLhMfAAGMv77

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
