### ISSUE TITLE
TikTokCaptchaError:

### ISSUE THREAD

**Issue by walterjesus88** [davidteather/TikTok-Api#785]
I can't see the s_v_web_id, apparently tiktok replaced it

TikTokCaptchaError:

**Comment by akorchyn** [comment]
same, have only msToken

**Comment by akorchyn** [comment]
But i think it's because our ip got banned by tiktok

**Comment by botcoder-sys** [comment]
I was not able to see the s_v_web_id as well but it will show to me if I logout and login again. Try to do that @walterjesus88 @akorchyn

**Comment by akorchyn** [comment]
Unfortunately, it doesn't seem to work to me.

**Comment by botcoder-sys** [comment]
@akorchyn I just logged out and then logged in to same account in chrome and click the box and saw the s_v_webid from there!

**Comment by walterjesus88** [comment]
@botcoder-sys @akorchyn When I closed the session it appeared, I hope it does not disappear again

**Comment by davidteather** [comment]
Yeah I haven't seemed to need it in my testing the last few days, but anyways [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
