### ISSUE TITLE
[BUG] - get_user() and get_user_object() not returning user object but html

### ISSUE THREAD

**Issue by warkey456** [davidteather/TikTok-Api#786]
I tried crawl username with get_user() not return user object but html, i put it on other link :

https://drive.google.com/file/d/1E0ilemWDxuziM7QzPfwkj4F8GgZ2pNcY/view?usp=sharing

When i put it on notepad and open it via browser it appears like this.

![image](https://user-images.githubusercontent.com/97008638/147898289-a169d08e-7c74-414d-b6a3-b0689d268d71.png)

Any advice ?

**Comment by angelopouloschristos** [comment]
same for the method by_username. It returns a HTML response, the page of the user you are looking for but does not extract anything.

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
