### ISSUE TITLE
Missing dependencies - amazon linux 2

### ISSUE THREAD

**Issue by jadenmazzone** [davidteather/TikTok-Api#788]
After installing:
```
pip install TikTokApi
python -m playwright install
```
Then after importing TikTokApi I was given the following "missing dependencies" error: 

```
playwright._impl._api_types.Error: Host system is missing dependencies!

  Install missing packages with:
      sudo apt-get install gstreamer1.0-libav

  Missing libraries we didn't find packages for:
      libnotify.so.4
      libicui18n.so.66
      libicuuc.so.66
      libwoff2dec.so.1.0.2
      libgcrypt.so.20
      libjpeg.so.8
      libpng16.so.16
      libwebpdemux.so.2
      libwebp.so.6
      libenchant.so.1
      libhyphen.so.0
      libevdev.so.2
      libgudev-1.0.so.0
```

Is it possible to install playwright on an EC2 instance running amazon linux 2? If so, how do I install the missing dependencies?

TikTokApi 4.0.1

**Comment by akorchyn** [comment]
python3 -m playwright install-deps

**Comment by jadenmazzone** [comment]
@akorchyn I got "Cannot install dependencies for this linux distribution!" I don't think playwright supports it.

**Comment by davidteather** [comment]
Unfortunately you are correct playwright doesn’t support centOS based operating systems
