### ISSUE TITLE
[BUG] - could not find verify fp cookie on tiktik.com

### ISSUE THREAD

**Issue by mdcofficial** [davidteather/TikTok-Api#790]
**Describe the bug**

could not find verify fp cookie on tiktik.com

**Desktop**
 - OS: [Windows 10]
 - TikTokApi Version [3.3.1]

**Comment by sipka** [comment]
Hey, I had a similar issue. I am not sure why but in case you want a quick fix to just move on - what seem to have worked for me is deleting all the cookies and logging back in, but not by scanning a QR code, but with the mobile number.
This has triggered a captcha and once resolved, I was logged in fine, with a verify fp ready to go.
Hope this helps you!

**Comment by davidteather** [comment]
I don't think it's needed anymore at least fully please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
