### ISSUE TITLE
[FEATURE_REQUEST] - Get current user info from cookie

### ISSUE THREAD

**Issue by balmacefa** [davidteather/TikTok-Api#794]
I want dynamically to know who is the owner of the user **cookie**, specifically the **user_name** or **user_id**.
Is this currently possible? Can this be calculated from the cookies?

**Comment by s1saida** [comment]
+1.
FYI this is a demo of getting current login session of Instagram from Firefox cookies db and use it in instaloader (unofficial Instagram API):
https://instaloader.github.io/troubleshooting.html#login-error

**Comment by davidteather** [comment]
The user cookie is not used in this package
