### ISSUE TITLE
[BUG] - Your Error Here

### ISSUE THREAD

**Issue by PeteLigon** [davidteather/TikTok-Api#795]
# Read Below!!! If this doesn't fix your issue delete these two lines
**You may need to install chromedriver for your machine globally. Download it [here](https://sites.google.com/a/chromium.org/chromedriver/) and add it to your path.**

**Describe the bug**
Getting an error in call get_trending function 

Tried to execute get_trending.py in the example folder by getting an error. I also tried to input a custom_verifyfp but still getting the same error. 

**The buggy code**

get_trending.py

Please insert the code that is throwing errors or is giving you weird unexpected results.
1. script I tried to execute is get_trending.py. 
2. second script is below, which uses the customverifyFp. 

from TikTokApi import TikTokApi
api = TikTokApi.get_instance()
results = 10

trending = api.by_trending(count=results, custom_verifyFp="verify_kyat3dlk_jjAEDYEw_aHce_4kZD_9uu3_J9WvCO7ktDtA")

for tiktok in trending:
    # Prints the id of the tiktok
    print(tiktok['id'])

print(len(trending))

```
# Code Goes Here
```

**Expected behavior**
Able to pull the list of trending videos

Able to pull the list of trending videos

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```

 File "C:\Projects\tiktok\test.py", line 7, in <module>
    trending = api.by_trending(count=results, custom_verifyFp="verify_kyat3dlk_jjAEDYEw_aHce_4kZD_9uu3_J9WvCO7ktDtA")
  File "C:\Projects\tiktok\env\lib\site-packages\TikTokApi\tiktok.py", line 486, in by_trending
    ttwid = spawn.cookies["ttwid"]
  File "C:\Projects\tiktok\env\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Projects\tiktok\env\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='ttwid', domain=None, path=None"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version : 4.1.0

**Additional context**

Haven't download chromedriver, is it really required?

**Comment by odogancay-ku** [comment]
Hey I experience this too!

**Comment by vionde** [comment]
Looks like tiktok doesn't generate `ttwid` cookie via HEAD request anymore.
https://github.com/davidteather/TikTok-Api/blob/a356324ab3171d473619fdf3e1dd71e5996cfc29/TikTokApi/tiktok.py#L481

For temporary solution i can offer changing line 486 in `tiktok.py`. You will need to replace `ttwid = spawn.cookies["ttwid"]` for `ttwid = YOURCOOKIE` where is `YOURCOOKIE` is your `ttwid` cookie which you can get by navigating to tiktok.com from your browser (or via GET request).
https://github.com/davidteather/TikTok-Api/blob/a356324ab3171d473619fdf3e1dd71e5996cfc29/TikTokApi/tiktok.py#L486

OR

Replace `request.head` to `request.get` at 481 line of `tiktok.py`. I think it must fix error too
https://github.com/davidteather/TikTok-Api/blob/a356324ab3171d473619fdf3e1dd71e5996cfc29/TikTokApi/tiktok.py#L481

**Comment by KozlovAntonn** [comment]
I experienced that too. And solution from @vionde has worked! @vionde Thank you very much

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem

**Comment by Otorhin** [comment]
**Code**
```
from TikTokApi import TikTokApi

api = TikTokApi(custom_verify_fp="***")

for video in api.trending.videos():
    print(video)
```


**Error**
```Traceback (most recent call last):
  File "D:\Project\Python\tiktok\main.py", line 7, in <module>
    for video in api.trending.videos():
  File "D:\Project\Python\tiktok\venv\lib\site-packages\TikTokApi\api\trending.py", line 40, in videos
    ttwid = spawn.cookies["ttwid"]
  File "D:\Project\Python\tiktok\venv\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "D:\Project\Python\tiktok\venv\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='ttwid', domain=None, path=None"
```

I use V5.0.0

**Comment by the-owl** [comment]
For me upgrading to v5 actually _introduced_ this bug

**Comment by RobinvLeeuwen** [comment]
Just got here because I had the same error in V5.0.0, but when I switched off my VPN the message did disappear. And API worked.

**Comment by krusalovorg** [comment]
I have the same problem

**Comment by StefanoGITA** [comment]
Hi,
I have the same problem with both **4.1.0** and **5.1.1**.
I haven't installed "_chromedriver globally_" because i'm not the machine administrator, but in this machine i use python scripts with selenium and ChromeDriverManager without issues:

```python
# Initialize a new browser
def start_chrome_driver(url, wait=30):
    """
    create an instance of selenium Chrome
    :param url: the url of the site to connect to
    :type url: string
    :param wait: seconds to wait
    :type wait: int
    :return: driver
    :rtype: webdriver.Chrome
    """

    user_data_dir = f"{os.getcwd()}\\UserData"
    os.makedirs(os.path.dirname(user_data_dir), exist_ok=True)
    sys.path.append(user_data_dir)

    options = Options()
    options.headless = True
    options.add_argument("--window-position=10,10")
    options.add_argument('--user-agent=Chrome/79.0.3945.130 Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                         'AppleWebKit/537.36 (KHTML, like Gecko) ')
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-extensions")
    options.add_argument("--disable-gpu")
    options.add_argument("--disable-d3d11")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument(f'user-data-dir={user_data_dir}')

    options.add_experimental_option('excludeSwitches', ['enable-logging'])
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
    driver.implicitly_wait(wait)
    driver.get(url)
    return driver
```

**Comment by Ukosent** [comment]
> Looks like tiktok doesn't generate `ttwid` cookie via HEAD request anymore.
> 
> https://github.com/davidteather/TikTok-Api/blob/a356324ab3171d473619fdf3e1dd71e5996cfc29/TikTokApi/tiktok.py#L481
> 
> Replace `request.head` to `request.get` at 481 line of `tiktok.py`
> 
> https://github.com/davidteather/TikTok-Api/blob/a356324ab3171d473619fdf3e1dd71e5996cfc29/TikTokApi/tiktok.py#L481
> 
> OR
> 
> You can change line 486 in `tiktok.py`. You will need to replace `ttwid = spawn.cookies["ttwid"]` for `ttwid = YOURCOOKIE` where is `YOURCOOKIE` is your `ttwid` cookie which you can get by navigating to tiktok.com from your browser (or via GET request).
> 
> https://github.com/davidteather/TikTok-Api/blob/a356324ab3171d473619fdf3e1dd71e5996cfc29/TikTokApi/tiktok.py#L486

How exactly do I find the ttwid please ? I'm pretty new to this, I've logged onto tiktok, went into dev tools and tried to find ttwid somewhere but I can't find any value, could you explain more precisely how I get it please ?

**Comment by vionde** [comment]
> > Looks like tiktok doesn't generate `ttwid` cookie via HEAD request anymore.
> > https://github.com/davidteather/TikTok-Api/blob/a356324ab3171d473619fdf3e1dd71e5996cfc29/TikTokApi/tiktok.py#L481
> > 
> > Replace `request.head` to `request.get` at 481 line of `tiktok.py`
> > https://github.com/davidteather/TikTok-Api/blob/a356324ab3171d473619fdf3e1dd71e5996cfc29/TikTokApi/tiktok.py#L481
> > 
> > OR
> > You can change line 486 in `tiktok.py`. You will need to replace `ttwid = spawn.cookies["ttwid"]` for `ttwid = YOURCOOKIE` where is `YOURCOOKIE` is your `ttwid` cookie which you can get by navigating to tiktok.com from your browser (or via GET request).
> > https://github.com/davidteather/TikTok-Api/blob/a356324ab3171d473619fdf3e1dd71e5996cfc29/TikTokApi/tiktok.py#L486
> 
> How exactly do I find the ttwid please ? I'm pretty new to this, I've logged onto tiktok, went into dev tools and tried to find ttwid somewhere but I can't find any value, could you explain more precisely how I get it please ?

Open TikTok from browser. ttwid is a cookie, so you can use cookie editor extension, or open dev tools (f12) -> application -> cookies and find ttwid

**Comment by Ukosent** [comment]
> Open TikTok from browser. ttwid is a cookie, so you can use cookie editor extension, or open dev tools (f12) -> application -> cookies and find ttwid

I did find my ttwid, however, whenever I try to use a function from the module, I get no data:

`import imp
from TikTokApi import TikTokApi

api = TikTokApi()
print(api.user(username='therock'))`

Output:
`TikTokApi.user(username='therock', user_id='None', sec_uid='None')`

**Comment by Zenahr** [comment]
Please open this issue. It's still persistent and none of the suggestions above have solved it for me.

```
import json
from TikTokApi import TikTokApi

def get_cookies_from_file():
    with open('cookies.json') as f:
        cookies = json.load(f)
    cookies_kv = {}
    for cookie in cookies:
        cookies_kv[cookie['name']] = cookie['value']
    return cookies_kv

def get_cookies(**kwargs):
    return get_cookies_from_file()

api = TikTokApi(custom_verify_fp=get_cookies)
api._get_cookies = get_cookies  # This fixes issues the api was having

for v in api.trending.videos():
    print(v.author.username)
```

I've also hardcoded the ttwid where applicable.

**Comment by kodurrrr** [comment]
> > > Looks like tiktok doesn't generate `ttwid` cookie via HEAD request anymore.
> > > https://github.com/davidteather/TikTok-Api/blob/a356324ab3171d473619fdf3e1dd71e5996cfc29/TikTokApi/tiktok.py#L481
> > > 
> > > Replace `request.head` to `request.get` at 481 line of `tiktok.py`
> > > https://github.com/davidteather/TikTok-Api/blob/a356324ab3171d473619fdf3e1dd71e5996cfc29/TikTokApi/tiktok.py#L481
> > > 
> > > OR
> > > You can change line 486 in `tiktok.py`. You will need to replace `ttwid = spawn.cookies["ttwid"]` for `ttwid = YOURCOOKIE` where is `YOURCOOKIE` is your `ttwid` cookie which you can get by navigating to tiktok.com from your browser (or via GET request).
> > > https://github.com/davidteather/TikTok-Api/blob/a356324ab3171d473619fdf3e1dd71e5996cfc29/TikTokApi/tiktok.py#L486
> > 
> > 
> > How exactly do I find the ttwid please ? I'm pretty new to this, I've logged onto tiktok, went into dev tools and tried to find ttwid somewhere but I can't find any value, could you explain more precisely how I get it please ?
> 
> Open TikTok from browser. ttwid is a cookie, so you can use cookie editor extension, or open dev tools (f12) -> application -> cookies and find ttwid

Can i hardcode the cookie values inside a json file and read from that file in order to log in ?

**Comment by AmeetKumar-SE** [comment]
ttwid = spawn.cookies["ttwid"] tiktok api, still the same error tries all the above solutions.
