### ISSUE TITLE
[INSTALLATION] - Your error here

### ISSUE THREAD

**Issue by Nitch-dev** [davidteather/TikTok-Api#801]
when i run the code it says this error and i have install playwright now it says to install this and i did this and it says command not found nothing is working :( 

 ║ Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     sudo playwright install-deps                           ║
║                                                            ║
║ <3 Playwright Team         

 - OS: Arch Linux

**Comment by 89z** [comment]
I have an alternate API:

https://github.com/89z/mech

**Comment by davidteather** [comment]
I had this issue on popos, I think `sudo python -m playwright install-deps` worked.
