### ISSUE TITLE
[BUG] - api.by_trending() does not respond

### ISSUE THREAD

**Issue by odogancay-ku** [davidteather/TikTok-Api#806]
**Describe the bug**

when running previously working code suddenly code gets stuck at api.by_trending()

**The buggy code**

```
api = TikTokApi(cookie=cookie, use_test_endpoints=True)
search_results = api.by_trending(count=results)
```

**Expected behavior**

Previously this request returned in 30 seconds, now doesn't respond

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version - Latest

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
