### ISSUE TITLE
_ The URL signature calculation of signature uses get_ acrawler. Py inside_ get_ Acrawler?

### ISSUE THREAD

**Issue by 760644586** [davidteather/TikTok-Api#807]
I see a lot of garbled code in it, and the JS code can't work normally

**Comment by davidteather** [comment]
It should still work properly, it’s just obfuscated js, this one might be less obfuscated on line 24 

https://github.com/drawrowfly/tiktok-scraper/blob/master/src/helpers/Signature.ts

**Comment by 89z** [comment]
Where do those functions come from?

**Comment by 760644586** [comment]
> 它应该仍然可以正常工作，它只是混淆了 js，这个可能在第 24 行被混淆了
> 
> https://github.com/drawrowfly/tiktok-scraper/blob/master/src/helpers/Signature.ts

URL composition, members have those, can you give me some advice?

**Comment by davidteather** [comment]
The URL could look like

`https://api.Tiktok.com/some/path?With_url_params=True...`

This is just an example it's the full url and url params

**Comment by 760644586** [comment]
![1](https://user-images.githubusercontent.com/41118619/151208176-3ec53a5c-6ba2-4711-ae05-717dff9bb083.png)
![2](https://user-images.githubusercontent.com/41118619/151208186-90f159c3-de29-45e9-8b6c-7d4f4120169c.png)

https://us.tiktok.com/api/commit/follow/user/?aid=1988&app_language=zh-Hant-TW&app_name=tiktok_web&battery_info=0.58&browser_language=zh-CN&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F97.0.4692.99%20Safari%2F537.36&channel=tiktok_web&channel_id=0&cookie_enabled=true&device_id=7044877592931976705&device_platform=web_pc&focus_state=true&from=18&fromWeb=1&from_page=user&from_pre=0&history_len=2&is_fullscreen=false&is_page_visible=true&os=windows&priority_region=&referer=&region=US&screen_height=900&screen_width=1440&sec_user_id=MS4wLjABAAAAYQIn0ghGQeUMmuqngrxATRDvKvq8dksgQBjXfrOdFo6wdO3DGbciDey2TfJE6EAR&type=1&tz_name=America%2FChicago&user_id=7035930273985479685&webcast_language=zh-Hant-TW&msToken=9ZVRfvLh5KCA9fRwcMTx5ysMVMj7H45hx2NXcHnbY9e1jcESeY2W74Pg3yyBDNFWV8FiPTkZKizt9BhfdgLhahVygTko7rZsISzU8zN408oycsxLlALrDRHd5mW-jBPFsda-dQ==&X-Bogus=DFSzs3fLzhXANxVYSLIiPRKeej0y&_signature=_02B4Z6wo00001j7htJQAAIDDQG3qaCLmgBY-4dgAAO5X40

If I use the above URL, I can't calculate the same result as tiktok using your JS code

**Comment by davidteather** [comment]
Use V6
