### ISSUE TITLE
You can get video_id by this api

### ISSUE THREAD

**Issue by MiraUMR** [davidteather/TikTok-Api#808]
from this issue thanks to 89z : 
https://github.com/TufayelLUS/TikTok-Video-Downloader-PHP/issues/28

You can get video_id like 'v09044g40000c6n1e5bc77udh7itcncg' by this api :

http://api2.musical.ly/aweme/v1/aweme/detail/?aweme_id=7038589018707070213

https://api-h2.tiktokv.com/aweme/v1/play/?video_id=v09044g40000c6n1e5bc77udh7itcncg

**Comment by devope** [comment]
Doesn't work
