### ISSUE TITLE
No "s_v_web_id" cookie 

### ISSUE THREAD

**Issue by tss333** [davidteather/TikTok-Api#816]
Hi, following the instruction of TikTok-Api, it requires the s_v_web_id value, however it seems no such value now. How can I sovle this problem?

**Comment by baodv1001** [comment]
https://sf16-scmcdn-va.ibytedtos.com/goofy/secsdk-captcha/va/2.15.21/index.html
You can go to this site and get s_v_web_id value like youtube video.

**Comment by davidteather** [comment]
Not sure you need this with V5.0.0 anymore
