### ISSUE TITLE
[BUG] - get_recommended_tiktoks_by_video_id giving StatusCode 10404

### ISSUE THREAD

**Issue by jefferyschroed** [davidteather/TikTok-Api#821]
**Describe the bug**

I am trying to get a list of videos that are recommended by video id. However, any amount returns with the error below.

**The buggy code**

```
from TikTokApi import TikTokApi
api = TikTokApi.get_instance(use_test_endpoints=True)
verifyFp = "verify_51c1fffae69e8b1f44dcb5921bf3c94f"

number_of_tiktoks = int(input("How many TikToks to search through?\n"))

recommendedresults = api.get_recommended_tiktoks_by_video_id(6757817457937499141, count=number_of_tiktoks, custom_verifyFp=verifyFp)

print(recommendedresults)
```

**Expected behavior**

I imagined that x number of tiktoks would be printed from the recommended list of the specified TikTok ID.

**Error Trace (if any)**

```
Traceback (most recent call last):
  File "C:\Users\Jeff\PycharmProjects\messAround\app.py", line 25, in <module>
    recommendedresults = api.get_recommended_tiktoks_by_video_id('6757817457937499141', count=number_of_tiktoks, custom_verifyFp=verifyFp)
  File "C:\Users\Jeff\PycharmProjects\messAround\venv\lib\site-packages\TikTokApi\tiktok.py", line 1168, in get_recommended_tiktoks_by_video_id
    res = self.get_data(url=api_url, **kwargs)
  File "C:\Users\Jeff\PycharmProjects\messAround\venv\lib\site-packages\TikTokApi\tiktok.py", line 364, in get_data
    raise GenericTikTokError(
TikTokApi.exceptions.GenericTikTokError: TikTok sent an unknown StatusCode of 10404
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version: most recent

**Additional context**

I tried getting a fresh verifyFp, loading a new venv, but nothing seems to work. Other functions, such as by_hashtag work just fine though.

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
