### ISSUE TITLE
[BUG] AttributeError: type object 'TikTokApi' has no attribute 'get_instance'

### ISSUE THREAD

**Issue by angelopouloschristos** [davidteather/TikTok-Api#823]
Whatever i execute i get "get_instance" issue ... do someone have the same issue ? Can someone help me to fix it ?

`AttributeError: type object 'TikTokApi' has no attribute 'get_instance'`

Yes, my tiktok api is updated ...

thanks

**Comment by davidteather** [comment]
Please try using [V5.0.0](https://github.com/davidteather/TikTok-Api/releases/tag/V5.0.0) this may solve your problem
