### ISSUE TITLE
How to find user country and user category

### ISSUE THREAD

**Issue by etale-cohomology** [davidteather/TikTok-Api#831]
Is there a way to find (from public TikTok data, any end point) the country that a user belongs to (as far as TikTok is concerned?).
And also his category (eg. Comedy, Technology, Nature, Travel, etc.)

Maybe it's not implemented here; I'm simply wondering if it's possible to get that data, and how. (Several TikTok services that list TikTok profiles also list the country, and even audience demographics, but I've no idea where they get that data. Eg. [TikTok's own platform](https://creatormarketplace.tiktok.com/ad#/market) is one such service, though it's not the only one.)

**Comment by davidteather** [comment]
Not possible, this only allows features possible on tiktok.com
