### ISSUE TITLE
custom_verify_fp automation

### ISSUE THREAD

**Issue by Popesites** [davidteather/TikTok-Api#837]
Is there a way to automatically get the custom_verify_fp? Having to open a google chrome browser to get a new token kinda defeats the purpose of this library.

**Comment by EllisMuch** [comment]
I've been looking into this too, will post when I have an answer

**Comment by EllisMuch** [comment]
No but you can message me on Discord. Ellisless on there

**Comment by Popesites** [comment]
@EllisMuch add treeleafz#8970

**Comment by brimonk** [comment]
Any updates on this?

**Comment by davidteather** [comment]
Use V6
