### ISSUE TITLE
[BUG] - V5.0.0 user_example.py raises TikTokCaptchaError when calling user.videos 

### ISSUE THREAD

**Issue by elfpvke** [davidteather/TikTok-Api#838]
Trying out the TikTokApi v5.0.0 user_example.py example on Windows 10 Python 3.9.7 , the call on line 8: 

`for video in user.videos():`

raises a `TikTokApi.exceptions.TikTokCaptchaError`: TikTok blocks this request displaying a Captcha

I tried the example both initializing TikTokApi passing a custom_verify_fp value, and initializing with no parameters with the same result  both times.  I also tried use_test_endpoints=True and got the same result.

**Comment by kevit-dhairya-bapodra** [comment]
I am also facing the same issue.

**Comment by Popesites** [comment]
I initially fixed this by using the `custom_verify_fp` option. It is still working for me. My problem right now, is how do you generate more `custom_verify_fp` tokens? TikTok is no longer sending a `s_v_web_id` cookie

**Comment by dejl** [comment]
Using custom_verify_fp  and it doesn't work for me

**Comment by ucmuller** [comment]
I have same problem

**Comment by EllisMuch** [comment]
Hi @impossibleno1 - try to find your cookies using f12:
https://developer.chrome.com/docs/devtools/storage/cookies/

**Comment by Popesites** [comment]
@impossibleno1 When you log in it will send you a captcha, and it will definitely generate the `s_v_web_id`. But either way it will not be useful, the token generated doesn't work with this API.

**Comment by remillou** [comment]
Anyone managed to make user.videos() work recently ?

**Comment by davidteather** [comment]
V6
