### ISSUE TITLE
Use msTokens for requests

### ISSUE THREAD

**Issue by Popesites** [davidteather/TikTok-Api#839]
It would seem that `msToken`'s are being used throughout TikTok as some sort of sub/replacement of `s_v_web_id`. Therefore, it would be nice to support using `msToken` to request certain data.

**Comment by hungnt61h** [comment]
Is there any way to get or generate msToken? I tried to call this api link ```https://www.tiktok.com/api/user/detail```, it could not return data without msToken param.
