### ISSUE TITLE
[BUG] - Trending() Not Returning Data

### ISSUE THREAD

**Issue by EllisMuch** [davidteather/TikTok-Api#845]
I hope I am not missing anything obvious - I have seen others raise the same issue.

I have been using the API extensively and have been through the documentation. 

Trending() is not longer fetching any videos; I believe since 26/02.

Please can someone try the example to confirm.
https://github.com/davidteather/TikTok-Api/blob/master/examples/trending_example.py

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - TikTokApi Version [e.g. 5.0.0] - if out of date upgrade before posting an issue

**Comment by ale3692** [comment]
I can confirm it's still not returning anything. I've been using both V5 and the last V4 and both are returning blank.

**Comment by etale-cohomology** [comment]
Not sure if this is what's going on, but they recently changed the `https://www.tiktok.com/api/recommend/item_list/?aid=1988&count=35` endpoint to require a **signed** URL, which [something like this produces](https://github.com/carcabot/tiktok-signature). Up to a few days ago you could use the signed URLs (and the `x-tt-params`) that [Carcabot](https://github.com/carcabot/)'s repo produced to access all sort of endpoints in the TikTok private API, but not anymore.

**Comment by Popesites** [comment]
@etale-cohomology i think the X-BOGUS is required now. I made same discovery as you for generateXBogus on the Carcabot repo, and noticed the `signer.js` file seems to add sign function somehow.

If you go to tiktok.com, check `window.byted_acrawler.frontierSign`, the new function comes from https://sf16-secsdk.ttwstatic.com/obj/rc-web-sdk-gcs/webmssdk/1.0.0.200/webmssdk.js

somehow we could probably take the code from here to add to Carcabot repo?

**Comment by etale-cohomology** [comment]
Not sure if it's only `X-Bogus`, or `msToken` as well, that's needed now.

Yes, `signer.js` has the `window.byted_acrawler.sign` function (just as the `xttparams.js` has `window.genXTTParams` function), and then those functions get loaded by Carcabot's `index.js`. I think the `window.byted_acrawler.sign` function is somehow encoded or "encrypted" in plain text, and then `signer.js` decodes/decrypts the JS and evaluates it. Or something.

I hadn't noticed this repo had `signer.js`. Thanks for that. Where is it, though? I also wonder where it came from. (Maybe it came from `webmssdk.js`.)

**Comment by Popesites** [comment]
@etale-cohomology well not exactly a `signer.js` file, but essentially does the same thing: https://github.com/davidteather/TikTok-Api/blob/master/TikTokApi/browser_utilities/get_acrawler.py

**Comment by EllisMuch** [comment]
@Popesites @etale-cohomology - Hi both,

Have either of you managed to get the Trending() function working following this?

**Comment by davidteather** [comment]
fixed v6
