### ISSUE TITLE
[BUG] - KeyError: "name='ttwid', domain=None, path=None"

### ISSUE THREAD

**Issue by rachmadrinaldie** [davidteather/TikTok-Api#849]
So I was trying to get user videos and I try to follow the example code :

```
from TikTokApi import TikTokApi

verify_fp = "verify_xxx"
# Notes : im using my own verify_fp

api = TikTokApi(custom_verify_fp=verify_fp)

user = api.user(username="therock")

for video in user.videos():
    print(video.id)
```

**Expected behavior**

List of user videos based on username I wrote.

**Error Trace (if any)**

```
Traceback (most recent call last):
  File "/home/rachmadrin/api-social-media/testing_tiktok.py", line 10, in <module>
    for video in user.videos():
  File "/home/rachmadrin/venv-kolabora/lib/python3.8/site-packages/TikTokApi/api/user.py", line 133, in videos
    self.__find_attributes()
  File "/home/rachmadrin/venv-kolabora/lib/python3.8/site-packages/TikTokApi/api/user.py", line 263, in __find_attributes
    for u in self.parent.search.users(self.username):
  File "/home/rachmadrin/venv-kolabora/lib/python3.8/site-packages/TikTokApi/api/search.py", line 85, in search_type
    ttwid = spawn.cookies["ttwid"]
  File "/home/rachmadrin/venv-kolabora/lib/python3.8/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/home/rachmadrin/venv-kolabora/lib/python3.8/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='ttwid', domain=None, path=None"
```

**Notes : it's still do the same error even if I didn't use custom_verify_fp anymore**

**Environment:**
 - OS: Ubuntu 20.04
 - TikTokApi Version 5.0.0

**Comment by 3dian** [comment]
I get this too

**Comment by maksam07** [comment]
I get this too

**Comment by bjtuweb-12281047** [comment]
I get this too, docker run

**Comment by Kreimen123** [comment]
I get this too

**Comment by rachmadrinaldie** [comment]
> 这个问题解决了么

until today these issues still happen, dude.

直到今天，这个问题仍然发生，伙计。

@mengguiyouziyi

**Comment by jp-wagner** [comment]
Same here. Going back to 4.1.0 for now.

**Comment by wrogers3** [comment]
> Same here. Going back to 4.1.0 for now.

do the older versions work?

**Comment by wrogers3** [comment]
i get the above terminal prompt too

**Comment by 419606974** [comment]
I get this too

**Comment by pashamaladec** [comment]
I too, version 5.1.1

**Comment by hmoazam** [comment]
> Same here. Going back to 4.1.0 for now.

Is there a link to the documentation for 4.1.0? I am getting started and facing the same issue, but also can't find the docs for v4

**Comment by nickkarp** [comment]
I get this too.

Windows 11
version 5.1.1

**Comment by miholeus** [comment]
+1, not working

**Comment by looCiprian** [comment]
Same here

**Comment by Monteleone** [comment]
Same here

**Comment by dylancaponi** [comment]
This suggestion solves the ttwid error but then there's a CaptchaException: 
https://github.com/davidteather/TikTok-Api/issues/890#issuecomment-1145724326

**Comment by Arax250190** [comment]
+1

**Comment by aladynjr** [comment]
same issue here

**Comment by realchandan** [comment]
I also faced same issues

**Comment by Tracer-Shield** [comment]
+1

**Comment by bilalahmedkhatri** [comment]
Is anyone got any solution ?

**Comment by Saditud** [comment]
Same here

**Comment by Debangsha1992** [comment]
same problem here

**Comment by jc-a3s** [comment]
Same for me. It seems that there is anti-bot mechanism which adds `_abck` and `bm_sz` cookies at the beginning. (https://security.stackexchange.com/questions/182895/anti-bot-javascript-library-identification). TikTok-Api uses requests lib to call "http://www.tiktok.com" to get `ttwid` cookie but anti-bot tool detects that it's not a human and returns `403` code without attaching `ttwid`. You can check it by returning status code just before this line: http://www.tiktok.com
I suppose real request from the browser (e.g. via selenium) for the first call would resolve the issue. I'm able to retrieve `ttwid` with Postman's call.

**Comment by helloeveryworlds** [comment]
+1

**Comment by fiott248** [comment]
+1

**Comment by oknehcnap** [comment]
So It doesn't work ?

**Comment by Kamushy** [comment]
broken for me also

**Comment by Nagapetyan** [comment]
+1

**Comment by terrok9** [comment]
Broken. I recommend using https://github.com/Russell-Newton/TikTokPy

**Comment by 444joseph444** [comment]
Good day, I want to get an agency

في الأربعاء، ١١ يناير ٢٠٢٣ ٢:٤٨ ص terrok9 ***@***.***> كتب:

**Comment by SyrupTheSrc** [comment]
> Broken. I recommend using https://github.com/Russell-Newton/TikTokPy

How do you plan on using this library at scale? It is very slow for me

**Comment by davidteather** [comment]
should be fixed in v6
