### ISSUE TITLE
Limited extracted hashtag videos

### ISSUE THREAD

**Issue by MohamedZribi** [davidteather/TikTok-Api#851]
Hi...so I'm trying to scrape video ids of a certain hashtag.....there are unlimited videos of the said hashtag on Tiktok but when using the API....after changing the count in Hashtag.py to say 10000 for example.....I only get slightly less than 1000 ids...is there some limit set by Tiktok or maybe a certain parameter I should change?

**Comment by benostarzec** [comment]
it has been my experience that count only really loosley works in the search methods. i'd just get the generator with more than u need and then use a for loop or something to iterate thru it however many times you want. I've also had it happen where certain searches yield one result that for some reason doesnt work w the api and then every other result after is messed up too becuase you cant really iterate past the messed up one. that could be why yours is returning so few results. for example, that has happened to me w the 12th or 13th video if u search videos w the keyword adhd. good luck

**Comment by wait3** [comment]
> it has been my experience that count only really loosley works in the search methods. i'd just get the generator with more than u need and then use a for loop or something to iterate thru it however many times you want. I've also had it happen where certain searches yield one result that for some reason doesnt work w the api and then every other result after is messed up too becuase you cant really iterate past the messed up one. that could be why yours is returning so few results. for example, that has happened to me w the 12th or 13th video if u search videos w the keyword adhd. good luck

Thanks for your reply....I already set the count to more than I need...still under the 1k mark and it varies for each keyword...btw tried the "adhd" keyword with my script....seems like I can get slightly under the 1k videos as well. 
But I need higher volumes so I'm still trying to come up with a solution.

**Comment by Popesites** [comment]
Are you using the cursor parameter?

**Comment by wait3** [comment]
> Are you using the cursor parameter?

It is set by default to match the offset, how should I set it?

**Comment by kornosk** [comment]
@MohamedZribi Have you solved the problem? I'm facing the video data collection through hashtags too.

**Comment by davidteather** [comment]
This is a TikTok web limit as far as I know

**Comment by binaryplatitude** [comment]
Any ideas on getting around this for grabbing 1000+ on a specific hashtag? Hacky solutions would be just fine.
