### ISSUE TITLE
Tik Tok displaying captcha, even after using proxy. (how to find verify_fp?)

### ISSUE THREAD

**Issue by wrogers3** [davidteather/TikTok-Api#864]
Despite the usage of proxies, there seems to still be the bug in regards to tiktok blocking the requests through captcha. Is there a way we could use a different verifyfp because I know that is the main problem. HOW TO FIND VERIFYFP that is usable?

You run the following:

**SET LOGGING LEVEL TO INFO BEFORE POSTING CODE OUTPUT**
```py
import logging
TikTokApi(logging_level=logging.INFO) # SETS LOGGING_LEVEL TO INFO
# Hopefully the info level will help you debug or at least someone else on the issue
```

```py
# Code Goes Here
```import logging
TikTokApi(logging_level=logging.INFO)
from TikTokApi import TikTokApi

verify_fp = "verify_xxx"
api = TikTokApi(custom_verify_fp=verify_fp)

tag = api.hashtag(name="fyp")

print(tag.info())
for video in tag.videos():
    print(video.id)



**Expected behavior**

283974239889324
209348230948398
293084230948234
.
.
.

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```Traceback (most recent call last):
  File "idget.py", line 9, in <module>
    for video in tag.videos():
  File "/home/beta/.local/lib/python3.8/site-packages/TikTokApi/api/hashtag.py", line 117, in videos
    res = self.parent.get_data(path, **kwargs)
  File "/home/beta/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 293, in get_data
    raise TikTokCaptchaError()
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha 
Tip: Consider using a proxy or a custom_verify_fp as method parameters


**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS x86_64
 - TikTokApi Version 5.0.0

**Additional context**

Add any other context about the problem here.

**Comment by 3dian** [comment]
same to me

**Comment by pablobots** [comment]
same to me

**Comment by leonardparisi** [comment]
https://www.youtube.com/watch?v=zwLmLfVI-VQ&t=117s

**Comment by leonardparisi** [comment]
Still having this issue...

**Comment by sheepcloud** [comment]
> how to find verify_fp?

- delete cookie 
- Login with your phone number.

**Comment by JavierEspinMegias** [comment]
Restarting router worked for me.

**Comment by flyck** [comment]
For me all that was needed was opening the page in a new browser and clicking around on the page to randomly trigger the captcha. No need to login or give a phone number!

**Comment by Enu0** [comment]
I got the verify_fp by finishing the captcha after deleting cookies and attempting to login with phone number, and then I put it in the 

```
api = TikTokApi(custom_verify_fp=verify_fp)
```

But it still asks for captcha.

**Comment by Alex-Laparra** [comment]
> I got the verify_fp by finishing the captcha after deleting cookies and attempting to login with phone number, and then I put it in the
> 
> ```
> api = TikTokApi(custom_verify_fp=verify_fp)
> ```
> 
> But it still asks for captcha.

Yeah it's pretty much the same for everyone. Let's hope David sees this and finds a fix!

**Comment by yokotoka** [comment]
Same trouble. Phone not helps

**Comment by davidteather** [comment]
Try v6 will require msToken
