### ISSUE TITLE
[BUG] - 'TikTokApi' object has no attribute 'by_username'

### ISSUE THREAD

**Issue by TiagoDS7** [davidteather/TikTok-Api#871]
**Describe the bug**

"'TikTokApi' object has no attribute 'by_username'" , I've tried everything to no avail. Any ideas?

**Comment by davidteather** [comment]
Check the readme to upgrading to V5, you're using V4 syntax

**Comment by andvsilva** [comment]
Hi, same issue here.  **Successfully installed TikTokApi-5.2.2 pyee-9.0.4**

`import nest_asyncio
nest_asyncio.apply()
from TikTokApi import TikTokApi
api = TikTokApi()
n_videos = 100
username = 'washingtonpost'
user_videos = api.byUsername(username, count=n_videos)`

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/andsilva/Desktop/scrapetiktok.ipynb Cell 2 in <cell line: 5>()
      [3](vscode-notebook-cell:/home/andsilva/Desktop/scrapetiktok.ipynb#W3sZmlsZQ%3D%3D?line=2) n_videos = 100
      [4](vscode-notebook-cell:/home/andsilva/Desktop/scrapetiktok.ipynb#W3sZmlsZQ%3D%3D?line=3) username = 'washingtonpost'
----> [5](vscode-notebook-cell:/home/andsilva/Desktop/scrapetiktok.ipynb#W3sZmlsZQ%3D%3D?line=4) user_videos = api.byUsername(username, count=n_videos)

**AttributeError: 'TikTokApi' object has no attribute 'byUsername'`**
