### ISSUE TITLE
[FEATURE_REQUEST] - Video license filter

### ISSUE THREAD

**Issue by mizhozan** [davidteather/TikTok-Api#873]
**Is your feature request related to a problem? Please describe.**
I have concern about downloaded videos from TikTok for non-commercial/non-profit use (fair use?) e.g. in research. Is it possible to filter videos based on their license like YouTube?

**Describe the solution you'd like**
Having a filter which only download specific category of videos regarding their license by the owner.

**Comment by davidteather** [comment]
I don't think you can filter by license or even set a license when uploading a TikTok video
