### ISSUE TITLE
[BUG] - Hashtag only pulls 30 results

### ISSUE THREAD

**Issue by Jordaan** [davidteather/TikTok-Api#874]
I've used the example hashtag code but it only pulls 30 videos as a result. Video count request does not seem possible. Can the output be expanded?

**Comment by sigterm9kill** [comment]
Try an async throttle... i.e., wait 500 ms inside your loop. This isn't a bug.

**Comment by sheepcloud** [comment]
30 responses are returned regardless of the countif value specified for the option.

**Comment by davidteather** [comment]
Might be fixed in v5.2.0

**Comment by kareemrasheed89** [comment]
> Might be fixed in v5.2.0

do you have this version now
