### ISSUE TITLE
RuntimeError: This event loop is already running[BUG] - Your Error Here

### ISSUE THREAD

**Issue by kareemrasheed89** [davidteather/TikTok-Api#879]
Fill Out the template :)

**I have installed all required library and still getting runtime error**

**from TikTokApi import TikTokApi
api = TikTokApi()
n_videos = 100
username = 'nastyblaq'
user_videos = api.byUsername(username, count=n_videos)**

Please add any relevant code that is giving you unexpected results.

Preferably the smallest amount of code to reproduce the issue.

**SET LOGGING LEVEL TO INFO BEFORE POSTING CODE OUTPUT**
```py
import logging
TikTokApi(logging_level=logging.INFO) # SETS LOGGING_LEVEL TO INFO
# Hopefully the info level will help you debug or at least someone else on the issue
```

```py
# Code Goes Here
```

**Expected behavior**

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-3-55c3fab06e06>](https://localhost:8080/#) in <module>()
      1 from TikTokApi import TikTokApi
----> 2 api = TikTokApi()
      3 n_videos = 100
      4 username = 'nastyblaq'
      5 user_videos = api.byUsername(username, count=n_videos)
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - TikTokApi Version [e.g. 5.0.0] - if out of date upgrade before posting an issue

**Additional context**

**Comment by davidteather** [comment]
V6 fully async
