### ISSUE TITLE
[BUG] - TikTok returning status_code 0 from trending.videos

### ISSUE THREAD

**Issue by Jordan-M** [davidteather/TikTok-Api#880]
**Describe the bug**

api.trending.videos is not returning any results. Stepping into the TikTok-Api code reveals that TikTok is responding with status_code 0 with no other objects in the response:
![image](https://user-images.githubusercontent.com/8267794/166878752-62bc1492-a0ea-4285-9e9e-6c84d5eb6031.png)

 Going to the url crafted in Trending.py returns the same status_code 0 response:
![image](https://user-images.githubusercontent.com/8267794/166878266-8ca2409d-71f9-4fdd-a653-017e19187286.png)

**The buggy code**
```
from TikTokApi import TikTokApi

with TikTokApi() as api:
    for trending_video in api.trending.videos(count=50):
        print(trending_video.author.username)

```

**Expected behavior**

Videos would be returned from the call

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version 5.1.1

**Comment by jacksonw765** [comment]
Seeing the same issue on Mac as well.

**Comment by Denon** [comment]
I have the same problem

**Comment by Hiroyuki1995** [comment]
same problem here

**Comment by alete89** [comment]
Same here, interesting enough, copying the URL that `requests.get` is using and just pasting it into the browser returns a valid payload with tiktok data. Not sure how the request is messing it up :/

**Comment by davidteather** [comment]
Should be fixed in V6
