### ISSUE TITLE
TikTokAPI has no attribute called get_instance()

### ISSUE THREAD

**Issue by Ifeanyi55** [davidteather/TikTok-Api#885]
**Describe the bug**

I tried to run `TikTokAPI.get_instance()`, and I got the error message below.

**The buggy code**

`api = TikTokApi.get_instance()`

```
AttributeError                            Traceback (most recent call last)
<ipython-input-2-e523dd49e8b2> in <module>
----> 1 api = TikTokApi.get_instance()
      2 print(api.by_trending(count=1))

AttributeError: type object 'TikTokApi' has no attribute 'get_instance'

```
Is there a dependency that I need to install?

**Comment by Alex-Laparra** [comment]
Read this:
https://github.com/davidteather/TikTok-Api#upgrading-from-v4-to-v5

**Comment by davidteather** [comment]
^
