### ISSUE TITLE
[FEATURE_REQUEST] - usage

### ISSUE THREAD

**Issue by A4pro** [davidteather/TikTok-Api#886]
in theory, based on this, you can create an account registrar with the ability to interact with live users?

**Comment by justt-jay** [comment]
Hey, this library us not for that. However there's a library that's close to what you're talking about.
 > [here](https://github.com/isaackogan/TikTokLive)

**Comment by A4pro** [comment]
how can i find it?

**Comment by justt-jay** [comment]
> how can i find it?

You can click "here", in the comment I've replied with

**Comment by A4pro** [comment]
sorry, thanks)
