### ISSUE TITLE
Api seems entirely dysfunctional 

### ISSUE THREAD

**Issue by Alex-Laparra** [davidteather/TikTok-Api#887]
Has anyone been able to do anything with the api recently? Anything I try to do raises errors.

**Comment by justt-jay** [comment]
**Please provide what you're experiencing issues with**, no one can help you by just saying *Anything I try to do raises errors", you can just join the discord server instead of making issues, without being specific.

**Comment by Alex-Laparra** [comment]
> **Please provide what you're experiencing issues with**, no one can help you by just saying "Anything I try to do raises errors", you can just join the discord server instead of making issues, without being specific.

I intentionally wasn't being specific because all the issues i'm having are those already posted in the section since a month now and more. I simply wanted to know if anybody had managed to make anything work with the api since I can't, and I seem to not be the only one. What's the discord?

**Comment by mizhozan** [comment]
I had similar problem by trying out different modes of installation, troubleshooting  etc. One main reason is pywright. It uses Ubuntu specific static libraries and it's basically a mess to handle and quite incompatible in many situations. The docker also has its own problem... Is there better alternative?



> > **Please provide what you're experiencing issues with**, no one can help you by just saying "Anything I try to do raises errors", you can just join the discord server instead of making issues, without being specific.
> 
> I intentionally wasn't being specific because all the issues i'm having are those already posted in the section since March. I simply wanted to know if anybody had managed to make anything work with the api since I can't, and it seems I'm not the only one in this situation. What's the discord?

**Comment by davidteather** [comment]
Fixed some things check out new version
