### ISSUE TITLE
[BUG] - cannot put anything after api.trending

### ISSUE THREAD

**Issue by yoyoweiii** [davidteather/TikTok-Api#888]
`api.trending` will return a line "bound method TikTokApi.trending of <TikTokApi.tiktok.TikTokApi object"

but when I tried to add attribute such as `api.trending()` or` api.trending(count=10)` or `api.trending.videos()`, it will report object has no attribute.

    OS: windows11
    TikTokApi Version 5.1.1

**Comment by DioCodes** [comment]
I have the same problem. Downloading videos by id is working fine, but I need random tranding videos..

MacOS/Python 10

**Comment by davidteather** [comment]
Try V6
