### ISSUE TITLE
[BUG] - cannot find user

### ISSUE THREAD

**Issue by Naiym223** [davidteather/TikTok-Api#889]
Getting " Please try again, that account does not exist, or something went wrong."

code:
    config = get_config()

    @nextcord.slash_command(name="user", description="Check TikTok stats of user")
    async def user(self, interaction, username: str):
        username = username.lower().replace("@", "")
        user = api.user(username=username).info_full()
(command code) and then 
            embedvar = nextcord.Embed(title="<:pinkerror101:944344224084672592> | Please try again, that account does not exist, or something went wrong.", color=0xf01c54)
            await interaction.send(embed=embedvar, delete_after=7.5)

for some reason its saying cannot find the user.

**Comment by davidteather** [comment]
Try V6
