### ISSUE TITLE
[INSTALLATION] - generator not generating for api.trending.videos()

### ISSUE THREAD

**Issue by BrianStinerGithub** [davidteather/TikTok-Api#895]
**Describe the error**

```
Following tutorial does not download video.
```

**The buggy code**

When using:
`with TikTokApi as api:`
It requests I provide an  `__enter__` and `__exit__` function.
switched to the below method using a variable.

```
def scrape_tiktoks():
    api = TikTokApi()
    print(api)
    something = api.trending.videos(count=10)
    print(something)
    for video in something:
        print(video)
        download(video.bytes, "test.mp4") #f"{TIKTOKPATH}/{video.id}.mp4")     
        print("Downloaded:", video.id)
```
the console shows:
```
Scraping Videos...
<TikTokApi.tiktok.TikTokApi object at 0x0000013891C04FD0>
<generator object Trending.videos at 0x00000138942FB430>
Scraped Videos!
./assets/videos/TikToks/funny-June_6_2022 
```
**Error Trace (if any)**

No error, just no downloaded videos.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version 5.1.1 - New version, new problems?

**Comment by davidteather** [comment]
+1 TikTok changed their trending route, still not been fixed

**Comment by barrysteyn** [comment]
I don't think this has been fixed yet?

**Comment by davidteather** [comment]
should be fixed V6
