### ISSUE TITLE
Most recent elements

### ISSUE THREAD

**Issue by Wathfea** [davidteather/TikTok-Api#896]
Hello everyone, I just wondering how we can get the most recent elements from the API?
For example If I search for a hashtag #cats and I would like to see the last 3 days?  Because currently I saw posts from 2020 and from 21 so it is totaly seems random to me. @davidteather Do you have any suggestion? Thank you so much!

**Comment by davidteather** [comment]
Unfortunately we're at the mercy of whatever TikTok sends back from their API on tiktok.com
