### ISSUE TITLE
[FEATURE_REQUEST] - Comments API

### ISSUE THREAD

**Issue by ctaity** [davidteather/TikTok-Api#898]
**Is your feature request related to a problem? Please describe.**
I i would like be able to get the video comments 

**Describe the solution you'd like**
Use the tiktok API for example this URL:
`# https://www.tiktok.com/api/comment/list/?aid=1988&app_language=ja-JP&app_name=tiktok_web&aweme_id=7107077283675950342&battery_info=1&browser_language=en-US&browser_name=Mozilla&browser_online=true&browser_platform=MacIntel&browser_version=5.0%20%28Macintosh%3B%20Intel%20Mac%20OS%20X%2010_15_7%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F102.0.5005.115%20Safari%2F537.36&channel=tiktok_web&cookie_enabled=true&count=20&current_region=JP&cursor=20&device_id=6935471859140888069&device_platform=web_pc&focus_state=false&fromWeb=1&from_page=video&history_len=5&is_fullscreen=false&is_page_visible=true&os=mac&priority_region=AR&referer=&region=AR&screen_height=1080&screen_width=3840&tz_name=America%2FBuenos_Aires&webcast_language=en&msToken=uqYO5WCXZP99sKQvmP6BFINfTzNrxsao-Avsw_Z0u4fhY5KRElh9lI7UhUWjTZA7CyfQC06VhT_NXsJFe758aHet44VSSlA06CNPnBHOK9POPcL7bL6SuJYI01-djNjPvlJSCyeC3kRZUAo=&X-Bogus=DFSzswjLymbANr8VSvA2Ur7TlqCT&_signature=_02B4Z6wo00001LPw1PAAAIDDJyaP.CipVhiz8NhAAE5k96
`

**Describe alternatives you've considered**
None

**Additional context**

**Comment by davidteather** [comment]
[V5.2.0] Just released provides this :)

Also pretty sure you provided some code in the Discord server 🙏
