### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by romilxz** [davidteather/TikTok-Api#90]
Sir I have created a register script for tiktok but I am having a problem with a header
X-GORGON
How is this generated .
Can you please help sir

**Comment by davidteather** [comment]
I have no clue how to generate the X-GORGON header. This Api is only meant for non logged in interactions with tiktok

**Comment by xgorgon** [comment]
@romilxz

I can sell script to generate xgorgon header contact me at xgorgon@protonmail.com or telegram https://t.me/adotdaniel
