### ISSUE TITLE
playwright._impl._api_types.Error: Browser closed.

### ISSUE THREAD

**Issue by niuhongbin1** [davidteather/TikTok-Api#903]
Fill Out the template :)

**Describe the bug**
I used this code a few days ago and it worked fine, but when I used it today, I got this exception.  Running this code, the browser opens a blank page and does not close it, but the code throws an exception 

**The buggy code**
def bom():
    __USER_DATE_DIR_PATH__ = f"C:\\Users\\{getuser()}\\AppData\Local\Google\Chrome\\User Data"
    # chrome.exe 的地址
    __EXECUTABLE_PATH__ = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
    playwright = sync_playwright().start()
    browser = playwright.chromium.launch_persistent_context(
        # 指定本机用户缓存地址
        user_data_dir=__USER_DATE_DIR_PATH__,
        # 指定本机google客户端exe的路径
        executable_path=__EXECUTABLE_PATH__,
        # 要想通过这个下载文件这个必然要开  默认是False
        accept_downloads=True,
        # 设置不是无头模式
        headless=False,
        bypass_csp=True,
        slow_mo=10,
        # 跳过检测
        args=['--disable-blink-features=AutomationControlled']
    )
    return browser.new_page()

error

  File "D:\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> C:\Program Files\Google\Chrome\Application\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --disable-blink-features=AutomationControlled --user-data-dir=C:\Users\twopic\AppData\Local\Google\Chrome\User Data --remote-debugging-pipe about:blank
<launched> pid=8932
[pid=8932][out] �������е�������Ự�д򿪡�
=========================== logs ===========================
<launching> C:\Program Files\Google\Chrome\Application\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,Mediading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptConentUpdater --allow-pre-commit-input --disable-hang-monitoHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater -ompt-on-repost --disable-renderer-backgrounding --disable-s-allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-proenable-automation --password-store=basic --use-mock-keychaitection --disable-popup-blocking --disable-prompt-on-repost --disable-reneatures=AutomationControlled --user-data-dir=C:\Users\twopiderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-rnkecording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox 
--disable-blink-features=AutomationControlled --user-data-dir=C:\Users\twopic\AppData\Local\Google\Chrome\User Data --remote-debugging-pipe about:blank
<launched> pid=8932
[pid=8932][out] �������е�������Ự�д򿪡�
============================================================

**Comment by davidteather** [comment]
try V6
