### ISSUE TITLE
[FEATURE_REQUEST] - Output as CSV

### ISSUE THREAD

**Issue by batmanscode** [davidteather/TikTok-Api#905]
**Is your feature request related to a problem? Please describe.**
No built in method to get data as a CSV

**Describe the solution you'd like**
A `to_csv` function similar to `as_dict`

**Describe alternatives you've considered**
Turn dict into a dataframe/csv using pandas

**Additional context**
Pandas dataframes are easier to do analysis on

**Comment by davidteather** [comment]
I think it's better to leave outside of this library as TikTok changes data response formats a lot and I can't update this library that frequently. The only reason the objects have `.as_dict` is because it's storing the data TikTok sent back from their API.

**Comment by batmanscode** [comment]
> I think it's better to leave outside of this library as TikTok changes data response formats a lot and I can't update this library that frequently. The only reason the objects have `.as_dict` is because it's storing the data TikTok sent back from their API.

Oh I didn't realise they change formats too. I thought the just the data changes but not the format. Thanks
