### ISSUE TITLE
[BUG] - AttributeError: parent doesn't exist on TikTokApi.api.Video

### ISSUE THREAD

**Issue by bumothekid** [davidteather/TikTok-Api#909]
**Bug description**

The code says that there's no parent/that this TikTok is not an duet or stitch of an TikTok and that's true. I just want to get the bytes from the video.

**The buggy code**

```py
    video = TikTokApi.video(url=url) # error here
    videoName = video.as_dict
    videoBytes = video.bytes()

    with open("tiktok/video.mp4", "wb") as output:
        output.write(videoBytes)
```

**Expected behavior**

I'm trying to get the Tiktok Video then getting the bytes and writing it to an mp4 file

<img width="783" alt="Screenshot 2022-07-05 at 5 22 47 PM" src="https://user-images.githubusercontent.com/40246197/177362886-8729f4c1-3a65-455a-98ea-ad4c9df3659e.png">

**Laptop:**
 - OS: MacOS Monterey 12.4
 - TikTokApi Version Up to date

**Comment by keko950** [comment]
It's not bugged, you have to first build the API object. Try:
```python3
    api = TikTokApi()
    video = api.video(url=url) # error here
    videoName = video.as_dict
    videoBytes = video.bytes()

    with open("tiktok/video.mp4", "wb") as output:
        output.write(videoBytes)

```

**Comment by farazBhatti** [comment]
@keko950  still its not working, I am getting the following error.
'AttributeError: 'TikTokApi' object has no attribute 'video' '

**Comment by davidteather** [comment]
I assume this is fixed in V6 lmk
