### ISSUE TITLE
[BUG] attributeError: 'TikTokApi' object has no attribute 'byHashtag'

### ISSUE THREAD

**Issue by cplasabas** [davidteather/TikTok-Api#91]
I'm getting this error:

Traceback (most recent call last):
  File "getTiktoksByHashtag.py", line 7, in <module>
    tiktoks = api.byHashtag('funny', count=count)
AttributeError: 'TikTokApi' object has no attribute 'byHashtag'

**Comment by cplasabas** [comment]
never mind on this, i've figured it out. i had to remove the package and install it again.

**Comment by botcoder-sys** [comment]
@cplasabas Can you tell me how you fixed it. I am getting same error.

**Comment by davidteather** [comment]
Use by_hashtag now

**Comment by WhiteWolf47** [comment]
@davidteather i am geting the error even while using by_hashtag

**Comment by Alfred2050** [comment]
> @davidteather i am geting the error even while using by_hashtag

@WhiteWolf47 did you manage to resolve it?
