### ISSUE TITLE
[BUG] - Supported python versions

### ISSUE THREAD

**Issue by SpangleLabs** [davidteather/TikTok-Api#910]
**Describe the bug**

Setup says python 3.7+ are supported, but as of 5.2.0, this package can only import in python 3.9 and above, due to type hints

**The buggy code**

Using python 3.8.10:
```py
from TikTokApi import TikTokApi
```

**Expected behavior**

Expected package to import, as pypi says it supports python 3.7 to 3.10

**Error Trace (if any)**

```
>>> from TikTokApi import TikTokApi 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Spangle\PycharmProjects\faexport_db\venvtikkytokky\lib\site-packages\TikTokApi\__init__.py", li
ne 6, in <module>
    from TikTokApi.tiktok import TikTokApi
  File "C:\Users\Spangle\PycharmProjects\faexport_db\venvtikkytokky\lib\site-packages\TikTokApi\tiktok.py", line
 14, in <module>
    from .api.sound import Sound
  File "C:\Users\Spangle\PycharmProjects\faexport_db\venvtikkytokky\lib\site-packages\TikTokApi\api\sound.py", l
ine 9, in <module>
    from ..helpers import extract_tag_contents
  File "C:\Users\Spangle\PycharmProjects\faexport_db\venvtikkytokky\lib\site-packages\TikTokApi\helpers.py", lin
e 2, in <module>
    from TikTokApi.browser_utilities.browser import browser
  File "C:\Users\Spangle\PycharmProjects\faexport_db\venvtikkytokky\lib\site-packages\TikTokApi\browser_utilitie
s\browser.py", line 22, in <module>
    class browser(BrowserInterface):
  File "C:\Users\Spangle\PycharmProjects\faexport_db\venvtikkytokky\lib\site-packages\TikTokApi\browser_utilitie
s\browser.py", line 24, in browser
    kwargs: dict[str, Any]
TypeError: 'type' object is not subscriptable
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TikTokApi Version: 5.2.0

**Additional context**

PEP-585 added the ability to use `dict` as a type hint, rather than using `typing.Dict`:
https://peps.python.org/pep-0585/

**Comment by mk-admin** [comment]
Same here
python 3.8.10
Ubuntu under WSL Windows 10
TikTokApi Version: 5.2.0

**Comment by Brannydonowt** [comment]
Same here
python 3.8.10
Windows, custom docker image

**Comment by SpangleLabs** [comment]
I can add btw, that 5.1.1 installs on python 3.8 without an issue for me.

```
pip install TikTokApi==5.1.1
```

(Except I then get a captcha error when fetching user videos list, but that's separate to this issue)

**Comment by max-08** [comment]
I got the same error


I used s.o. Linux Ubuntu 20.04.2 LTS
Pycharm with Python 3.8.



![Schermata da 2022-07-06 20-36-38](https://user-images.githubusercontent.com/52009177/177619958-7f400174-034d-4b73-9c3b-2f7d2e4f2b7c.png)

**Comment by Brannydonowt** [comment]
> I can add btw, that 5.1.1 installs on python 3.8 without an issue for me.
> 
> ```
> pip install TikTokApi==5.1.1
> ```
> 
> (Except I then get a captcha error when fetching user videos list, but that's separate to this issue)

Yep, installing `5.1.1` specifically has resolved the error for me.

Also managed to get this working correctly with Docker as a result.
