### ISSUE TITLE
Issue with Dockerfile failing step 5 on build.

### ISSUE THREAD

**Issue by Drumsk8** [davidteather/TikTok-Api#915]
Hello, 

I was attempting to build from the Dockerfile as listed in this repo. However, I found that it was failing on step 5. 

`STEP 5/5: RUN python -m playwright install
/bin/sh: 1: python: not found
Error: error building at STEP "RUN python -m playwright install": error while running runtime: exit status 127`

Since step 4 was installing pip3 sucessfully, I updated the local Dockerfile to explicitly call python3:

`RUN python3 -m playwright install`

The build now sucessfully completes. You may want to update the Dockerfile.

**Comment by slouchd** [comment]
#914 This should get fixed by this pull if reviewed

**Comment by Drumsk8** [comment]
Terribly sorry for not getting back to you on this. I can see the commit, so will close this with thanks. :)
