### ISSUE TITLE
[BUG] - TikTokApi.exceptions.CaptchaException when running example `search_example.py`

### ISSUE THREAD

**Issue by howjmay** [davidteather/TikTok-Api#919]
Fill Out the template :)

**Describe the bug**

when running example `search_example.py` the following error is returned

```
TikTokApi.exceptions.CaptchaException: 0 -> TikTok blocks this request displaying a Captcha 
Tip: Consider using a proxy or a custom_verify_fp as method parameters
```
**The buggy code**

```py
import logging
TikTokApi(logging_level=logging.INFO) # SETS LOGGING_LEVEL TO INFO
# Hopefully the info level will help you debug or at least someone else on the issue
```

```py
from TikTokApi import TikTokApi

with TikTokApi() as api:
    for user in api.search.users("therock"):
        print(user.username)

    for sound in api.search.sounds("funny"):
        print(sound.title)

    for hashtag in api.search.hashtags("funny"):
        print(hashtag.name)
```

**Expected behavior**

Example can successfully run

**Error Trace (if any)**

Put the error trace below if there's any error thrown.
```
# Error Trace Here
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - TikTokApi Version 5.x.x

**Additional context**

**Comment by Ohmnito** [comment]
same exact issue, actually none of the examples code work, each time it gives the same error:

```
TikTokApi.exceptions.CaptchaException: 0 -> TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verify_fp as method parameters
```
I tried putting a custom_verify_fp or even using a proxy, same issue, absolutely nothing works...

**Comment by siqyka** [comment]
same problem ，i using a proxy，but also fail

**Comment by jhough-veritone** [comment]
I've been running into the same issue, and I think it is related specifically to when you are searching a user instance. For example, when you use the API to search the data for a specific video the captcha exception does not come up. However, trying to search for information specific to a user will raise the Captcha exception whether or not you're using a proxy.

**Comment by sajjaddevel** [comment]
same here

**Comment by Rashad-j** [comment]
same here

**Comment by davidteather** [comment]
should be fixed in V6
