### ISSUE TITLE
 AttributeError: 'TikTokApi' object has no attribute '_browser'

### ISSUE THREAD

**Issue by sudo-paoo** [davidteather/TikTok-Api#925]
heroku logs showing  AttributeError: 'TikTokApi' object has no attribute '_browser'
i have playwright, puppeteer buildpack on heroku

2022-07-28T07:13:11.018984+00:00 app[bot.1]: Traceback (most recent call last):
2022-07-28T07:13:11.018985+00:00 app[bot.1]: File "/app/.heroku/python/lib/python3.10/site-packages/TikTokApi/tiktok.py", line 421, in __del__
2022-07-28T07:13:11.019011+00:00 app[bot.1]: File "/app/.heroku/python/lib/python3.10/site-packages/TikTokApi/tiktok.py", line 635, in shutdown
2022-07-28T07:13:11.019061+00:00 app[bot.1]: AttributeError: 'TikTokApi' object has no attribute '_browser'
2022-07-28T07:13:11.244049+00:00 heroku[bot.1]: State changed from up to crashed

**Comment by sudo-paoo** [comment]
figured out what is the cause but i didnt know why,, if i run this code from vs code it works
```
#working on vscode // doesnt work on heroku
from TikTokApi import TikTokApi

api = TikTokApi()
```
however the code above doesnt work on heroku so i did this instead of using a variable to call TikTokApi i just use TikTokApi
```
#works perfectly
TikTokApi.video(url=url).info()
```

**Comment by sudo-paoo** [comment]
mb it doesnt work on heroku,, other cmds are working however the TikTokApi have some error saying that

` 'TikTokApi' object has no attribute '_browser' `

**Comment by sudo-paoo** [comment]
> mb it doesnt work on heroku,, other cmds are working however the TikTokApi have some error saying that
> 
> `'TikTokApi' object has no attribute '_browser'`

is there a way to fix this?
![image](https://user-images.githubusercontent.com/104471005/181670271-0ff53249-b38c-4a90-9a56-fecdbb341750.png)

**Comment by mrksbgg** [comment]
Try ### python3 -m playwright install, maybe this gonna help you.

**Comment by sudo-paoo** [comment]
> Try **python3 -m playwright instal**l, maybe this gonna help you.

i already tried that :(

here are the things i've tried

- added  pytest-playwright on the requirements.txt
- run ` pip install pytest-playwright` in the vs code
- run ` pip install pytest-playwright` in the heroku console
- run `playwright install` in vs code
- run `playwright install` in heroku console

**Comment by lirankor** [comment]
Having the same issue :(

**Comment by robertmoga** [comment]
Add the following snippet 
`import nest_asyncio
nest_asyncio.apply()` 
prior to instantiate your API object. 

Reference is from here: https://stackoverflow.com/questions/46827007/runtimeerror-this-event-loop-is-already-running-in-python

**Comment by mike-fmh** [comment]
What fixed this for me was uninstalling and re-installing playwright with pip, and then running
>playwright install

again

**Comment by mrksbgg** [comment]
ok  Saturday, 03 December 2022, 11:09PM +03:00 from Michael Miele-Herndon  ***@***.*** :

**Comment by davidteather** [comment]
should be fixed in V6

**Comment by alfonsov2678** [comment]
having this issue now, have tried everything in this thread with no fix. Not sure if it is because I am running the code from within a docker container

**Comment by obscure723** [comment]
same issue

**Comment by reinvertise** [comment]
Same issue, im running from  a docker

**Comment by Gereks123** [comment]
I'm running this from modal.com cloud environment (basically Docker) and I get this error, although when running locally (Windows 11), version 6.5.2, everything works fine!

**Comment by studiokevinabanto** [comment]
same

**Comment by jennyallen** [comment]
I was able to get this working by adding `RUN playwright install-deps` to the docker file

**Comment by Egor-Pizyk** [comment]
I solved this problem in my Docker environment using the following commands
`
COPY pyproject.toml .
RUN uv sync
RUN uv run python -m playwright install-deps
RUN uv run python -m playwright install
`
