### ISSUE TITLE
[FEATURE_REQUEST] - Get TikTok ads

### ISSUE THREAD

**Issue by master0yoda** [davidteather/TikTok-Api#927]
Hi, so I go straight to the point. I reveresed tiktok about a month ago, I can get any data I want, I can do any actions I want. BUT I can't crawl tiktok ads... I tried everything, I redo all the requests, generated a new `device_id`, etc. none of the worked. I don't what am I missing
So can you support tiktok ads in this package or can someone tell math what im doing wrong?
thanks for your time :)

**Comment by davidteather** [comment]
You can't just look for TikTok ads on the webapp, check out `video.as_dict` I think there's fields abut ads
