### ISSUE TITLE
Evaluation failed: ReferenceError: webpackJsonp is not defined   

### ISSUE THREAD

**Issue by adebayor123** [davidteather/TikTok-Api#93]
Hello, thank you for your effort into the API.
Unfortunately, I'm coming across this error:

> Traceback (most recent call last):
>   File "D:/tiktok/tiktok/test.py", line 4, in <module>
>     trending = api.byHashtag('funny', 5)
>   File "D:\Anaconda\lib\site-packages\TikTokApi\tiktok.py", line 176, in byHashtag
>     id = self.getHashtagObject(hashtag)['challengeInfo']['challenge']['id']
>   File "D:\Anaconda\lib\site-packages\TikTokApi\tiktok.py", line 211, in getHashtagObject
>     b = browser(api_url)
>   File "D:\Anaconda\lib\site-packages\TikTokApi\browser.py", line 27, in __init__
>     asyncio.get_event_loop().run_until_complete(self.start())
>   File "D:\Anaconda\lib\asyncio\base_events.py", line 573, in run_until_complete
>     return future.result()
>   File "D:\Anaconda\lib\site-packages\TikTokApi\browser.py", line 55, in start
>     }''')
>   File "D:\Anaconda\lib\site-packages\pyppeteer\page.py", line 1184, in evaluate
>     return await frame.evaluate(pageFunction, *args, force_expr=force_expr)
>   File "D:\Anaconda\lib\site-packages\pyppeteer\frame_manager.py", line 309, in evaluate
>     pageFunction, *args, force_expr=force_expr)
>   File "D:\Anaconda\lib\site-packages\pyppeteer\execution_context.py", line 54, in evaluate
>     pageFunction, *args, force_expr=force_expr)
>   File "D:\Anaconda\lib\site-packages\pyppeteer\execution_context.py", line 113, in evaluateHandle
>     helper.getExceptionMessage(exceptionDetails)))
> pyppeteer.errors.ElementHandleError: Evaluation failed: ReferenceError: webpackJsonp is not defined
>     at __pyppeteer_evaluation_script__:3:11

I have never seen such error before, and I'm not very familiar with pypeteer as well...
Do you know how I could solve this issue? 

Thank you

**Comment by davidteather** [comment]
What code are you running?

**Comment by adebayor123** [comment]
Hi David,

I created a file called test.py and tried to run 
`trending = api.byHashtag('funny', 5)`
as mentioned in the example files in the repo.

**Comment by davidteather** [comment]
So your entire code was 
```
from TikTokApi import TikTokApi

api = TikTokApi()
trending = api.byHashtag('funny', 5)
```

**Comment by madnai** [comment]
I had the same problem. 
I resolved it by removing and installing it again. 
I run it using `sudo python3 test.py`

If you run it on linux make sure that you have chrome installed.

**Comment by ShovanSarker** [comment]
`/opt/api/venv-3.6.8/lib/python3.6/site-packages/TikTokApi/browser.py in __init__(self, url)
     25         }
     26 
---> 27         asyncio.get_event_loop().run_until_complete(self.start())
     28 
     29     async def start(self):

/usr/local/python-3.6.8/lib/python3.6/asyncio/base_events.py in run_until_complete(self, future)
    482             raise RuntimeError('Event loop stopped before Future completed.')
    483 
--> 484         return future.result()
    485 
    486     def stop(self):

/opt/api/venv-3.6.8/lib/python3.6/site-packages/TikTokApi/browser.py in start(self)
     28 
     29     async def start(self):
---> 30         self.browser = await pyppeteer.launch(self.options)
     31         self.page = await self.browser.newPage()
     32 

/opt/api/venv-3.6.8/lib/python3.6/site-packages/pyppeteer/launcher.py in launch(options, **kwargs)
    303         option with extreme caution.
    304     """
--> 305     return await Launcher(options, **kwargs).launch()
    306 
    307 

/opt/api/venv-3.6.8/lib/python3.6/site-packages/pyppeteer/launcher.py in launch(self)
    164 
    165         connectionDelay = self.slowMo
--> 166         self.browserWSEndpoint = get_ws_endpoint(self.url)
    167         logger.info(f'Browser listening on: {self.browserWSEndpoint}')
    168         self.connection = Connection(self.browserWSEndpoint, self._loop, connectionDelay, )

/opt/api/venv-3.6.8/lib/python3.6/site-packages/pyppeteer/launcher.py in get_ws_endpoint(url)
    223     while (True):
    224         if time.time() > timeout:
--> 225             raise BrowserError('Browser closed unexpectedly:\n')
    226         try:
    227             with urlopen(url) as f:

BrowserError: Browser closed unexpectedly:`
I'm getting this. any clue why?

**Comment by adebayor123** [comment]
@davidteather Yes, it was basically following your example codes.
@madnai , I did reinstall both pyppeteer and TikTokApi two times yesterday, but it didn't seem to help for me.

**Comment by davidteather** [comment]
Did you run pyppeteer-install and try to run as administrator?

**Comment by davidteather** [comment]
When you run "chromedriver" in the command line is the command registered?

If not you might have to install chromedriver and add it to your path you can download it [here](https://sites.google.com/a/chromium.org/chromedriver/)

**Comment by adebayor123** [comment]
@davidteather , it works like a charm now. 
I don't know what solved it, but it is working without any issues. Thanks for your help!
