### ISSUE TITLE
Working with thread class - getting: There is no current event loop in thread

### ISSUE THREAD

**Issue by lirankor** [davidteather/TikTok-Api#940]
Hello, 

This is my class: 

```
import threading
import time
from TikTokApi import TikTokApi

class getTagMeta:
    def __init__(self, tag, proxy, list):
        self.tag = tag
        self.proxy = proxy
        self.list = list
        instThread = threading.Thread(target=self.getTagVideos)
        instThread.start()

    def getTagVideos(self):
        with TikTokApi(proxy=self.proxy,request_delay=1) as api:
            tagResults = api.hashtag(name=self.tag)

            videos = tagResults.videos(count=200)

            self.videos_list = []
            for video in videos: 
                print('Tag: #' + self.tag + ' Video ID '+video.id+' Parsed and added to list')
                self.videos_list.append(video.as_dict)

            self.list[self.tag] = self.videos_list
```

For some reason I get this error:

`
File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "d:\localhost\PythonTikTokAPI\getTag.py", line 11, in getTagVideos
    with TikTokApi(proxy=self.proxy,request_delay=1) as api:
  File "C:\Python38\lib\site-packages\TikTokApi\tiktok.py", line 159, in __init__
    self._initialize(
  File "C:\Python38\lib\site-packages\TikTokApi\tiktok.py", line 205, in _initialize
    self._browser = asyncio.get_event_loop().run_until_complete(
  File "C:\Python38\lib\asyncio\events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1'.
`

When calling getTagVideos directly it runs great when using a thread is when I get this error
BTW I'm also new to Python :)

**Comment by TTImmortal** [comment]
i have the same problem. I thing it because "asyncio.get_event_loop()",you can use "loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)", it works to me.

**Comment by lirankor** [comment]
Thank you @TTImmortal This helped me a lot!

The code is now running, mostly, there are still some issues:

```
class getTagMeta:
    def __init__(self, tag, proxy, list, jobs):
        self.tag = tag
        self.proxy = proxy
        self.list = list
        self.jobs = jobs
        self.loop = asyncio.new_event_loop()
        instThread = threading.Thread(target=self.getTagVideos)
        instThread.start()

    def getTagVideos(self):
        with TikTokApi(proxy=self.proxy,request_delay=3, asyncio=asyncio.set_event_loop(self.loop)) as api:
        
            tagResults = api.hashtag(name=self.tag)

            videos = tagResults.videos(count=20000)

            self.videos_list = []

            try:
                for video in videos: 
                    print('Tag: #' + self.tag + ' Video ID '+video.id+' Parsed and added to list')
                    self.videos_list.append(video.as_dict)
            except Exception as e:
                print(f'Some error accord for Tag {self.tag}. Error: {e}')

            self.list[self.tag] = self.videos_list

            self.jobs.remove(self.tag)
```

There's still one exception related to the asyncio event loop and other errors related to '_browser' attribute. again running one tag without opening threads still works well

Here are the errors:
`
Some error accord for Tag amazonmusthaves. Error: 'TikTokApi' object has no attribute '_browser'
Some error accord for Tag mademebuy. Error: 'TikTokApi' object has no attribute '_browser'
Some error accord for Tag tiktokmademebuythis. Error: 'TikTokApi' object has no attribute '_browser'
Some error accord for Tag TikTokMadeMeBuyIt. Error: 'TikTokApi' object has no attribute '_browser'
Some error accord for Tag aliexpresscompras. Error: The future belongs to a different loop than the one specified as the loop argument
`

**Comment by TTImmortal** [comment]
you can go through this issue:
https://github.com/davidteather/TikTok-Api/issues/925

and maybe you can help me with my issue bro, the new one?

**Comment by davidteather** [comment]
V6 fully aysync

**Comment by ThitipongPurinsjuwan** [comment]
i use version TikTokApi=6.2.0, But still get same problem  'TikTokApi' object has no attribute 'browser'

**Comment by zakrian07** [comment]
When ever get these issue
Plz set your script on retry
I have 3 retries when it failed on 3rd retry it get success
