### ISSUE TITLE
create a live broadcast room

### ISSUE THREAD

**Issue by MrsZ** [davidteather/TikTok-Api#943]
Hello, 

how should I create a live broadcast room after the user login, and then start the broadcast?

**Comment by Joystickplays** [comment]
You can't. This API has no functionality that involves anything that needs authentication.
> This api is designed to retrieve data TikTok. It can not be used post or upload content to TikTok on the behalf of a user. It has no support any user-authenticated routes, if you can't access it while being logged out on their website you can't access it here.
