### ISSUE TITLE
[BUG] - TikTok blocks this request displaying a Captcha 

### ISSUE THREAD

**Issue by blithum** [davidteather/TikTok-Api#946]
I'm trying to get the video urls from an account and I keep running into this error, I've included my cookies with the ms token and have read through others facing the same issue but none of the solutions seem to work. Any help would be much appreciated

This is the code I've got atm:

```py
from TikTokApi import TikTokApi

with TikTokApi() as api:
        ms_token = 'mUAXXtTLDEriJ7YzOHczfy_ClOU_ypBNadE2lUMPfA61eJeG6546cfQ5xqlp8spFSJLA59CGK3s0xPwG4S2aT2sVhKZOz7FWUV475oEdG4tH4xwX'
        api = TikTokApi(custom_verify_fp=ms_token, use_api_endpoints=True)
        user = api.user(username="nottooshabbycakes")
        for video in user.videos():
            print(video.id)
            for u_vid in video.author.videos():
                print(u_vid.id)
```

Is it the case of an incorrect cookie?

 - OS: Mac
 - TikTokApi Version 5.2.2

**Comment by PolcovnicGauss** [comment]
see my telegram bot for tiktok capthca solve https://t.me/cap_watch_dog_bot

**Comment by davidteather** [comment]
Should be fixed in V6 I think? Use msToken
