### ISSUE TITLE
pyppeteer.errors.BrowserError: Browser closed unexpectedly

### ISSUE THREAD

**Issue by NeelDroid** [davidteather/TikTok-Api#95]
System is Ubuntu 16.04 LTS
I am using a virtualenv which uses python3.7.
`>>> api.byHashtag('cat', count=30)`

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/tiktok-search/tkenv/lib/python3.7/site-packages/TikTokApi/tiktok.py", line 176, in byHashtag
    id = self.getHashtagObject(hashtag)['challengeInfo']['challenge']['id']
  File "/home/ubuntu/tiktok-search/tkenv/lib/python3.7/site-packages/TikTokApi/tiktok.py", line 211, in getHashtagObject
    b = browser(api_url)
  File "/home/ubuntu/tiktok-search/tkenv/lib/python3.7/site-packages/TikTokApi/browser.py", line 27, in __init__
    asyncio.get_event_loop().run_until_complete(self.start())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/ubuntu/tiktok-search/tkenv/lib/python3.7/site-packages/TikTokApi/browser.py", line 30, in start
    self.browser = await pyppeteer.launch(self.options)
  File "/home/ubuntu/tiktok-search/tkenv/lib/python3.7/site-packages/pyppeteer/launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "/home/ubuntu/tiktok-search/tkenv/lib/python3.7/site-packages/pyppeteer/launcher.py", line 166, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/home/ubuntu/tiktok-search/tkenv/lib/python3.7/site-packages/pyppeteer/launcher.py", line 225, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:
`

I am unable to see what's wrong. I was searching around. but did not get anything.

**Comment by NeelDroid** [comment]
Ok I tried python3.6 as well. same issue. But surprisingly, it's working on windows anaconda with python3.6

**Comment by davidteather** [comment]
Is your chrome driver in your path? Is the command “chromedriver” registered?

**Comment by NeelDroid** [comment]
Ok I had to manually install it over apt.
`sudo apt-get install chromium-chromedriver`

It's fetching JSON now. Thank you a lot. This was very important for me.

So, it means after installing the API & running `pyppeteer-install` on a virtualenv one needs to install the `chromedriver` seperately or I think running the `pyppeteer-install` globally should work.

**Comment by davidteather** [comment]
Glad you figured it out. I’ll add that in the next update’s documentation. It’s already on the nightly branch’s documentation. 

Thanks!

**Comment by thanhnguyen1121** [comment]
I encountered your same problem. I also installed "sudo apt-get install chromium-chromedriver". But it does not work. Please help me!

**Comment by davidteather** [comment]
What does it say when you run the command chromedriver ?

**Comment by thanhnguyen1121** [comment]
@davidteather haizzzz... thanks your question. It reminds me that I have not installed "sudo apt install ./google-chrome-stable_current_amd64.deb"! thank you very much.

**Comment by mtdunphy-umd** [comment]
Got it to work on my Mac no problem, but has anyone been able to get it to work in a Jupyter notebook? Still getting the "Browser closed unexpectedly" even after adding "!pyppeteer-install" and installing chromedriver with "!pip install chromedriver_installer". Am I just missing something basic here?

**Comment by crazygmr101** [comment]
I don't see it ever working without something similar to #198, due to the fact Jupyter makes an event loop to run things in. Related to #115

**Comment by michellebao** [comment]
Advice for trying to get it to work on Jupyter? I'm working in Colab but also running into the "browser closed unexpectedly error." I tried installing Chromedriver like this: `!wget https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip -O /tmp/chromedriver.zip && unzip /tmp/chromedriver.zip -d /opt && sudo chmod 755 /opt/chromedriver && sudo ln -fs /opt/chromedriver /usr/bin/chromedriver && sudo ln -fs /opt/chromedriver /usr/local/bin/chromedriver` and like this: `!pip install chromedriver_install`  but am getting the error for both ways. Also, `!pip install chromedriver_installer` gave this error:   ERROR: Failed building wheel for chromedriver-installer. I am also doing the `import nest_asyncio
nest_asyncio.apply()` workaround.

I don't think I'm installing chromedriver correctly, advice appreciated!

**Comment by AlexVerrico** [comment]
Just thought I would post this here in case it helps anyone else, I had to run the command ```sudo apt install chromium-driver``` to get this to work (Debian 10, Python 3.7)
Cheers,
Alex.

**Comment by vikasnavgire** [comment]
Run 
sudo apt-get install gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

It worked for me.

**Comment by thomasrice** [comment]
> Run
> sudo apt-get install gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
> 
> It worked for me.

Thanks, that worked for me too.
