### ISSUE TITLE
[BUG / FEATURE?] Getting exact playCount values for a video?

### ISSUE THREAD

**Issue by tyler-england** [davidteather/TikTok-Api#950]
Both `video.info()` and `video.info_full()` return playCount values, but those values start to be rounded at a certain threshold. 

For example, I tried looking at views for [this video](http://www.tiktok.com/@theresa.leung/video/7117663869073591598). TikTokApi returns 4,300,000 but [livecounts.io](https://livecounts.io/tiktok-live-view-counter) returns 4,291,312.

I will note that the exact playCount is returned as long as it's low enough, but I'm not sure what the threshold is. I'm also not sure whether the same problem applies to diggCount and commentCount.

**Comment by davidteather** [comment]
TikTok's API response is unfortunantely rounded
