### ISSUE TITLE
[BUG] - Video download not working

### ISSUE THREAD

**Issue by bruttoapp** [davidteather/TikTok-Api#952]
from TikTokApi import TikTokApi

    verify_fp="my_verify"

    with TikTokApi(custom_verify_fp=verify_fp) as api:
    video = api.video(id="7041997751718137094")

    # Bytes of the TikTok video
    video_data = video.bytes()

    with open("out.mp4", "wb") as out_file:
        out_file.write(video_data)

This code is not working correctly
Throws the following error:

 #### raise TikTokException(statusCode, r, TikTokApi.exceptions.TikTokException: 10204 -> TikTok sent an unknown StatusCode of 10204

How to be in this situation?

**Comment by vnpnh** [comment]
10204 code status means videos not found. Probably the video is deleted. Try using another available video.
