### ISSUE TITLE
[FEATURE_REQUEST] - Can you please tell me if there is a signature server?

### ISSUE THREAD

**Issue by prairieson** [davidteather/TikTok-Api#957]
Interested in how you sign API requests so that they do not get banned? Is there a mechanism like in this repository https://github.com/merlinssh/TikTok-Library? I will be grateful for the answer!

**Comment by Wolfhound905** [comment]
There is another library I have seen that can generate singed links. https://github.com/carcabot/tiktok-signature

**Comment by davidteather** [comment]
This code leverages same as carcabot/tiktok-signature
