### ISSUE TITLE
[BUG] - Script not ending when using TikTokApi

### ISSUE THREAD

**Issue by eric-hochberger** [davidteather/TikTok-Api#958]
**Describe the bug**

When pulling data using the hashtag method, data prints out as expected, but then the script does not end and I have to use CTRL+C to stop it. 

**The buggy code**

Please add any relevant code that is giving you unexpected results.

Preferably the smallest amount of code to reproduce the issue.

```py
from TikTokApi import TikTokApi
api = TikTokApi(custom_verifyFp = '')
id_list = []
for video in api.hashtag('fyp').videos():
    print(video.id)
```

**Expected behavior**

After IDs are printed I would expect the script to end

**Desktop (please complete the following information):**
 - OS: [macOS Big Sur 11.2.3]
 - TikTokApi Version [5.2.2]

**Comment by davidteather** [comment]
Should be fixed in V6
