### ISSUE TITLE
[Question] yt-dlp code reuse

### ISSUE THREAD

**Issue by upintheairsheep** [davidteather/TikTok-Api#959]
Hello, can we (the yt-dlp programmers) reuse your code in yt=dlp? The program is licenced unter The Unlicence and requires all reused code either to have the unlicence or get premission from the creator to copy code and unlicence it. The licence basically is the public domain

**Comment by davidteather** [comment]
Yes feel free! Pretty sure with MIT license you can relicense it under a larger project, but thank you for asking
