### ISSUE TITLE
How to implement this API

### ISSUE THREAD

**Issue by Mokin711** [davidteather/TikTok-Api#96]
This is def something wonderful and I would love to try it out. I am a front-end developer for iOS apps and still learning a lot of new things so I was a bit confused about how I could implement this API into iOS or android (i use flutter for android). Is it possible to walk through the general ideas? Thx!

**Comment by davidteather** [comment]
If flutter has the ability to use puppeteer and puppeteer extra stealth you should be able to generate the signatures. 

The other option is to have some rest api in python using this code and make calls to that server from the flutter app

**Comment by davidteather** [comment]
If you’re looking for a more simplistic api just to generate the signature I recommend looking at the TikTokApi/browser.py of this module or check out what the file was based on at carcabot/tiktok-signature
