### ISSUE TITLE
[BUG] - AttributeError: 'browser' object has no attribute 'signature'

### ISSUE THREAD

**Issue by fahad3007** [davidteather/TikTok-Api#969]
I am trying to use TiktokAPI to extract trending stuffs of tiktok but hitting into 

AttributeError: 'browser' object has no attribute 'signature'

----------------------installation-----------------------------
!pip install TikTokApi-Pyppeteer

----------------------python code----------------------------
from TikTokApi import TikTokApi
api = TikTokApi()

results = 10

trending = api.trending(count=results)

for tiktok in trending:
    # Prints the id of the tiktok
    print(tiktok['id'])

print(len(trending))

------------------------------------------------------------

Error:

AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 6>()
      2 api = TikTokApi()
      4 results = 10
----> 6 trending = api.trending(count=results)
      8 for tiktok in trending:
      9     # Prints the id of the tiktok
     10     print(tiktok['id'])

File ~/opt/anaconda3/lib/python3.9/site-packages/TikTokApi/tiktok.py:222, in TikTokApi.trending(self, count, minCursor, maxCursor, **kwargs)
    218 api_url = "{}api/item_list/?{}&{}".format(
    219     BASE_URL, self.__add_new_params__(), urlencode(query)
    220 )
    221 b = browser(api_url, **kwargs)
--> 222 res = self.getData(b, **kwargs)
    224 for t in res.get("items", []):
    225     response.append(t)

File ~/opt/anaconda3/lib/python3.9/site-packages/TikTokApi/tiktok.py:107, in TikTokApi.getData(self, b, **kwargs)
    105 else:
    106     verify_fp, did, signature, userAgent, referrer = self.external_signer(kwargs['url'], custom_did=kwargs.get('custom_did', None))
--> 107 query = {"verifyFp": b.verifyFp, "did": b.did, "_signature": b.signature}
    108 url = "{}&{}".format(b.url, urlencode(query))
    109 r = requests.get(
    110     url,
    111     headers={
   (...)
    126     proxies=self.__format_proxy(proxy),
    127 )

AttributeError: 'browser' object has no attribute 'signature'

**Comment by Joystickplays** [comment]
https://github.com/davidteather/TikTok-Api#common-issues

**Comment by davidteather** [comment]
Changed it on V6
