### ISSUE TITLE
[BUG] - playwright._impl._api_types.Error: Target closed

### ISSUE THREAD

**Issue by Kentarre** [davidteather/TikTok-Api#970]
I’m not quite shure that this is a bug, but recently I’ve started to get this kind of error while parsing a video.

> playwright._impl._api_types.Error: Target closed

Any ideas what might be the cause? 

Latest logs below:

>Nov 06 15:52:58 :   File "/root/vernam/./tt_api.py", line 9, in get_video
Nov 06 15:52:58 :     with TikTokApi(asyncio=asyncio.set_event_loop(self.loop)) as api:
Nov 06 15:52:58 :   File "/root/vernam/vernamenv/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 159, in __ini>
Nov 06 15:52:58 :     self._initialize(
Nov 06 15:52:58 :   File "/root/vernam/vernamenv/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 205, in _init>
Nov 06 15:52:58 :     self._browser = asyncio.get_event_loop().run_until_complete(
Nov 06 15:52:58 :   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
Nov 06 15:52:58 :     return future.result()
Nov 06 15:52:58 :   File "/root/vernam/vernamenv/lib/python3.8/site-packages/TikTokApi/browser_utilities/browser.py",>
Nov 06 15:52:58 :     page = await context.new_page()
Nov 06 15:52:58 :   File "/root/vernam/vernamenv/lib/python3.8/site-packages/playwright/async_api/_generated.py", lin>
Nov 06 15:52:58 :     return mapping.from_impl(await self._impl_obj.new_page())
Nov 06 15:52:58 :   File "/root/vernam/vernamenv/lib/python3.8/site-packages/playwright/_impl/_browser_context.py", l>
Nov 06 15:52:58 :     return from_channel(await self._channel.send("newPage"))
Nov 06 15:52:58 :   File "/root/vernam/vernamenv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 4>
Nov 06 15:52:58 :     return await self._connection.wrap_api_call(
Nov 06 15:52:58 :   File "/root/vernam/vernamenv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 3>
Nov 06 15:52:58 :     return await cb()
Nov 06 15:52:58 :   File "/root/vernam/vernamenv/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 7>
Nov 06 15:52:58 :     result = next(iter(done)).result()
Nov 06 15:52:58 : playwright._impl._api_types.Error: Target closed

**Comment by tahmad08** [comment]
Any updates?

**Comment by slimshreydy** [comment]
Still getting this too! Was trying to download a video.

**Comment by davidteather** [comment]
THink this should be fixed on V6
