### ISSUE TITLE
comments stopped working -

### ISSUE THREAD

**Issue by yaonur** [davidteather/TikTok-Api#972]
video.py 152
        spawn = requests.head(
            "https://www.tiktok.com",
            proxies=Video.parent._format_proxy(processed.proxy),
            **Video.parent._requests_extra_kwargs,
        )
now returning 403 forbidden

**Comment by yaonur** [comment]
def comments(self, count=20, offset=0, **kwargs) -> Iterator[Comment]:
        """
        Returns Comments from the video

        - Parameters:
            - count (int): The amount of videos you want returned.
            - offset (int): The offset you want to check comments of
        """

        processed = Video.parent._process_kwargs(kwargs)
        kwargs["custom_device_id"] = processed.device_id
        cursor = offset

        while cursor - offset <= count:
            query = {
                "aweme_id": self.id,
                "cursor": cursor,
                "app_language": Video.parent._language,
                "count": 30,
            }
            path = "api/comment/list/?{}&{}".format(
                Video.parent._add_url_params(), urlencode(query)
            )


            api_response = self.parent.get_data_no_sig(path, subdomain="us", **kwargs)


            for comment_data in api_response.get("comments", []):
                yield self.parent.comment(data=comment_data)

            if api_response.get("has_more", 0) == 0:
                Video.parent.logger.info(
                    "TikTok is not sending comments beyond this point."
                )
                return

            cursor = int(api_response.get("cursor", cursor))

get_data_no_sig() is simply working a simple solution for now

**Comment by Zoher15** [comment]
@yaonur  do you mind making a pull request so that it falls on @davidteather  and co's radar?

**Comment by chris0piper** [comment]
> simple change in comments() function get_data_no_sign() is working fine when used here def comments(self, count=20, offset=0, **kwargs) -> Iterator[Comment]:
> 
> ```
>     processed = Video.parent._process_kwargs(kwargs)
>     kwargs["custom_device_id"] = processed.device_id
>     cursor = offset
> 
>     while cursor - offset <= count:
>         query = {
>             "aweme_id": self.id,
>             "cursor": cursor,
>             "app_language": Video.parent._language,
>             "count": 30,
>         }
>         path = "api/comment/list/?{}&{}".format(
>             Video.parent._add_url_params(), urlencode(query)
>         )
> 
> 
>         api_response = self.parent.get_data_no_sig(path, subdomain="us", **kwargs)
> 
> 
>         for comment_data in api_response.get("comments", []):
>             yield self.parent.comment(data=comment_data)
> 
>         if api_response.get("has_more", 0) == 0:
>             Video.parent.logger.info(
>                 "TikTok is not sending comments beyond this point."
>             )
>             return
> 
>         cursor = int(api_response.get("cursor", cursor))
> ```

This still working for you?

**Comment by glossyweb** [comment]
get_data_no_sig or get_data_no_sign ?

**Comment by yaonur** [comment]
> @yaonur do you mind making a pull request so that it falls on @davidteather and co's radar?

that shouldnt be the final solution on this.Anyway it doesnt works any more for now Tiktok throwing captcha on comments page now

**Comment by yaonur** [comment]
> get_data_no_sig or get_data_no_sign ? 
no_sig  [TikTokApi.tiktok.py [line:384]](https://github.com/davidteather/TikTok-Api/blob/c104a6633bcec1e731f580cfccc73ff55c25eaf7/TikTokApi/tiktok.py#L384)

**Comment by yaonur** [comment]
> > simple change in comments() function get_data_no_sign() is working fine when used here def comments(self, count=20, offset=0, **kwargs) -> Iterator[Comment]:
> > ```
> >     processed = Video.parent._process_kwargs(kwargs)
> >     kwargs["custom_device_id"] = processed.device_id
> >     cursor = offset
> > 
> >     while cursor - offset <= count:
> >         query = {
> >             "aweme_id": self.id,
> >             "cursor": cursor,
> >             "app_language": Video.parent._language,
> >             "count": 30,
> >         }
> >         path = "api/comment/list/?{}&{}".format(
> >             Video.parent._add_url_params(), urlencode(query)
> >         )
> > 
> > 
> >         api_response = self.parent.get_data_no_sig(path, subdomain="us", **kwargs)
> > 
> > 
> >         for comment_data in api_response.get("comments", []):
> >             yield self.parent.comment(data=comment_data)
> > 
> >         if api_response.get("has_more", 0) == 0:
> >             Video.parent.logger.info(
> >                 "TikTok is not sending comments beyond this point."
> >             )
> >             return
> > 
> >         cursor = int(api_response.get("cursor", cursor))
> > ```
> 
> This still working for you?

Nope theres a new captcha problem now

**Comment by davidteather** [comment]
Should be fixed in V6 I think?
