### ISSUE TITLE
[BUG] - Getting videos by Hashtag stopped working

### ISSUE THREAD

**Issue by lirankor** [davidteather/TikTok-Api#976]
Getting an exception:

`Tag #viral, Error: Expecting value: line 1 column 1 (char 0)`

It fails at this code:

```
with TikTokApi() as api:
    tag = api.hashtag(name="viral")

    print(tag.info())

    ->for video in tag.videos():
        print(video.id)
```
the for loop fires the exception and return 0 videos

This is the log output
```
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): m.tiktok.com:443
urllib3.connectionpool - DEBUG - https://m.tiktok.com:443 "GET /api/challenge/detail" 200 308
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): us.tiktok.com:443
urllib3.connectionpool - DEBUG - https://us.tiktok.com:443 "GET /api/challenge/item_list" 200 0
batch - ERROR - Tag #viral, Error: Expecting value: line 1 column 1 (char 0)
```

It was working perfectly on production, code above is a simplified example of my code, the issue happens with or without a proxy
It was working up to the Nov 15th

**Comment by mandys** [comment]
+1

**Comment by DarinKumarnsit** [comment]
same here

**Comment by mandys** [comment]
On first looks, the query

            query = {
                "aid": 1988,
                "count": page_size,
                "challengeID": self.id,
                "cursor": cursor,
            }

Now needs to contain all the params that tiktok is using.

https://www.tiktok.com/api/challenge/item_list/?aid=1988&app_language=en&app_name=tiktok_web&battery_info=0.92&browser_language=en-GB&browser_name=Mozilla&browser_online=true&browser_platform=MacIntel&browser_version=5.0%20%28Macintosh%3B%20Intel%20Mac%20OS%20X%2010_13_6%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F106.0.0.0%20Safari%2F537.36&challengeID=<channelId>&channel=tiktok_web&cookie_enabled=true&count=30&cursor=0&device_id=<device_id>&device_platform=web_pc&focus_state=true&from_page=hashtag&history_len=3&is_fullscreen=false&is_page_visible=true&language=en&os=mac&priority_region=US&referer=&region=US&screen_height=1080&screen_width=1920&tz_name=US%2FCenral&webcast_language=en&msToken=<token>&X-Bogus=DFSzswVO0OzANagAS8kYkAPtYMEz&_signature=<sig>

If you remove even one of the params also, it will stop working.

**Comment by lirankor** [comment]
@mandys thank you, you are correct. In this case I've omitted the GET variables to make my post cleaner, I the original log output all the variables are there.

**Comment by Jmallone** [comment]
The pagination seems to have changed too

**Comment by azickri** [comment]
@mandys, i was try hit with full request params and response is blank.. how you solve this issue?

**Comment by Jmallone** [comment]
@azickri There is another URL, see in https://github.com/dfreelon/pyktok/issues/6

**Comment by mesaleh** [comment]
This works

`def test_search(keyword, offset=0):
    params = {
        'keyword': keyword,
        'offset': offset,
    }
    cookies = {
        'ttwid': '** REDACTED **',
        'sessionid': '** REDACTED **',
    }
    request = requests.get("http://us.tiktok.com/api/search/item/full/", params=params, cookies=cookies)
    return(request.json())`

**Comment by DarinKumarnsit** [comment]
May i ask how do you get ttwid and  sessionid?

**Comment by azickri** [comment]
@DarinKumarnsit ,

I think, that not sessionid but csrf_session_id

**Comment by DarinKumarnsit** [comment]
@azickri I see. Thank you so much :)

**Comment by arsoni20** [comment]
@DarinKumarnsit were you able to get data by using ttwid(tt_csrf_token) ?

**Comment by DarinKumarnsit** [comment]
@arsoni20  I get data by using ttwid But can not get data by using tt_csrf_token.  I think ttwid and tt_csrf_token is not the same.
![image](https://user-images.githubusercontent.com/58914019/203059913-f4276dd7-746f-4883-9a37-28472ca9a6bf.png)

**Comment by azickri** [comment]
@DarinKumarnsit, which cookie you set in request?
only ttwid?

**Comment by DarinKumarnsit** [comment]
Yes, i using only ttwid  like https://github.com/dfreelon/pyktok/issues/6#issuecomment-1319294441

**Comment by DarinKumarnsit** [comment]
@azickri Would you mind showing your code?

**Comment by azickri** [comment]
```
async function testRequest() {
  await axios.get('https://www.tiktok.com/api/search/item/full/', {
    params: {
      device_id: randomString(19),
      keyword: 'anime',
      offset: 0,
      aid: '1988'
    },
    headers: {
      cookie: 'ttwid=1%7CaPvKddcezIA9R7xZpD44PAjDHCznRBAPaI4AqndhsXY%7C1669084761%7C38de50273e2db3696d265d4ff1e4ee24eb299f4d5820800db49df7f3b2938a18'
    }
  }).then((response) => {
    console.log('response', response.data);
  }).catch((error) => {
    console.log('error', error.response.data);
  });
}

testRequest();
```

I got this response

```
{
  code: '10000',
  from: 'shark_admin',
  type: 'verify',
  version: '',
  region: 'sg',
  subtype: 'slide',
  detail: 'xHxMn1eVSIaRrec4k7PYhzVkdmV7E6Kk0zqY1Qt--72R*tCU8Lsc314Nz6mCoKOA7AhqWIyEGUW*DFK1ud6pjfOwXP*o5i9BoNHXsSmfBH3B2v5bJSYj1mHUMmaUFYXtTW5z9Nt3iKMP3Z9457HfqtEfOREU8K6cUaTTCJd7*dQWuP1B1Vbqr*oHsERsbNcQuNds9WeBvKTahBdlsCMLwOApr71EpcHo2opBWYubsuBF4YpZ0tg3*mqbRWiawDnxiLtyuRNGhqAkAxu6cjn3ADcW0Rd7RYFLDxqMacsOp*g6L-ZGzdcBtcxiFxhrdQ96zO8YCnoCUwrnOH61idKkACcxYA7cEVD3e-DDZQ..',
  verify_event: '',
  fp: 'verify_larlzcp1_FzJVwMtq_xb5m_4YNd_9Txt_UZMJ4DRGll2U',
  server_sdk_env: '{"idc":"sg1","region":"ALISG","server_type":"business"}'
}
```

**Comment by azickri** [comment]
I think **msToken** should be include in cookie.. because, i was try with 2 cookie, (ttwid and msToken)
When request without ttwid, its should be teturn "Login first..." you now..

**Comment by azickri** [comment]
Anybody have same issue?
I try hit API with full request Cookie, but response is

```
{
 status_msg: 'Please login your account first',
 log_pb: { impr_id: '202211240158570102450591401C07BBFC' },
 status_code: 2483
}
```

**Comment by matiquec** [comment]
> Anybody have same issue? I try hit API with full request Cookie, but response is
> 
> ```
> {
>  status_msg: 'Please login your account first',
>  log_pb: { impr_id: '202211240158570102450591401C07BBFC' },
>  status_code: 2483
> }
> ```

I downloaded the full cookies in a json and used the code @mesaleh replacing the value in cookies, and it worked
The cookies code was in #891 @adamd01

**Comment by azickri** [comment]
@matiquec, are you have same issue now?
When i request with full cookie after tiktok login, response from API https://www.tiktok.com/api/search/item/full/ got Blank response with status 200

**Comment by matiquec** [comment]
@azickri  I am working with this, using as guideline the comments in others issues:


```
import json

#----------------------read cookies----------#
#get the cookies file downloaded in chrome with cookie manager
def get_cookies_from_file():
    with open('cookies.json') as f:
        cookies = json.load(f)

    cookies_kv = {}
   #Just use the name and the value properties
    for cookie in cookies:
        cookies_kv[cookie['name']] = cookie['value']
    return cookies_kv

#---------------------Request-----------------#
import requests

def test_search(keyword, offset=0):
   #Define params and headers
    params = {
        'keyword': keyword,
        'offset': offset
    }
   #Just test of headers, i think it's no neccesary
    headers = {
        "priority_regio":"CO",
        "tz_name=America":"%2FBogota"
    }
   #get all cookies
    cookies = get_cookies_from_file()

##just a test with only ttwid and session id
    # {
    #     'ttwid': <value of ttwid cookie>,
    #     'sessionid': <value of sessionid cookie>,
    # }

   #try request with /search/item/full
    request = requests.get("http://us.tiktok.com/api/search/item/full/", headers=headers, params=params, cookies=cookies)    
    
    #try request with /search/geneal/full
    # request = requests.get("http://us.tiktok.com/api/search/general/full/", headers=headers, params=params, cookies=cookies)

    #---print request---#
    # print(request.request.url)
    # print(request.request.body)
    # print(request.request.headers)

    return(request.json())

# Create an offset test, (tiktok return 12 videos in every run, I think that is neccesary read the propiertie has_more) 
offset = [0,12,24,36]
# run script for every offset

for count in offset:
    result = test_search(<word>, offset=count)
    # save the result in a file
    with open("hashtag.json", "a") as f:
        json.dump(result, f , indent=4)
        f.write('\n')
        f.close()

```

I am working with this code for search by keyword

**Comment by Maverick1983** [comment]
@davidteather can you update the code?

**Comment by Russell-Newton** [comment]
For anyone still needing to get around this issue, I'm working on [my own library](https://github.com/Russell-Newton/TikTokPy) that does work with getting videos under a tag. You don't need to preload any cookies because it doesn't handle API calls in the same way. I have yet to need to provide a proxy for bulk scraping. The methodology to get a large number of videos from a tag or user or comments under a video is handled a bit different, but this is [explained in the documentation](https://tiktokpy.readthedocs.io/en/latest/users/explanation.html#data-collection). I am actively working on the development of the library and am open to issues and contributions.

**Comment by davidteather** [comment]
fixed in V6

**Comment by azickri** [comment]
@davidteather , wow.. thanks
