### ISSUE TITLE
[BUG] - CaptchaException even with proxy and custom_verify_fp

### ISSUE THREAD

**Issue by gbiz123** [davidteather/TikTok-Api#978]
Fill Out the template :)

Getting captcha exception no matter what I do, even with custom_verify_fp and residential proxy

```
from TikTokApi import TikTokApi
proxy = "http:my_proxy:port"
sv = "verify_lb1f1ug1_u3VZLU0Y_u56b_4liW_ASSF_2qSvrqrdJjTZ"
api = TikTokApi(proxy=proxy, custom_verify_fp=sv)
user = api,user(username="any_user")
user.as_dict

Exception:
CaptchaException: 0 -> TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verify_fp as method parameters
``

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - TikTokApi Version [e.g. 5.0.0] - latest version (did pip install --upgrade)

**Comment by fer0m** [comment]
Up. Have same problem. Any ideas?

**Comment by Russell-Newton** [comment]
I can't help with this library, but I've created [my own that circumvents this issue](https://github.com/Russell-Newton/TikTokPy). It grabs data in a slightly different way that doesn't require providing a verify_fp or a proxy because it automatically grabs the verify_fp for you. The behavior of mine is slightly different, but I've been using it without a hitch so far. I'm actively trying to improve it as people bring issues to my attention and am open to contributions and ideas.

**Comment by terrok9** [comment]
After 5 - 6 hours of research and workaround, I couldn't make a solution to this problem.
I can summarize some points that I have discovered through try and error:

> First: We can't reach Tiktok's s_v_web_id token. This is due a change on the overall web page.
> Second: Even if you force the webpage to give you a token using a custom [link (here the example)](https://sf16-scmcdn-va.ibytedtos.com/goofy/secsdk-captcha/va/2.15.21/index.html) or consuming full resources using a bot based on Selenium to pop a captcha, the resulting code still fails.
> Third: It seems that @davidteather have solved this issue after v5 but captcha still popping and we can't go deep on the API. You can see the related issue [here](https://github.com/davidteather/TikTok-Api/issues/849).

I really believe that this project is state of the art input for the next NLP models, I will see how can I help in the workaround.

**Comment by 444joseph444** [comment]
Good day, I want to get an agency, how is the work, how much is the price,
and how are things going

في الأربعاء، ١١ يناير ٢٠٢٣ ٤:٥٦ ص terrok9 ***@***.***> كتب:

**Comment by hacknapier** [comment]
TikTok Captcha Solving Service is available here with demo to Login successfully into your TikTok Account.
https://rapidapi.com/flyCaptcha/api/flycaptcha

**Comment by davidteather** [comment]
Should be fixed in V6 I think?
