### ISSUE TITLE
TikTokApi.exceptions.TikTokException: 10004

### ISSUE THREAD

**Issue by ShreKrente** [davidteather/TikTok-Api#989]
from TikTokApi import TikTokApi
api = TikTokApi()

video_tt = api.video(url=link).bytes()

TikTokApi.exceptions.TikTokException: 100004 -> TikTok sent an unknown StatusCode of 100004

What can I do about this?

**Comment by 444joseph444** [comment]
I'm new here and I don't know the system and I don't know anything here so I'm asking for something that's not allowed here sorry I want to get a buying agency Tik Tok support 
BIGO live Support

**Comment by 444joseph444** [comment]
I'm new here and I don't know the system and I don't know anything here so I'm asking for something that's not allowed here sorry I want to get a buying agency Tik Tok support 
BIGO live Support

**Comment by ShreKrente** [comment]
> from TikTokApi import TikTokApi api = TikTokApi()
> 
> video_tt = api.video(url=link).bytes()
> 
> TikTokApi.exceptions.TikTokException: 100004 -> TikTok sent an unknown StatusCode of 100004
> 
> What can I do about this?
