### ISSUE TITLE
[BUG] - AttributeError: 'TikTokApi' object has no attribute 'byUsername'

### ISSUE THREAD

**Issue by andvsilva** [davidteather/TikTok-Api#991]
Hi, I have a problem with the TikTokApi

`$ python -m pip install TikTokApi`                                         

Installing collected packages: TikTokApi
Successfully installed TikTokApi-5.2.2

```
$ python
Python 3.9.10 (main, Jul 10 2022, 21:54:43) 
Type "help", "copyright", "credits" or "license" for more information.

>>> from TikTokApi import TikTokApi
>>> api = TikTokApi()
>>> n_videos = 100
>>> username = 'washingtonpost'
>>> user_videos = api.byUsername(username, count=n_videos)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**AttributeError: 'TikTokApi' object has no attribute 'byUsername'**
```

reference - tutorial - https://towardsdatascience.com/how-to-collect-data-from-tiktok-tutorial-ab848b40d191

Someone can help me to fix this issue?

Thanks!

**Comment by KJY0202** [comment]
I have same issue with that Attribute error with get_user either I can't understand what I have to use

**Comment by davidteather** [comment]
These functions were changed in V5, please look at the examples folder on this repo
