### ISSUE TITLE
[BUG] - Cannot get exactly user likes, follows.

### ISSUE THREAD

**Issue by sinhpn92** [davidteather/TikTok-Api#992]
**Describe the bug**

The user information do not return exactly user likes, follows when the number is more than 1M.

Have anyone facing this issue? How can I fix it? Thank you

**Comment by SyrupTheSrc** [comment]
Can you copy and post your code in this thread so we can see where the issue is.

Also are you using a proxy to get these request through the api?

**Comment by davidteather** [comment]
Unfortunately I believe TikTok's web app rounds to human readable # of likes/followers
