### ISSUE TITLE
[BUG] - Your Error Here

### ISSUE THREAD

**Issue by Psychopat228** [davidteather/TikTok-Api#998]
[{"domain":"\ufeff.tiktok.com","expirationDate":"1662654804","hostOnly":true,"httpOnly":true,"name":"passport_csrf_token","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"e91366cd016a8f42dd4c53a2ae8b469f","id":0,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1662654804","hostOnly":true,"httpOnly":true,"name":"passport_csrf_token_default","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"e91366cd016a8f42dd4c53a2ae8b469f","id":1,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1691166832","hostOnly":true,"httpOnly":true,"name":"cookie-consent","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"{%22ga%22:true%2C%22af%22:true%2C%22fbp%22:true%2C%22lip%22:true%2C%22bing%22:true%2C%22ttads%22:true%2C%22reddit%22:true%2C%22version%22:%22v8%22}","id":2,"storeId":"0"},{"domain":".www.tiktok.com","expirationDate":"1659595289","hostOnly":true,"httpOnly":true,"name":"_tea_utm_cache_2643","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"undefined","id":3,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1693076073","hostOnly":true,"httpOnly":true,"name":"_ttp","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"2BkzF2tJ5RW1SnpTAvhA9oxDcwv","id":4,"storeId":"0"},{"domain":".www.tiktok.com","expirationDate":"1660024438","hostOnly":true,"httpOnly":true,"name":"__tea_cache_tokens_1988","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"{%22user_unique_id%22:%227118782755223782918%22%2C%22timestamp%22:1659419638776%2C%22_type_%22:%22default%22}","id":5,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"cmpl_token","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"AgQQAPP3F-RO0rLbbI3BOp08-KtmAUHVf4R8YMWb1Q","id":6,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"sessionid","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"4fc6ebb06037ae6cb85b3fb167676826","id":7,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"sessionid_ss","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"4fc6ebb06037ae6cb85b3fb167676826","id":8,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1690523633","hostOnly":true,"httpOnly":true,"name":"sid_guard","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"4fc6ebb06037ae6cb85b3fb167676826%7C1659419633%7C5184000%7CSat%2C+01-Oct-2022+05%3A53%3A53+GMT","id":9,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"sid_tt","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"4fc6ebb06037ae6cb85b3fb167676826","id":10,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"sid_ucp_v1","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"1.0.0-KGVmNmJmODE2MGMyMGNjZjBmNzcyNmQzNDAwMzExMzY1MzFlZjhhMTEKIAiFiKHIpMXg8mIQ8feilwYYswsgDDDahJaXBjgHQPQHEAMaBm1hbGl2YSIgNGZjNmViYjA2MDM3YWU2Y2I4NWIzZmIxNjc2NzY4MjY","id":11,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"ssid_ucp_v1","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"1.0.0-KGVmNmJmODE2MGMyMGNjZjBmNzcyNmQzNDAwMzExMzY1MzFlZjhhMTEKIAiFiKHIpMXg8mIQ8feilwYYswsgDDDahJaXBjgHQPQHEAMaBm1hbGl2YSIgNGZjNmViYjA2MDM3YWU2Y2I4NWIzZmIxNjc2NzY4MjY","id":12,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"store-country-code","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"se","id":13,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"store-idc","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"maliva","id":14,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"tt-target-idc","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"useast1a","id":15,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1690955641","hostOnly":true,"httpOnly":true,"name":"ttwid","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"1%7CIYeskwrfyfx2uyQycqgTnRGslChqHt7Hnk_WajVSAf0%7C1659419641%7C68844b5e2876e79a488e61a4330e8a66204cc54d387c3c3f2a22c04cc4bb3142","id":16,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"uid_tt","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"b6a894b9df83403a95930112ea47ddc32b3d249e4f19f95b9a61e6f7106cb1dc","id":17,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"uid_tt_ss","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"b6a894b9df83403a95930112ea47ddc32b3d249e4f19f95b9a61e6f7106cb1dc","id":18,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1690956195","hostOnly":true,"httpOnly":true,"name":"odin_tt","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"b046aa5c67e571a9b5fafafad4face74fe303daf99e7e3e0d7ca7748259f1b4bc3becc531dfb35383930351fe71050b1dec83b9f74fb21fdf9f797390020e255","id":19,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1659459896","hostOnly":true,"httpOnly":true,"name":"bm_sz","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"?","id":20,"storeId":"0"},{"domain":"www.tiktok.com","expirationDate":"1667229542","hostOnly":true,"httpOnly":true,"name":"msToken","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"T84qmWGxOla3H6HkZPHIs7Jg0q5g_v_eNSCJ9XtiYoNdA8bEqhbhiub972a6s5LHXwpQMwhE12x3eRFe2khWVIkweA0mt7q-1QJPltlq5XeLnEM_39n_wtaRqCWXQhG2JDR8KwD6","id":21,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1690989598","hostOnly":true,"httpOnly":true,"name":"_abck","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"39457728429D2BF4D9D9280C7F4976A5~-1~YAAQHNr\/U33HwzWCAQAAN2wkXwhb5M+G6l7QmxOGJ+fa+55ssYtUWz633YXeEUz7vQFTjMOS1Ew9y2Nh4FwMFjSMJPLgWVcAZYreT\/f4UmZRej4uc+HBsB6DE+GSG+y3IviIt5P1hQp9M+BP4wXcfwvO1GeA2bw33TMrO\/447QuCs851CPv\/hWFmymBJZFP93xa21mfMArRcstxfSNxBnfb85aHjkosm3e1GA4K8zq7qNzrFOVgRlhPZ0VslAWMeZAW8SFA8xFP6rWDE2CPEfk2MwgOWFJpT8n5fdlCNJ1cHlLCBt152wfciWz9aWImXNz29CZW5Bfwc559gWJAluQjLUONMgt0Z8u7wBvF1TBGI~-1~-1~-1","id":22,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1660317601","hostOnly":true,"httpOnly":true,"name":"msToken","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"DrZrs-6x-9eDk96KSn1erc-fKBEDmjYfpwZ4v-ZaUcSjBGd6N3Uqy2M3gYqr9H6oPMZBNy8UAE9EmT5E8ylkMZ-qT9eWUEf_STsWcd79iXlgMQD3kDP1","id":23,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1662654804","hostOnly":true,"httpOnly":true,"name":"passport_csrf_token","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"e91366cd016a8f42dd4c53a2ae8b469f","id":24,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1662654804","hostOnly":true,"httpOnly":true,"name":"passport_csrf_token_default","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"e91366cd016a8f42dd4c53a2ae8b469f","id":25,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1691166832","hostOnly":true,"httpOnly":true,"name":"cookie-consent","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"{%22ga%22:true%2C%22af%22:true%2C%22fbp%22:true%2C%22lip%22:true%2C%22bing%22:true%2C%22ttads%22:true%2C%22reddit%22:true%2C%22version%22:%22v8%22}","id":26,"storeId":"0"},{"domain":".www.tiktok.com","expirationDate":"1659595289","hostOnly":true,"httpOnly":true,"name":"_tea_utm_cache_2643","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"undefined","id":27,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1693076073","hostOnly":true,"httpOnly":true,"name":"_ttp","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"2BkzF2tJ5RW1SnpTAvhA9oxDcwv","id":28,"storeId":"0"},{"domain":".www.tiktok.com","expirationDate":"1660024438","hostOnly":true,"httpOnly":true,"name":"__tea_cache_tokens_1988","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"{%22user_unique_id%22:%227118782755223782918%22%2C%22timestamp%22:1659419638776%2C%22_type_%22:%22default%22}","id":29,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"cmpl_token","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"AgQQAPP3F-RO0rLbbI3BOp08-KtmAUHVf4R8YMWb1Q","id":30,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"sessionid","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"4fc6ebb06037ae6cb85b3fb167676826","id":31,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"sessionid_ss","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"4fc6ebb06037ae6cb85b3fb167676826","id":32,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1690523633","hostOnly":true,"httpOnly":true,"name":"sid_guard","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"4fc6ebb06037ae6cb85b3fb167676826%7C1659419633%7C5184000%7CSat%2C+01-Oct-2022+05%3A53%3A53+GMT","id":33,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"sid_tt","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"4fc6ebb06037ae6cb85b3fb167676826","id":34,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"sid_ucp_v1","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"1.0.0-KGVmNmJmODE2MGMyMGNjZjBmNzcyNmQzNDAwMzExMzY1MzFlZjhhMTEKIAiFiKHIpMXg8mIQ8feilwYYswsgDDDahJaXBjgHQPQHEAMaBm1hbGl2YSIgNGZjNmViYjA2MDM3YWU2Y2I4NWIzZmIxNjc2NzY4MjY","id":35,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"ssid_ucp_v1","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"1.0.0-KGVmNmJmODE2MGMyMGNjZjBmNzcyNmQzNDAwMzExMzY1MzFlZjhhMTEKIAiFiKHIpMXg8mIQ8feilwYYswsgDDDahJaXBjgHQPQHEAMaBm1hbGl2YSIgNGZjNmViYjA2MDM3YWU2Y2I4NWIzZmIxNjc2NzY4MjY","id":36,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"store-country-code","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"se","id":37,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"store-idc","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"maliva","id":38,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"tt-target-idc","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"useast1a","id":39,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1690955641","hostOnly":true,"httpOnly":true,"name":"ttwid","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"1%7CIYeskwrfyfx2uyQycqgTnRGslChqHt7Hnk_WajVSAf0%7C1659419641%7C68844b5e2876e79a488e61a4330e8a66204cc54d387c3c3f2a22c04cc4bb3142","id":40,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"uid_tt","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"b6a894b9df83403a95930112ea47ddc32b3d249e4f19f95b9a61e6f7106cb1dc","id":41,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1664603633","hostOnly":true,"httpOnly":true,"name":"uid_tt_ss","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"b6a894b9df83403a95930112ea47ddc32b3d249e4f19f95b9a61e6f7106cb1dc","id":42,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1690956195","hostOnly":true,"httpOnly":true,"name":"odin_tt","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"b046aa5c67e571a9b5fafafad4face74fe303daf99e7e3e0d7ca7748259f1b4bc3becc531dfb35383930351fe71050b1dec83b9f74fb21fdf9f797390020e255","id":43,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1659459896","hostOnly":true,"httpOnly":true,"name":"bm_sz","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"?","id":44,"storeId":"0"},{"domain":"www.tiktok.com","expirationDate":"1667229542","hostOnly":true,"httpOnly":true,"name":"msToken","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"T84qmWGxOla3H6HkZPHIs7Jg0q5g_v_eNSCJ9XtiYoNdA8bEqhbhiub972a6s5LHXwpQMwhE12x3eRFe2khWVIkweA0mt7q-1QJPltlq5XeLnEM_39n_wtaRqCWXQhG2JDR8KwD6","id":45,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1690989598","hostOnly":true,"httpOnly":true,"name":"_abck","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"39457728429D2BF4D9D9280C7F4976A5~-1~YAAQHNr\/U33HwzWCAQAAN2wkXwhb5M+G6l7QmxOGJ+fa+55ssYtUWz633YXeEUz7vQFTjMOS1Ew9y2Nh4FwMFjSMJPLgWVcAZYreT\/f4UmZRej4uc+HBsB6DE+GSG+y3IviIt5P1hQp9M+BP4wXcfwvO1GeA2bw33TMrO\/447QuCs851CPv\/hWFmymBJZFP93xa21mfMArRcstxfSNxBnfb85aHjkosm3e1GA4K8zq7qNzrFOVgRlhPZ0VslAWMeZAW8SFA8xFP6rWDE2CPEfk2MwgOWFJpT8n5fdlCNJ1cHlLCBt152wfciWz9aWImXNz29CZW5Bfwc559gWJAluQjLUONMgt0Z8u7wBvF1TBGI~-1~-1~-1","id":46,"storeId":"0"},{"domain":".tiktok.com","expirationDate":"1660317601","hostOnly":true,"httpOnly":true,"name":"msToken","path":"\/","sameSite":"no_restriction","secure":true,"session":true,"value":"DrZrs-6x-9eDk96KSn1erc-fKBEDmjYfpwZ4v-ZaUcSjBGd6N3Uqy2M3gYqr9H6oPMZBNy8UAE9EmT5E8ylkMZ-qT9eWUEf_STsWcd79iXlgMQD3kDP1","id":47,"storeId":"0"},{"name":"sid_guard","value":"4fc6ebb06037ae6cb85b3fb167676826|1663253527|5184000|Mon%2C+14-Nov-2022+14%3A52%3A07+GMT","domain":".tiktok.com","path":"\/","expires":1694357528,"secure":false,"httpOnly":true},{"name":"uid_tt","value":"b6a894b9df83403a95930112ea47ddc32b3d249e4f19f95b9a61e6f7106cb1dc","domain":".tiktok.com","path":"\/","expires":1668437528,"secure":false,"httpOnly":true},{"name":"uid_tt_ss","value":"b6a894b9df83403a95930112ea47ddc32b3d249e4f19f95b9a61e6f7106cb1dc","domain":".tiktok.com","path":"\/","expires":1668437528,"secure":true,"httpOnly":true,"sameSite":"None"},{"name":"sid_tt","value":"4fc6ebb06037ae6cb85b3fb167676826","domain":".tiktok.com","path":"\/","expires":1668437528,"secure":false,"httpOnly":true},{"name":"sessionid","value":"4fc6ebb06037ae6cb85b3fb167676826","domain":".tiktok.com","path":"\/","expires":1668437528,"secure":false,"httpOnly":true},{"name":"sessionid_ss","value":"4fc6ebb06037ae6cb85b3fb167676826","domain":".tiktok.com","path":"\/","expires":1668437528,"secure":true,"httpOnly":true,"sameSite":"None"},{"name":"sid_ucp_v1","value":"1.0.0-KGQwNTQ0MWRiYWMzMjRiZGMwZDY0YWI0NDEwYTBiYjRkOTA3OTdkNjcKIAiFiKHIpMXg8mIQl_iMmQYYswsgDDDahJaXBjgHQPQHEAMaBm1hbGl2YSIgNGZjNmViYjA2MDM3YWU2Y2I4NWIzZmIxNjc2NzY4MjY","domain":".tiktok.com","path":"\/","expires":1668437528,"secure":true,"httpOnly":true},{"name":"ssid_ucp_v1","value":"1.0.0-KGQwNTQ0MWRiYWMzMjRiZGMwZDY0YWI0NDEwYTBiYjRkOTA3OTdkNjcKIAiFiKHIpMXg8mIQl_iMmQYYswsgDDDahJaXBjgHQPQHEAMaBm1hbGl2YSIgNGZjNmViYjA2MDM3YWU2Y2I4NWIzZmIxNjc2NzY4MjY","domain":".tiktok.com","path":"\/","expires":1668437528,"secure":true,"httpOnly":true,"sameSite":"None"},{"name":"store-idc","value":"maliva","domain":".tiktok.com","path":"\/","expires":1668437528,"secure":false,"httpOnly":true},{"name":"store-country-code","value":"se","domain":".tiktok.com","path":"\/","expires":1668437528,"secure":false,"httpOnly":true},{"name":"store-country-code-src","value":"uid","domain":".tiktok.com","path":"\/","expires":1668437528,"secure":false,"httpOnly":true},{"name":"tt-target-idc","value":"useast1a","domain":".tiktok.com","path":"\/","expires":1668437528,"secure":false,"httpOnly":true},{"name":"odin_tt","value":"c840b9ba5dc4f85e6f0bb587b38923949ae46b13d211ceda7e788707c45f3ec9ffc6f2f029343481a2b3deac7693b0ff6b3aaf77b614df264af24fe56b2fa2cd","domain":".tiktok.com","path":"\/","expires":1694789528,"secure":false,"httpOnly":true},{"name":"_abck","value":"39457728429D2BF4D9D9280C7F4976A5~-1~YAAQLJoQAnHGBECDAQAA0LuiQQhCCXcggKUdhjgjvwWPwuIcPXknUuBNghR8Kyhwaubj6UyWE33ejAanjSZIjauvWqRAvNPpIk4Vd\/u89ZXql0ztCrivcymX5oZuAP\/\/+2eUBUW2X7XFW4QYqxSsRuPjFAyIzixXdZiUndxE9ab98ePq2yaNKGT9Y0VLowbKLIQtTg8aNQyUFw+T0htyaOuSOBegNWV8RQwjkeuMJK2js3cBr\/kmpeHb22CfhBZAPWEhhdFDG+tko\/tFiavz0iRAS7hK7RjDFfFfOt0OcBMdpyptAUS8Iq7Py9AmFHxcAcwcXZ1H97z+1+pIXvgMP6MK\/Y5Z22z8v7RE9MRU3rjH~-1~-1~-1","domain":".tiktok.com","path":"\/","expires":1694789528,"secure":true,"httpOnly":false}]

**Comment by davidteather** [comment]
???

**Comment by BOBER20037** [comment]
Да че за хуйня

**Comment by BOBER20037** [comment]
tiktok.com
