### ISSUE TITLE
'There is no current event loop in thread

### ISSUE THREAD

**Issue by sully20832** [davidteather/TikTok-Api#999]
Fill Out the template :)

**For some reason I keep getting this thread error when using the titkok api**

I keep getting this error when I run the code I do not know why this happens with TikTokAPI

Error:

File "C:\Users\SulyS\OneDrive\Desktop\AiSearchv1\app2.py", line 17, in <module>
    titkok("https://www.tiktok.com/@demonixslayer/video/7151993610303524123")
File "C:\Users\SulyS\OneDrive\Desktop\AiSearchv1\app2.py", line 9, in titkok
    with TikTokApi(custom_device_id=did) as api:
File "c:\users\sulys\appdata\local\programs\python\python38\lib\site-packages\TikTokApi\tiktok.py", line 159, in __init__
    self._initialize(
File "c:\users\sulys\appdata\local\programs\python\python38\lib\site-packages\TikTokApi\tiktok.py", line 205, in _initialize
    self._browser = asyncio.get_event_loop().run_until_complete(
File "c:\users\sulys\appdata\local\programs\python\python38\lib\asyncio\events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'

**import streamlit as st
from TikTokApi import TikTokApi
import random

st.write("TikTok Scrape examples")

def titkok(link):
    did = str(random.randint(10000, 999999999))
    with TikTokApi(custom_device_id=did) as api:
        video = api.video(id=id)
        video_data = video.bytes()

        with open(f"out.mp4", "wb") as out_file:
            out_file.write(video_data)

if (2==2):
    titkok("https://www.tiktok.com/@demonixslayer/video/7151993610303524123")**

```py
# Code Goes Here
import streamlit as st
from TikTokApi import TikTokApi
import random

st.write("TikTok Scrape examples")

def titkok(link):
    did = str(random.randint(10000, 999999999))
    with TikTokApi(custom_device_id=did) as api:
        video = api.video(id=id)
        video_data = video.bytes()

        with open(f"out.mp4", "wb") as out_file:
            out_file.write(video_data)

if (2==2):
    titkok("https://www.tiktok.com/@demonixslayer/video/7151993610303524123")
```

**Comment by sulynajimsj** [comment]
??

**Comment by sulynajimsj** [comment]
???

**Comment by Giaochan** [comment]
Having the same issue when developing a fastapi app

**Comment by davidteather** [comment]
V6 fully async
